gText_ApprenticeChallenge0::
	.string "אמ, אני החניך מס' {STR_VAR_2} של {STR_VAR_1}.\n"
	.string "מנוזל… המתח הזה משתלט עלי…$"

gText_ApprenticeChallenge1::
	.string "אני החניך מס' {STR_VAR_2} של {STR_VAR_1}!\n"
	.string "הנה אנחנו באים!$"

gText_ApprenticeChallenge2::
	.string "אני החניך מס' {STR_VAR_2} של {STR_VAR_1}!\n"
	.string "קבל{ADD_YUD} את האתגר שלי!$"

gText_ApprenticeChallenge3::
	.string "אמ… אני החניך מס' {STR_VAR_2} של {STR_VAR_1}…\n"
	.string "את{EMIT_HEY} חושב{ADD_TAF} שמישהו כמוני יכול לנצח?$"

gText_ApprenticeChallenge4::
	.string "אני החניך מס' {STR_VAR_2} של {STR_VAR_1}!\n"
	.string "אני אתן לך לאתגר אותי!$"

gText_ApprenticeChallenge5::
	.string "אני עסוק נורא, אבל אני גם במקרה\n"
	.string "החניך מס' {STR_VAR_2} של {STR_VAR_1}.$"

gText_ApprenticeChallenge6::
	.string "אני החניך מס' {STR_VAR_2} של {STR_VAR_1}.\n"
	.string "שמח להכיר אותך!$"

gText_ApprenticeChallenge7::
	.string "אני משרת כחניך מס' {STR_VAR_2} של {STR_VAR_1}.\n"
	.string "האם אני יכול להתחיל?$"

gText_ApprenticeChallenge8::
	.string "איכס! אני החניך מס' {STR_VAR_2} של {STR_VAR_1}!\n"
	.string "אני אעשה את המיטב!$"

gText_ApprenticeChallenge9::
	.string "יה-הא! אני החניך מס' {STR_VAR_2} של {STR_VAR_1}!\n"
	.string "תתכונ{SWAP_NUN}{ADD_YUD}!$"

gText_ApprenticeChallenge10::
	.string "אני החניך ה000,1 של {STR_VAR_1}!\n"
	.string "למעשה, אני מס' {STR_VAR_2}! הנה זה בא!$"

gText_ApprenticeChallenge11::
	.string "כן, אני החניך מס' {STR_VAR_2} של {STR_VAR_1}!\n"
	.string "בוא{ADD_YUD} נתחיל לרעוד ולהתגלגל!$"

gText_ApprenticeChallenge12::
	.string "יופי-יהו! אני מה שאת{EMIT_HEY} קורא{ADD_TAF} לו\n"
	.string "החניך מס' {STR_VAR_2} של {STR_VAR_1}!$"

gText_ApprenticeChallenge13::
	.string "שיעול! אני החניך מס' {STR_VAR_2} של {STR_VAR_1}.\n"
	.string "שמח להכיר אותך! שיעול!$"

gText_ApprenticeChallenge14::
	.string "זה מעצבן עצבים…\n"
	.string "אני החניך מס' {STR_VAR_2} של {STR_VAR_1}.$"

gText_ApprenticeChallenge15::
	.string "אני החניך מס' {STR_VAR_2} של {STR_VAR_1},\n"
	.string "וזה לא שקר.$"

gText_ApprenticePleaseTeach0::
	.string "את{EMIT_HEY}… {PLAYER}?\n"
	.string "אוי! מנוזל… יבבה…\p"
	.string "אוי! ססליחה…\n"
	.string "אני כל כך עצבני, אני לא יכול שלא לבכות…\p"
	.string "אני {STR_VAR_1}, ואני באמת מעריץ\n"
	.string "אותך, {PLAYER}.\p"
	.string "היה לי חלום לפגוש אותך יום אחד\n"
	.string "ולשאול אותך על פוקימונים.\p"
	.string "בבקשה, בבקשה, {PLAYER}!\n"
	.string "בבקשה למד{ADD_YUD} אותי על פוקימונים!$"

gText_ApprenticeRejectTeaching0::
	.string "אוי… אבבל…\n"
	.string "מנוזל… וואאאא!\p"
	.string "בבקשה!\n"
	.string "אני מתחנן בפניך, בבקשה!$"

gText_ApprenticeWhichLevelMode0::
	.string "אה, באמת? את{EMIT_HEY} תסכי{SWAP_MEM}{ADD_YUD}?\n"
	.string "מדהים! פרוע! אווהו!\p"
	.string "אוי… אני מצטער…\n"
	.string "אני כל כך שמח, אני בוכה…\p"
	.string "אמ… אז בבקשה תגיד{ADD_YUD} לי!\n"
	.string "זה על מגדל הקרב.\p"
	.string "מה יהיה טוב יותר עבורי: רמה 05\n"
	.string "או רמה פתוחה?$"

gText_ApprenticeLevelModeThanks0::
	.string "{STR_VAR_1}?\n"
	.string "וואאאא!\p"
	.string "אוי! אני כל כך מצטער!\n"
	.string "עשית אותי שמח שבחרת\l"
	.string "את הרמה עבורי, וזה גרם לי לבכות…\p"
	.string "מנוזל…\n"
	.string "תודה רבה לך!\l"
	.string "בבקשה דבר{ADD_YUD} איתי שוב!$"

gText_ApprenticePleaseTeach1::
	.string "וואו! את{EMIT_HEY} {PLAYER}, נכון?\n"
	.string "את{EMIT_HEY} חזק בטירוף, נכון?\p"
	.string "אני {STR_VAR_1}!\n"
	.string "זה עתה הפכתי למאמן!\p"
	.string "בבקשה, {PLAYER}!\n"
	.string "את{EMIT_HEY} יכול להיות המורה שלי ולספר לי\l"
	.string "הרבה על להיות מאמן?$"

gText_ApprenticeRejectTeaching1::
	.string "אוי, למה?\n"
	.string "אוי, בבקשה? בבקשה יפה?\l"
	.string "בבקשה תהי{EMIT_HEY}{ADD_YUD} המורה שלי, בבקשה!$"

gText_ApprenticeWhichLevelMode1::
	.string "יש! נהדר!\p"
	.string "הדבר הראשון שרציתי לשאול אותך הוא\n"
	.string "על מגדל הקרב!\p"
	.string "חדרי רמה 05 ורמה פתוחה…\n"
	.string "איזה מהם יהיה מושלם עבורי?$"

gText_ApprenticeLevelModeThanks1::
	.string "{STR_VAR_1}, הא? זה נכון!\n"
	.string "אני אעשה שם את המיטב!\p"
	.string "אם ניפגש כאן שוב, בבקשה למד{ADD_YUD}\n"
	.string "אותי משהו אחר, מורה!$"

gText_ApprenticePleaseTeach2::
	.string "אמ… את{EMIT_HEY} {PLAYER}?\n"
	.string "השם שלי הוא {STR_VAR_1}.\p"
	.string "אני רוצה להיות מאמן פוקימונים,\n"
	.string "אבל אני לא יודע מה לעשות…\p"
	.string "אז חשבתי שאולי אוכל לבקש ממך\n"
	.string "עצה כי את{EMIT_HEY} כל כך מפורס{SWAP_MEM}{ADD_TAF}.\p"
	.string "{PLAYER}, תוכל{ADD_YUD} לתת לי עצה?$"

gText_ApprenticeRejectTeaching2::
	.string "אוי, אבל…\p"
	.string "אני באמת רוצה להיות מאמן פוקימונים!\p"
	.string "בבקשה, את{EMIT_HEY} יכול{ADD_HEY} לענות על השאלות שלי?$"

gText_ApprenticeWhichLevelMode2::
	.string "תודה!\n"
	.string "הנה השאלה הראשונה שלי מיד!\p"
	.string "למגדל הקרב יש שתי רמות,\n"
	.string "רמה 05 ורמה פתוחה, נכון?\p"
	.string "איזו רמה את{EMIT_HEY} חושב{ADD_TAF}\n"
	.string "שמתאימה יותר בשבילי?$"

gText_ApprenticeLevelModeThanks2::
	.string "אה, אתגר {STR_VAR_1}?\n"
	.string "הבנתי!\p"
	.string "אם תהיה לי שאלה נוספת, אני אחזור\n"
	.string "לכאן לקבלת העצה שלך!$"

gText_ApprenticePleaseTeach3::
	.string "אה? הא? את{EMIT_HEY}…\n"
	.string "לא, זה לא יכול להיות נכון.\p"
	.string "אין מצב שמישהו\n"
	.string "כמוני יפגוש את {PLAYER}.\p"
	.string "…את{EMIT_HEY} באמת {PLAYER}?\n"
	.string "אני לא מאמין שאני מדבר איתך!\p"
	.string "כשמשהו כל כך טוב קורה,\n"
	.string "רק דברים נוראיים יקרו לי\l"
	.string "עכשיו, אני פשוט יודע את זה…\p"
	.string "…אני מצטער…\n"
	.string "אני… {STR_VAR_1}…\p"
	.string "אין בי שום דבר מיוחד\n"
	.string "שאני יכול להתגאות בו…\p"
	.string "אני אפילו לא צריך להגיד שום דבר על\n"
	.string "עצמי כי את{EMIT_HEY} תשכח…\p"
	.string "היה לי חלום שאם אי פעם אפגוש\n"
	.string "אותך, {PLAYER}, שאולי אוכל לבקש\l"
	.string "ממך עצה כמאמן.\p"
	.string "אבל אני לא חושב שאת{EMIT_HEY} תסכים\n"
	.string "לזה.\p"
	.string "…או שאת{EMIT_HEY} תהיה כל כך אדיב לתת\n"
	.string "לי עצה?$"

gText_ApprenticeRejectTeaching3::
	.string "ידעתי את זה…\p"
	.string "זה היה חייב לקרות כי אני כל כך\n"
	.string "אף אחד משעמם באמת…\p"
	.string "אבל חשבתי שאולי…\n"
	.string "את{EMIT_HEY} לא תשקול שוב, נכון?\p"
	.string "אבל אני לא יכול לוותר סתם כך.\n"
	.string "אני אשאל אותך בזמן שאני עדיין בר מזל!\p"
	.string "בבקשה, האם תהיה כל כך אדיב לתת\n"
	.string "לי עצה?$"

gText_ApprenticeWhichLevelMode3::
	.string "באמת? אני לא יכול להאמין!\n"
	.string "אני לא יכול להאמין שתייעץ לי!\l"
	.string "אני… אני כל כך שמח…\p"
	.string "מה שאני רוצה לשאול אותך הוא ממש\n"
	.string "טריוויאלי, אבל אני לא מצליח להחליט…\p"
	.string "במגדל הקרב, הם נותנים לך\n"
	.string "לבחור רמה 05 או רמה פתוחה.\p"
	.string "באיזה מסלול את{EMIT_HEY} חושב{ADD_TAF} שאפילו לי יש\n"
	.string "סיכוי?$"

gText_ApprenticeLevelModeThanks3::
	.string "{STR_VAR_1}? אוקי!\n"
	.string "אבל את{EMIT_HEY} באמת חושב שלמישהו כמוני\l"
	.string "יהיה סיכוי?\p"
	.string "אני אעשה את המיטב, למרות שאני לא\n"
	.string "חושב שזה יעבוד.\p"
	.string "תודה רבה לך שהקדשת\n"
	.string "זמן למישהו כמוני.$"

gText_ApprenticePleaseTeach4::
	.string "אוי! את{EMIT_HEY} {PLAYER}{KUN}, נכון?\p"
	.string "שמעתי שאת{EMIT_HEY} קשוח{ADD_HEY}\n"
	.string "בפוקימונים!\p"
	.string "אני {STR_VAR_1}!\n"
	.string "אני אהיה החבר שלך!\p"
	.string "ידעת?\p"
	.string "את{EMIT_HEY} לא יכול{ADD_HEY} לנצח בחזית הקרב\n"
	.string "אם כל מה שאת{EMIT_HEY} יודע{ADD_TAF}זה מה שמלמדים\l"
	.string "בבית הספר למאמנים.\p"
	.string "אני מוכן להקשיב לעצה שלך.\n"
	.string "את{EMIT_HEY} תסכים, כמובן?$"

gText_ApprenticeRejectTeaching4::
	.string "הא? למה את{EMIT_HEY} מסרב לי?\n"
	.string "אני זה שמבקש ממך!\l"
	.string "את{EMIT_HEY} חייב לשקול שוב!$"

gText_ApprenticeWhichLevelMode4::
	.string "אוקי, אז יש את זה.\n"
	.string "אני רוצה שתחליט את זה עבורי.\p"
	.string "את{EMIT_HEY} יודע{ADD_TAF}שבמגדל הקרב יש\n"
	.string "חדרי רמה 05 ורמה פתוחה?\p"
	.string "איזה מהם את{EMIT_HEY} חושב{ADD_TAF} שיהיה טוב\n"
	.string "עבורי, {PLAYER}{KUN}?$"

gText_ApprenticeLevelModeThanks4::
	.string "אוקי, {STR_VAR_1} מתאים לי?\n"
	.string "תודה!\p"
	.string "כשאני יודע שאת{EMIT_HEY} קיבלת את ההחלטה,\n"
	.string "{PLAYER}{KUN}, אני לא אהיה כל כך עצוב אם\l"
	.string "אפסיד.\p"
	.string "אוקי, אני אפנה אליך שוב לקבלת עצה.\n"
	.string "ביי!$"

gText_ApprenticePleaseTeach5::
	.string "אה, היי, שלום! {PLAYER}{KUN}!\n"
	.string "אני מכיר אותך כי את{EMIT_HEY} מפורסם!\l"
	.string "קרא לי {STR_VAR_1}! שמח להכיר אותך!\p"
	.string "אני טריאתלט, אז אני שומר על כושר\n"
	.string "אפילו בזמן שאני מגדל פוקימונים.\p"
	.string "אני מעורב גם בדברים אחרים\n"
	.string "כמו עבודה, תנומה, ריקודי סלון…\p"
	.string "להיות עסוק כל כך, זה לא כל כך קל עבורי\n"
	.string "להפוך למאמן ראוי.\p"
	.string "אז, יש לי הצעה!\p"
	.string "בטח יש סיבה שבגללה נפגשנו.\n"
	.string "אז, {PLAYER}{KUN}, מה דעתך לחלוק את\l"
	.string "החוכמה שלך איתי מדי פעם?$"

gText_ApprenticeRejectTeaching5::
	.string "אוי, אבל, בבקשה?\n"
	.string "בחור כמוני צריך מישהו כמו\l"
	.string "את{EMIT_HEY}, {PLAYER}{KUN}!\p"
	.string "בכנות, אני צריך את העצה שלך!$"

gText_ApprenticeWhichLevelMode5::
	.string "תודה! זה יותר דומה לזה!\n"
	.string "אז, בוא נתחיל עם משהו קל!\p"
	.string "את{EMIT_HEY} יודע{ADD_TAF}על שני המסלולים של מגדל\n"
	.string "הקרב, נכון?\l"
	.string "את{EMIT_HEY} יודע, רמה 05 ורמה פתוחה.\p"
	.string "אני בחור עסוק, איזה מהם אני צריך\n"
	.string "להתכונן אליו?$"

gText_ApprenticeLevelModeThanks5::
	.string "{STR_VAR_1}, הא? אוקי, הבנתי.\n"
	.string "אני אמצא זמן איכשהו ואנסה את זה!\p"
	.string "…אופס, מוטב שאצא לעבודה!\n"
	.string "תודה! נתראה בסביבה!$"

gText_ApprenticePleaseTeach6::
	.string "אין מצב! לא-לא!\n"
	.string "את{EMIT_HEY} אולי ה{PLAYER} האמיתי?\p"
	.string "א-הא! מדהים! אני {STR_VAR_1},\n"
	.string "כל כך שמח לפגוש אותך!\p"
	.string "{PLAYER}, את{EMIT_HEY} מאוד חזק,\n"
	.string "נכון?\p"
	.string "כולם מדברים עליך!\p"
	.string "אוי! היה לי זה עתה רעיון נהדר!\n"
	.string "אני אקבל ממך עצה, {PLAYER}!\l"
	.string "אני בטוח שזה יהפוך אותי לקשוח יותר!\p"
	.string "זה לא רעיון נהדר?\n"
	.string "בבקשה, אני רוצה את העצה שלך!$"

gText_ApprenticeRejectTeaching6::
	.string "חחחח, את{EMIT_HEY} יכול להעמיד פנים שאת{EMIT_HEY} מרושע,\n"
	.string "אבל את{EMIT_HEY} לא יכול לרמות אותי!\l"
	.string "את{EMIT_HEY} באמת מתכוון לאוקי, נכון?$"

gText_ApprenticeWhichLevelMode6::
	.string "יש! ידעתי שיש לך לב גדול,\n"
	.string "{PLAYER}!\p"
	.string "מה אני צריך לשאול אותך קודם?\n"
	.string "…אה, חשבתי על משהו!\p"
	.string "תופים, בבקשה!\n"
	.string "השאלה שיש לי היא…\p"
	.string "אם אני אקבל על עצמי אתגר במגדל\n"
	.string "הקרב, באיזו דרך אני צריך ללכת?\p"
	.string "רמה 05 או רמה פתוחה?\n"
	.string "איזה מהם מתאים לי יותר?$"

gText_ApprenticeLevelModeThanks6::
	.string "או-או-או!\n"
	.string "{STR_VAR_1}, את{EMIT_HEY} אומר!\l"
	.string "תודה על תגובה מגניבה לחלוטין!\p"
	.string "אני מניח שזה בערך כל מה שרציתי\n"
	.string "לשאול אותך היום.\p"
	.string "בוא ניפגש כאן שוב, אוקי?\n"
	.string "תודה!$"

gText_ApprenticePleaseTeach7::
	.string "אני מבקשת את סליחתך, אבל…\n"
	.string "את{EMIT_HEY} {PLAYER}?\p"
	.string "אני {STR_VAR_1}, ואני שמח\n"
	.string "להכיר אותך.\p"
	.string "אני מעריץ שלך כבר\n"
	.string "הרבה זמן…\p"
	.string "… … … … … …\p"
	.string "אמ… אני מקווה שאת{EMIT_HEY} לא מוצא את\n"
	.string "הבקשה הזו כנטל כבד מדי, אבל…\p"
	.string "האם אוכל להיות החניך שלך,\n"
	.string "{PLAYER}?$"

gText_ApprenticeRejectTeaching7::
	.string "אוי…!\p"
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "…בטח התעלפתי מההלם.\n"
	.string "אני מצטער, בטח שמעתי לא נכון.\p"
	.string "בבקשה! בבקשה תגיד שאת{EMIT_HEY} ת\n"
	.string "קבל אותי כחניך שלך!$"

gText_ApprenticeWhichLevelMode7::
	.string "אוי… אני שמח!\p"
	.string "אני לא רוצה לבזבז את זמנך,\n"
	.string "אז בבקשה יעץ לי על זה.\p"
	.string "אני מתכנן לקבל על עצמי אתגר במגדל\n"
	.string "הקרב בקרוב.\p"
	.string "עם זאת, יש שתי רמות…\p"
	.string "איזה מהן תהיה המתאימה ביותר עבורי?\n"
	.string "רמה 05 או רמה פתוחה?$"

gText_ApprenticeLevelModeThanks7::
	.string "{STR_VAR_1} זו הבחירה שלך!\n"
	.string "אני מבין. אני אעשה את המיטב!\p"
	.string "תודה, {PLAYER}.\n"
	.string "אני מקווה שאוכל לסמוך עליך שוב.\l"
	.string "בבקשה שמור על עצמך!$"

gText_ApprenticePleaseTeach8::
	.string "איכס! איכס! {PLAYER}!\n"
	.string "דיברת אלי!\l"
	.string "אני… אני מאושר!\p"
	.string "אני! השם שלי הוא {STR_VAR_1}!\n"
	.string "זה עתה הפכתי למאמן!\p"
	.string "אני שמח שפגשתי אותך, {PLAYER},\n"
	.string "השם הגדול בחוגי הפוקימונים!\p"
	.string "או-או-או, אני יודע!\n"
	.string "האם אוכל לבקש טובה ענקית, {PLAYER}?\p"
	.string "בבקשה קח אותי כחניך שלך!\n"
	.string "אני רוצה ללמוד ממך!$"

gText_ApprenticeRejectTeaching8::
	.string "וואאאא!\n"
	.string "{PLAYER} סירב לי…\l"
	.string "זו… זו חוויה שלא יסולא בפז!\p"
	.string "{PLAYER}, בבקשה! אני רוצה לשמוע\n"
	.string "תשובה חיובית הפעם!\p"
	.string "אני מתחנן בפניך להדרכה שלך!$"

gText_ApprenticeWhichLevelMode8::
	.string "היייה! {PLAYER} אמר כן!\n"
	.string "{PLAYER} אמר כן!\p"
	.string "אני לא אצליח לישון הלילה…\n"
	.string "תודה רבה לך!\p"
	.string "אז, הנה השאלה שלי!\p"
	.string "במגדל הקרב, מה נכון\n"
	.string "עבורי, רמה 05 או רמה פתוחה?$"

gText_ApprenticeLevelModeThanks8::
	.string "{STR_VAR_1}! הבנה מושלמת!\n"
	.string "אני מבין בצורה מושלמת!\l"
	.string "אני שמח עד עילפון!\p"
	.string "אני מקווה שתהיה מוכן ללמד אותי\n"
	.string "עוד פעם אחרת.$"

gText_ApprenticePleaseTeach9::
	.string "וואו! את{EMIT_HEY} יכול להיות…\n"
	.string "את{EMIT_HEY} יכול להיות… {PLAYER}{KUN}?!\l"
	.string "המאמן החזק והמפורסם הזה?\l"
	.string "טוב, שלום, אני פשוט בר מזל!\p"
	.string "שלום, השם הוא {STR_VAR_1}!\p"
	.string "חיפשתי\n"
	.string "מורה לפוקימונים.\p"
	.string "ועם תזמון טוב להפליא,\n"
	.string "הגעת את{EMIT_HEY}, {PLAYER}{KUN}!\p"
	.string "אז, הנה זה, {PLAYER}{KUN}!\n"
	.string "ת{SWAP_NUN}{ADD_YUD} לי להיות חניך שלך!$"

gText_ApprenticeRejectTeaching9::
	.string "גווואאאה!\n"
	.string "את{EMIT_HEY} די מגניב וקשוח…\p"
	.string "אל תהיה כזה, בבקשה.\n"
	.string "אני מבקש ממך!$"

gText_ApprenticeWhichLevelMode9::
	.string "אה, כן! זו תגובה מוצקה!\n"
	.string "מצוין, אני חייב להוסיף!\p"
	.string "אז מה דעתך על פיסת עצה ראשונה\n"
	.string "על מגדל הקרב?\p"
	.string "אם אני אלך, מה יהיה טוב יותר?\n"
	.string "רמה 05 או רמה פתוחה?$"

gText_ApprenticeLevelModeThanks9::
	.string "אהה, {STR_VAR_1} זה זה!\n"
	.string "אוקי, א-אוקי!\l"
	.string "אני אלך להראות את האומץ שלי, כאילו, ג'אם!\p"
	.string "טוב, אני אפנה אליך כאל המנטור שלי!\n"
	.string "להתראות!$"

gText_ApprenticePleaseTeach10::
	.string "אה, היי, {PLAYER}{KUN}, נכון?\n"
	.string "המשטרה חיפשה אותך!\p"
	.string "… … …\n"
	.string "כמובן שאני משקר!\p"
	.string "אני, אני {STR_VAR_1}. למרות איך\n"
	.string "שאני נראה, אני אלוף הפוקימונים!\l"
	.string "…זה גם שקר!\p"
	.string "זה לא שקר, למרות זאת.\n"
	.string "אני לא כל כך טוב בקרבות.\p"
	.string "אז, מה דעתך שתהפוך למאסטר שלי\n"
	.string "בכל הדברים הקשורים לפוקימונים?$"

gText_ApprenticeRejectTeaching10::
	.string "אם את{EMIT_HEY} הולך להתנהג ככה בקרירות,\n"
	.string "אני אראה לך מה אני אעשה!\p"
	.string "וואאא! וואאא! וואאא!\n" @TODO
	.string "שיהוק!\p"
	.string "חחחח, אלה היו הדמעות המזוייפות שלי!\p"
	.string "נו, בבקשה תהיה\n"
	.string "המאסטר שלי לפוקימונים?$"

gText_ApprenticeWhichLevelMode10::
	.string "יופי!\n"
	.string "אני אקנה לך סירה בשביל זה!\p"
	.string "כמובן שאני משקר שוב!\n"
	.string "אבל… תודה, מאסטר!\p"
	.string "את{EMIT_HEY} יודע{ADD_TAF}שיש רמה 05\n"
	.string "ורמה פתוחה במגדל הקרב?\p"
	.string "אני מתקשה להחליט באיזו\n"
	.string "רמה אני צריך להתחרות…\p"
	.string "את{EMIT_HEY} יכול להחליט עבורי, מאסטר?$"

gText_ApprenticeLevelModeThanks10::
	.string "אוקי, אז {STR_VAR_1} עדיף!\n"
	.string "אני אלך לרמה האחרת, אם כן!\p"
	.string "סתם צוחק!\n"
	.string "אני אציית ללימוד שלך, מאסטר!\p"
	.string "תודה, מאסטר!\n"
	.string "אני מקווה שתמשיך ללמד אותי!$"

gText_ApprenticePleaseTeach11::
	.string "הי!\n"
	.string "וזה מאיית הי, וזה אומר שלום!\p"
	.string "אני {STR_VAR_1}, הספן הראפר\n"
	.string "אני!\p"
	.string "תורך עכשיו, ספר לי קצת על\n"
	.string "עצמך, נסה זאת!\p"
	.string "אהה, אהה!\n"
	.string "השם שלך זה {PLAYER}{KUN},\l"
	.string "ופוקימון זה המשחק שלך!\p"
	.string "ואת{EMIT_HEY} בגיל עדין\n"
	.string "שבו כל העולם הוא הבמה שלך!\p"
	.string "בכל מקרה, אני רק רוצה לומר,\n"
	.string "שאת{EMIT_HEY} המאמן העשירי\l"
	.string "שדיברתי איתו היום.\p"
	.string "בוא נעשה מזה חגיגה!\n"
	.string "הפוך למנטור שלי לזכר הציון!$"

gText_ApprenticeRejectTeaching11::
	.string "אבל!\n"
	.string "את{EMIT_HEY} חייב לעבוד איתי!\p"
	.string "אל תהיה כזה מקניט!\n"
	.string "בבקשה תהפוך למנטור שלי, בבקשה!$"

gText_ApprenticeWhichLevelMode11::
	.string "זהו זה!\n"
	.string "{PLAYER}, יש לך את הרוח הזו!\p"
	.string "אז הנה השאלה הראשונה שלי\n"
	.string "שמבקשת את הצעתך!\p"
	.string "זה על מגדל הקרב,\n"
	.string "וזה תלוי בכוח שלי!\p"
	.string "רמה 05 ורמה פתוחה קיימות,\n"
	.string "איזו מהן טובה עבורי?$"

gText_ApprenticeLevelModeThanks11::
	.string "אוקי, {STR_VAR_1} זה זה, את{EMIT_HEY} אומר!\n"
	.string "אני אלך ואקבל את זה בדרכי!\p"
	.string "אם אי פעם אצטרך עצה,\n"
	.string "{PLAYER}, אני תמיד אקשיב למילה שלך!$"

gText_ApprenticePleaseTeach12::
	.string "היי, היי, את{EMIT_HEY} {PLAYER}?\n"
	.string "מה אני צריך לעשות? לדבר{ADD_YUD} אליך?\l"
	.string "למה לא? אני כבר מדבר אליך!\p"
	.string "{PLAYER}, את{EMIT_HEY} מופתע ממני?\n"
	.string "מוטב שאספר לך מי אני במקרה!\p"
	.string "{STR_VAR_1} זה מה שאת{EMIT_HEY} יכול לקרוא לי.\n"
	.string "הכוכב הבוהק ביותר בגיטרה,\l"
	.string "זה אני!\p"
	.string "את{EMIT_HEY} מקבל אותי?\n"
	.string "את{EMIT_HEY} מקבל אותי!\p"
	.string "המזל שלי בשיאו,\n"
	.string "אני אבקש ממך בקשה!\p"
	.string "{PLAYER}, ת{SWAP_NUN}{ADD_YUD} לי להיות חניך שלך!\n"
	.string "אני רוצה שתלמד אותי הכל!$"

gText_ApprenticeRejectTeaching12::
	.string "את{EMIT_HEY} מסרב לי, אם כן?\n"
	.string "אני פשוט אצטרך לבקש ממך שוב!\p"
	.string "{PLAYER}, אני מתחנן להיות חניך שלך!\n"
	.string "אני צריך שתלמד אותי הכל!$"

gText_ApprenticeWhichLevelMode12::
	.string "מזל, כן, ווהו!\n"
	.string "האם אני צריך לשאול אותך שאלה?\p"
	.string "מכיוון שאנחנו ליד מגדל הקרב,\n"
	.string "מה דעתך על שאלה על הכוח שלו?\p"
	.string "מבין האפשרויות שאת{EMIT_HEY} רואה,\n"
	.string "איזו היא הנכונה עבורי?$"

gText_ApprenticeLevelModeThanks12::
	.string "אם {STR_VAR_1} זה מה שאת{EMIT_HEY} מציע,\n"
	.string "זה חייב להיות הטוב ביותר!\p"
	.string "טוב, {PLAYER}, אני צריך לשוטט חופשי,\n"
	.string "אבל אל תשכח אותי.\p"
	.string "נתראה שוב, חברי החכם!$"

gText_ApprenticePleaseTeach13::
	.string "אה, היי! את{EMIT_HEY} שם!\n"
	.string "אני יכול לבקש שתעסה לי את הכתף?\p"
	.string "…כן, שם! זהו זה!\n"
	.string "אאוץ', אאוץ'! אווה, זה מרגיש נהדר!\p"
	.string "השם שלי הוא {STR_VAR_1}.\n"
	.string "אני מתאמן בקראטה, אבל הגוף שלי\l"
	.string "לא בנוי לספוג את ההתעללות…\p"
	.string "החלטתי שאלחם בפוקימונים\n"
	.string "ואחשל את עצמי.\p"
	.string "את{EMIT_HEY} {PLAYER}{KUN}, נכון?\n"
	.string "אלוף ליגת הפוקימונים?\p"
	.string "תקשיב, אני יכול לבקש שתיתן לי\n"
	.string "עצה?$"

gText_ApprenticeRejectTeaching13::
	.string "אה, למה?\p"
	.string "אני לא אהיה טרחה גדולה, אני מבטיח!\n"
	.string "בבקשה?$"

gText_ApprenticeWhichLevelMode13::
	.string "תודה. טוב מאוד מצדך!\n"
	.string "…שיעול! שיעול!\p"
	.string "אוו, אני צריך להתחשל מהר…\p"
	.string "אני אלך למגדל הקרב\n"
	.string "מיד, אבל מה יהיה טוב יותר\l"
	.string "עבורי? רמה 05 או רמה פתוחה?$"

gText_ApprenticeLevelModeThanks13::
	.string "הממ, בסדר. זה {STR_VAR_1}.\n"
	.string "אני אלך לשם מיד.\p"
	.string "אני מקווה שאוכל להמשיך לבקש ממך\n"
	.string "עזרה--אחרי הכל, את{EMIT_HEY} המנטור שלי!$"

gText_ApprenticePleaseTeach14::
	.string "אר… אמ…\n"
	.string "{PLAYER}{KUN}…?\p"
	.string "בבקשה, אל תסתכל עלי ככה.\n"
	.string "את{EMIT_HEY} גורם לי להיות מודע לעצמי.\p"
	.string "אני… אני {STR_VAR_1}.\p"
	.string "אני ממש נבוך לומר את זה,\n"
	.string "אבל אני חוקר חורבות עתיקות וכאלה.\p"
	.string "אני אפילו יותר נבוך להודות\n"
	.string "שאני מתעניין בחזית הקרב.\p"
	.string "{PLAYER}{KUN}, יש לך מוניטין כ\n"
	.string "מאמן קשוח…\p"
	.string "קשה לי לומר את זה,\n"
	.string "אבל אני רוצה לשאול משהו.\p"
	.string "תוכל{ADD_YUD} להיות המורה שלי\n"
	.string "ולתת לי עצה?$"

gText_ApprenticeRejectTeaching14::
	.string "בבקשה אל תנפנף אותי ככה!\n"
	.string "אני לא יכול לחיות עם ההשפלה.\p"
	.string "בבקשה תהיה המורה שלי!\n"
	.string "אני צריך את העצה שלך!$"

gText_ApprenticeWhichLevelMode14::
	.string "תתודה…\p"
	.string "אבל בבקשה אל תסתכל עלי ככה.\n"
	.string "זה גורם לי להיות מבולבל.\p"
	.string "בבקשה, ענה לי בלי להסתכל\n"
	.string "לי בעיניים.\p"
	.string "במגדל הקרב…\n"
	.string "באיזו רמה אני צריך לנסות?$"

gText_ApprenticeLevelModeThanks14::
	.string "אה… אוקי!\n"
	.string "אני אנסה את זה.\p"
	.string "אני מקווה שאוכל לקבל אתגר אמיץ\n"
	.string "בלי להיות מבולבל כל כך…\p"
	.string "תודה, {PLAYER}{KUN}.\n"
	.string "אם ניפגש שוב, אני מקווה שתהיה\l"
	.string "עוזר באותה מידה.$"

gText_ApprenticePleaseTeach15::
	.string "הממ? את{EMIT_HEY} נראה כמו {PLAYER}{KUN}…\n"
	.string "אבל את{EMIT_HEY} באמת אמיתי?\p"
	.string "את{EMIT_HEY} יכול לקרוא לי {STR_VAR_1}.\p"
	.string "שיחקתי עם הרעיון של\n"
	.string "להיות חניך של מאמן חזק.\p"
	.string "אז, אני חייב לומר שאני בר מזל שהגעת!\n"
	.string "…את{EMIT_HEY} באמת {PLAYER}{KUN}, כן?\p"
	.string "לא, לא, אם את{EMIT_HEY} אמיתי, זה בסדר.\n"
	.string "אני רק רוצה שתכיר בי\l"
	.string "כחניך שלך.$"

gText_ApprenticeRejectTeaching15::
	.string "אה?\n"
	.string "אבל מה יגרום לך לסרב?\p"
	.string "אני מתנצל על הספקנות שלי לגבי\n"
	.string "הזהות שלך.\p"
	.string "בבקשה קבל{ADD_YUD} את ההתנצלות שלי\n"
	.string "וקבל{ADD_YUD} אותי כחניך שלך.$"

gText_ApprenticeWhichLevelMode15::
	.string "את{EMIT_HEY} באמת מקבל אותי?\n"
	.string "אני לא רוצה לחגוג בטרם עת.\p"
	.string "אם זה נכון, אני מתנצל.\n"
	.string "אבל עכשיו, אני צריך את העצה שלך.\p"
	.string "אם אני אכנס למגדל הקרב,\n"
	.string "מה יהיה ראוי עבורי?\l"
	.string "רמה 05 או רמה פתוחה?$"

gText_ApprenticeLevelModeThanks15::
	.string "{STR_VAR_1}?\n"
	.string "את{EMIT_HEY} בטוח?\p"
	.string "אני מבין. אם זה המקרה, זה בסדר.\n"
	.string "אני מודה לך על זמנך.\p"
	.string "אני מבין שאני יכול להיות מעצבן, אבל זה משמח\n"
	.string "אותי שקיבלת אותי.\p"
	.string "בוא ניפגש שוב!$"

gText_ApprenticeWhatHeldItem0::
	.string "אנחה… יבבה…\n"
	.string "אוי, {PLAYER}!\p"
	.string "אני מסובך בדילמה\n"
	.string "שאני לא מצליח להחליט.\p"
	.string "אני לא מצליח להחליט מה אני צריך לגרום\n"
	.string "ל{STR_VAR_1} שלי להחזיק.\p"
	.string "בבקשה תגיד לי, {PLAYER}.\n"
	.string "איזה פריט אני צריך לגרום לו להחזיק?$"

gText_ApprenticeHoldNothing0::
	.string "אה, באמת? אני לא צריך לגרום\n"
	.string "ל{STR_VAR_1} שלי להחזיק כלום?$"

gText_ApprenticeThanksNoHeldItem0::
	.string "אה, אוקי! אני שמח שזה הוסדר!\n"
	.string "מדהים! פרוע! אווהו!\p"
	.string "תודה רבה לך!$"

gText_ApprenticeThanksHeldItem0::
	.string "אוי, אני כל כך שמח…\n"
	.string "אני חושב שיש לי גם את ה{STR_VAR_1} הזה.\p"
	.string "אני שמח שזה הוסדר!\n"
	.string "מדהים! פרוע! אווהו!\p"
	.string "תודה רבה לך!$"

gText_ApprenticeItemAlreadyRecommended0::
	.string "וואאאא! בבקשה אל תהיה מרושע!\p"
	.string "הפריט {STR_VAR_1} כבר\n"
	.string "הומלץ לי לפני כן, יבבה…\p"
	.string "או שאת{EMIT_HEY} מתכוון שאני לא צריך לגרום\n"
	.string "ל{STR_VAR_2} שלי להחזיק שום דבר?$"

gText_ApprenticeWhatHeldItem1::
	.string "יש! זה {PLAYER}!\n"
	.string "נהדר! רציתי לשאול אותך משהו!\p"
	.string "האם את{EMIT_HEY} גורם לפוקימונים שלך להחזיק פריטים?\n"
	.string "אני רוצה לגרום לשלי להחזיק פריטים, אבל…\p"
	.string "איזה פריט יהיה טוב עבור\n"
	.string "{STR_VAR_1} להחזיק?\p"
	.string "מה דעתך?$"

gText_ApprenticeHoldNothing1::
	.string "הא? את{EMIT_HEY} מתכוון שה{STR_VAR_1} שלי לא\n"
	.string "צריך להחזיק כלום?$"

gText_ApprenticeThanksNoHeldItem1::
	.string "אה, אני מבין! אני אעשה את זה!\n"
	.string "תודה שלימדת אותי!$"

gText_ApprenticeThanksHeldItem1::
	.string "אוי, וואו! {STR_VAR_1} אחד, הא?\n"
	.string "אוקי, אני אעשה את זה!\p"
	.string "תודה שלימדת אותי!$"

gText_ApprenticeItemAlreadyRecommended1::
	.string "אוי, אמ, לא, זה לא מה שהתכוונתי.\n"
	.string "אני רוצה לדעת על פריט אחר\l"
	.string "מהאלה שאני כבר מכיר.\p"
	.string "או שאת{EMIT_HEY} מתכוון שהפוקימון שלי לא\n"
	.string "צריך להחזיק כלום הפעם?$"

gText_ApprenticeWhatHeldItem2::
	.string "{PLAYER}, שלום!\n"
	.string "זה על ה{STR_VAR_1} שלי…\p"
	.string "אני רוצה לגרום לו להחזיק פריט טוב.\n"
	.string "מה יהיה טוב עבורו?$"

gText_ApprenticeHoldNothing2::
	.string "אה, אז ה{STR_VAR_1} שלי לא צריך\n"
	.string "להחזיק כלום?$"

gText_ApprenticeThanksNoHeldItem2::
	.string "אוקי, הבנתי!\n"
	.string "נתראה שוב!$"

gText_ApprenticeThanksHeldItem2::
	.string "אה, הפריט {STR_VAR_1}?\n"
	.string "הבנתי!\p"
	.string "אני אעשה את המיטב למצוא אחד!\n"
	.string "נתראה שוב!$"

gText_ApprenticeItemAlreadyRecommended2::
	.string "מישהו לימד אותי על\n"
	.string "ה{STR_VAR_1} כבר.\p"
	.string "אני רוצה שהפוקימון שלי יחזיק סוג\n"
	.string "אחר של פריט.\p"
	.string "או שאת{EMIT_HEY} חושב{ADD_TAF} ש{STR_VAR_2} לא\n"
	.string "צריך להחזיק כלום?$"

gText_ApprenticeWhatHeldItem3::
	.string "שלום, {PLAYER}…\n"
	.string "אני מצטער להפריע לך, אבל יש לי\l"
	.string "משהו אחר שרציתי לשאול אותך.\p"
	.string "אני לא חושב שאני מספיק טוב כדי לנצח\n"
	.string "במשחקים בעצמי, אז אני חושב\l"
	.string "לגרום ל{STR_VAR_1} שלי להחזיק פריט.\p"
	.string "אבל אני לא יודע מה יהיה טוב.\p"
	.string "{PLAYER}, בבקשה, תוכל{ADD_YUD} להחליט\n"
	.string "עבורי?$"

gText_ApprenticeHoldNothing3::
	.string "פוקימון ששייך למישהו כמוני\n"
	.string "יהיה עדיף בלי פריט?$"

gText_ApprenticeThanksNoHeldItem3::
	.string "אני מבין…\n"
	.string "את{EMIT_HEY} אומר שאני לא צריך להסתמך על פריטים.\l"
	.string "אני אעשה את המיטב שלא!\p"
	.string "תודה רבה לך!$"

gText_ApprenticeThanksHeldItem3::
	.string "הפריט {STR_VAR_1}, אוקי.\n"
	.string "אני לא בטוח אם אני יכול להשיג אחד…\l"
	.string "לא! אני אעשה את המיטב להשיג אותו.\p"
	.string "תודה רבה לך!$"

gText_ApprenticeItemAlreadyRecommended3::
	.string "אוי, אבל…\n"
	.string "אני חושב ששמעתי על זה לפני כן…\p"
	.string "האם זה אולי בגלל שלא טיפלתי\n"
	.string "בפריט {STR_VAR_1} טוב מספיק?\p"
	.string "או שאת{EMIT_HEY} מתכוון שאני לא צריך לגרום\n"
	.string "ל{STR_VAR_2} שלי להחזיק שום דבר?$"

gText_ApprenticeWhatHeldItem4::
	.string "אה, {PLAYER}{KUN}.\n"
	.string "יש משהו שרציתי לשאול אותך.\p"
	.string "את{EMIT_HEY} יודע{ADD_TAF}איך החלטת איזה\n"
	.string "פוקימון אני צריך שיהיה לי?\p"
	.string "אבל אף פעם לא שאלתי אותך איזה פריט\n"
	.string "הוא צריך להחזיק.\p"
	.string "מכיוון שכבר נתת לי עצה,\n"
	.string "מה דעתך לראות את זה עד הסוף?\p"
	.string "מה יהיה טוב? אני רוצה לגרום\n"
	.string "ל{STR_VAR_1} שלי להחזיק משהו.$"

gText_ApprenticeHoldNothing4::
	.string "אוי! אז ה{STR_VAR_1} שלי צריך לעשות\n"
	.string "את המיטב שהוא יכול בידיים ריקות?$"

gText_ApprenticeThanksNoHeldItem4::
	.string "אם את{EMIT_HEY} חושב{ADD_TAF} שזה הכי טוב, אני אעשה את זה.\p"
	.string "כשאני יודע שאת{EMIT_HEY} קיבלת את ההחלטה,\n"
	.string "{PLAYER}{KUN}, אני לא אהיה כל כך עצוב אם\l"
	.string "אפסיד.\p"
	.string "אוקי, אני אפנה אליך שוב לקבלת עצה.\n"
	.string "ביי!$"

gText_ApprenticeThanksHeldItem4::
	.string "הפריט {STR_VAR_1}, הא?\n"
	.string "לא רע. אני אשתמש בו!\p"
	.string "כשאני יודע שאת{EMIT_HEY} קיבלת את ההחלטה,\n"
	.string "{PLAYER}{KUN}, אני לא אהיה כל כך עצוב אם\l"
	.string "אפסיד.\p"
	.string "אוקי, אני אפנה אליך שוב לקבלת עצה.\n"
	.string "ביי!$"

gText_ApprenticeItemAlreadyRecommended4::
	.string "הא? מה את{EMIT_HEY} אומר?\n"
	.string "סיפרת לי על ה{STR_VAR_1}\l"
	.string "כבר לפני כן.\p"
	.string "או שאת{EMIT_HEY} מתכוון שה{STR_VAR_2} שלי צריך\n"
	.string "לעשות את המיטב שהוא יכול בידיים ריקות?$"

gText_ApprenticeWhatHeldItem5::
	.string "היי, {PLAYER}{KUN}!\p"
	.string "שנינו עסוקים, אבל נראה שאנחנו נתקלים\n"
	.string "אחד בשני לעיתים קרובות בכל זאת!\p"
	.string "היום אני צריך לעשות קצת הליכה,\n"
	.string "ניקיון, וצחצוח.\p"
	.string "אפילו לא היה לי זמן לקנות\n"
	.string "ל{STR_VAR_1} היקר שלי שום דבר.\p"
	.string "אין לי זמן, אז מה דעתך\n"
	.string "לתת לי עצה על מה אני צריך לגרום\l"
	.string "ל{STR_VAR_1} שלי להחזיק?$"

gText_ApprenticeHoldNothing5::
	.string "אה, אז אני בחור עסוק, את{EMIT_HEY} אומר\n"
	.string "שה{STR_VAR_1} שלי לא צריך כלום?$"

gText_ApprenticeThanksNoHeldItem5::
	.string "אוקי, הבנתי.\n"
	.string "אני לא אצטרך זמן בשביל זה.\p"
	.string "תודה היום!\n"
	.string "נתראה בסביבה!$"

gText_ApprenticeThanksHeldItem5::
	.string "אוקי, הבנתי.\n"
	.string "אני אמצא זמן איכשהו ואמצא\l"
	.string "את ה{STR_VAR_1} שהמלצת עליו.\p"
	.string "אני שמח שפגשתי מנטור טוב בך.\n"
	.string "תודה! נתראה בסביבה!$"

gText_ApprenticeItemAlreadyRecommended5::
	.string "הא? אני כבר יודע על\n"
	.string "ה{STR_VAR_1} הזה.\p"
	.string "אה, נכון, אני מבין.\n"
	.string "אז אני בחור עסוק, את{EMIT_HEY} אומר\l"
	.string "שה{STR_VAR_2} שלי לא צריך כלום?$"

gText_ApprenticeWhatHeldItem6::
	.string "היי, {PLAYER}! זה אני!\n"
	.string "אני צריך לנצל את הראש שלך שוב היום.\l"
	.string "בבקשה, אני צריך את העצה שלך!\p"
	.string "תופים, בבקשה!\n"
	.string "השאלה שיש לי היא…\p"
	.string "אם אני רוצה לגרום ל{STR_VAR_1} שלי להחזיק\n"
	.string "פריט, מה זה צריך להיות?$"

gText_ApprenticeHoldNothing6::
	.string "זה נכון? ה{STR_VAR_1} שלי לא\n"
	.string "צריך להחזיק פריט, את{EMIT_HEY} אומר.$"

gText_ApprenticeThanksNoHeldItem6::
	.string "אוקי, זה מה שאני אעשה!\p"
	.string "אני מניח שזה בערך כל מה שרציתי\n"
	.string "לשאול אותך היום.\p"
	.string "בוא ניפגש כאן שוב, אוקי?\n"
	.string "תודה!$"

gText_ApprenticeThanksHeldItem6::
	.string "אהה! {STR_VAR_1} אחד.\n"
	.string "איזו בחירה מגניבה!\l"
	.string "אני בהחלט אנסה את זה!\p"
	.string "אני מניח שזה בערך כל מה שרציתי\n"
	.string "לשאול אותך היום.\p"
	.string "בוא ניפגש כאן שוב, אוקי?\n"
	.string "תודה!$"

gText_ApprenticeItemAlreadyRecommended6::
	.string "חחחח! זה מטופש!\n"
	.string "כבר סיפרת לי על ה{STR_VAR_1}\l"
	.string "הזה לפני כן!\p"
	.string "את{EMIT_HEY} מרגיש בסדר, {PLAYER}?\p"
	.string "אה, רגע! ה{STR_VAR_2} שלי לא\n"
	.string "צריך להחזיק פריט, את{EMIT_HEY} אומר.$"

gText_ApprenticeWhatHeldItem7::
	.string "שלום, {PLAYER}. אני מקווה\n"
	.string "ששמרת על עצמך טוב.\p"
	.string "האם אוכל לפנות אליך לקבלת עצה?\p"
	.string "בקרב שנערך לאחרונה, היריב שלי\n"
	.string "נראה שנתן לפוקימון שלו\l"
	.string "פריט להחזיק.\p"
	.string "כתוצאה מכך, הובסתי…\p"
	.string "אני לא רוצה להישאר מאחור.\n"
	.string "אני רוצה לגרום ל{STR_VAR_1} שלי\l"
	.string "להחזיק פריט גם כן.\p"
	.string "זה ישמח אותי אם תוכל{ADD_YUD} להחליט\n"
	.string "מה יהיה נכון עבור הפוקימון שלי…$"

gText_ApprenticeHoldNothing7::
	.string "במילים אחרות… הפוקימון שלי לא\n"
	.string "צריך להחזיק פריט?$"

gText_ApprenticeThanksNoHeldItem7::
	.string "אני מבין בבירור עכשיו!\n"
	.string "אני אמשיך לנסות ככה.\p"
	.string "תודה, {PLAYER}.\n"
	.string "אני מקווה שאוכל לסמוך עליך שוב.\l"
	.string "בבקשה שמור על עצמך!$"

gText_ApprenticeThanksHeldItem7::
	.string "פריט {STR_VAR_1} אחד זה זה!\n"
	.string "אני אזמין אותו מיד.\p"
	.string "תודה, {PLAYER}.\n"
	.string "אני מקווה שאוכל לסמוך עליך שוב.\l"
	.string "בבקשה שמור על עצמך!$"

gText_ApprenticeItemAlreadyRecommended7::
	.string "כבר סיפרת לי על זה,\n"
	.string "וכבר יש לי את זה.\p"
	.string "או שאת{EMIT_HEY} אומר… הפוקימון שלי לא\n"
	.string "צריך להחזיק פריט?$"

gText_ApprenticeWhatHeldItem8::
	.string "איכס! {PLAYER}!\n"
	.string "אני… אני מאושר לראות אותך שוב!\p"
	.string "או-או-או! יש משהו שפשוט\n"
	.string "הייתי חייב לשאול אותך, {PLAYER}!\p"
	.string "בבקשה תחליט מה ה{STR_VAR_1}\n"
	.string "שלי צריך להחזיק!$"

gText_ApprenticeHoldNothing8::
	.string "אוי, וואו! לא ציפיתי לתשובה הזו!\n"
	.string "אז, פריט מוחזק לא נחוץ?$"

gText_ApprenticeThanksNoHeldItem8::
	.string "הבנה מושלמת!\n"
	.string "אני אמשיך בזה בלי פריט!\p"
	.string "אני מקווה שתהיה מוכן ללמד אותי\n"
	.string "עוד פעם אחרת.$"

gText_ApprenticeThanksHeldItem8::
	.string "{STR_VAR_1}! אני אשתמש בזה!\p"
	.string "אמ… יכול להיות, {PLAYER}, שגם את{EMIT_HEY}\n"
	.string "גורם לפוקימון שלך להחזיק את הפריט הזה?\p"
	.string "אני אדאג להשיג אותו!\n"
	.string "אני מקווה שתהיה מוכן ללמד אותי\l"
	.string "עוד פעם אחרת.$"

gText_ApprenticeItemAlreadyRecommended8::
	.string "אה? המלצת על ה{STR_VAR_1}\n"
	.string "הזה גם לפני כן.\p"
	.string "או שזה הדבר הטוב ביותר להחזיק?\n"
	.string "או שאת{EMIT_HEY} מתכוון שה{STR_VAR_2}\l"
	.string "שלי לא צריך להחזיק כלום?$"

gText_ApprenticeWhatHeldItem9::
	.string "הולה!\n"
	.string "המאסטרו שלי, {PLAYER}{KUN}!\p"
	.string "אני רוצה לבקש ממך עצה על\n"
	.string "כלי פוקימונים.\p"
	.string "מה את{EMIT_HEY} חושב{ADD_TAF} שיהיה טוב עבור\n"
	.string "ה{STR_VAR_1} שלי להחזיק?\p"
	.string "אל תתבייש עכשיו.\n"
	.string "בוא נפלוט את זה החוצה!$"

gText_ApprenticeHoldNothing9::
	.string "אה? אז את{EMIT_HEY} אומר שה{STR_VAR_1} שלי\n"
	.string "יכול לנצח בלי להחזיק שום פריט?$"

gText_ApprenticeThanksNoHeldItem9::
	.string "סי, בואנו!\n"
	.string "אני אתן את המיטב שלי, כאילו, סלאם!\p"
	.string "טוב, תודה, כמו תמיד!\n"
	.string "להתראות!$"

gText_ApprenticeThanksHeldItem9::
	.string "אהה, זה {STR_VAR_1} אחד?\n"
	.string "סי, בואנו!\l"
	.string "אני אלך למצוא לי אחד, כאילו, באם!\p"
	.string "טוב, תודה, כמו תמיד!\n"
	.string "להתראות!$"

gText_ApprenticeItemAlreadyRecommended9::
	.string "לא, לא! כבר סיפרת לי על\n"
	.string "ה{STR_VAR_1} הזה לפני כן.\p"
	.string "אה, חכה רגע כאן…\n"
	.string "אז, את{EMIT_HEY} אומר שה{STR_VAR_2} שלי\l"
	.string "יכול לנצח בלי להחזיק שום פריט?$"

gText_ApprenticeWhatHeldItem10::
	.string "{PLAYER}{KUN}, משהו לא יאומן\n"
	.string "קרה!\p"
	.string "התעוררתי הבוקר, ולפוקימון שלי\n"
	.string "היו 10 גושי זהב!\p"
	.string "כמובן שאני משקר!\n"
	.string "וואחחחח!\p"
	.string "זה לא שקר, למרות זאת.\n"
	.string "אני לא כל כך טוב בלחשוב על\l"
	.string "איזה פריטים פוקימונים צריכים להחזיק.\p"
	.string "אז, מה דעתך שתחליט עבורי מה\n"
	.string "ה{STR_VAR_1} שלי צריך להחזיק, מאסטר?$"

gText_ApprenticeHoldNothing10::
	.string "מה זה אומר?\n"
	.string "לא לגרום לו להחזיק שום דבר?$"

gText_ApprenticeThanksNoHeldItem10::
	.string "אוקי, אז הוא לא צריך להחזיק כלום.\n"
	.string "אם כך, מוטב שאשיג לו משהו!\p"
	.string "סתם צוחק!\n"
	.string "אני אציית ללימוד שלך, מאסטר!\p"
	.string "תודה, מאסטר!\n"
	.string "אני מקווה שתמשיך ללמד אותי!$"

gText_ApprenticeThanksHeldItem10::
	.string "אוקי, אז זה {STR_VAR_1} אחד!\n"
	.string "אני אגרום לו להחזיק כל דבר חוץ מזה!\p"
	.string "סתם צוחק!\n"
	.string "אני אציית ללימוד שלך, מאסטר!\p"
	.string "תודה, מאסטר!\n"
	.string "אני מקווה שתמשיך ללמד אותי!$"

gText_ApprenticeItemAlreadyRecommended10::
	.string "אמ, סיפרת לי על זה לפני כן,\n"
	.string "לא?\p"
	.string "אין משהו אחר?\p"
	.string "או שאת{EMIT_HEY} מתכוון, אל תגרום\n"
	.string "ל{STR_VAR_2} שלי להחזיק שום דבר?$"

gText_ApprenticeWhatHeldItem11::
	.string "הי!\n"
	.string "וזה מאיית הי!\p"
	.string "הספן הראפר אני!\n"
	.string "אני מציג בפניך שאלה\l"
	.string "שהיא די מגניבה!\p"
	.string "זו שאלת פריט\n"
	.string "שמבקשת את הצעתך!\p"
	.string "ה{STR_VAR_1} שלי צריך פריט להחזיק,\n"
	.string "מה זה צריך להיות, אם יורשה לי להיות נועז?$"

gText_ApprenticeHoldNothing11::
	.string "זה נכון?\n"
	.string "ה{STR_VAR_1} שלי לא צריך להיות\l"
	.string "מחזיק שום דבר חזק?$"

gText_ApprenticeThanksNoHeldItem11::
	.string "אוקי, אני שומע אותך, בטח שאני שומע!\n"
	.string "הפוקימון שלי ילך בידיים ריקות, גם כן!\p"
	.string "אם אי פעם אצטרך עצה,\n"
	.string "{PLAYER}, אני תמיד אקשיב למילה שלך!$"

gText_ApprenticeThanksHeldItem11::
	.string "אוקי, {STR_VAR_1} אחד,\n"
	.string "זה מה שאני אשתמש בו.\l"
	.string "צדקתי שבחרתי בך לבחור!\p"
	.string "אם אי פעם אצטרך עצה,\n"
	.string "{PLAYER}, אני תמיד אקשיב למילה שלך!$"

gText_ApprenticeItemAlreadyRecommended11::
	.string "אוקי, {STR_VAR_1} אחד, את{EMIT_HEY} אומר?\n"
	.string "אמרת לי את זה ביום אחר.\l"
	.string "אני צריך רעיון חדש, דרך חדשה לגמרי.\p"
	.string "או, מה, זה נכון?\n"
	.string "הפוקימון שלי לא צריך להחזיק\l"
	.string "שום דבר חזק?$"

gText_ApprenticeWhatHeldItem12::
	.string "היי, היי, {PLAYER}!\n"
	.string "מצאתי אותך שוב היום!\p"
	.string "מה אני צריך לעשות? לקבל את העצה שלך?\n"
	.string "למה לא? אני כבר מדבר אליך!\p"
	.string "{PLAYER}, את{EMIT_HEY} נגעל ממני?\n"
	.string "לא, אין סיכוי, זה לא יכול להיות.\p"
	.string "תקשיב לי?\n"
	.string "אני מחפש עצה--זה מה\l"
	.string "שאני מדבר עליו.\p"
	.string "זה על פריט מוחזק עבור\n"
	.string "ה{STR_VAR_1} שלי שיהיה טוב.\l"
	.string "חוסר ההחלטה שלי גורם לי להיות מדוכא.$"

gText_ApprenticeHoldNothing12::
	.string "ה{STR_VAR_1} שלי לא צריך כלום?\n"
	.string "לא צריך להחזיק כלום?$"

gText_ApprenticeThanksNoHeldItem12::
	.string "אם לא להחזיק כלום זה הכי טוב,\n"
	.string "אני אעשה כפי שאת{EMIT_HEY} מציע!\p"
	.string "טוב, {PLAYER}, אני צריך לשוטט חופשי,\n"
	.string "אבל אל תשכח אותי.\p"
	.string "נתראה שוב, חברי החכם!$"

gText_ApprenticeThanksHeldItem12::
	.string "אם להחזיק את ה{STR_VAR_1} זה\n"
	.string "הכי טוב, אני אעשה כפי שאת{EMIT_HEY} מציע!\p"
	.string "טוב, {PLAYER}, אני צריך לשוטט חופשי,\n"
	.string "אבל אל תשכח אותי.\p"
	.string "נתראה שוב, חברי החכם!$"

gText_ApprenticeItemAlreadyRecommended12::
	.string "האם לא שמעתי על ה{STR_VAR_1}\n"
	.string "הזה לפני כן?\l"
	.string "אני בטוח שכן, זה בטוח!\p"
	.string "אני צריך משהו חדש!\n"
	.string "או, ה{STR_VAR_2} שלי לא צריך כלום?\l"
	.string "לא צריך להחזיק כלום?$"

gText_ApprenticeWhatHeldItem13::
	.string "גוואח! אאוץ'! {PLAYER}{KUN}, היד שלי שבורה!\n"
	.string "אל תיגע בה, בבקשה!\p"
	.string "בטח שברתי אותה בזמן שניסיתי\n"
	.string "פריטים מוחזקים שונים עם הפוקימונים\l"
	.string "שלי.\p"
	.string "אז, כשהדברים ככה,\n"
	.string "אני צריך שתחליט עבורי.\p"
	.string "{PLAYER}{KUN}, מה את{EMIT_HEY} חושב{ADD_TAF} שיהיה\n"
	.string "טוב ל{STR_VAR_1} שלי להחזיק?$"

gText_ApprenticeHoldNothing13::
	.string "אאוץ'…\p"
	.string "אז ההצעה שלך היא שה{STR_VAR_1}\n"
	.string "שלי לא צריך להחזיק כלום?$"

gText_ApprenticeThanksNoHeldItem13::
	.string "הממ, בסדר. זה יהיה קל יותר\n"
	.string "עבורי, כפי שהדברים עכשיו.\p"
	.string "אני מקווה שאוכל להמשיך לבקש ממך\n"
	.string "עזרה ככה.$"

gText_ApprenticeThanksHeldItem13::
	.string "הממ, בסדר. זה {STR_VAR_1} אחד.\n"
	.string "היד של הפוקימון שלי בסדר, אז אני אגרום\l"
	.string "לו להחזיק את הפריט הזה מיד.\p"
	.string "אני מקווה שאוכל להמשיך לבקש ממך\n"
	.string "עזרה ככה.$"

gText_ApprenticeItemAlreadyRecommended13::
	.string "לא, לא, סיפרת לי על ה{STR_VAR_1}\n"
	.string "הזה לפני כן, זוכר?\p"
	.string "מה דעתך לספר לי משהו\n"
	.string "אפילו טוב יותר?\p"
	.string "אה, רגע שני.\n"
	.string "אז ההצעה שלך היא שה{STR_VAR_2}\l"
	.string "שלי לא צריך להחזיק כלום?$"

gText_ApprenticeWhatHeldItem14::
	.string "אר… אמ…\n"
	.string "{PLAYER}{KUN}…\p"
	.string "בבקשה, אל תסתכל עלי ככה.\n"
	.string "לפוקימונים שלי אין כלום.\p"
	.string "אני… אני ממש נבוך בקשר לזה,\n"
	.string "אבל אני באמת צריך את העצה שלך.\p"
	.string "אני לא מצליח להחליט איזה פריט מוחזק\n"
	.string "יהפוך את ה{STR_VAR_1} שלי לחזק.\p"
	.string "{PLAYER}{KUN}, מה את{EMIT_HEY} חושב{ADD_TAF} שיהיה\n"
	.string "טוב?$"

gText_ApprenticeHoldNothing14::
	.string "אה… אם כך, את{EMIT_HEY} חושב{ADD_TAF} שיהיה טוב יותר\n"
	.string "אם ל{STR_VAR_1} שלי לא יהיה פריט?$"

gText_ApprenticeThanksNoHeldItem14::
	.string "אה… אוקי!\n"
	.string "אני אלך בלי פריט.\p"
	.string "זה מעצבן עצבים, למרות זאת.\n"
	.string "זה לא יהיה יותר מדי מגניב?\p"
	.string "תודה, {PLAYER}{KUN}.\n"
	.string "אם ניפגש שוב, אני מקווה שתהיה\l"
	.string "עוזר באותה מידה.$"

gText_ApprenticeThanksHeldItem14::
	.string "אה… אוקי!\n"
	.string "אני אלך עם ה{STR_VAR_1} הזה.\p"
	.string "זה מעצבן עצבים, למרות זאת.\n"
	.string "זה לא יהיה יותר מדי מגניב?\p"
	.string "תודה, {PLAYER}{KUN}.\n"
	.string "אם ניפגש שוב, אני מקווה שתהיה\l"
	.string "עוזר באותה מידה.$"

gText_ApprenticeItemAlreadyRecommended14::
	.string "אבבל כבר שמעתי על זה.\p"
	.string "בבקשה אל תנפנף אותי ככה!\n"
	.string "אני לא יכול לחיות עם ההשפלה.\p"
	.string "אה… האם אני מסיק מסקנות מוקדמות?\n"
	.string "את{EMIT_HEY} חושב{ADD_TAF} שיהיה טוב יותר אם\l"
	.string "ל{STR_VAR_2} שלי לא יהיה פריט?$"

gText_ApprenticeWhatHeldItem15::
	.string "הממ? את{EMIT_HEY} נראה כמו {PLAYER}{KUN}…\n"
	.string "אבל את{EMIT_HEY} באמת?\l"
	.string "אולי את{EMIT_HEY} תאום?\p"
	.string "אוי, לא, לא, לא, אל תדאג!\n"
	.string "אם את{EMIT_HEY} באמת {PLAYER}, בבקשה\l"
	.string "תשכח מהגסות רוח שלי.\p"
	.string "מה שהייתי רוצה זה עוד\n"
	.string "מהעצה הטובה שלך.\p"
	.string "יש לי כאן את ה{STR_VAR_1} שלי שאני רוצה\n"
	.string "לגרום לו להחזיק פריט נוח.\p"
	.string "מה יהיה ראוי עבורו?$"

gText_ApprenticeHoldNothing15::
	.string "עדיף אם הוא יחזיק כלום?\n"
	.string "את{EMIT_HEY} בטוח?$"

gText_ApprenticeThanksNoHeldItem15::
	.string "אני מבין. אם זה המקרה, זה בסדר.\n"
	.string "אני מודה לך על זמנך.\p"
	.string "בוא ניפגש שוב!$"

gText_ApprenticeThanksHeldItem15::
	.string "{STR_VAR_1} אחד?\n"
	.string "את{EMIT_HEY} בטוח?\p"
	.string "אני מבין. אם זה המקרה, זה בסדר.\n"
	.string "אני מודה לך על זמנך.\p"
	.string "אני מקווה שהפוקימון שלי יוכל\n"
	.string "להשתמש בו כראוי.\p"
	.string "בוא ניפגש שוב!$"

gText_ApprenticeItemAlreadyRecommended15::
	.string "לא, לא, חכה רגע.\n"
	.string "אני מאמין שלימדת אותי את זה לפני כן.\p"
	.string "הייתי רוצה שתמליץ לי\n"
	.string "על משהו אחר הפעם.\p"
	.string "אולי את{EMIT_HEY} מציע שה{STR_VAR_2}\n"
	.string "שלי צריך להחזיק כלום?\l"
	.string "את{EMIT_HEY} בטוח?$"

gText_ApprenticeWhichMonFirst0::
	.string "וואא, {PLAYER}!\n"
	.string "יש לי דילמה, יבבה…\p"
	.string "אני רוצה להתחיל להילחם באנשים אחרים,\n"
	.string "אבל אני לא יודע מה לעשות.\p"
	.string "איך אני צריך לסדר את הפוקימונים שלי\n"
	.string "כדי שהם יהיו הכי חזקים?\p"
	.string "בבקשה תגיד לי, {PLAYER}.\n"
	.string "אם היית אני, איזה מהפוקימונים האלה\l"
	.string "היית שולח ראשון?$"

gText_ApprenticeMonFirstThanks0::
	.string "ה{STR_VAR_1} שלי צריך לצאת ראשון?\n"
	.string "וואאאא!\p"
	.string "אוי! אני כל כך מצטער!\n"
	.string "עשית אותי שמח שבחרת\l"
	.string "את הפוקימון הראשון שלי, וזה גרם לי לבכות…\p"
	.string "תודה רבה לך!$"

gText_ApprenticeWhichMonFirst1::
	.string "יש! זה {PLAYER}!\n"
	.string "נהדר! רציתי לשאול אותך משהו!\p"
	.string "אמ, מבין הפוקימונים שלי, מי את{EMIT_HEY}\n"
	.string "חושב צריך לצאת ראשון?$"

gText_ApprenticeMonFirstThanks1::
	.string "ה{STR_VAR_1} שלי? זה נכון.\n"
	.string "אוקי, אני אעשה את זה!\p"
	.string "תודה שלימדת אותי!$"

gText_ApprenticeWhichMonFirst2::
	.string "{PLAYER}, שלום!\p"
	.string "אני חושב שבקרב, זה מאוד חשוב\n"
	.string "איזה פוקימון יוצא ראשון.\p"
	.string "מבין הפוקימונים שיש לי,\n"
	.string "איזה יהיה טוב לשלוח ראשון?$"

gText_ApprenticeMonFirstThanks2::
	.string "ה{STR_VAR_1} שלי יוצא ראשון?\n"
	.string "אוקי, הבנתי!\p"
	.string "נתראה שוב!$"

gText_ApprenticeWhichMonFirst3::
	.string "שלום, {PLAYER}…\n"
	.string "אני מצטער להפריע לך שוב עם\l"
	.string "שאלה נוספת.\p"
	.string "יש לי כל כך מעט בטחון, אני לא\n"
	.string "יודע מה הייתי עושה בלעדיך, {PLAYER}.\p"
	.string "אולי זה בזבוז זמן עבורי\n"
	.string "אפילו לדאוג בקשר לזה, אבל אני פשוט לא מצליח\l"
	.string "להחליט משהו…\p"
	.string "איזה מהפוקימונים שלי אני צריך לשלוח\n"
	.string "ראשון בקרב?$"

gText_ApprenticeMonFirstThanks3::
	.string "ה{STR_VAR_1} שלי?\n"
	.string "הבנתי!\p"
	.string "אני לא מאמין שאת{EMIT_HEY} טורח\n"
	.string "לענות על השאלות שלי כל כך הרבה פעמים!\p"
	.string "אני כל כך אסיר תודה שאת{EMIT_HEY} אפילו\n"
	.string "מדבר איתי… תודה!$"

gText_ApprenticeWhichMonFirst4::
	.string "אה, {PLAYER}{KUN}! זה אני!\n"
	.string "אני כל כך שמח לראות אותך כי יש לי\l"
	.string "את הבעיה הקטנה הזו.\p"
	.string "אני לא מצליח להחליט איך הפוקימונים שלי\n"
	.string "צריכים להיות מסודרים. את{EMIT_HEY} יכול להחליט עבורי?\p"
	.string "אה, את{EMIT_HEY} לא צריך להחליט את כל\n"
	.string "הקבוצה עכשיו.\p"
	.string "מה דעתך שתחליט רק את הפוקימון\n"
	.string "הראשון עבורי?$"

gText_ApprenticeMonFirstThanks4::
	.string "ה{STR_VAR_1} שלי? זה נהדר!\p"
	.string "כשאני יודע שאת{EMIT_HEY} קיבלת את ההחלטה,\n"
	.string "{PLAYER}{KUN}, אני לא אהיה כל כך עצוב אם\l"
	.string "אפסיד.\p"
	.string "אוקי, אני אפנה אליך שוב לקבלת עצה.\n"
	.string "ביי!$"

gText_ApprenticeWhichMonFirst5::
	.string "היי, המורה שלי {PLAYER}{KUN}!\n"
	.string "אני עסוק שוב היום!\p"
	.string "אני צריך לעשות קצת רכיבה על אופניים, קניות,\n"
	.string "ומלמול.\p"
	.string "אפילו לא היה לי זמן להחליט\n"
	.string "איך לסדר את צוות הפוקימונים שלי.\p"
	.string "אז, מה דעתך לבדוק את הצוות שלי?\n"
	.string "איזה מהם צריך לצאת ראשון?$"

gText_ApprenticeMonFirstThanks5::
	.string "אוקי, הבנתי.\n"
	.string "יש לי מספיק זמן לפחות לשים\l"
	.string "את ה{STR_VAR_1} שלי בראש התור!\p"
	.string "אופס, החברה שלי מחכה!\n"
	.string "תודה! נתראה בסביבה!$"

gText_ApprenticeWhichMonFirst6::
	.string "יוהו! היי, {PLAYER}!\n"
	.string "את{EMIT_HEY} תמיד מסתובב ונראה קשוח!\p"
	.string "תקשיב, אני צריך ממך משהו\n"
	.string "שוב! זה הדבר הרגיל!\p"
	.string "תופים, בבקשה!\n"
	.string "השאלה שיש לי היא על הצוות שלי.\p"
	.string "איזה פוקימון שלי צריך להיות הראשון\n"
	.string "שיצא לקרב?$"

gText_ApprenticeMonFirstThanks6::
	.string "הממ!\n"
	.string "ה{STR_VAR_1} שלי, את{EMIT_HEY} אומר!\l"
	.string "תודה על תשובה הכי מגניבה!\p"
	.string "אני מניח שזה בערך כל מה שרציתי\n"
	.string "לשאול אותך היום.\p"
	.string "בוא ניפגש כאן שוב, אוקי?\n"
	.string "תודה!$"

gText_ApprenticeWhichMonFirst7::
	.string "תודה רבה לך שעצרת\n"
	.string "לשוחח איתי, {PLAYER}.\p"
	.string "אני יודע שאני מנצל את טוב לבך,\n"
	.string "אבל האם אוכל לבקש עצה?\p"
	.string "הייתי רוצה שתחליט על הסדר\n"
	.string "של צוות הפוקימונים שלי.\p"
	.string "זה ישמח אותי אם תוכל{ADD_YUD} להחליט\n"
	.string "איזה פוקימון צריך לבוא ראשון.$"

gText_ApprenticeMonFirstThanks7::
	.string "ה{STR_VAR_1} שלי זה זה!\n"
	.string "אני אשים אותו ראשון מיד!\p"
	.string "תודה, {PLAYER}.\n"
	.string "אני מקווה שאוכל לסמוך עליך שוב.\l"
	.string "בבקשה שמור על עצמך!$"

gText_ApprenticeWhichMonFirst8::
	.string "איכס! {PLAYER}!\n"
	.string "אני… אני מאושר לראות אותך שוב!\p"
	.string "הפוקימונים שלי הפכו הרבה יותר\n"
	.string "חזקים!\p"
	.string "אבל אני לא תמיד מנצח. נראה שזה תלוי\n"
	.string "באיזה פוקימון יוצא ראשון.\p"
	.string "{PLAYER}, בבקשה, אני צריך את עזרתך!\p"
	.string "בבקשה תחליט איזה מהפוקימונים שלי\n"
	.string "צריך לצאת ראשון!$"

gText_ApprenticeMonFirstThanks8::
	.string "אנחה… אני מוצף באושר…\p"
	.string "זה כמו חלום שאת{EMIT_HEY} מחליט\n"
	.string "עבורי, {PLAYER}.\p"
	.string "אבל הבנה מושלמת!\n"
	.string "אני אלך עם ה{STR_VAR_1} שלי ראשון!\p"
	.string "אני מקווה שתהיה מוכן ללמד אותי\n"
	.string "עוד פעם אחרת.$"

gText_ApprenticeWhichMonFirst9::
	.string "שלום, שלום!\n"
	.string "המנטור שלי, {PLAYER}{KUN}!\l"
	.string "הצף אותי עם העצה החכמה שלך היום!\p"
	.string "את{EMIT_HEY} מבין, הרכבתי צוות של\n"
	.string "שלושה פוקימונים. עד כה הכל טוב.\p"
	.string "אבל סדר הקרב של הצוות עדיין\n"
	.string "לא הוסדר.\p"
	.string "כאן את{EMIT_HEY} נכנס לתמונה, {PLAYER}{KUN}!\n"
	.string "את{EMIT_HEY} מחליט איזה פוקימון מוביל!\p"
	.string "אל תתבייש עכשיו.\n"
	.string "בוא נפלוט את זה החוצה!$"

gText_ApprenticeMonFirstThanks9::
	.string "אהה, ה{STR_VAR_1} שלי מוביל!\n"
	.string "אוקי, א-אוקי!\l"
	.string "אני אסדר מחדש את המערך, כאילו, וואם!\p"
	.string "טוב, תודה, כמו תמיד!\n"
	.string "להתראות!$"

gText_ApprenticeWhichMonFirst10::
	.string "{PLAYER}{KUN}, תקשיב!\n"
	.string "זה משבר!\p"
	.string "הפוקימונים שלי, שלושתם, נכנסים\n"
	.string "לקרב בבת אחת!\p"
	.string "כמובן שזה בלתי אפשרי!\n"
	.string "וואחחחח!\p"
	.string "זה לא שקר, למרות זאת.\n"
	.string "אני לא כל כך טוב בלחשוב על\l"
	.string "איך אני צריך לסדר את הפוקימונים שלי.\p"
	.string "אז, מה דעתך שתחליט עבורי איזה\n"
	.string "פוקימון צריך לצאת ראשון, מאסטר?$"

gText_ApprenticeMonFirstThanks10::
	.string "אוקי, אז זה ה{STR_VAR_1} שלי שבחרת?\n"
	.string "אני אתן לכל אחד חוץ מזה לצאת ראשון!\p"
	.string "סתם צוחק!\n"
	.string "אני אציית ללימוד שלך, מאסטר!\p"
	.string "תודה, מאסטר!\n"
	.string "אני מקווה שתמשיך ללמד אותי!$"

gText_ApprenticeWhichMonFirst11::
	.string "הי!\n"
	.string "וזה מאיית הי!\p"
	.string "הספן הראפר אני!\n"
	.string "אני מציג בפניך שאלה\l"
	.string "שהיא די מגניבה!\p"
	.string "זו שאלת סידור צוות\n"
	.string "שמבקשת את הצעתך!\p"
	.string "מבין כל אלה, מי צריך לצאת ראשון\n"
	.string "כראשון במקום?$"

gText_ApprenticeMonFirstThanks11::
	.string "אוקי, אני שומע אותך, בטח שאני שומע!\n"
	.string "אני אחליף אותם, זה מה שאני אעשה!\p"
	.string "אם אי פעם אצטרך עצה,\n"
	.string "{PLAYER}, אני תמיד אקשיב למילה שלך!$"

gText_ApprenticeWhichMonFirst12::
	.string "יהו, {PLAYER}!\n"
	.string "מה שלומך?\p"
	.string "מה אני צריך לעשות? לשאול עכשיו?\n"
	.string "אהה, יש לי משהו לשאול!\l"
	.string "את{EMIT_HEY} מקבל אותי?\l"
	.string "את{EMIT_HEY} מקבל אותי!\p"
	.string "את{EMIT_HEY} צריך להחליט, מי מה\n"
	.string "פוקימונים שלי הוא הראשון לרכב!\l"
	.string "לקרב, אני מתכוון לומר.$"

gText_ApprenticeMonFirstThanks12::
	.string "ה{STR_VAR_1} שלי? כן!\n"
	.string "זה יספיק, אין מצוקה!\p"
	.string "טוב, {PLAYER}, אני צריך לשוטט חופשי,\n"
	.string "אבל אל תשכח אותי.\p"
	.string "נתראה שוב, חברי החכם!$"

gText_ApprenticeWhichMonFirst13::
	.string "…אוף…אאוץ'… {PLAYER}{KUN}…\n"
	.string "הבטן שלי כואבת פתאום…\p"
	.string "…זה משתפר עכשיו…\p"
	.string "בטח דאגתי לעצמי עד בחילה מלחשוב\n"
	.string "איך אני צריך לסדר את חבורת\l"
	.string "הפוקימונים שלי.\p"
	.string "אז, כשהדברים ככה,\n"
	.string "אני צריך שתחליט עבורי.\p"
	.string "{PLAYER}{KUN}, איזה מהפוקימונים שלי צריך\n"
	.string "לצאת ראשון? כדי שאנצח, אני מתכוון.$"

gText_ApprenticeMonFirstThanks13::
	.string "הממ, בסדר.\n"
	.string "ה{STR_VAR_1} שלי יוצא ראשון.\p"
	.string "אני אתקן את המערך ככה אחרי\n"
	.string "שאוכל ארוחת ערב.\p"
	.string "אני מקווה שאוכל להמשיך לבקש ממך\n"
	.string "עזרה ככה.$"

gText_ApprenticeWhichMonFirst14::
	.string "אר… אמ…\n"
	.string "{PLAYER}{KUN}?\p"
	.string "בבקשה, אל תסתכל עלי ככה.\n"
	.string "את{EMIT_HEY} גורם לי להרגיש מבולבל.\p"
	.string "אמ…\n"
	.string "אני באמת צריך את העצה שלך.\p"
	.string "זה גורם לי להיות ביישן לומר את זה,\n"
	.string "אבל בחרתי בצוות של 3 פוקימונים.\l"
	.string "אני לא מצליח להחליט על הסדר, למרות זאת.\p"
	.string "איזה פוקימון אני צריך לשלוח ראשון\n"
	.string "כדי שלפחות אראה מסוגל?$"

gText_ApprenticeMonFirstThanks14::
	.string "אה… אוקי!\n"
	.string "אני אוביל עם ה{STR_VAR_1} שלי.\p"
	.string "אני מקווה שאוכל לעשות את המיטב בלי\n"
	.string "להיות מבולבל כל כך.\p"
	.string "תודה, {PLAYER}{KUN}.\n"
	.string "אם ניפגש שוב, אני מקווה שתהיה\l"
	.string "עוזר באותה מידה.$"

gText_ApprenticeWhichMonFirst15::
	.string "הממ? את{EMIT_HEY} נראה כמו {PLAYER}{KUN}…\n"
	.string "אבל את{EMIT_HEY} באמת?\l"
	.string "אולי את{EMIT_HEY} כפיל חכם?\p"
	.string "אוי, לא, לא, לא, אל תדאג!\n"
	.string "אם את{EMIT_HEY} באמת {PLAYER}, בבקשה\l"
	.string "תשכח מהגסות רוח שלי.\p"
	.string "מה שהייתי רוצה זה את העצה הטובה שלך.\p"
	.string "יש לי כאן את צוות הפוקימונים שלי.\n"
	.string "הייתי רוצה שתגיד לי איזה מהם\l"
	.string "צריך לצאת ראשון בקרב.$"

gText_ApprenticeMonFirstThanks15::
	.string "ה{STR_VAR_1} שלי…\n"
	.string "את{EMIT_HEY} לא צוחק עלי?\p"
	.string "אני מבין. אם זה המקרה, זה בסדר.\n"
	.string "אני מודה לך על זמנך.\p"
	.string "אני כפי שאת{EMIT_HEY} רואה, אבל אני אעשה\n"
	.string "את המיטב שלי.\p"
	.string "בוא ניפגש שוב!$"

gText_ApprenticeWhichMon0::
	.string "מנוזל…\n"
	.string "אוי, {PLAYER}!\p"
	.string "איזה תזמון מושלם!\n"
	.string "יש משהו שאני פשוט לא מצליח להחליט…\p"
	.string "אני לא מצליח להחליט באיזה פוקימון אני צריך\n"
	.string "להשתמש.\p"
	.string "אני לא מצליח להחליט בין הפוקימונים\n"
	.string "{STR_VAR_1} ו{STR_VAR_2}…\p"
	.string "{PLAYER}, איזה מהם את{EMIT_HEY} חושב{ADD_TAF} שיתן\n"
	.string "אפילו לי סיכוי לנצח?$"

gText_ApprenticeMonThanks0::
	.string "מנוזל… אני… אני מבין!\n"
	.string "אוי! אני כל כך מצטער!\l"
	.string "עשית אותי כל כך שמח, אני בוכה…\p"
	.string "אני אעשה את המיטב לתפוס {STR_VAR_1}\n"
	.string "אחד!\p"
	.string "תודה רבה לך!$"

gText_ApprenticeWhichMon1::
	.string "יש! זה {PLAYER}!\n"
	.string "יש, הגעת בזמן הנכון, גם כן!\l"
	.string "אני צריך את העצה שלך שוב!\p"
	.string "אמ, אני מבולבל--האם אני צריך להשתמש\n"
	.string "ב{STR_VAR_1} שלי או ב{STR_VAR_2}…\p"
	.string "איזה מהם את{EMIT_HEY} חושב{ADD_TAF} שאני צריך לגדל,\n"
	.string "{PLAYER}?$"

gText_ApprenticeMonThanks1::
	.string "אה, אז ה{STR_VAR_1} שלי עדיף!\n"
	.string "אוקי, אני אעשה את זה!\p"
	.string "תודה שלימדת אותי!$"

gText_ApprenticeWhichMon2::
	.string "{PLAYER}, שלום!\n"
	.string "יש לי שאלה שרציתי לשאול.\p"
	.string "אני בדילמה האם אני צריך\n"
	.string "לגדל {STR_VAR_1} אחד או {STR_VAR_2}.\p"
	.string "איזה פוקימון את{EMIT_HEY} חושב{ADD_TAF} שיהיה\n"
	.string "חזק יותר?$"

gText_ApprenticeMonThanks2::
	.string "{STR_VAR_1} זו הבחירה שלך?\n"
	.string "אוקי, הבנתי!\p"
	.string "אני אלך לתפוס {STR_VAR_1} חזק\n"
	.string "מיד!\p"
	.string "נתראה שוב!$"

gText_ApprenticeWhichMon3::
	.string "שלום, {PLAYER}…\p"
	.string "אמ, בטח כבר שכחת\n"
	.string "ממישהו כמוני…\p"
	.string "…אבל זה לא משנה אם את{EMIT_HEY}\n"
	.string "יכול לתת לי עצה…\p"
	.string "אני לא מצליח להחליט על סוג הפוקימון\n"
	.string "האחד שאני צריך לגדל…\p"
	.string "צמצמתי את האפשרויות לפוקימונים\n"
	.string "{STR_VAR_1} ו{STR_VAR_2}, אבל כאן\l"
	.string "נתקעתי…\p"
	.string "{PLAYER}, את{EMIT_HEY} בטח לא רוצה\n"
	.string "לטרוח, אבל בבקשה תחליט עבורי.$"

gText_ApprenticeMonThanks3::
	.string "אבל האם {STR_VAR_1} פראי בכלל ישים\n"
	.string "לב אלי?\p"
	.string "אני אנסה!\p"
	.string "אבל האם אני בכלל אוכל לתפוס אחד…\n"
	.string "לא! אני אעשה את המיטב!\p"
	.string "תודה!$"

gText_ApprenticeWhichMon4::
	.string "אה, {PLAYER}{KUN}! אני כל כך שמח לראות אותך!\n"
	.string "כמעט הלכתי לחפש אותך!\p"
	.string "את{EMIT_HEY} יכול להחליט איזה סוג של פוקימון\n"
	.string "אני צריך להשתמש?\p"
	.string "לדוגמה…\n"
	.string "מה דעתך על הפוקימונים {STR_VAR_1}\l"
	.string "ו{STR_VAR_2}?\p"
	.string "איזה מהם את{EMIT_HEY} חושב{ADD_TAF} שיהיה\n"
	.string "טוב יותר?$"

gText_ApprenticeMonThanks4::
	.string "{STR_VAR_1}? זה נהדר!\p"
	.string "כשאני יודע שאת{EMIT_HEY} קיבלת את ההחלטה,\n"
	.string "{PLAYER}{KUN}, אני לא אהיה כל כך עצוב אם\l"
	.string "אפסיד.\p"
	.string "אוקי, אני אפנה אליך שוב לקבלת עצה.\n"
	.string "ביי!$"

gText_ApprenticeWhichMon5::
	.string "אם זה לא {PLAYER}{KUN}! מה קורה?\n"
	.string "אני עסוק שוב כמו תמיד!\p"
	.string "אני רוצה להצליח עם פוקימונים, גם כן,\n"
	.string "אבל לא הצלחתי להחליט\l"
	.string "באיזה פוקימון אני צריך להשתמש.\p"
	.string "את{EMIT_HEY} יודע{ADD_TAF}איך {STR_VAR_1} נראים חזקים?\n"
	.string "אבל קשה להתעלם מ{STR_VAR_2}.\p"
	.string "{PLAYER}{KUN}, ת{SWAP_NUN}{ADD_YUD} לי קצת מהעצה הטובה\n"
	.string "שלך! איזה מהם יהיה טוב עבורי?$"

gText_ApprenticeMonThanks5::
	.string "אוקי, הבנתי.\n"
	.string "אני אמצא זמן איכשהו ואתפוס\l"
	.string "את ה{STR_VAR_1} שהמלצת עליו.\p"
	.string "אני שמח שפגשתי מנטור טוב בך.\n"
	.string "תודה! נתראה בסביבה!$"

gText_ApprenticeWhichMon6::
	.string "אה!\n"
	.string "יש, זה {PLAYER}!\p"
	.string "לא בזבזתי זמן בלספר\n"
	.string "לחברים שלי על הפגישה איתך!\p"
	.string "אני צריך לנצל את הראש שלך שוב היום.\n"
	.string "זו שאלה קלה עבורך!\p"
	.string "תופים, בבקשה!\n"
	.string "השאלה שיש לי היא…\p"
	.string "אם אני אגדל פוקימון,\n"
	.string "והאפשרויות הן {STR_VAR_1} אחד\l"
	.string "או {STR_VAR_2}, איזה מהם זה צריך להיות?$"

gText_ApprenticeMonThanks6::
	.string "אההה!\n"
	.string "{STR_VAR_1}, את{EMIT_HEY} אומר!\l"
	.string "תודה על תשובה הכי מגניבה!\p"
	.string "אני מניח שזה בערך כל מה שרציתי\n"
	.string "לשאול אותך היום.\p"
	.string "בוא ניפגש כאן שוב, אוקי?\n"
	.string "תודה!$"

gText_ApprenticeWhichMon7::
	.string "אה, זה את{EMIT_HEY}, {PLAYER}?\n"
	.string "אני שמח לראות אותך שוב!\p"
	.string "מאז שהפכתי לחניך שלך,\n"
	.string "הבטחון שלי פורח.\p"
	.string "אני חושב שאני מוכן לגדל פוקימון\n"
	.string "משלי!\p"
	.string "{PLAYER}, האם אוכל לבקש ממך שתבחר\n"
	.string "איזה פוקימון אני צריך לגדל?\p"
	.string "האפשרויות הן הפוקימונים\n"
	.string "{STR_VAR_1} או {STR_VAR_2}…\l"
	.string "איזה פוקימון נכון עבורי?$"

gText_ApprenticeMonThanks7::
	.string "{STR_VAR_1} אחד זה זה!\n"
	.string "אני אמצא אחד מיד!\p"
	.string "תודה, {PLAYER}.\n"
	.string "אני מקווה שאוכל לסמוך עליך שוב.\l"
	.string "בבקשה שמור על עצמך!$"

gText_ApprenticeWhichMon8::
	.string "איכס! {PLAYER}! פגשתי אותך שוב!\n"
	.string "אני… אני מאושר!\p"
	.string "או-או-או, אני יודע!\n"
	.string "אני לא צריך לוותר על ההזדמנות הזו!\p"
	.string "האם אוכל לבקש טובה ענקית, {PLAYER}?\n"
	.string "בבקשה תבחר עבורי פוקימון!\p"
	.string "בבקשה תחליט איזה יהיה טוב יותר,\n"
	.string "{STR_VAR_1} או {STR_VAR_2}!$"

gText_ApprenticeMonThanks8::
	.string "וואו! החלטת עבורי!\n"
	.string "{STR_VAR_1} אחד זה מה שאני אגדל\l"
	.string "למיטב יכולתי.\p"
	.string "אני מקווה שתהיה מוכן ללמד אותי\n"
	.string "עוד פעם אחרת.$"

gText_ApprenticeWhichMon9::
	.string "היי, היי!\n"
	.string "המנטור שלי, {PLAYER}{KUN}!\l"
	.string "שלום, חיפשתי אותך\n"
	.string "בשביל עוד מהעצה החכמה שלך!\p"
	.string "איזה סוג של פוקימון יהיה נכון\n"
	.string "עבורי, {STR_VAR_1} אחד או {STR_VAR_2}?\p"
	.string "אל תתבייש עכשיו.\n"
	.string "בוא נפלוט את זה החוצה!$"

gText_ApprenticeMonThanks9::
	.string "אהה, {STR_VAR_1} אחד זה זה!\n"
	.string "אוקי, א-אוקי!\l"
	.string "אני אשיג אחד בכדור, כאילו, קראם!\p"
	.string "טוב, תודה, כמו תמיד!\n"
	.string "להתראות!$"

gText_ApprenticeWhichMon10::
	.string "{PLAYER}{KUN}, תקשיב! חדשות גדולות!\n"
	.string "תפסתי פוקימון מיראז'!\p"
	.string "כמובן שאני משקר!\n"
	.string "וואחחחח!\p"
	.string "זה לא שקר, למרות זאת.\n"
	.string "אני לא כל כך טוב בלתפוס\l"
	.string "פוקימונים.\p"
	.string "אז, מה דעתך שתחליט עבורי איזה\n"
	.string "סוג של פוקימון אני צריך לתפוס,\l"
	.string "מאסטר?\p"
	.string "איזה יהיה טוב יותר?\n"
	.string "{STR_VAR_1} או {STR_VAR_2}?$"

gText_ApprenticeMonThanks10::
	.string "אוקי, אז זה {STR_VAR_1} שבחרת?\n"
	.string "אני אבחר את הסוג האחר, אם כן!\p"
	.string "סתם צוחק!\n"
	.string "אני אציית ללימוד שלך, מאסטר!\p"
	.string "תודה, מאסטר!\n"
	.string "אני מקווה שתמשיך ללמד אותי!$"

gText_ApprenticeWhichMon11::
	.string "הי!\n"
	.string "וזה מאיית הי!\p"
	.string "הספן הראפר אני!\n"
	.string "בטח את{EMIT_HEY} זוכר מי אני?\p"
	.string "היום, יש לי שאלת פוקימון\n"
	.string "שמבקשת את הצעתך!\p"
	.string "יש לי בחירה בין ה{STR_VAR_1} הזה\n"
	.string "ו{STR_VAR_2}, את{EMIT_HEY} רואה.\l"
	.string "איזה מהם לתפוס עבורי?$"

gText_ApprenticeMonThanks11::
	.string "{STR_VAR_1}, את{EMIT_HEY} אומר, היי, היי!\n"
	.string "אני אלך להשיג לי אחד מיד!\p"
	.string "אם אי פעם אצטרך עצה,\n"
	.string "{PLAYER}, אני תמיד אקשיב למילה שלך!$"

gText_ApprenticeWhichMon12::
	.string "אוי, וואו, אם זה לא {PLAYER}!\p"
	.string "מה אני צריך לעשות? לקבל את העצה שלך?\n"
	.string "למה לא? אני כבר מדבר אליך!\p"
	.string "עבר הרבה זמן. ת{SWAP_NUN}{ADD_YUD} לי לשבור\n"
	.string "את הקרח. אני גם מחפש עצה!\l"
	.string "את{EMIT_HEY} מקבל אותי?\l"
	.string "את{EMIT_HEY} מקבל אותי!\p"
	.string "הפוקימון שלי--איזה אני צריך להשתמש?\n"
	.string "זה או {STR_VAR_1} או {STR_VAR_2}.\l"
	.string "במה את{EMIT_HEY} בוחר?$"

gText_ApprenticeMonThanks12::
	.string "אם ה{STR_VAR_1} הזה הוא הכי טוב,\n"
	.string "אני אעשה כפי שאת{EMIT_HEY} מציע!\p"
	.string "טוב, {PLAYER}, אני צריך לשוטט חופשי,\n"
	.string "אבל אל תשכח אותי.\p"
	.string "נתראה שוב, חברי החכם!$"

gText_ApprenticeWhichMon13::
	.string "אה, היי, {PLAYER}{KUN}…\n"
	.string "יש לי את כאב הראש הנוראי הזה…\p"
	.string "בטח דאגתי יותר מדי לגבי\n"
	.string "הסוג של פוקימון שאני צריך לגדל.\p"
	.string "אז, כשהדברים ככה,\n"
	.string "אני צריך שתחליט עבורי.\p"
	.string "{PLAYER}{KUN}, אם הייתי צריך לבחור בין\n"
	.string "הפוקימונים {STR_VAR_1}\l"
	.string "ו{STR_VAR_2}, איזה זה צריך להיות?$"

gText_ApprenticeMonThanks13::
	.string "הממ, {STR_VAR_1} אחד, בסדר.\n"
	.string "אני אלך לחפש אחד כשאשתפר.\p"
	.string "אני מקווה שאוכל להמשיך לבקש ממך\n"
	.string "עזרה ככה.$"

gText_ApprenticeWhichMon14::
	.string "אר… אמ…\n"
	.string "{PLAYER}{KUN}…?\p"
	.string "בבקשה, אל תסתכל עלי ככה.\n"
	.string "אני נהיה מבולבל כל כך…\l"
	.string "אני… אני צריך את העצה שלך.\p"
	.string "אני… אני ממש נבוך, אבל אני לא מצליח\n"
	.string "להחליט באיזה פוקימון להשתמש.\p"
	.string "אם האפשרויות היו {STR_VAR_1} או\n"
	.string "{STR_VAR_2}, איזה יהיה טוב יותר?$"

gText_ApprenticeMonThanks14::
	.string "אה… אוקי!\n"
	.string "אני אעשה את המיטב עם {STR_VAR_1} אחד.\p"
	.string "אני מקווה שאוכל לעשות את המיטב בלי\n"
	.string "להיות מבולבל כל כך.\p"
	.string "תודה, {PLAYER}{KUN}.\n"
	.string "אם ניפגש שוב, אני מקווה שתהיה\l"
	.string "עוזר באותה מידה.$"

gText_ApprenticeWhichMon15::
	.string "הממ? את{EMIT_HEY} נראה כמו {PLAYER}{KUN}…\n"
	.string "אבל את{EMIT_HEY} באמת אמיתי?\p"
	.string "לא, לא, אם את{EMIT_HEY} אמיתי, זה בסדר.\n"
	.string "דרך אגב, אני רוצה לקבל\l"
	.string "את העצה שלך.\p"
	.string "זה על הפוקימון שאני צריך להשתמש.\p"
	.string "אם האפשרויות הן הפוקימונים\n"
	.string "{STR_VAR_1} ו{STR_VAR_2}, איזה מהם\l"
	.string "ראוי יותר עבורי?$"

gText_ApprenticeMonThanks15::
	.string "{STR_VAR_1}?\n"
	.string "את{EMIT_HEY} בטוח?\p"
	.string "אני מבין. אם זה המקרה, זה בסדר.\n"
	.string "אני מודה לך על זמנך.\p"
	.string "אני מקווה שזה משהו שאפילו אני יכול\n"
	.string "לטפל בו בקלות.\p"
	.string "בוא ניפגש שוב!$"

gText_ApprenticeWhichMove0::
	.string "וואא! אוי, {PLAYER}!\n"
	.string "מנוזל… שיהוק…\p"
	.string "יש לי דילמה!\n"
	.string "אני לא מצליח להחליט על מהלך עבור\l"
	.string "ה{STR_VAR_1} שלי…\p"
	.string "בבקשה, בבקשה, {PLAYER}.\n"
	.string "את{EMIT_HEY} יכול להחליט עבורי?\p"
	.string "עבור ה{STR_VAR_1} שלי, איזה מהלך יהיה\n"
	.string "הבחירה הטובה יותר: {STR_VAR_2}\l"
	.string "או {STR_VAR_3}?$"

gText_ApprenticeMoveThanks0::
	.string "{STR_VAR_1}?\n"
	.string "וואאאא!\p"
	.string "אוי! אני כל כך מצטער, {PLAYER}!\n"
	.string "עשית אותי כל כך שמח שהחלטת\l"
	.string "על המהלך, אני בוכה…\p"
	.string "מנוזל…\n"
	.string "תודה רבה לך!$"

gText_ApprenticeWhichMove1::
	.string "יש! היי, {PLAYER}!\n"
	.string "אני צריך את העצה שלך שוב!\p"
	.string "אני רוצה ללמד את ה{STR_VAR_1} שלי\n"
	.string "מהלך מגניב.\p"
	.string "אני אוהב כל אחד מהמהלכים\n"
	.string "{STR_VAR_2} או {STR_VAR_3}.\l"
	.string "מה ההמלצה שלך?$"

gText_ApprenticeMoveThanks1::
	.string "{STR_VAR_1} עדיף? אני מניח שכן!\n"
	.string "אוקי, אני אלך על זה!\p"
	.string "אם ניפגש כאן שוב, בבקשה למד\n"
	.string "אותי משהו אחר, מורה!$"

gText_ApprenticeWhichMove2::
	.string "{PLAYER}, שלום!\n"
	.string "זה על ה{STR_VAR_1} שלי, אבל אני\l"
	.string "דואג לגבי המהלכים שלו.\p"
	.string "את{EMIT_HEY} מבין, זה המהלכים {STR_VAR_2}\n"
	.string "ו{STR_VAR_3}.\p"
	.string "איזה מהם חזק יותר וטוב יותר עבור\n"
	.string "ה{STR_VAR_1} שלי?$"

gText_ApprenticeMoveThanks2::
	.string "{STR_VAR_1} זו הבחירה שלך?\n"
	.string "אוקי, הבנתי!\p"
	.string "אני אלך ללמד את {STR_VAR_1}\n"
	.string "לפוקימון שלי מיד!\p"
	.string "נתראה שוב!$"

gText_ApprenticeWhichMove3::
	.string "אווו, {PLAYER}…\n"
	.string "אני חסר תקווה, לא, באמת!\p"
	.string "החלטתי לגדל פוקימון,\n"
	.string "אבל עכשיו אני אפילו לא מצליח להחליט איזה\l"
	.string "מהלך אני צריך לתת לו ללמוד…\p"
	.string "אני יודע שזה לא אומר כלום\n"
	.string "לך, {PLAYER}.\p"
	.string "אבל זה אומר הרבה לי…\p"
	.string "בבקשה, {PLAYER}, את{EMIT_HEY} יכול לבחור\n"
	.string "מהלך עבור ה{STR_VAR_1} שלי?\p"
	.string "אם תוכל{ADD_YUD} אפילו לבחור בין\n"
	.string "{STR_VAR_2} ו{STR_VAR_3}…$"

gText_ApprenticeMoveThanks3::
	.string "אני מבין!\p"
	.string "אבל האם הוא בכלל יהיה מוכן ללמוד\n"
	.string "{STR_VAR_1} עבורי…\l"
	.string "לא! אני אעשה את המיטב!\p"
	.string "תודה!$"

gText_ApprenticeWhichMove4::
	.string "אה, {PLAYER}{KUN}!\n"
	.string "בדיוק קיוויתי לראות אותך, גם כן!\p"
	.string "תהיתי איזה מהלך יהיה\n"
	.string "מתאים עבור ה{STR_VAR_1} שלי.\p"
	.string "אני לא מצליח להחליט, אז את{EMIT_HEY} יכול להחליט\n"
	.string "עבורי במקום?\p"
	.string "לדוגמה… מה דעתך על המהלכים\n"
	.string "{STR_VAR_2} ו{STR_VAR_3}?\l"
	.string "איזה מהם יהיה טוב יותר?$"

gText_ApprenticeMoveThanks4::
	.string "{STR_VAR_1}? זה נהדר!\p"
	.string "כשאני יודע שאת{EMIT_HEY} קיבלת את ההחלטה,\n"
	.string "{PLAYER}{KUN}, אני לא אהיה כל כך עצוב אם\l"
	.string "אפסיד.\p"
	.string "אוקי, אני אפנה אליך שוב לקבלת עצה.\n"
	.string "ביי!$"

gText_ApprenticeWhichMove5::
	.string "איך יכול להיות שדברים כל כך עסוקים?\n"
	.string "היי, אם זה לא {PLAYER}{KUN}!\l"
	.string "מה קורה?\p"
	.string "מאז שקמתי הבוקר, עשיתי\n"
	.string "ריצה קלה, שחייה, ובישול!\p"
	.string "את{EMIT_HEY} לא תאמין כמה אני עסוק!\p"
	.string "אני אפילו לא מצליח להחליט איזה מהלך\n"
	.string "ה{STR_VAR_1} שלי צריך ללמוד!\p"
	.string "{STR_VAR_2} נראה טוב, הא?\n"
	.string "אבל {STR_VAR_3} גם ראוי.\p"
	.string "{PLAYER}{KUN}, ת{SWAP_NUN}{ADD_YUD} לי קצת מהעצה הטובה\n"
	.string "שלך! איזה מהלך יהיה טוב עבורי?$"

gText_ApprenticeMoveThanks5::
	.string "אוקי, הבנתי.\n"
	.string "אני אפנה מקום בלוח הזמנים שלי\l"
	.string "ואלמד את המהלך הזה.\p"
	.string "אני שמח שפגשתי מנטור טוב בך.\n"
	.string "תודה! נתראה בסביבה!$"

gText_ApprenticeWhichMove6::
	.string "אה! מזל!\n"
	.string "פגשתי אותך שוב, {PLAYER}!\l"
	.string "אני צריך לנצל את הראש שלך שוב היום.\p"
	.string "תופים, בבקשה!\n"
	.string "השאלה שיש לי היא…\p"
	.string "עבור ה{STR_VAR_1} שלי, איזה מהלך הוא\n"
	.string "המתאים ביותר, {STR_VAR_2} או\l"
	.string "{STR_VAR_3}?$"

gText_ApprenticeMoveThanks6::
	.string "אההה!\n"
	.string "{STR_VAR_1}, את{EMIT_HEY} אומר!\l"
	.string "תודה על תשובה הכי מגניבה!\p"
	.string "אני מניח שזה בערך כל מה שרציתי\n"
	.string "לשאול אותך היום.\p"
	.string "בוא ניפגש כאן שוב, אוקי?\n"
	.string "תודה!$"

gText_ApprenticeWhichMove7::
	.string "אה, שלום, {PLAYER}.\n"
	.string "אני מקווה ששלומך טוב?\p"
	.string "אני צריך לבקש את עצתך שוב.\n"
	.string "זה על ה{STR_VAR_1} היקר שלי.\p"
	.string "מה יהיה המהלך האידיאלי עבור\n"
	.string "ה{STR_VAR_1} האהוב שלי?\l"
	.string "{STR_VAR_2} או {STR_VAR_3}?$"

gText_ApprenticeMoveThanks7::
	.string "{STR_VAR_1} זה זה!\n"
	.string "אני אלמד את זה מיד!\p"
	.string "תודה, {PLAYER}.\n"
	.string "אני מקווה שאוכל לסמוך עליך שוב.\l"
	.string "בבקשה שמור על עצמך!$"

gText_ApprenticeWhichMove8::
	.string "איכס! {PLAYER}! פגשתי אותך שוב!\n"
	.string "אני… אני מאושר!\p"
	.string "בכל פעם שאני בצורך, את{EMIT_HEY} תמיד\n"
	.string "שם בשבילי, {PLAYER}!\p"
	.string "היום, אני רוצה שתמליץ לי\n"
	.string "על מהלך!\p"
	.string "בבקשה תבחר מהלך עבור\n"
	.string "ה{STR_VAR_1} שלי!\p"
	.string "איזה מהלך יהיה טוב יותר,\n"
	.string "{STR_VAR_2} או {STR_VAR_3}?$"

gText_ApprenticeMoveThanks8::
	.string "או-או-או! תודה!\n"
	.string "{STR_VAR_1} זה זה!\l"
	.string "הבנה מושלמת!\p"
	.string "אני מקווה שתהיה מוכן ללמד אותי\n"
	.string "עוד פעם אחרת.$"

gText_ApprenticeWhichMove9::
	.string "הולה, {PLAYER}{KUN}, בואנו!\n"
	.string "אני מקווה לעוד מהעצה החכמה\l"
	.string "שלך היום!\p"
	.string "מה יהיה המהלך הטוב ביותר עבור\n"
	.string "ה{STR_VAR_1} שלי?\p"
	.string "זה צריך להיות משהו שיגרום\n"
	.string "לי לנצח ככה סתם!\p"
	.string "האם זה יהיה {STR_VAR_2}?\n"
	.string "או {STR_VAR_3}?$"

gText_ApprenticeMoveThanks9::
	.string "אהה, {STR_VAR_1} זה זה!\n"
	.string "סי, בואנו!\l"
	.string "אני אלמד את זה, כאילו, קא-בלאם!\p"
	.string "טוב, תודה, כמו תמיד!\n"
	.string "להתראות!$"

gText_ApprenticeWhichMove10::
	.string "{PLAYER}{KUN}, זה פרוע לחלוטין!\p"
	.string "הפוקימון שלי!\n"
	.string "הוא למד שישה מהלכים!\p"
	.string "כמובן שאני משקר!\n"
	.string "וואחחחח!\p"
	.string "זה לא שקר, למרות זאת.\n"
	.string "אני לא כל כך טוב בבחירת מהלכים\l"
	.string "עבור הפוקימונים שלי.\p"
	.string "אז, מה דעתך שתחליט עבורי איזה\n"
	.string "סוג של מהלך אני צריך ללמד?\p"
	.string "{STR_VAR_2} או {STR_VAR_3}--איזה\n"
	.string "מהם יתאים ל{STR_VAR_1} שלי הכי טוב?$"

gText_ApprenticeMoveThanks10::
	.string "אוקי, אז זה {STR_VAR_1} שבחרת?\n"
	.string "אני אבחר מהלך אחר, אם כן!\p"
	.string "סתם צוחק!\n"
	.string "אני אציית ללימוד שלך, מאסטר!\p"
	.string "תודה, מאסטר!\n"
	.string "אני מקווה שתמשיך ללמד אותי!$"

gText_ApprenticeWhichMove11::
	.string "הי!\n"
	.string "וזה מאיית הי!\p"
	.string "הספן הראפר אני!\n"
	.string "אני תמיד עם זה, אל תשאל למה.\p"
	.string "היום, יש לי שאלת מהלך\n"
	.string "שמבקשת את הצעתך!\p"
	.string "{STR_VAR_2} ו{STR_VAR_3} הם\n"
	.string "המהלכים. מה יהיה הטוב ביותר\l"
	.string "עבור ה{STR_VAR_1} שלי כדי שהוא יתקדם?$"

gText_ApprenticeMoveThanks11::
	.string "{STR_VAR_1}, את{EMIT_HEY} אומר, היי, היי!\n"
	.string "אני אלך ללמד את זה מיד!\p"
	.string "אם אי פעם אצטרך עצה,\n"
	.string "{PLAYER}, אני תמיד אקשיב למילה שלך!$"

gText_ApprenticeWhichMove12::
	.string "אה, כן, אם זה לא {PLAYER}!\p"
	.string "מה אני צריך לעשות? לקבל את העצה שלך?\n"
	.string "למה לא? אני כבר מדבר אליך!\p"
	.string "{PLAYER}, את{EMIT_HEY} מופתע ממני?\n"
	.string "אני רוצה את העצה שלך, את{EMIT_HEY} לא רואה?\p"
	.string "את{EMIT_HEY} מקבל אותי?\n"
	.string "את{EMIT_HEY} מקבל אותי!\p"
	.string "ה{STR_VAR_1} שלי--במה הוא צריך להשתמש?\n"
	.string "זה {STR_VAR_2} או {STR_VAR_3},\l"
	.string "במה את{EMIT_HEY} בוחר?$"

gText_ApprenticeMoveThanks12::
	.string "אם ה{STR_VAR_1} הזה הוא הכי טוב,\n"
	.string "אני אעשה כפי שאת{EMIT_HEY} מציע!\p"
	.string "טוב, {PLAYER}, אני צריך לשוטט חופשי,\n"
	.string "אבל אל תשכח אותי.\p"
	.string "נתראה שוב, חברי החכם!$"

gText_ApprenticeWhichMove13::
	.string "גהאק! גאה! אוי, {PLAYER}{KUN}…\n"
	.string "יש לי את הצינון המגעיל הזה, כן…\p"
	.string "אני רוצה לבחור מהלך עבור הפוקימון שלי,\n"
	.string "אבל אני לא מסוגל לזה…\p"
	.string "אז, כשהדברים ככה,\n"
	.string "אני צריך שתחליט עבורי.\p"
	.string "{PLAYER}{KUN}, אם הייתי צריך לבחור בין\n"
	.string "{STR_VAR_2} ו{STR_VAR_3} עבור\l"
	.string "ה{STR_VAR_1} שלי, איזה זה יהיה?$"

gText_ApprenticeMoveThanks13::
	.string "הממ, {STR_VAR_1}, בסדר. שיעול!\n"
	.string "אני אלך ללמד אותו כשאשתפר.\p"
	.string "אני מקווה שאוכל להמשיך לבקש ממך\n"
	.string "עזרה ככה.$"

gText_ApprenticeWhichMove14::
	.string "אר… אמ…\n"
	.string "{PLAYER}{KUN}…?\p"
	.string "בבקשה, אל תסתכל עלי ככה.\n"
	.string "אני נהיה מבולבל כל כך…\l"
	.string "אני… אני צריך את העצה שלך.\p"
	.string "אני… אני ממש נבוך, אבל אני לא מצליח\n"
	.string "להחליט איזה מהלך אני צריך ללמד\l"
	.string "את הפוקימון שלי.\p"
	.string "זה עבור ה{STR_VAR_1} שלי.\n"
	.string "אם האפשרויות היו {STR_VAR_2} או\l"
	.string "{STR_VAR_3}, איזה יהיה טוב יותר?$"

gText_ApprenticeMoveThanks14::
	.string "אה… אוקי!\n"
	.string "אני אנסה את ה{STR_VAR_1} הזה.\p"
	.string "אני מקווה שאוכל ללמד את המהלך הזה…\n"
	.string "זה כל כך מעצבן עצבים…\p"
	.string "תודה, {PLAYER}{KUN}.\n"
	.string "אם ניפגש שוב, אני מקווה שתהיה\l"
	.string "עוזר באותה מידה.$"

gText_ApprenticeWhichMove15::
	.string "הממ? את{EMIT_HEY} נראה כמו {PLAYER}{KUN}…\n"
	.string "אבל את{EMIT_HEY} באמת אמיתי?\p"
	.string "אולי את{EMIT_HEY} אחד מאותם מחקים\n"
	.string "פופולריים?\p"
	.string "לא, לא, אם את{EMIT_HEY} אמיתי, זה בסדר.\n"
	.string "אין צורך להיות כל כך עצבני, אני מבטיח לך!\p"
	.string "דרך אגב, אני רוצה לקבל\n"
	.string "את העצה שלך.\p"
	.string "זה על ה{STR_VAR_1} שלי.\p"
	.string "איזה מהלך יהיה טוב יותר עבורו\n"
	.string "להשתמש, {STR_VAR_2} או {STR_VAR_3}?$"

gText_ApprenticeMoveThanks15::
	.string "{STR_VAR_1}?\n"
	.string "אין שאלה לגבי זה?\p"
	.string "אני מבין. אם זה המקרה, זה בסדר.\n"
	.string "אני מודה לך על זמנך.\p"
	.string "אני מקווה שזה משהו שאפילו\n"
	.string "הפוקימון שלי יכול ללמוד.\p"
	.string "בוא ניפגש שוב!$"

gText_ApprenticePickWinSpeech0::
	.string "אה… {PLAYER}?\n"
	.string "זה {PLAYER}!\l"
	.string "אוי! מנוזל… יבבה… בבקשה, תקשיב!\p"
	.string "אני… כשאני נלחם, אני נהיה כל כך עצבני,\n"
	.string "אני לא יכול שלא לבכות אפילו אם אני מנצח…\p"
	.string "הלוואי שיכולתי לומר משהו מגניב\n"
	.string "כשאני מנצח…\p"
	.string "בבקשה, בבקשה, {PLAYER}!\n"
	.string "אולי תוכל{ADD_YUD} ללמד אותי משהו\l"
	.string "מגניב לומר כשאני מנצח כדי שאני לא אבכה?$"

gText_ApprenticeWinSpeechThanks0::
	.string "{STR_VAR_1}\p"
	.string "מדהים! פרוע! אווהו!\n"
	.string "זה ממש מגניב!\p"
	.string "אוי… אני מצטער…\n"
	.string "אני כל כך שמח, אני בוכה…\p"
	.string "מנוזל… {PLAYER}!\n"
	.string "תודה רבה לך על הכל!\p"
	.string "אני אלחם הכי טוב שאני יכול בשבילך,\n"
	.string "{PLAYER}!\p"
	.string "{PLAYER}…\n"
	.string "בפעם הבאה… אנחנו צריכים להילחם!$"

gText_ApprenticePickWinSpeech1::
	.string "יש! זה {PLAYER}! שלום!\n"
	.string "רציתי לשאול אותך משהו!\p"
	.string "אני רוצה לומר משהו מגניב כשאני\n"
	.string "מנצח משחק.\p"
	.string "יש לך אמירה מגניבה\n"
	.string "שאת{EMIT_HEY} יכול{ADD_HEY} להמליץ לי עליה?$"

gText_ApprenticeWinSpeechThanks1::
	.string "{STR_VAR_1}\p"
	.string "אוי, וואו! זה כל כך מגניב!\n"
	.string "אוקי, אני אגיד את זה!\p"
	.string "תודה שלימדת אותי כל הזמן הזה!\n"
	.string "אני הולך לעשות את המיטב שאני יכול\l"
	.string "בכל מקום שאליו אלך מעכשיו!\p"
	.string "כשניפגש שוב, זה יהיה\n"
	.string "לקרב!$"

gText_ApprenticePickWinSpeech2::
	.string "{PLAYER}, שלום!\p"
	.string "הפוקימונים שלי ואני מוכנים\n"
	.string "לכל דבר, חוץ מדבר אחד.\p"
	.string "אני חושב שיהיה טוב אם יהיה לי\n"
	.string "משהו לצעוק כשאני מנצח.\p"
	.string "את{EMIT_HEY} יכול לחשוב על משהו טוב\n"
	.string "לומר?$"

gText_ApprenticeWinSpeechThanks2::
	.string "{STR_VAR_1}\p"
	.string "…מגניב!\n"
	.string "אני אשתמש בזה!\p"
	.string "אני יוצא להילחם בכל\n"
	.string "המקום.\p"
	.string "מי יודע, אולי אפילו אזכה להילחם\n"
	.string "בך יום אחד, {PLAYER}.\p"
	.string "בפעם הבאה, בוא ניפגש במקום\n"
	.string "של קרב!$"

gText_ApprenticePickWinSpeech3::
	.string "שלום, {PLAYER}…\n"
	.string "אני מצטער להטריד אותך, אבל אני חסר תקווה…\p"
	.string "אפילו כש…\n"
	.string "אפילו כשאני מנצח, אין לי שום דבר\l"
	.string "מיוחד לומר…\p"
	.string "אני יודע שזה לא אומר כלום\n"
	.string "לך, {PLAYER}.\p"
	.string "אבל זה אומר הרבה לי…\p"
	.string "בבקשה, {PLAYER}, מה אני צריך לומר\n"
	.string "אם אני מנצח קרב?$"

gText_ApprenticeWinSpeechThanks3::
	.string "{STR_VAR_1}\p"
	.string "זה מעורר השראה…\p"
	.string "אמ… האם זה בסדר למישהו כמוני\n"
	.string "בכלל לומר את זה?\p"
	.string "לא! אני אעשה את המיטב!\p"
	.string "{PLAYER}, תודה רבה לך\n"
	.string "שסבלת אותי כל כך הרבה זמן…\p"
	.string "אני מבטיח לעשות את המיטב שלי מעכשיו.\p"
	.string "אני בטוח שאת{EMIT_HEY} תשכח במהירות מ\n"
	.string "מישהו כמוני, אבל בוא ניפגש\l"
	.string "שוב איפשהו!$"

gText_ApprenticePickWinSpeech4::
	.string "אה, {PLAYER}{KUN}.\n"
	.string "יש משהו שאני רוצה שתשמע.\p"
	.string "אני יודע שאני לא תמיד נשמע\n"
	.string "נחמד או מנומס…\p"
	.string "כשאני מנצח קרב, אני חושב שאני יוצא\n"
	.string "יהיר.\p"
	.string "אני לא רוצה שאנשים לא יאהבו אותי,\n"
	.string "אז אני רוצה לומר משהו נחמד\l"
	.string "למישהו שהבסתי.\p"
	.string "אבל אני לא מצליח לחשוב על שום דבר טוב!\n"
	.string "את{EMIT_HEY} יכול לחשוב על משהו עבורי?$"

gText_ApprenticeWinSpeechThanks4::
	.string "{STR_VAR_1}\p"
	.string "לא רע!\n"
	.string "כן, עם זה אני אלך!\p"
	.string "אני הולך לצאת לדרך ולעשות מה\n"
	.string "שאני יכול עם מה שלימדת אותי\l"
	.string "בראש ובלב שלי.\p"
	.string "אני מצטער שהייתי כל כך לחוץ\n"
	.string "איתך!\p"
	.string "בפעם הבאה, אנחנו נלחמים, אוקי?\n"
	.string "ביי!$"

gText_ApprenticePickWinSpeech5::
	.string "אוי, אני לא מצליח להתגבר על כמה שאני עסוק!\n"
	.string "אה, היי, חיפשתי אותך, {PLAYER}{KUN}.\p"
	.string "את{EMIT_HEY} בסדר כרגיל?\n"
	.string "דברים לא השתנו עבורי בכלל.\p"
	.string "יש לי ריצה, לחימה, ומיפוי\n"
	.string "לעשות. למה אני כל כך עסוק?\p"
	.string "אבל למרות שאני עסוק, זה יהיה גס רוח\n"
	.string "פשוט להסתובב וללכת מ\l"
	.string "ניצחון בלי לומר מילה.\p"
	.string "אז, מה תהיה אמירה מגניבה\n"
	.string "להדגיש את המגניבות שלי כשאני מסיים\l"
	.string "והולך משם? {PLAYER}{KUN}, עז{EMIT_VAV}ר{ADD_YUD} לי!$"

gText_ApprenticeWinSpeechThanks5::
	.string "{STR_VAR_1}\p"
	.string "אוקי, הבנתי.\n"
	.string "אני יכול למצוא זמן לומר את זה!\p"
	.string "בכנות, אני שמח שפגשתי מנטור טוב\n"
	.string "כמוך.\p"
	.string "אני הולך למצוא זמן איכשהו כדי\n"
	.string "שאוכל להיכנס לקרבות.\p"
	.string "תודה על הכל, {PLAYER}{KUN}!\n"
	.string "אנחנו חייבים להילחם, את{EMIT_HEY} ואני, יום אחד!$"

gText_ApprenticePickWinSpeech6::
	.string "שוב היה לי מזל!\n"
	.string "{PLAYER}! אני שמח לראות אותך!\l"
	.string "כרגיל, אני צריך את העצה שלך!\p"
	.string "תופים, בבקשה!\n"
	.string "השאלה האחרונה שיש לי היא…\p"
	.string "אם אני מנצח קרב ורוצה לסיים\n"
	.string "אותו עם פריחה מגניבה, מה\l"
	.string "אני צריך לומר?$"

gText_ApprenticeWinSpeechThanks6::
	.string "{STR_VAR_1}\p"
	.string "זה… זה נהדר!\n"
	.string "זה מכובד ומגניב! אני לוקח את זה!\p"
	.string "…תקשיב, אני חושב שאני נהיה ראוי\n"
	.string "לזה, הא?\p"
	.string "אז, אני חושב לאתגר מאמנים\n"
	.string "אחרים מעכשיו.\p"
	.string "{PLAYER}, העצה שלך באמת עזרה לי.\p"
	.string "אולי יום אחד, יגיע זמן\n"
	.string "שאנחנו נלחם!\p"
	.string "תודה על הכל!$"

gText_ApprenticePickWinSpeech7::
	.string "אה, {PLAYER}.\n"
	.string "אני כל כך שמח שפגשתי אותך!\p"
	.string "אין לי יותר דאגות בנוגע\n"
	.string "לפוקימונים שלי.\p"
	.string "זה אני עצמי שמדאיג אותי…\p"
	.string "את{EMIT_HEY} יודע{ADD_TAF}איך מאמן אומר\n"
	.string "כמה דברים לאחר ניצחון בקרב?\p"
	.string "בהחלט, הלוואי שיכולתי לעשות את זה,\n"
	.string "גם כן!\p"
	.string "בבקשה, מה אני צריך לומר כשאני\n"
	.string "מנצח קרב?$"

gText_ApprenticeWinSpeechThanks7::
	.string "{STR_VAR_1}\p"
	.string "אה! האמירה הזו! היא מרעננת אותי\n"
	.string "וגורמת לי להרגיש שנולדתי מחדש!\p"
	.string "אני חייב להשתמש בזה מיד!\p"
	.string "ועכשיו, אני חייב ללכת,\n"
	.string "{PLAYER}…\p"
	.string "אני אלך להילחם בהרבה אחרים,\n"
	.string "אבל לעולם לא אשכח את הלימודים שלך.\p"
	.string "אולי יום אחד…\n"
	.string "להתראות!$"

gText_ApprenticePickWinSpeech8::
	.string "איכס! זיהיתי את {PLAYER}!\n"
	.string "אני… אני מאושר לראות אותך!\p"
	.string "או-או-או! יש משהו שפשוט\n"
	.string "הייתי חייב לשאול אותך!\p"
	.string "לפני זמן קצר, ניצחתי קרב.\n"
	.string "החלק הזה היה משכר!\p"
	.string "אבל זה עשה אותי כל כך מאושר\n"
	.string "שנחנקתי ולא יכולתי לומר דבר!\p"
	.string "אז עכשיו, {PLAYER}, בבקשה, אני רוצה\n"
	.string "שתחשוב על משפט סיום לניצחון שלי!$"

gText_ApprenticeWinSpeechThanks8::
	.string "{STR_VAR_1}\p"
	.string "וואאאא!\n"
	.string "אני הולך לומר את זה?!\l"
	.string "אני… אני שמח עד עילפון!\p"
	.string "תתתודה!\n"
	.string "לא נותר לי שום דבר להתחרט עליו עכשיו!\p"
	.string "אני הולך לטייל עכשיו ולהילחם\n"
	.string "בכל מיני אנשים.\p"
	.string "הכל, אני חייב לך, {PLAYER}.\n"
	.string "באמת, באמת, תודה!\p"
	.string "אני חייב ללכת עכשיו, אבל בוא ניפגש\n"
	.string "בקרב יום אחד!$"

gText_ApprenticePickWinSpeech9::
	.string "הולה, בואנו!\n"
	.string "{PLAYER}{KUN}!\p"
	.string "את{EMIT_HEY} יודע, אני מקבל גירוד לנדוד\n"
	.string "ולהילחם איפה שאוכל.\p"
	.string "אבל לפני שאני עושה זאת, אני רוצה את העצה\n"
	.string "שלך שוב, בבקשה!\p"
	.string "אם אני אנצח קרב, מה תהיה\n"
	.string "התפארות טובה שאוכל לומר ליריב\l"
	.string "המאמן המובס שלי?$"

gText_ApprenticeWinSpeechThanks9::
	.string "{STR_VAR_1}\p"
	.string "אהה, זה מתוק!\n"
	.string "סי, בואנו!\l"
	.string "אני אנסה לומר את זה, כאילו, האם!\p"
	.string "ועכשיו, הגיע הזמן לומר להתראות!\n"
	.string "תודה על כל מיני דברים!\p"
	.string "ת{SWAP_NUN}{ADD_YUD} לי קרב יום אחד, אוקי?\n"
	.string "להתראות!$"

gText_ApprenticePickWinSpeech10::
	.string "{PLAYER}{KUN}, יש צרה גדולה!\p"
	.string "כשאני מנצח קרב, אני מתפאר בזה\n"
	.string "לפחות שעה!\p"
	.string "כמובן שאני משקר!\n"
	.string "וואחחחח!\p"
	.string "זה לא שקר, למרות זאת.\n"
	.string "אני לא כל כך טוב בפטפוט.\p"
	.string "אז, מה דעתך שתחליט עבורי מה\n"
	.string "אני צריך לומר אחרי ניצחון בקרב,\l"
	.string "מאסטר?$"

gText_ApprenticeWinSpeechThanks10::
	.string "{STR_VAR_1}\p"
	.string "זה מה שאני צריך לומר, הא?\n"
	.string "אם כך, אני אתרחק מזה!\p"
	.string "סתם צוחק!\n"
	.string "אני אציית ללימוד שלך, מאסטר!\p"
	.string "תודה שלימדת אותי כל הזמן הזה,\n"
	.string "מאסטר!\p"
	.string "אני סוף סוף מבין מה זה להיות\n"
	.string "מאמן.\p"
	.string "אני הולך לצאת ולנצח בקרבות\n"
	.string "נגד כל מאמן.\p"
	.string "אולי זה תהיה את{EMIT_HEY} יום אחד, מאסטר!\p"
	.string "זה הכל!\n"
	.string "להתראות, מאסטר שלי!$"

gText_ApprenticePickWinSpeech11::
	.string "הי!\n"
	.string "וזה מאיית הי!\p"
	.string "הספן הראפר אני!\n"
	.string "זו תהיה השאלה האחרונה שלי,\l"
	.string "אל תבכה!\p"
	.string "זו שאלת אמירה\n"
	.string "שמבקשת את הצעתך!\p"
	.string "אם אני מנצח משחק, מה אני יכול לומר\n"
	.string "בצורה ממש מגניבה?$"

gText_ApprenticeWinSpeechThanks11::
	.string "{STR_VAR_1}\p"
	.string "מושלם! זה מה שאני אשתמש בו.\n"
	.string "צדקתי שבחרתי בך לבחור!\p"
	.string "ועכשיו, אני חושב שיהיה הכי טוב,\n"
	.string "אם אני אעזוב את הקן!\p"
	.string "תודה על כל מה שלימדת אותי.\n"
	.string "אני יוצא למסע קרב!\p"
	.string "ב-ו-ן-ו-א-ז'-'א-ז'!\n"
	.string "וזה מאיית בון וויה, זו המחווה שלי\l"
	.string "אליך!$"

gText_ApprenticePickWinSpeech12::
	.string "אה, כן, {PLAYER}!\n"
	.string "מצאתי אותך שוב היום!\p"
	.string "מה אני צריך לעשות? לשאול אותך שוב?\n"
	.string "למה לא? אני כבר שואל אותך!\p"
	.string "בכל מקרה, {PLAYER}…\n"
	.string "את{EMIT_HEY} מקבל אותי?\l"
	.string "את{EMIT_HEY} מקבל אותי!\l"
	.string "אני צריך עוד עצה עבורי!\p"
	.string "זה על מה אני צריך לצעוק.\n"
	.string "משהו מגניב לצעוק כאשר\l"
	.string "קרב מסתיים טוב.\p"
	.string "נו, אני רוצה לשמוע אותך אומר את זה!$"

gText_ApprenticeWinSpeechThanks12::
	.string "{STR_VAR_1}\p"
	.string "בסדר גמור, בסדר גמור!\n"
	.string "אני אשתמש בזה כי זה כל כך מדויק!\p"
	.string "נגמרו לי הדברים לשאול אותך.\n"
	.string "לנופף לשלום זה כל מה שנותר לי לעשות.\p"
	.string "אבל אולי יום אחד ניפגש, עם אחד\n"
	.string "שנגזר עליו ליפול בתבוסה.\p"
	.string "אבל, זה באמת זמן לומר להתראות.\p"
	.string "טוב, {PLAYER}, אני צריך לשוטט חופשי,\n"
	.string "אבל אל תשכח אותי!\p"
	.string "שמור על עצמך, {PLAYER}!\n"
	.string "אוהב אותך!$"

gText_ApprenticePickWinSpeech13::
	.string "{PLAYER}{KUN}, אני גמור…\n"
	.string "האף שלי לא מפסיק לטפטף…\p"
	.string "ניסיתי לחשוב על משהו\n"
	.string "מגניב לומר כשאני מנצח קרב.\p"
	.string "זה עורר אותי כל כך, שזה גרם לי לבכות,\n"
	.string "ועכשיו האף שלי לא מפסיק לנזול…\p"
	.string "אז, כשהדברים ככה,\n"
	.string "אני צריך שתחליט עבורי, {PLAYER}{KUN}.\p"
	.string "כשאני מנצח קרב,\n"
	.string "מה אני צריך לומר?$"

gText_ApprenticeWinSpeechThanks13::
	.string "{STR_VAR_1}\p"
	.string "… … …זה טוב.\n"
	.string "לא, זה מעורר יראה!\l"
	.string "זה מביא דמעות חדשות לעיניים שלי!\p"
	.string "אבל למרות הדמעות והאף הנוזל שלי,\n"
	.string "אני אשתמש באמירה הזו!\p"
	.string "נגמרו לי לחלוטין הדברים לשאול אותך,\n"
	.string "{PLAYER}{KUN}.\p"
	.string "מעכשיו, אנחנו יריבים!\n"
	.string "תודה על הכל!$"

gText_ApprenticePickWinSpeech14::
	.string "אר… אמ…\n"
	.string "{PLAYER}{KUN}…?\p"
	.string "בבקשה, אל תסתכל עלי ככה.\n"
	.string "את{EMIT_HEY} גורם לי להיות עצבני.\p"
	.string "אני… אני צריך את העצה שלך שוב.\n"
	.string "אני אעשה את זה האחרון שלי, למרות זאת…\p"
	.string "זה ממש מביך לשאול,\n"
	.string "אבל מה אם אני אנצח קרב?\l"
	.string "מה אני צריך לומר?$"

gText_ApprenticeWinSpeechThanks14::
	.string "{STR_VAR_1}\p"
	.string "אה… אוקי!\n"
	.string "אני אנסה לומר את זה!\l"
	.string "אני עלול להיות עצבני מדי כדי לומר את זה…\p"
	.string "תודה, {PLAYER}{KUN}.\n"
	.string "אני צריך לומר להתראות עכשיו.\p"
	.string "אני אציית לכל מה שלימדת אותי,\n"
	.string "{PLAYER}{KUN}, ואעשה את המיטב שאני יכול.$"

gText_ApprenticePickWinSpeech15::
	.string "הממ? את{EMIT_HEY} נראה כמו {PLAYER}{KUN}…\n"
	.string "אבל את{EMIT_HEY} באמת?\l"
	.string "אולי בובת {PLAYER} חכמה?\p"
	.string "אוי, לא, לא, לא, אל תדאג!\n"
	.string "אם את{EMIT_HEY} באמת אמיתי, בבקשה\l"
	.string "תשכח מהגסות רוח שלי.\p"
	.string "אין צורך להיות כל כך כועס. כל מה שאני רוצה\n"
	.string "זה עוד מהעצה הטובה שלך.\p"
	.string "זה נוגע לאמירה.\p"
	.string "בצורה מדויקת יותר, מה אני צריך לומר\n"
	.string "אם אני מנצח קרב?$"

gText_ApprenticeWinSpeechThanks15::
	.string "{STR_VAR_1}\p"
	.string "… … … … … …\n"
	.string "כשאני מנצח משחק…\p"
	.string "{STR_VAR_1}\p"
	.string "…את{EMIT_HEY} רציני?\p"
	.string "אני מבין. אם את{EMIT_HEY} רציני, זה בסדר.\n"
	.string "אני מודה לך על זמנך.\p"
	.string "אני מקווה שאפילו אני אוכל\n"
	.string "להשתמש באמירה הזו כראוי.\p"
	.string "נראה שנגמרו לי העצות\n"
	.string "שאני צריך.\p"
	.string "אני באמת מאמין שהגיע הזמן שאפרד לשלום\n"
	.string "ואצא לדרכי לבד.\p"
	.string "תודה, המנטור שלי!\n"
	.string "אני מתנצל על הספקנות שלי!$"
