FallarborTown_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "אני מברך אותך על הגעתך לאוהל הקרב\n"
	.string "אתר פאלרבור!\p"
	.string "אני המדריכה שלך לטורניר סט נוקאאוט!$"

FallarborTown_BattleTentLobby_Text_TakeChallenge:
	.string "עכשיו, האם ברצונך לקבל את האתגר\n"
	.string "בטורניר סט נוקאאוט?$"

FallarborTown_BattleTentLobby_Text_AwaitAnotherChallenge:
	.string "אנחנו נחכה לאתגר שלך\n"
	.string "בהזדמנות אחרת!$"

FallarborTown_BattleTentLobby_Text_ExplainFallarborTent:
	.string "בפולרבר אוהל הקרב,\n"
	.string "מתקיים טורניר סט נוקאאוט.\p"
	.string "כל המשתתפים נכנסים עם צוות של\n"
	.string "שלושה פוקימונים.\p"
	.string "שלושת הפוקימונים חייבים להיות מסודרים\n"
	.string "בסדר שבו הם יופיעו.\p"
	.string "במהלך הקרב, הפוקימונים יופיעו\n"
	.string "אחד אחד בסדר שנקבע מראש.\p"
	.string "ברגע שפוקימון נכנס לקרב, הוא חייב\n"
	.string "להישאר עד שהקרב יוכרע.\p"
	.string "אם קרב לא יוכרע בתוך\n"
	.string "שלושה סיבובים, הוא יגיע לשיפוט.\p"
	.string "אם ברצונך להפסיק את האתגר,\n"
	.string "אנא שמ{EMIT_VAV}ר{ADD_YUD} את המשחק.\p"
	.string "אם אינך שומר, לא תוכל{ADD_YUD}\n"
	.string "להמשיך עם האתגר שלך.\p"
	.string "אם תצליח{ADD_YUD} להביס\n"
	.string "שלושה מאמנים ברצף,\l"
	.string "אנחנו נעניק לך פרס נפלא.$"

FallarborTown_BattleTentLobby_Text_SaveBeforeChallenge:
	.string "לפני שאדריך אותך לאוהל הקרב,\n"
	.string "אני חייב לשמור. זה בסדר?$"

@ Unused
FallarborTown_BattleTentLobby_Text_WhichLevelMode:
	.string "אנו מציעים שני רמות אתגר,\n"
	.string "רמה 05 ורמה פתוחה.\l"
	.string "מהי הבחירה שלך?$"

FallarborTown_BattleTentLobby_Text_SelectThreeMons:
	.string "טוב מאוד, עכשיו בחר{ADD_YUD} את\n"
	.string "שלושת הפוקימונים שלך.$"

FallarborTown_BattleTentLobby_Text_NotEnoughValidMonsLv50:
	.string "מאתגר יקר!\p"
	.string "אין לך את שלושת הפוקימונים\n"
	.string "הנדרשים לכניסה.\p"
	.string "הם גם חייבים להחזיק פריטים שונים.\p"
	.string "ביצים{STR_VAR_1} אינן מתאימות.\p"
	.string "כאשר תסיים בהכנותיך,\n"
	.string "אנא חז{EMIT_VAV}ר{ADD_YUD}.$"

FallarborTown_BattleTentLobby_Text_NotEnoughValidMonsLvOpen:
	.string "מאתגר יקר!\p"
	.string "אין לך את שלושת הפוקימונים\n"
	.string "הנדרשים לכניסה.\p"
	.string "כדי להשתתף, עליך להביא שלושה\n"
	.string "סוגים שונים של פוקימון.\p"
	.string "הם גם חייבים להחזיק פריטים שונים.\p"
	.string "ביצים{STR_VAR_1} אינן מתאימות.\p"
	.string "כאשר תסיים בהכנותיך,\n"
	.string "אנא חז{EMIT_VAV}ר{ADD_YUD}.$"

FallarborTown_BattleTentLobby_Text_GuideYouToBattleTent:
	.string "כעת אדריך אותך ל\n"
	.string "אוהל הקרב.$"

FallarborTown_BattleTentLobby_Text_DidntSaveBeforeQuitting:
	.string "אתגר יקר!\p"
	.string "לא שמרת את המשחק לפני\n"
	.string "שעצרת את המשחק, נכון?\p"
	.string "לצערנו, זה גרם\n"
	.string "לפסילה מהאתגר.\l"
	.string "אתה כמובן יכול להתחיל\n"
	.string "את האתגר מחדש.$"

FallarborTown_BattleTentLobby_Text_BeatThreeTrainers:
	.string "נפלא! הבסת\n"
	.string "שלושה מאמנים ברצף!$"

FallarborTown_BattleTentLobby_Text_WaitWhileSaveGame:
	.string "אנא המתן בזמן שאני שומר את המשחק.$"

FallarborTown_BattleTentLobby_Text_PresentYouWithPrize:
	.string "לאות כבוד על רצף של 3 הניצחונות שלך,\n"
	.string "אנחנו נעניק לך את הפרס הזה.$"

FallarborTown_BattleTentLobby_Text_ReceivedPrize:
	.string "{PLAYER} קיבל{ADD_HEY} את הפרס\n"
	.string "{STR_VAR_1}.$"

FallarborTown_BattleTentLobby_Text_BagFullReturnForPrize:
	.string "אה?\n"
	.string "התיק שלך נראה מלא.\p"
	.string "אני ממליץ לפנות מקום ולחז{EMIT_VAV}ר\n"
	.string "לקבלת הפרס שלך.$"

FallarborTown_BattleTentLobby_Text_ThankYouWaitWhileSaving:
	.string "תודה רבה על השתתפותך!\p"
	.string "אנא המת{EMIT_VAV}{SWAP_NUN}{ADD_YUD} בזמן שאני שומר את המשחק.$"

FallarborTown_BattleTentLobby_Text_AwaitAnotherChallenge2:
	.string "אנחנו נחכה לאתגר שלך\n"
	.string "בהזדמנות אחרת!$"

FallarborTown_BattleTentLobby_Text_LookingForwardToArrival:
	.string "חיכינו להגעתך.\p"
	.string "לפני שאדריך אותך לאוהל הקרב,\n"
	.string "אני חייב לשמור את המשחק. אנא המת{EMIT_VAV}{SWAP_NUN}{ADD_YUD}.$"

VerdanturfTown_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "אני מברך אותך על הגעתך לאוהל הקרב\n"
	.string "אתר ורדנטרף!\p"
	.string "כאן נבחן את אמונו של המאמן בפוקימון.$"

VerdanturfTown_BattleTentLobby_Text_TakeChallenge:
	.string "האם ברצונך לקבל את אתגר\n"
	.string "אוהל הקרב של ורדנטרף?$"

VerdanturfTown_BattleTentLobby_Text_ExplainVerdanturfTent:
	.string "בורדנטרף אוהל הקרב,\n"
	.string "חוק אחד קריטי חייב להתקיים.\l"
	.string "מאמנים מורשים רק להחליף\n"
	.string "את הפוקימונים שלהם.\p"
	.string "אסור למאמנים לתת הוראות לפוקימון.\p"
	.string "הפוקימון יתנהג לפי טבעו\n"
	.string "וילחם בעצמו.\p"
	.string "עליך לתת אמון בפוקימון שלך\n"
	.string "ולהשגיח עליו.\p"
	.string "אם תצליח{ADD_YUD} להביס שלושה מאמנים\n"
	.string "ברצף,\l"
	.string "תקבל{ADD_YUD} פרס.\p"
	.string "אם ברצונך להפסיק את האתגר,\n"
	.string "אנא שמ{EMIT_VAV}ר{ADD_YUD} את המשחק.\p"
	.string "אם לא תשמ{EMIT_VAV}ר{ADD_YUD}, תפסל{ADD_YUD} מהאתגר.$"

VerdanturfTown_BattleTentLobby_Text_ReturnFortified:
	.string "כאשר חיזקת את לבך\n"
	.string "ופוקימון, עליך לחז{EMIT_VAV}ר{ADD_YUD}.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_WhichLevelMode:
	.string "There are two levels of difficulty,\n"
	.string "Level 50 and Open Level.\l"
	.string "Which is your choice of a challenge?$"

VerdanturfTown_BattleTentLobby_Text_NotEnoughValidMonsLv50:
	.string "אה…\p"
	.string "אין לך את שלושת הפוקימונים\n"
	.string "הנדרשים לאתגר.\p"
	.string "לכניסה דרושים שלושה פוקימונים שונים.\p"
	.string "הם גם חייבים להחזיק פריטים שונים.\p"
	.string "ביצים{STR_VAR_1} אינן מתאימות.\p"
	.string "חז{EMIT_VAV}ר{ADD_YUD} כאשר תסיי{SWAP_MEM}{ADD_YUD} בהכנות.$"

VerdanturfTown_BattleTentLobby_Text_NotEnoughValidMonsLvOpen:
	.string "אה…\p"
	.string "אין לך את שלושת הפוקימונים\n"
	.string "הנדרשים לאתגר.\p"
	.string "לכניסה דרושים שלושה פוקימונים שונים.\p"
	.string "הם גם חייבים להחזיק פריטים שונים.\p"
	.string "ביצים{STR_VAR_1} אינן מתאימות.\p"
	.string "חז{EMIT_VAV}ר{ADD_YUD} כאשר תסיי{SWAP_MEM}{ADD_YUD} בהכנות.$"

VerdanturfTown_BattleTentLobby_Text_SelectThreeMons:
	.string "טוב. עכשיו עליך לבחור\n"
	.string "את שלושת הפוקימונים שלך.$"

VerdanturfTown_BattleTentLobby_Text_SaveBeforeChallenge:
	.string "אני חייב לשמור לפני שאדריך אותך\n"
	.string "לאוהל הקרב. זה בסדר?$"

VerdanturfTown_BattleTentLobby_Text_NowFollowMe:
	.string "טוב.\n"
	.string "עכשיו, עק{EMIT_VAV}ב{ADD_YUD} אחרי.$"

VerdanturfTown_BattleTentLobby_Text_ResultsWillBeRecorded:
	.string "זהו כבוד לראות את הפוקימונים שלך\n"
	.string "בקרבות.\p"
	.string "התוצאות יירשמו.\n"
	.string "אנא המת{ADD_YUD}{SWAP_NUN}{ADD_YUD} מעט.$"

VerdanturfTown_BattleTentLobby_Text_AchievedThreeWinStreak:
	.string "כדי להשיג רצף של 3 ניצחונות…\p"
	.string "הקשרים בין ליבך לפוקימון שלך נראים איתנים ונאמנים.$"

VerdanturfTown_BattleTentLobby_Text_FeatWillBeRecorded:
	.string "הישגך יירשם.\n"
	.string "אנא המת{ADD_YUD}{SWAP_NUN}{ADD_YUD} מעט.$"

VerdanturfTown_BattleTentLobby_Text_PresentYouWithPrize:
	.string "לאות על רצף של 3 הניצחונות שלך,\n"
	.string "אנחנו נעניק לך את הפרס הזה.$"

SlateportCity_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "ברוכים הבאים לאוהל הקרב\n"
	.string "אתר סלייטפורט!\p"
	.string "אני המדריכה שלך לטורניר החלפת קרב.$"

SlateportCity_BattleTentLobby_Text_TakeChallenge:
	.string "האם ברצונך לקבל את אתגר החלפת קרב?$"

SlateportCity_BattleTentLobby_Text_ExplainSlateportTent:
	.string "כאן בסלייטפורט אוהל הקרב,\n"
	.string "מתקיימים אירועי החלפת קרב\l"
	.string "עם פוקימון להשאלה.\p"
	.string "קודם כל, תקבל שלושה פוקימונים\n"
	.string "לשימוש באירוע זה.\p"
	.string "באמצעות הפוקימונים להשאלה,\n"
	.string "עליך לנהל קרב יחיד.\p"
	.string "אם תנצח, תוכל להחליף\n"
	.string "אחד מהפוקימונים של היריב.\p"
	.string "חז{EMIT_VAV}ר{ADD_YUD} על מחז{EMIT_VAV}ר{ADD_YUD} הקרב וההחלפה--\l"
	.string "אם תנצח שלוש פעמים ברצף,\n"
	.string "תקבל פרס נפלא.\p"
	.string "אם ברצונך להפסיק את האתגר,\n"
	.string "אנא שמור את המשחק.\p"
	.string "אם לא תשמ{EMIT_VAV}ר{ADD_YUD} לפני העצירה,\n"
	.string "תפסל{ADD_YUD} מהאתגר.$"

SlateportCity_BattleTentLobby_Text_LookForwardToNextVisit:
	.string "מצפים לביקורך הבא.$"

@ Unused
SlateportCity_BattleTentLobby_Text_WhichLevelMode:
	.string "Which level do you wish to challenge?\n"
	.string "Level 50 or Level 100?$"

SlateportCity_BattleTentLobby_Text_SaveBeforeChallenge:
	.string "לפני תחילת האתגר,\n"
	.string "אני חייב לשמור. האם זה בסדר?$"

@ Unused
SlateportCity_BattleTentLobby_Text_HoldMonsForSafekeeping:
	.string "Okay, I will hold your POKéMON for\n"
	.string "safekeeping while you compete.$"

SlateportCity_BattleTentLobby_Text_StepThisWay:
	.string "אנא צעד{ADD_YUD} בדרך זו.$"

SlateportCity_BattleTentLobby_Text_ReturnRentalMonsSaveResults:
	.string "תודה על השתתפותך!\p"
	.string "אני אחזיר את הפוקימונים שלך בתמורה\n"
	.string "לפוקימון להשאלה שלנו.\p"
	.string "אני גם אשמור את תוצאות האירוע.\n"
	.string "אנא המתן.$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReturnMonsExchangeRentals:
	.string "I will return your POKéMON in exchange\n"
	.string "for our rental POKéMON.$"

SlateportCity_BattleTentLobby_Text_WonThreeMatchesReturnMons:
	.string "ברכות!\n"
	.string "ניצחת שלושה קרבות רצופים!\p"
	.string "אני אחזיר את הפוקימונים שלך בתמורה\n"
	.string "לפוקימון להשאלה שלנו.\p"
	.string "אני גם אשמור את תוצאות האירוע.\n"
	.string "אנא המתן.$"

SlateportCity_BattleTentLobby_Text_AwardYouThisPrize:
	.string "לאות כבוד על רצף של 3 הניצחונות שלך,\n"
	.string "אנחנו נעניק לך את הפרס הזה.$"

SlateportCity_BattleTentLobby_Text_NoRoomInBagMakeRoom:
	.string "אה?\n"
	.string "נראה שאין לך מקום לכך.\p"
	.string "אנא פנ{EMIT_HEY}{ADD_YUD} מקום בתיק שלך\n"
	.string "ואודיע{ADD_YUD} לי.$"

SlateportCity_BattleTentLobby_Text_BeenWaitingForYou:
	.string "חיכינו לך!\p"
	.string "לפני שנמשיך את האתגר,\n"
	.string "אני חייב לשמור את המשחק.$"

SlateportCity_BattleTentLobby_Text_DidntSaveBeforeQuitting:
	.string "מצטער, אך לא שמרת\n"
	.string "לפני שעצרת את המשחק.\p"
	.string "כתוצאה מכך, הורחקת\n"
	.string "מהאתגר שלך.$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReturnPersonalMons:
	.string "We'll return your personal POKéMON.$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReceivedPrize:
	.string "{PLAYER} received the prize\n"
	.string "{STR_VAR_1}.$"

@ Unused
SlateportCity_BattleTentLobby_Text_RulesAreListed:
	.string "The Battle Swap rules are listed.$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReadWhichHeading:
	.string "Which heading do you want to read?$"

SlateportCity_BattleTentLobby_Text_ExplainBasicRules:
	.string "באירוע החלפת קרב, ניתן להשתמש\n"
	.string "רק בשלושה פוקימונים.\p"
	.string "בין אם להשאלה או החלפה,\n"
	.string "הצוות שלך לא יכול להכיל שני\n"
	.string "פוקימונים זהים.$"

SlateportCity_BattleTentLobby_Text_ExplainSwapPartnerRules:
	.string "ניתן להחליף פוקימון רק עם\n"
	.string "המאמן שהבסת זה עתה.\p"
	.string "ניתן להחליף רק בפוקימון\n"
	.string "שמשמש את המאמן המובס.$"

SlateportCity_BattleTentLobby_Text_ExplainSwapNumberRules:
	.string "לאחר כל קרב שבו ניצחת,\n"
	.string "תוכל להחליף אחד מהפוקימונים\n"
	.string "של היריב המובס.\p"
	.string "לא תוכל{ADD_YUD} להחליף פוקימון\n"
	.string "עם המאמן השלישי באירוע.$"

SlateportCity_BattleTentLobby_Text_ExplainSwapNotes:
	.string "יש שני דברים חשובים לדעת\n"
	.string "בזמן החלפת פוקימון.\p"
	.string "ראשית, בהחלפה, אינך יכול לבדוק\n"
	.string "את הסטטיסטיקות של הפוקימונים\n"
	.string "שעתיד להגיע.\p"
	.string "שנית, הפוקימונים בצוות מסודרים\n"
	.string "בסדר שנבחר בעת ההשאלה.\p"
	.string "סדר זה נשמר גם לאחר החלפות.$"

SlateportCity_BattleTentLobby_Text_ExplainMonRules:
	.string "כל הפוקימונים בסלייטפורט אוהל הקרב\n"
	.string "הם להשאלה.\p"
	.string "כל הפוקימונים להשאלה הם\n"
	.string "ברמה 03.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_RulesAreListed2:
	.string "The ורדנטרף אוהל הקרב\n"
	.string "rules are listed.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ReadWhichHeading:
	.string "Which heading do you want to read?$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainBasicRules:
	.string "Here at the ורדנטרף אוהל הקרב,\n"
	.string "POKéMON are required to think and\l"
	.string "battle by themselves.\p"
	.string "Unlike in the wild, POKéMON that live\n"
	.string "with people behave differently\l"
	.string "depending on their nature.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainNatureRules:
	.string "Depending on its nature, a POKéMON\n"
	.string "may prefer to attack no matter what.\p"
	.string "Another POKéMON may prefer to protect\n"
	.string "itself from any harm.\p"
	.string "Yet another may enjoy vexing or\n"
	.string "confounding its foes.\p"
	.string "Depending on its nature, a POKéMON\n"
	.string "will have favorite moves that it is good\l"
	.string "at using.\p"
	.string "It may also dislike certain moves that\n"
	.string "it has trouble using.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainMoveRules:
	.string "There are offensive moves that inflict\n"
	.string "direct damage on the foe.\p"
	.string "There are defensive moves that are\n"
	.string "used to prepare for enemy attacks or\l"
	.string "used to heal HP and so on.\p"
	.string "There are also other somewhat-odd\n"
	.string "moves that may enfeeble the foes with\l"
	.string "stat problems including poison and \l"
	.string "paralysis.\p"
	.string "POKéMON will consider using moves in\n"
	.string "these three categories.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainUnderpoweredRules:
	.string "When not under command by its TRAINER,\n"
	.string "a POKéMON may be unable to effectively\l"
	.string "use certain moves.\p"
	.string "A POKéMON is not good at using any\n"
	.string "move that it dislikes.\p"
	.string "If a POKéMON only knows moves that\n"
	.string "do not match its nature, it will often\l"
	.string "be unable to live up to its potential.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainWhenInDangerRules:
	.string "Depending on its nature, a POKéMON may\n"
	.string "start using moves that don't match its\l"
	.string "nature when it is in trouble.\p"
	.string "If a POKéMON begins behaving oddly\n"
	.string "in a pinch, watch it carefully.$"

BattleTentLobby_Text_ExplainLevelRules:
	.string "באוהל זה, רמות הפוקימונים של היריבים\n"
	.string "יתואמו לרמות הפוקימונים שלך.\l"
	.string "עם זאת, אין מאמן ברמה נמוכה מ03.$"

VerdanturfTown_BattleTentLobby_Text_RulesAreListed:
	.string "חוקי אוהל הקרב של ורדנטרף\n"
	.string "מופיעים כאן.$"
