PetalburgCity_Gym_Text_GiveEnigmaBerry:
	.string "אבא: היי, {PLAYER}!\p"
	.string "קיבלתי עכשיו פרי יער נדיר מאוד.\n"
	.string "אני רוצה שתקח{ADD_YUD} אותו.$"

Route104_Text_PlantBerriesInSoilTakeThis:
	.string "אם את{EMIT_HEY} רואה פירות יער גדלים באדמה\n"
	.string "פורייה, תרגיש{ADD_YUD} חופשי לקחת אותם.\p"
	.string "אבל וודא{ADD_YUD} שאת{EMIT_HEY} שותל{ADD_TAF} פרי יער\n"
	.string "באותו מקום. זה מנהג נימוסי.\p"
	.string "הנה, אני אשתף אותך עם זה.$"

Route104_Text_TrainersOftenMakeMonHoldBerries:
	.string "מראך אומר שאת{EMIT_HEY} חייב{ADD_TAF} להיות\n"
	.string "מאמ{SWAP_NUN}{ADD_TAF}, נכון?\p"
	.string "מאמנים לעיתים נותנים לפוקימון\n"
	.string "להחזיק פירות יער.\p"
	.string "הבחירה היא שלך אם לגדל פירות יער\n"
	.string "או להשתמש בהם.$"

Route111_Text_WateredPlantsEveryDayTakeBerry:
	.string "השקיתי את הצמחים כל יום.\n"
	.string "הם גידלו המון פרחים.\p"
	.string "והם נתנו לי גם המון פירות יער.\p"
	.string "הנה, בשבילך!\n"
	.string "את{EMIT_HEY} יכול{ADD_HEY} לקחת אותו!$"

Route111_Text_GoingToTryToMakeDifferentColorBerries:
	.string "אני עומד לנסות בכל כוחי לייצר\n"
	.string "פירות יער בצבעים שונים.\p"
	.string "אני מקווה שגם את{EMIT_HEY} תתאמ{SWAP_TZADIK}{ADD_YUD}!$"

Route111_Text_WhatColorBerriesToLookForToday:
	.string "אני תוהה באיזה צבע פירות יער אחפש\n"
	.string "היום?$"

Route114_Text_LoveUsingBerryCrushShareBerry:
	.string "אני אוהב להשתמש במכונת מחיצת פירות,\n"
	.string "לכן אני אוסף פירות יער.\p"
	.string "אם תרצ{EMIT_HEY}{ADD_YUD}, אתן לך אחד.$"

Route114_Text_TryBerryCrushWithFriends:
	.string "את{EMIT_HEY} צריך לנסות את המכונת מחיצת פירות\n"
	.string "עם החברים שלך.$"

Route114_Text_FunToThinkAboutBerries:
	.string "איזה פרי יער כדאי לשתול?\n"
	.string "כדאי לך להשתמש במידי או לצבור פירות יער?\p"
	.string "זה כיף לחשוב על זה.$"

Route120_Text_BerriesExpressionOfLoveIsntIt:
	.string "פירות יער גדלים על ידי ספיגת אור השמש.\p"
	.string "אנחנו עוזרים לפירות יער לגדול על ידי\n"
	.string "השקיה סדירה.\p"
	.string "זו הבעת אהבה, לא כך?$"

Route120_Text_YesYouUnderstand:
	.string "כן, כן.\n"
	.string "את{EMIT_HEY} מבי{SWAP_NUN}{ADD_HEY} למה אני מתכוון.\p"
	.string "קח{ADD_YUD} את זה.$"

Route120_Text_MakeYourOwnImpressions:
	.string "או… אבל חשוב ליצור את\n"
	.string "ההתרשמות שלך, אני חושב…\p"
	.string "את{EMIT_HEY} יכול{ADD_HEY} לקחת את זה.$"

Route120_Text_BerryIsRareRaiseItWithCare:
	.string "אני חושב שהפרי יער הזה נדיר.\n"
	.string "אני מקווה שתטפח{ADD_YUD} אותו באהבה.$"

Route120_Text_IllGetMoreBerriesFromBerryMaster:
	.string "אני אקבל עוד פירות יער\n"
	.string "ממומחה הערבוב.$"

LilycoveCity_Text_BerrySuitsYou:
	.string "בסופו של דבר…\p"
	.string "באותו אופן שחליפות מתאימות לי בצורה מושלמת,\n"
	.string "נשיבת רוח קרירה מתאימה לים.\p"
	.string "ואת{EMIT_HEY}, פרי יער מתאים לך בצורה מושלמת…\p"
	.string "למה זה כך?$"

LilycoveCity_Text_BecauseYoureTrainer:
	.string "בסופו של דבר…\p"
	.string "זה כי את{EMIT_HEY} מאמ{SWAP_NUN}{ADD_TAF}!$"

LilycoveCity_Text_PokeblocksSuitPokemon:
	.string "בסופו של דבר…\p"
	.string "כמו שפשטות מעודנת מתאימה לי,\n"
	.string "פוקיגושים מתאימים לפוקימון בצורה מושלמת.$"

Route123_BerryMastersHouse_Text_YoureDeservingOfBerry:
	.string "את{EMIT_HEY} יכול{ADD_HEY} לקרוא לי מומחה לפירות יער.\p"
	.string "אני חולם למלא את העולם\n"
	.string "בפרחים יפים, לכן אני מגדל פירות יער\l"
	.string "ונותן אותם לכל אחד.\p"
	.string "את{EMIT_HEY} ראוי{ADD_HEY} לאחד!$"

Route123_BerryMastersHouse_Text_WhyBeStingyTakeAnother:
	.string "למה להיות קמצן?\n"
	.string "קח{ADD_YUD} עוד אחד!$"

Route123_BerryMastersHouse_Text_VisitPrettyPetalFlowerShop:
	.string "בקר{ADD_YUD} בחנות הפרחים יפה עלי כותרת\n"
	.string "ליד רסטבורו.\p"
	.string "ת{SWAP_NUN}{ADD_YUD} לפרחים למלא את העולם!$"

Route123_BerryMastersHouse_Text_DoneForToday:
	.string "סיימתי להיום.\n"
	.string "תחז{EMIT_VAV}ר{ADD_YUD} ביום אחר.\p"
	.string "ת{SWAP_NUN}{ADD_YUD} לפרחים למלא את העולם!$"

Route123_BerryMastersHouse_Text_HeardAGoodSayingLately:
	.string "האופן שבו בעלי מגדל פירות יער,\n"
	.string "או, הוא הכי טוב בעולם.\p"
	.string "זה גורם לי להיות גאה בו.\p"
	.string "אגב, ילד{ADD_HEY}, שמעת פתגם\n"
	.string "טוב לאחרונה?$"

Route123_BerryMastersHouse_Text_InspirationalTakeThis:
	.string "אה! איזה פתגם יוצא דופן!\n"
	.string "מעורר השראה, הוא!\p"
	.string "אני רוצה שתיקח{ADD_YUD} את זה.$"

Route123_BerryMastersHouse_Text_GoodSayingTakeThis:
	.string "או! זה פתגם טוב.\n"
	.string "את{EMIT_HEY} ממש יוצא{ADD_TAF} דופן.\p"
	.string "אני רוצה שתיקח{ADD_YUD} את זה.$"

Route123_BerryMastersHouse_Text_JoyNeverGoesOutOfMyLife:
	.string "ארבעת נכדינו צריכים להיות\n"
	.string "יותר מוצלחים מבעלי.\p"
	.string "השמחה לא תיעלם מחיי!$"

Route123_BerryMastersHouse_Text_Ah:
	.string "אה…$"

Route104_PrettyPetalFlowerShop_Text_ThisIsPrettyPetalFlowerShop:
	.string "שלום!\p"
	.string "זוהי חנות הפרחים יפה עלי כותרת.\n"
	.string "מפיצים פרחים בכל רחבי העולם!$"

Route104_PrettyPetalFlowerShop_Text_LearnAboutBerries:
	.string "{PLAYER}{KUN}, האם תרצ{EMIT_HEY}{ADD_YUD} ללמוד על\n"
	.string "פירות יער?$"

Route104_PrettyPetalFlowerShop_Text_IntroLearnAboutBerries:
	.string "איך קוראים לך?\p"
	.string "{PLAYER}{KUN}.\n"
	.string "זה שם נחמד.\p"
	.string "{PLAYER}{KUN}, האם תרצ{EMIT_HEY}{ADD_YUD} ללמוד על\n"
	.string "פירות יער?$"

Route104_PrettyPetalFlowerShop_Text_BerriesExplanation:
	.string "פירות יער גדלים על עצים שמסתדרים\n"
	.string "רק באדמה רכה ופורייה.\p"
	.string "אם תיקח{ADD_YUD} כמה פירות יער, הקפ{ADD_YUD}ד{ADD_YUD} לשתול\n"
	.string "אחד שוב באותה אדמה פורייה.\p"
	.string "פרי יער שתשתול יצמיח במהרה נבג,\n"
	.string "יהפוך לצמח, יפרח יפהפייה,\l"
	.string "ואז יגדל פירות יער שוב.\p"
	.string "אני רוצה לראות את עולמנו\n"
	.string "מלא בפרחים יפים.\l"
	.string "זה החלום שלי.\p"
	.string "עזור לי, {PLAYER}{KUN}. שת{EMIT_VAV}ל{ADD_YUD} פירות יער\n"
	.string "והב{ADD_YUD}א{ADD_YUD} עוד פרחים לעולם.$"

Route104_PrettyPetalFlowerShop_Text_FlowersBringHappiness:
	.string "פרחים מביאים כל כך הרבה שמחה\n"
	.string "לאנשים, לא כך?$"

Route104_PrettyPetalFlowerShop_Text_YouCanHaveThis:
	.string "שלום!\p"
	.string "ככל שתתן יותר תשומת לב לפרחים,\n"
	.string "כך הם יפרחו יפות יותר.\p"
	.string "את{EMIT_HEY} תאהב{ADD_YUD} לטפח פרחים. אני בטוחה\n"
	.string "בזה. את{EMIT_HEY} יכול{ADD_HEY} לקבל את זה.$"

Route104_PrettyPetalFlowerShop_Text_WailmerPailExplanation:
	.string "בעת שצמחי פרי יער גדלים,\n"
	.string "השקה אותם עם מזלף וויילמר.\p"
	.string "או, דבר נוסף.\p"
	.string "אם לא תקטוף פירות יער זמן מה,\n"
	.string "הם ייפלו לקרקע.\l"
	.string "אבל הם ינביטו שוב.\p"
	.string "לא מדהים?\n"
	.string "זה כאילו יש להם רצון לחיות.$"

Route104_PrettyPetalFlowerShop_Text_ImGrowingFlowers:
	.string "אני מנסה להיות כמו האחיות הגדולות שלי.\n"
	.string "גם אני מגדלת פרחים!\p"
	.string "הנה, בשבילך!\n"
	.string "זה בשבילך!$"

Route104_PrettyPetalFlowerShop_Text_MachineMixesBerries:
	.string "את{EMIT_HEY} יכול{ADD_HEY} לשתול פרי יער ולגדלו,\n"
	.string "או לגרום לפוקימון להחזיק אותו.\p"
	.string "אבל עכשיו יש מכונה שמערבבת\n"
	.string "פירות יער שונים ומכינה ממתקים\l"
	.string "עבור פוקימון.\p"
	.string "גם אני רוצה קצת ממתקים.$"

SootopolisCity_Text_NameIsKiriHaveOneOfThese:
	.string "היי, איך קוראים לך?\p"
	.string "… … …  … … …  … … …\n"
	.string "אוקיי. נחמד!\p"
	.string "שמי קירי.\p"
	.string "אמי ואבי קראו לי כך כדי\n"
	.string "שאהיה בריאה וחמה בלב.\l"
	.string "זה מה שהם רצו.\p"
	.string "את{EMIT_HEY} יכול{ADD_HEY} לקחת אחד מאלה.$"

SootopolisCity_Text_GiveYouThisBerryToo:
	.string "קירי תתן לך גם את הפרי יער הזה!\n"
	.string "אני ממש אוהבת אותו!$"

SootopolisCity_Text_WhatKindOfWishInYourName:
	.string "אני תוהה איזו בקשה כלולה\n"
	.string "בשם שלך.$"

SootopolisCity_Text_LikeSeasonBornIn:
	.string "אביב, קיץ, סתיו וחורף.\p"
	.string "אם נולדת באביב, האם את{EMIT_HEY} אוהב{ADD_TAF}\n"
	.string "את האביב, ואם נולדת בקיץ, האם\l"
	.string "את{EMIT_HEY} אוהב{ADD_TAF} את הקיץ?$"

SootopolisCity_Text_ThenILoveAutumn:
	.string "אז קירי נולדה בסתיו,\n"
	.string "לכן אני אוהבת את הסתיו!\p"
	.string "איזה עונה את{EMIT_HEY} אוהב{ADD_TAF}?$"

SootopolisCity_Text_OhDoesntMatter:
	.string "או…\n"
	.string "זה לא חשוב…\p"
	.string "יש כל כך הרבה שאני רוצה לדעת…$"
