gText_Birch_Welcome::
	.string "היי! סליחה על ההמתנה!\p"
	.string "ברוכים הבאים לעולם הפוקימונים!\p"
	.string "שמי הוא בירץ'.\p"
	.string "אבל כולם קוראים לי הפרופסור\n"
	.string "לפוקימון.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "זה מה שאנחנו מכנים פוקימון.\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "העולם שלנו מיושב לרווחה\n"
	.string "ביצורים הידועים בשם פוקימון.\p"
	.string "אנחנו בני האדם חיים לצד פוקימון,\n"
	.string "בזמני משחקי ידידות,\l"
	.string "ובזמנים כעובדים משותפים.\p"
	.string "ולפעמים, אנחנו קושרים יחדיו\n"
	.string "ונלחמים באחרים כמונו. \p"
	.string "אבל למרות הקירוב, אנחנו לא\n"
	.string "יודעים הרבה על פוקימון.\p"
	.string "למעשה, יש הרבה, הרבה\n"
	.string "סודות סביב פוקימון.\p"
	.string "כדי לחשוף תעלומות של פוקימון,\n"
	.string "אני עושה מחקרים.\l"
	.string "זה מה שאני עושה.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "ומי אתם?$"

gText_Birch_BoyOrGirl::
	.string "הנך בן?\n"
	.string "או בת?$"

gText_Birch_WhatsYourName::
	.string "מצויין.\n"
	.string "מה שמך?$"

gText_Birch_SoItsPlayer::
	.string "אז זה {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "אה, אוקיי!\p"
	.string "הנך {PLAYER}{KUN} שמגיע\n"
	.string "לעיר מולדי ליטלרוט.\l"
	.string "אני מבין את זה עכשיו!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "בסדר, הנך מוכן?\p"
	.string "ההרפתקאה שלך עומדת\n"
	.string "להתחיל.\p"
	.string "אזרו אומץ, וזנקו אל תוך\n"
	.string "עולם הפוקימונים, איפה שחלומות, \l"
	.string "הרפתקאות, וחברות מחכים!\p"
	.string "ובכן, אני מצפה לראותך מאוחר יותר.\n"
	.string "בואו לראות אותי במעבדת הפוקימון שלי.\p"
	.string "$"
