BerryBlender_Text_BlendWithTheBlendMaster:
	.string "מאסטר הערבוב: אכן כן!\n"
	.string "אני מאסטר הערבוב!\p"
	.string "ערבב איתי, ותראה\n"
	.string "את המיומנות שאני מביא לערבוב!$"

BerryBlender_Text_SeeMyMasteryInAction:
	.string "מאסטר הערבוב: הממ! אז אתה רוצה\n"
	.string "לראות את המיומנות שלי בפעולה?$"

BerryBlender_Text_TooBusyNowIsee:
	.string "הממ!\p"
	.string "אז אתה עסוק מדי עכשיו, אני רואה!\p"
	.string "אבל אל תדאג!\n"
	.string "אני אהיה כאן כל היום!\l"
	.string "חזור במהרה מהסידורים שלך!$"

BerryBlender_Text_BlendMasterNoBerries:
	.string "הממ!\p"
	.string "אין לך אפילו גרגר אחד!\p"
	.string "אני אהיה כאן כל היום!\n"
	.string "חזור במהרה עם כמה גרגרים!$"

BerryBlender_Text_BlendMasterKnowHowToMakePokeblocks:
	.string "כמובן!\n"
	.string "כמובן!\p"
	.string "אגב...\n"
	.string "אתה יודע איך לערבב {POKEBLOCK}S @ TODO\l"
	.string "מגרגרים?$"

BerryBlender_Text_BlendMasterExplainBerryBlending:
	.string "הממ!\p"
	.string "אה, אבל זה תהליך פשוט!\p"
	.string "כשהחץ של הערבוב מגיע לסמן שלך, פשוט לחץ על כפתור A.\p"
	.string "זה כל מה שצריך לעשות.\p"
	.string "כשתראה כמה מדויק אני לוחץ\n"
	.string "על כפתור A, תבין.$"

BerryBlender_Text_BlendMasterLetsBerryBlender:
	.string "טוב!\p"
	.string "בוא נתחיל!\p"
	.string "כולם יחד עם מאסטר הערבוב,\n"
	.string "בואו נערבב גרגרים!$"

BerryBlender_Text_BlendMasterNoPokeblockCase:
	.string "הממ!\p"
	.string "נראה שאין לך את {POKEBLOCK} CASE @ TODO!\p"
	.string "אני אהיה כאן כל היום!\n"
	.string "השג את {POKEBLOCK} CASE @ TODO וחזור במהרה!$"

BerryBlender_Text_BlendMasterPokeblockCaseFull:
	.string "הממ!\p"
	.string "נראה ש-{POKEBLOCK} CASE @ TODO שלך מלא!\p"
	.string "אני אהיה כאן כל היום!\n"
	.string "השתמש בכמה {POKEBLOCK}S @ TODO וחזור במהרה!$"

BerryBlender_Text_WhoaAwesome:
	.string "וואו!\n"
	.string "מדהים!$"

BerryBlender_Text_WickedlyFast:
	.string "מהיר בטירוף!$"

BerryBlender_Text_WhatAnExpert:
	.string "איזה מומחה!$"

BerryBlender_Text_MadeAmazingPokeblocksWithMaster:
	.string "כשערבבתי עם המאסטר,\n"
	.string "יצרנו {POKEBLOCK}S @ TODO מדהימים!$"

BerryBlender_Text_QualitiesOfBlendMaster:
	.string "עיניים שעוקבות אחרי החץ\n"
	.string "בעוצמה מכנית...\p"
	.string "יד שלוחצת על כפתור A\n"
	.string "בדייקנות של שעון...\p"
	.string "המאפיינים האלו הופכים את\n"
	.string "מאסטר הערבוב לגדול באמת.$"

BerryBlender_Text_MasterWorksOnSkillsInMountains:
	.string "אומרים שמאסטר הערבוב עובד\n"
	.string "על כישוריו עמוק בהרים.\p"
	.string "לפעמים, הוא מגיע לליליקוב @ TODO\n"
	.string "כדי לערבב גרגרים כל היום.$"
