gContestHallPaintingCaption::
	.string "{STR_VAR_1}\n"
	.string "{STR_VAR_3} של {STR_VAR_2}$"

@ Unused
gContestPaintingContest::
	.string "תחרות$"

gContestRankNormal::
	.string "דרגה רגילה$"

gContestRankSuper::
	.string "דרגה על$"

gContestRankHyper::
	.string "דרגה היפר$"

gContestRankMaster::
	.string "דרגת מאסטר$"

gContestLink::
	.string "קישור$"

gContestCoolness::
	.string "קוליות$"

gContestBeauty::
	.string "יופי$"

gContestCuteness::
	.string "חמידות$"

gContestSmartness::
	.string "חוכמה$"

gContestToughness::
	.string "חוזק$"

gContestPaintingCool1::
	.string "קוליות בלתי פוסקת--\n"
	.string "הבלתי ניתן להערכה {STR_VAR_1}$"

gContestPaintingCool2::
	.string "היי, אתה!\n"
	.string "הפוקימון הנאה {STR_VAR_1}$" @ TODO

gContestPaintingCool3::
	.string "הנפלא, המדהים, והגדול מאוד {STR_VAR_1}$"

gContestPaintingBeauty1::
	.string "ונוס האחרונה של המאה הזו--\n"
	.string "היפה {STR_VAR_1}$"

gContestPaintingBeauty2::
	.string "החיוך הנוצץ והמנצנץ של {STR_VAR_1}$"

gContestPaintingBeauty3::
	.string "האליל העל של מרכז הפוקימון--\n" @ TODO
	.string "הבלתי ניתן להשוואה {STR_VAR_1}$"

gContestPaintingCute1::
	.string "החמוד והמתוק {STR_VAR_1}$"

gContestPaintingCute2::
	.string "הדיוקן המנצח של {STR_VAR_1} היפה$"

gContestPaintingCute3::
	.string "תן לנו קריצה!\n"
	.string "הפוקימון החמוד {STR_VAR_1}$" @ TODO

gContestPaintingSmart1::
	.string "מאסטר החוכמה--\n"
	.string "הפוקימון החכם {STR_VAR_1}$" @ TODO

gContestPaintingSmart2::
	.string "{STR_VAR_1}--הנבחר\n"
	.string "מעל כל הפוקימונים$" @ TODO

gContestPaintingSmart3::
	.string "הרגע האלגנטי של {STR_VAR_1} המצוין$"

gContestPaintingTough1::
	.string "המהיר השרירי והחזק {STR_VAR_1}$"

gContestPaintingTough2::
	.string "החזק, החזק יותר, והכי חזק {STR_VAR_1}$"

gContestPaintingTough3::
	.string "הפוקימון החזק מאוד\n" @ TODO
	.string "היפר {STR_VAR_1}$"
