@ With the exception of Link standby, none of the below texts are used

gTest_MissedTurn::
	.string "החמיץ תור$"

gText_LinkStandby4::
	.string "המתן לקישור!$"

gText_WinnerIsPlayersMonCongrats::
	.string "המנצח הוא {STR_VAR_1} של {STR_VAR_2}!\n"
	.string "מזל טוב!$"

gText_WinnerIsPlayersMon::
	.string "המנצח הוא {STR_VAR_1} של {STR_VAR_2}!{PAUSE_UNTIL_PRESS}$"

gText_PrimaryJudgingNumX::
	.string "שיפוט ראשי: מס' {STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

gText_SecondaryJudgingNumX::
	.string "שיפוט משני: מס' {STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

gText_SetEventNumX::
	.string "הגדר אירוע: מס' {STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

gText_MoveUsedMostOften::
	.string "המתקפה שהשתמשו בה הכי הרבה:\n"
	.string "{STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

gText_MostImpressiveMon::
	.string "הפוקימון המרשים ביותר:\n" @ TODO
	.string "{STR_VAR_1} של {STR_VAR_2}{PAUSE_UNTIL_PRESS}$"

gText_SetEventNumX2::
	.string "הגדר אירוע: מס' {STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

gText_LinkTVProgramWillNotBeMadeTrainerLost::
	.string "תוכנית טלוויזיה לא תיווצר\n"
	.string "כי המאמן הפסיד.{PAUSE_UNTIL_PRESS}$"
