EventTicket_Text_ShowOldSeaMap:
	.string "המעבורת ל-SLATEPORT @ TODO היא...\p"
	.string "סליחה?\n"
	.string "האם נוכל להפליג למקום הזה במפה?\p"
	.string "אני מכיר מישהו שיוכל לעזור לך יותר.\n"
	.string "אנא המתן.$"

EventTicket_Text_ThatPass:
	.string "המעבורת ל-SLATEPORT @ TODO היא...\p"
	.string "אה?\n"
	.string "הכרטיס הזה...$"

EventTicket_Text_ShowEonTicket:
	.string "היי, חבר, אתה זה שהבאת\n"
	.string "את הכרטיס המוזר הזה?\p"
	.string "אני אגיד לך, אתה מנסה להגיע\n"
	.string "לאי קטן בדרום הרחוק.\p"
	.string "אי אפשר לדעת מה נפגוש\n"
	.string "כשהגענו לשם, הא?\l"
	.string "זה ממש מרגש!\p"
	.string "כולם לעלות!$"

EventTicket_Text_SouthernIslandSailBack:
	.string "היי, חבר, אין כאן מה לראות\n"
	.string "או לעשות באי הזה.\p"
	.string "מה דעתך שנחזור לליליקוב?" @ TODO

EventTicket_Text_SailHome:
	.string "טוב, בסדר!\n"
	.string "נפליג הביתה!$"

EventTicket_Text_AsYouLike:
	.string "טוב, כפי שתרצה.$"

SouthernIsland_Interior_Text_Sign:
	.string ""כל החלומות הם רק מציאות אחרת.\n"
	.string "לעולם אל תשכח..."$"

SouthernIsland_Exterior_Text_Sign:
	.string ""אלו שזכרונותיהם דוהים מחפשים\n"
	.string "לחרוט אותם בליבם..."$"
