EventTicket_Text_OldSeaMapTooFar:
	.string "מה קורה, צעיר?\p"
	.string "מה, זה אתה שאמור להיות עם\n"
	.string "מפה ישנה וקרועה?\p"
	.string "בוא נראה.\n"
	.string "... ... ... ... ... ...\p"
	.string "וואו, זה ממש רחוק.\n"
	.string "אני חושש שאני לא יכול לעזור לך...$"

EventTicket_Text_BrineyHoldOnASecond:
	.string "ברייני: רגע אחד!\p"
	.string "מה פתאום לסרב למישהו שאני חייב לו כל כך הרבה?$"

EventTicket_Text_BrineyLetsSail:
	.string "{PLAYER}{KUN}, אני ממש מצטער.\p"
	.string "באת אליי לבקש עזרה,\n"
	.string "וכמעט סירבנו לך.\p"
	.string "אז תן לי לתקן.\p"
	.string "נפליג מיד, כמובן!\p"
	.string "בוא נמצא את האי הזה\n"
	.string "במפה הישנה!$"

EventTicket_Text_OddTicketGetOnBoard:
	.string "זה אתה שהבאת את הכרטיס המוזר הזה?\p"
	.string "לאן שאתה מנסה להגיע זה אי\n"
	.string "רחוק, רחוק מאוד.\p"
	.string "אף אחד לא יודע מה מחכה שם...\p"
	.string "המחשבה עצמה מרגשת אותי\n"
	.string "כמלח!\p"
	.string "עלה לסיפון, צעיר!$"

FarawayIsland_Entrance_Text_SailorReturn:
	.string "הקפטן ברייני יכול להיות כל כך הפכפך...\p"
	.string "רוצה לחזור לליליקוב?" @ TODO

BirthIsland_Harbor_Text_SailorReturn:
	.string "איזה אי מוזר בצורתו, הא?\n"
	.string "רוצה לחזור לליליקוב?" @ TODO

EventTicket_Text_OddTicketsWhereTo:
	.string "זה אתה שהבאת את כל הכרטיסים המוזרים האלה?\p"
	.string "... ... ...המ.\p"
	.string "הכרטיסים האלה ייקחו אותך לאיים\n"
	.string "רחוקים מאוד.\p"
	.string "אף אחד לא יודע מה מחכה שם,\n"
	.string "או מה יקרה שם.\p"
	.string "המחשבה עצמה מרגשת אותי\n"
	.string "כמלח!\p"
	.string "עלה לסיפון, צעיר!\n"
	.string "לאן נפליג קודם?$"

NavelRock_Harbor_Text_SailorReturn:
	.string "שמעת... שמעת את זה?\n"
	.string "הנהמה הנמוכה מתוך המקום הזה.\p"
	.string "אתה בטוח שזה בטוח?\n"
	.string "אתה חושב שכדאי שנעזוב?$"

FarawayIsland_Entrance_Text_Sign:
	.string "הכתיבה דוהה כאילו נכתבה לפני זמן רב...\p"
	.string ""...בר, יום 6\n"
	.string "אם מישהו... ידרוך כאן שוב...\l"
	.string "שיהיה אדם טוב לב...\l"
	.string "...עם התקווה הזו, אני עוזב..."$"

FarawayIsland_Interior_Text_Mew:
	.string "מייו...$"
