@ Battle Tower
gText_AnabelWonSilver::
	.string "זה מאוד מאכזב...$"

gText_AnabelDefeatSilver::
	.string "אוקיי, הבנתי...$"

gText_AnabelWonGold::
	.string "אני ממש מצטערת...$"

gText_AnabelDefeatGold::
	.string "תודה...$"

@ Battle Dome
gText_TuckerWonSilver::
	.string "אהאהאה! אתה לא מתבייש?\n"
	.string "כולם מסתכלים!$"

gText_TuckerDefeatSilver::
	.string "גרר...\n"
	.string "מה זה...$"

gText_TuckerWonGold::
	.string "התואר שלי כ-ACE של הכיפה @ TODO הוא לא רק בשביל ההצגה!$"

gText_TuckerDefeatGold::
	.string "אהאהאה!\n"
	.string "אתה מעורר השראה!$"

@ Battle Factory
gText_NolandWonSilver::
	.string "עבודה טובה!\n"
	.string "זו הייתה שיעור טוב, הא?$"

gText_NolandDefeatSilver::
	.string "עבודה טובה!\n"
	.string "אתה יודע מה אתה עושה!$"

gText_NolandWonGold::
	.string "היי, היי, היי!\n"
	.string "כבר סיימת?$"

gText_NolandDefeatGold::
	.string "מה קרה כאן?$"

@ Battle Pike
gText_LucyWonSilver::
	.string "המפ...$"

gText_LucyDefeatSilver::
	.string "ארק...$"

gText_LucyWonGold::
	.string "הא!$"

gText_LucyDefeatGold::
	.string "לעזאזל!$"

@ Battle Arena
gText_GretaWonSilver::
	.string "נו באמת!\n"
	.string "אתה צריך להתאמץ יותר מזה!$"

gText_GretaDefeatSilver::
	.string "אין מצב!\n"
	.string "עבודה טובה!$"

gText_GretaWonGold::
	.string "חהחה!\n"
	.string "מה ציפית?$"

gText_GretaDefeatGold::
	.string "הא?\n"
	.string "אתה רציני?!$"

@ Battle Palace
gText_SpenserWonSilver::
	.string "הפוקימונים שלך חלשים כי\n" @ TODO
	.string "אתה חלש כמאמן!$"

gText_SpenserDefeatSilver::
	.string "אה...\n"
	.string "זה כבר משהו אחר...$"

gText_SpenserWonGold::
	.string "גוואהאהאה!\n"
	.string "אחים שלי, אין לנו ממה לפחד!$"

gText_SpenserDefeatGold::
	.string "גוואה!\n"
	.string "חחחח!$"

@ Battle Pyramid
gText_BrandonWonSilver::
	.string "היי! מה קורה איתך!\n"
	.string "בוא נראה קצת מאמץ! קום!$"

gText_BrandonDefeatSilver::
	.string "זהו זה! עשית עבודה נהדרת!\n"
	.string "עבדת קשה בשביל זה!$"

gText_BrandonWonGold::
	.string "היי! אל תוותר עכשיו!\n"
	.string "קום! אל תאבד אמונה בעצמך!$"

gText_BrandonDefeatGold::
	.string "זהו זה! הצלחת!\n"
	.string "המשכת לעבוד בשביל זה!$"
