LilycoveCity_DepartmentStore_1F_Text_LotteryCornerDrawTicket:
	.string "זהו פינת הפוקימון לוטו.\p"
	.string "כל הקונים בחנות כלבו\n"
	.string "יכולים לשלוף כרטיס פוקימון לוטו.\p"
	.string "אם המספר שעל הכרטיס לוטו תואם את\n"
	.string "המספר זיהוי של אחד מהפוקימונים שלך,\l"
	.string "תקבל{ADD_YUD} פרס מופלא.\p"
	.string "רוצה לשלוף כרטיס פוקימון לוטו?$"

LilycoveCity_DepartmentStore_1F_Text_ComeBackTomorrow:
	.string "אנא חז{EMIT_VAV}ר{ADD_YUD} מחר.$"

LilycoveCity_DepartmentStore_1F_Text_PleaseVisitAgain:
	.string "נשמח לראותך שוב.$"

LilycoveCity_DepartmentStore_1F_Text_PleasePickTicket:
	.string "נא לבחור כרטיס לוטו.\n"
	.string "…{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}…{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}…{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

LilycoveCity_DepartmentStore_1F_Text_TicketNumberIsXPleaseWait:
	.string "מספר הכרטיס לוטו הוא {STR_VAR_1}.\p"
	.string "אני צריכה לבדוק אם המספר הזה תואם\n"
	.string "לאחד ממספרי הזיהוי של הפוקימונים שלך.\l"
	.string "נא להמתין.$"

LilycoveCity_DepartmentStore_1F_Text_TicketMatchesPartyMon:
	.string "ברכות!\p"
	.string "המספר זיהוי של חבר הצוות\n"
	.string "{STR_VAR_1} תואם את המספר\l"
	.string "של כרטיס הלוטו שלך!$"

LilycoveCity_DepartmentStore_1F_Text_TicketMatchesPCMon:
	.string "ברכות!\p"
	.string "המספר זיהוי של {STR_VAR_1}\n"
	.string "במחשב שלך תואם את המספר\l"
	.string "של כרטיס הלוטו שלך!$"

LilycoveCity_DepartmentStore_1F_Text_NoNumbersMatched:
	.string "אני מצטערת.\n"
	.string "אף מספר לא תאם.$"

LilycoveCity_DepartmentStore_1F_Text_TwoDigitsMatched:
	.string "שתי ספרות תואמות, אז זכית\n"
	.string "בפרס השלישי!\l"
	.string "זכית ב{STR_VAR_1}!$"

LilycoveCity_DepartmentStore_1F_Text_ThreeDigitsMatched:
	.string "שלוש ספרות תואמות, אז זכית\n"
	.string "בפרס השני!\l"
	.string "זכית ב{STR_VAR_1}!$"

LilycoveCity_DepartmentStore_1F_Text_FourDigitsMatched:
	.string "ארבע ספרות תואמות, אז זכית\n"
	.string "בפרס הראשון!\l"
	.string "זכית ב{STR_VAR_1}!$"

LilycoveCity_DepartmentStore_1F_Text_AllFiveDigitsMatched:
	.string "או, וואי לי, כל חמשת הספרות\n"
	.string "תואמות!\p"
	.string "זכית בפרס הגדול!\n"
	.string "זכית ב{STR_VAR_1}!$"

LilycoveCity_DepartmentStore_1F_Text_NoRoomForThis:
	.string "או?\n"
	.string "נראה שאין לך מקום לזה.\p"
	.string "בבקשה תפנ{EMIT_HEY}{ADD_YUD} מקום בתיק שלך\n"
	.string "ותודיע{ADD_YUD} לי.$"

LilycoveCity_DepartmentStore_1F_Text_PrizeWeveBeenHolding:
	.string "{PLAYER}?\n"
	.string "כן, ציפיתי לבואך.\p"
	.string "זהו הפרס ששמרנו בשבילך.$"

LilycoveCity_DepartmentStore_1F_Text_PleaseVisitAgain2:
	.string "בבקשה תבוא{ADD_YUD} שוב.$"
