LilycoveCity_DepartmentStore_1F_Text_LotteryCornerDrawTicket:
	.string "זהו פינת ההגרלה של פוקימון.\p" @ TODO
	.string "כל הקונים בחנות הכלבו שלנו\n"
	.string "יכולים למשוך כרטיס לוטו פוקימון.\p" @ TODO
	.string "אם המספר של כרטיס הלוטו תואם\n"
	.string "את מספר הזיהוי של אחד מהפוקימונים שלך,\l" @ TODO
	.string "תקבל מתנה נהדרת.\p"
	.string "האם תרצה למשוך כרטיס לוטו פוקימון?\n" @ TODO
	.string "$"

LilycoveCity_DepartmentStore_1F_Text_ComeBackTomorrow:
	.string "אנא חזור מחר.$"

LilycoveCity_DepartmentStore_1F_Text_PleaseVisitAgain:
	.string "אנא בקר שוב.$"

LilycoveCity_DepartmentStore_1F_Text_PleasePickTicket:
	.string "אנא בחר כרטיס לוטו.\n" @ TODO
	.string "…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

LilycoveCity_DepartmentStore_1F_Text_TicketNumberIsXPleaseWait:
	.string "מספר כרטיס הלוטו הוא {STR_VAR_1}.\p"
	.string "אני צריך לבדוק את המספר הזה\n"
	.string "כדי לראות אם הוא תואם לאחד\l"
	.string "ממספרי הזיהוי של הפוקימונים שלך. אנא המתן.$" @ TODO

LilycoveCity_DepartmentStore_1F_Text_TicketMatchesPartyMon:
	.string "מזל טוב!\p"
	.string "מספר הזיהוי של {STR_VAR_1} מהקבוצה שלך\n"
	.string "תואם את מספר כרטיס הלוטו שלך!$" @ TODO

LilycoveCity_DepartmentStore_1F_Text_TicketMatchesPCMon:
	.string "מזל טוב!\p"
	.string "מספר הזיהוי של {STR_VAR_1} שבמחשב שלך\n"
	.string "תואם את מספר כרטיס הלוטו שלך!$" @ TODO

LilycoveCity_DepartmentStore_1F_Text_NoNumbersMatched:
	.string "מצטער.\n"
	.string "אף מספר לא תאם.$"

LilycoveCity_DepartmentStore_1F_Text_TwoDigitsMatched:
	.string "שתי ספרות תואמות, אז זכית בפרס השלישי!\n"
	.string "זכית ב-{STR_VAR_1}!$"

LilycoveCity_DepartmentStore_1F_Text_ThreeDigitsMatched:
	.string "שלוש ספרות תואמות, אז זכית בפרס השני!\n"
	.string "זכית ב-{STR_VAR_1}!$"

LilycoveCity_DepartmentStore_1F_Text_FourDigitsMatched:
	.string "ארבע ספרות תואמות, אז זכית בפרס הראשון!\n"
	.string "זכית ב-{STR_VAR_1}!$"

LilycoveCity_DepartmentStore_1F_Text_AllFiveDigitsMatched:
	.string "וואו, כל חמש הספרות תואמות!\n"
	.string "זכית בפרס הגדול!\p"
	.string "זכית ב-{STR_VAR_1}!$"

LilycoveCity_DepartmentStore_1F_Text_NoRoomForThis:
	.string "אה?\n"
	.string "נראה שאין לך מקום לזה.\p"
	.string "אנא פנה מקום בתיק שלך ותגיד לי.$"

LilycoveCity_DepartmentStore_1F_Text_PrizeWeveBeenHolding:
	.string "{PLAYER}?\n"
	.string "כן, חיכיתי לך.\p"
	.string "זהו הפרס ששמרנו עבורך\n"
	.string "במיוחד.$"

LilycoveCity_DepartmentStore_1F_Text_PleaseVisitAgain2:
	.string "אנא בקר שוב.$"
