MatchCall_WildBattleText1::
	.string "היי! {PLAYER}{KUN}, שלום!\n"
	.string "זה {STR_VAR_1}.\p"
	.string "ראיתי את ה{STR_VAR_2} הזה לפני\n"
	.string "זמן מה אבל לא הצלחתי לתפוס אותו.\p"
	.string "זה היה גם כל כך קרוב!\n"
	.string "טוב, נתראה שוב!$"

MatchCall_WildBattleText2::
.string "שלום, {PLAYER}{KUN}.\n"	
	.string "זו {STR_VAR_1}.\p"
	.string "ניסיתי לתפוס {STR_VAR_2} נחמד\n"
	.string "לפני זמן קצר.\p"
	.string "אבל, הוא ברח.\n"
	.string "הייתי בטוח מאוכזב!\p"
	.string "אוקיי, ביי!$"

MatchCall_WildBattleText3::
	.string "היי {PLAYER}!\n"
	.string "זה אני, {STR_VAR_1}.\p"
	.string "בדיוק ניסיתי לתפוס\n"
	.string "את ה{STR_VAR_2} הזה, אבל הוא ברח.\p"
	.string "הייתי כל כך קרוב, גם!\p"
	.string "זה הרס לי את היום…\n"
	.string "טוב, נתראה!$"

MatchCall_WildBattleText4::
	.string "היי, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} כאן.\p"
	.string "את{EMIT_HEY} מכיר את הפוקימון {STR_VAR_2}?\n"
	.string "כמעט השגתי אחד.\p"
	.string "זה היה ממש לפני זמן קצר.\n"
	.string "חשבתי שתפסתי אותו אבל הוא ברח.\p"
	.string "אם אראה אותו שוב, אני אשיג אותו\n"
	.string "בטוח, למרות זאת.\p"
	.string "טוב, נתפוס אותך מאוחר יותר.$"

MatchCall_WildBattleText5::
	.string "היי, {PLAYER}{KUN}!\n"
	.string "זו {STR_VAR_1}.\l"
	.string "תפסת פוקימונים לאחרונה?\p"
	.string "לפני זמן קצר הייתי קרוב ל\n"
	.string "לתפוס אחד, אבל הוא השתחרר.\p"
	.string "טוב, שמ{EMIT_VAV}ר{ADD_YUD} על עצמך!$"

MatchCall_WildBattleText6::
	.string "היי, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} כאן.\l"
	.string "תפסת פוקימונים לאחרונה?\p"
	.string "כמעט תפסתי אחד יום אחד.\n"
	.string "אבל הוא חמק ממני איכשהו.\p"
	.string "שמ{EMIT_VAV}ר{ADD_YUD} על עצמך.$"

MatchCall_WildBattleText7::
	.string "…אה, {PLAYER}{KUN}?\n"
	.string "זה אני, {STR_VAR_1}.\p"
	.string "אה, רגע! רגע!\n"
	.string "אני יכול לתפוס את ה{STR_VAR_2} הזה…\p"
	.string "אאאררג! הוא ברח!\n"
	.string "זה לא היה רק קרוב!$"

MatchCall_WildBattleText8::
	.string "אוי, {PLAYER}{KUN}, מה שלומך?\n"
	.string "זה {STR_VAR_1} מדבר.\p"
	.string "האם הצלחת בתפיסת\n"
	.string "פוקימונים לאחרונה?\p"
	.string "הייתי קרוב מאוד לפני זמן קצר\n"
	.string "אבל המטרה שלי השתחררה.\p"
	.string "אני צריך לנסות יותר!\n"
	.string "נתראה שוב!$"

MatchCall_WildBattleText9::
	.string "אוי, {PLAYER}{KUN}, היי!\n"
	.string "זו {STR_VAR_1}!\p"
	.string "נו? את{EMIT_HEY} אוסף עוד פוקימונים?\n"
	.string "יחד?\p"
	.string "לי הולך רע עם זה!\n"
	.string "הם כולם בורחים ממני!\p"
	.string "נתראה!$"

MatchCall_WildBattleText10::
	.string "אוי, {PLAYER}{KUN}, שלום…\n"
	.string "זה {STR_VAR_1}.\p"
	.string "תקשיב, הייתי כפסע\n"
	.string "מללכוד את ה{STR_VAR_2} הזה…\p"
	.string "אבל, הוא חמק ממני…\p"
	.string "אני צריך לנסות יותר.\n"
	.string "נתראה בסביבה.$"

MatchCall_WildBattleText11::
	.string "אה, {PLAYER}{KUN}.\n"
	.string "זה {STR_VAR_1}.\l"
	.string "מה שלומך?\p"
	.string "ניסיתי לתפוס {STR_VAR_2} פראי\n"
	.string "מוקדם יותר, אבל הוא הצליח לברוח.\p"
	.string "אני מרגיש מובס…$"

MatchCall_WildBattleText12::
	.string "שלום, {PLAYER}{KUN}.\n"
	.string "זה אני, {STR_VAR_1}.\l"
	.string "את{EMIT_HEY} עדיין תופס פוקימונים?\p"
	.string "אני ניסיתי לתפוס אותם\n"
	.string "בעצמי, אבל זה לא קל כל כך.\p"
	.string "דרך הפוקימון היא עמוקה!$"

MatchCall_WildBattleText13::
	.string "אה, שלום, {PLAYER}{KUN}!\n"
	.string "זה {STR_VAR_1}!\l"
	.string "האם תפסת פוקימונים?\p"
	.string "אני ניסיתי לתפוס אותם\n"
	.string "בעצמי, אבל עם הצלחה מועטה.\p"
	.string "דרך הפוקימון היא עמוקה!$"

MatchCall_WildBattleText14::
	.string "אוי, היי, {PLAYER}{KUN}, מה שלומך?\n"
	.string "זה {STR_VAR_1}.\p"
	.string "בדיוק עכשיו, ניסיתי לתפוס {STR_VAR_2}\n"
	.string "חמוד.\p"
	.string "הוא ברח, למרות זאת!\n"
	.string "אוי, את{EMIT_HEY} יכול להמר שהייתי מאוכזב!\p"
	.string "ביי ביי!$"

MatchCall_WildBattleText15::
	.string "היי, {PLAYER}!\n"
	.string "זה {STR_VAR_1}!\p"
	.string "חשבתי לנסות\n"
	.string "לתפוס לי כמה פוקימונים.\p"
	.string "אבל אני לא מצליח למצוא אף אחד.\n"
	.string "זו ממש תעלומה בשבילי!\p"
	.string "אני אובד עצות!\n"
	.string "נתראה בסביבה!$"

MatchCall_NegativeBattleText1::
	.string "היי! {PLAYER}{KUN}, שלום!\n"
	.string "זה {STR_VAR_1}.\p"
	.string "ניסיתי להילחם במאמן אחר,\n"
	.string "אבל הפסדתי.\p"
	.string "זה היה ממש מאכזב.\n"
	.string "טוב, נתראה שוב!$"

MatchCall_NegativeBattleText2::
	.string "שלום, {PLAYER}{KUN}.\n"
	.string "זו {STR_VAR_1}.\p"
	.string "אתגרתי מישהו אחר אחרי\n"
	.string "שנלחמנו.\p"
	.string "הייתי קרוב, אבל בסוף\n"
	.string "הפסדתי. נו מילא!$"

MatchCall_NegativeBattleText3::
	.string "היי {PLAYER}!\n"
	.string "זה אני, {STR_VAR_1}.\p"
	.string "הרגע חטפתי הפסד בקרב.\p"
	.string "אני מניח שאני צריך לאמן את הצוות שלי\n"
	.string "עוד קצת!$"

MatchCall_NegativeBattleText4::
	.string "היי, {PLAYER}.\n"
	.string "{STR_VAR_1} כאן.\p"
	.string "ניסיתי קרב נוסף אתמול,\n"
	.string "אבל לא הצלחתי לנצח.\p"
	.string "הצוות שלי צריך עוד אימון.\n"
	.string "טוב, נתפוס אותך מאוחר יותר.$"

MatchCall_NegativeBattleText5::
	.string "היי {PLAYER}!\n"
	.string "זו {STR_VAR_1}.\p"
	.string "מה שלומך?\p"
	.string "אני ממשיך להילחם,\n"
	.string "אבל לא ניצחתי לעיתים קרובות.\p"
	.string "אני לא מצליח להתארגן על עצמי.\n"
	.string "טוב, שמ{EMIT_VAV}ר{ADD_YUD} על עצמך!$"

MatchCall_NegativeBattleText6::
	.string "היי, {PLAYER}.\n"
	.string "{STR_VAR_1} כאן.\p"
	.string "מה קורה איתך?\p"
	.string "נלחמתי קשה לאחרונה,\n"
	.string "אך עם הצלחה מועטה.\p"
	.string "אני לא מצליח להיכנס לקצב.\n"
	.string "שמ{EMIT_VAV}ר{ADD_YUD} על עצמך.$"

MatchCall_NegativeBattleText7::
	.string "{STR_VAR_1} כאן.\n"
	.string "מה קורה לאחרונה?\p"
	.string "הפסדתי בקרב אתמול,\n"
	.string "וזה ממלא את מחשבותיי.\p"
	.string "אני חייב לתכנן תוכנית…\n"
	.string "נתראה.$"

MatchCall_NegativeBattleText8::
	.string "אוי, {PLAYER}{KUN}, מה שלומך?\n"
	.string "זו {STR_VAR_1} מדברת.\p"
	.string "מה שלום הפוקימונים שלך?\n"
	.string "הפסדתי בקרב יום אחד.\p"
	.string "אני צריך לנסות יותר!\n"
	.string "נתראה שוב!$"

MatchCall_NegativeBattleText9::
	.string "אוי, {PLAYER}{KUN}, היי!\n"
	.string "זו {STR_VAR_1}!\p"
	.string "תקשיב, תקשיב, את{EMIT_HEY} חייב{ADD_TAF} לשמוע\n"
	.string "את זה!\p"
	.string "היה לי קרב פוקימונים מוקדם יותר,\n"
	.string "אבל הפסדתי ברגע האחרון.\p"
	.string "אוי, זה שורף אותי!$"

MatchCall_NegativeBattleText10::
	.string "אוי, {PLAYER}{KUN}, שלום…\n"
	.string "זה {STR_VAR_1}.\p"
	.string "לפני זמן קצר, הייתי בקרב.\n"
	.string "הפסדתי, למרות זאת.\p"
	.string "אני צריך לאמן את הפוקימונים שלי יותר.\n"
	.string "נתראה בסביבה.$"

MatchCall_NegativeBattleText11::
	.string "אה, {PLAYER}{KUN}.\n"
	.string "זה {STR_VAR_1}.\l"
	.string "מה שלום הפוקימונים שלך?\p"
	.string "בדיוק הפסדתי בקרב נוסף.\p"
	.string "טוב, נתראה!$"

MatchCall_NegativeBattleText12::
	.string "שלום, {PLAYER}{KUN}.\n"
	.string "זה אני, {STR_VAR_1}.\l"
	.string "את{EMIT_HEY} עדיין נלחם קשה?\p"
	.string "לגבי, הפסדתי לאחרונה, אז אני\n"
	.string "מאמן את הצוות שלי מחדש לגמרי.\p"
	.string "בוא{ADD_YUD} ניפגש שוב.$"

MatchCall_NegativeBattleText13::
	.string "אה, שלום, {PLAYER}{KUN}!\n"
	.string "זה {STR_VAR_1}!\p"
	.string "אני מקווה שאת{EMIT_HEY} שומר על עצמך.\p"
	.string "הייתי בקרב ממש קצת\n"
	.string "לפני השיחה הזו.\p"
	.string "{PLAYER}{KUN}, תנס{EMIT_HEY}{ADD_YUD} להיות פעיל כמוני.\n"
	.string "נתראה שוב!$"

MatchCall_NegativeBattleText14::
	.string "אוי, היי, {PLAYER}{KUN}.\n"
	.string "זה {STR_VAR_1}.\p"
	.string "האם את{EMIT_HEY} בסדר?\p"
	.string "את{EMIT_HEY} צריך ללכת הביתה מדי פעם,\n"
	.string "למרות זאת.\p"
	.string "ביי ביי!$"

MatchCall_PositiveBattleText1::
	.string "היי! {PLAYER}{KUN}, שלום!\n"
	.string "זה {STR_VAR_1}!\p"
	.string "נלחמתי במאמן אחר מוקדם יותר.\n"
	.string "ניצחתי! ניצחתי!\p"
	.string "ה{STR_VAR_2} שלי באמת עבד קשה\n"
	.string "בשבילי. זה כל כך נהדר!$"

MatchCall_PositiveBattleText2::
	.string "שלום, {PLAYER}{KUN}!\n"
	.string "זו {STR_VAR_1}!\p"
	.string "היה לי קרב אתמול ו\n"
	.string "ניצחתי! זה פנטסטי!$"

MatchCall_PositiveBattleText3::
	.string "היי {PLAYER}!\n"
	.string "זה אני, {STR_VAR_1}!\l"
	.string "מה מצב הקרבות שלך?\p"
	.string "אני, היה לי קרב יום אחד,\n"
	.string "וה{STR_VAR_2} שלי היה ענק!\p"
	.string "בפעם הבאה שנילחם,\n"
	.string "{PLAYER}, זה לא יהיה אני המפסיד!$"

MatchCall_PositiveBattleText4::
	.string "היי, {PLAYER}.\n"
	.string "{STR_VAR_1} כאן.\p"
	.string "היה לי קרב מוקדם יותר.\n"
	.string "הצלחתי לנצח, אבל זה היה צמוד.\p"
	.string "ה{STR_VAR_2} שלי נתן הופעה\n"
	.string "מלאת השראה.$"

MatchCall_PositiveBattleText5::
	.string "היי, {PLAYER}{KUN}!\n"
	.string "זו {STR_VAR_1}.\p"
	.string "מה שלומך?\n"
	.string "נלחם הרבה?\p"
	.string "בדיוק ניצחתי לפני זמן קצר!\n"
	.string "ה{STR_VAR_2} שלי היה מבריק!\p"
	.string "חכ{EMIT_HEY}{ADD_YUD} ותראה. אני אנצח אותך\n"
	.string "בפעם הבאה! טוב, שמ{EMIT_VAV}ר{ADD_YUD} על עצמך!$"

MatchCall_PositiveBattleText6::
	.string "היי, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} כאן.\p"
	.string "מה קורה איתך?\p"
	.string "אני נמצא במומנטום חם.\n"
	.string "למעשה, בדיוק ניצחתי בקרב.\p"
	.string "בפעם הבאה שיהיה לנו קרב,\n"
	.string "אני בטוח לא הולך להפסיד!$"

MatchCall_PositiveBattleText7::
	.string "{PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} כאן.\p"
	.string "ה{STR_VAR_2} שלי הוא כוח!\n"
	.string "הוא ניצח לי בקרב נוסף בדיוק עכשיו!\p"
	.string "אני לא יכול לחכות לקרב חוזר\n"
	.string "איתך.$"

MatchCall_PositiveBattleText8::
	.string "אוי, {PLAYER}{KUN}, מה שלומך?\n"
	.string "זו {STR_VAR_1} מדברת.\p"
	.string "אני מקווה שהיית בסדר.\n"
	.string "רציתי לספר לך שבדיוק ניצחתי.\p"
	.string "ה{STR_VAR_2} שלי עבד במיוחד\n"
	.string "קשה כדי להשיג את הניצחון.\p"
	.string "נתראה שוב!$"

MatchCall_PositiveBattleText9::
	.string "אוי, {PLAYER}{KUN}, היי!\n"
	.string "זו {STR_VAR_1}!\p"
	.string "מה שלום הפוקימונים שלך?\n"
	.string "שלי בדיוק ניצח בקרב!\p"
	.string "ה{STR_VAR_2} שלי היה מרהיב,\n"
	.string "אני חייב לציין!\p"
	.string "הלוואי שיכולתי להראות לך!\n"
	.string "נתראה שוב!$"

MatchCall_PositiveBattleText10::
	.string "אוי, {PLAYER}{KUN}, שלום…\n"
	.string "זה {STR_VAR_1}.\p"
	.string "איך החיים מתייחסים אליך?\p"
	.string "הפוקימונים שלי נראים\n"
	.string "מלאי אנרגיה.\p"
	.string "בדיוק ניצחתי איתם בקרב.\n"
	.string "נתראה בסביבה.$"

MatchCall_PositiveBattleText11::
	.string "אה, {PLAYER}{KUN}.\n"
	.string "זה {STR_VAR_1}.\p"
	.string "היית בקרבות לאחרונה?\n"
	.string "בדיוק ניצחתי באחד נוסף היום!\p"
	.string "אני במומנטום! גאהאהאהא!\n"
	.string "טוב, נתראה!$"

MatchCall_PositiveBattleText12::
	.string "שלום, {PLAYER}{KUN}.\n"
	.string "זה אני, {STR_VAR_1}.\p"
	.string "אני סומך על כך שהיית בסדר?\n"
	.string "אני עדיין מתפקע מחיים!\p"
	.string "למעשה, בדיוק עכשיו, ניצחתי בקרב נוסף.\n"
	.string "אני לא מפנה את מקומי ל\l"
	.string "צעירים עדיין!$"

MatchCall_PositiveBattleText13::
	.string "אה, שלום, {PLAYER}{KUN}!\n"
	.string "זה {STR_VAR_1}!\p"
	.string "אני מקווה שאת{EMIT_HEY} שומר על עצמך.\n"
	.string "עדיין יש לי קפיץ בצעד!\p"
	.string "למעשה, בדיוק ניצחתי בקרב שוב.\n"
	.string "אוי, אני לא אפסיד לצעירים\l"
	.string "עדיין!\p"
	.string "נתראה שוב!$"

MatchCall_PositiveBattleText14::
	.string "אוי, היי, {PLAYER}{KUN}.\n"
	.string "זה {STR_VAR_1}.\p"
	.string "הייתי בקרב לאחרונה, וה{STR_VAR_2} שלי\n"
	.string "היה יוצא דופן!\p"
	.string "הלוואי שיכולת לראות את זה,\n"
	.string "{PLAYER}{KUN}. ביי ביי!$"

MatchCall_SameRouteBattleRequestText1::
	.string "היי! {PLAYER}, שלום!\n"
	.string "זה {STR_VAR_1}.\p"
	.string "הא? רגע, את{EMIT_HEY} ליד\n"
	.string "{STR_VAR_2}?\p"
	.string "אוי, וואו, אנחנו חייבים להילחם, אם כן!\n"
	.string "אני אחכ{EMIT_HEY}{ADD_YUD}! נתראה!$"

MatchCall_SameRouteBattleRequestText2::
	.string "שלום, {PLAYER}!\n"
	.string "זו {STR_VAR_1}.\p"
	.string "אה? במקרה את{EMIT_HEY} נמצא בסביבת\n"
	.string "{STR_VAR_2} עכשיו?\p"
	.string "תרצה להילחם עכשיו?\n"
	.string "אני אחכ{EMIT_HEY}{ADD_YUD} לך! נתראה!$"

MatchCall_SameRouteBattleRequestText3::
	.string "היי {PLAYER}!\n"
	.string "זה אני, {STR_VAR_1}.\p"
	.string "אוי, היי, את{EMIT_HEY} קרוב ל\n"
	.string "{STR_VAR_2} עכשיו?\p"
	.string "מה דעתך להילחם\n"
	.string "איתי ממש עכשיו?\p"
	.string "אני לא מפסיד שוב!\n"
	.string "אני אחכ{EMIT_HEY}{ADD_YUD}! נתפוס אותך בקרוב!$"

MatchCall_SameRouteBattleRequestText4::
	.string "היי, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} כאן.\p"
	.string "איפה את{EMIT_HEY} נמצא עכשיו?\n"
	.string "הא? {STR_VAR_2}?\p"
	.string "רוצה להילחם עכשיו?\n"
	.string "אני אחכ{EMIT_HEY}{ADD_YUD} לך. נתראה!$"

MatchCall_SameRouteBattleRequestText5::
	.string "היי, {PLAYER}{KUN}!\n"
	.string "זו {STR_VAR_1}.\l"
	.string "מה שלומך?\p"
	.string "איפה את{EMIT_HEY} עכשיו?\n"
	.string "{STR_VAR_2}?\p"
	.string "טוב, מה דעתך על קרב חוזר\n"
	.string "מהיר עכשיו?\p"
	.string "אני אשגיח עליך.\n"
	.string "נתראה בקרוב!$"

MatchCall_SameRouteBattleRequestText6::
	.string "היי, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} כאן.\l"
	.string "מה שלום הפוקימונים שלך?\p"
	.string "אה, זה נכון? את{EMIT_HEY} בסביבת\n"
	.string "{STR_VAR_2}?\p"
	.string "טוב, אם כך, עדיף שיהיה לנו\n"
	.string "קרב חוזר.\p"
	.string "אני יכול לחכות, בטח.\n"
	.string "נתראה!$"

MatchCall_SameRouteBattleRequestText7::
	.string "…אה, {PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} כאן…\p"
	.string "אה, במקרה את{EMIT_HEY} נמצא בסביבת\n"
	.string "{STR_VAR_2}?\p"
	.string "אם כך, בוא{ADD_YUD} נלחם.\n"
	.string "ממש עכשיו, אני מתכוון.\p"
	.string "אני אראה לך את הפוקימונים שלי.\n"
	.string "אני אחכ{EMIT_HEY}{ADD_YUD} לך.$"

MatchCall_SameRouteBattleRequestText8::
	.string "אוי, {PLAYER}{KUN}, מה שלומך?\n"
	.string "זו {STR_VAR_1} מדברת.\p"
	.string "אני מקווה שאת{EMIT_HEY} עושה חיל.\n"
	.string "אוי, את{EMIT_HEY} ליד {STR_VAR_2}.\p"
	.string "תרצה להילחם\n"
	.string "איתי, אם כן?\p"
	.string "אני אחכ{EMIT_HEY}{ADD_YUD} לך.\n"
	.string "נתראה בקרוב!$"

MatchCall_SameRouteBattleRequestText9::
	.string "אוי, {PLAYER}{KUN}, היי!\n"
	.string "זו {STR_VAR_1}!\p"
	.string "את{EMIT_HEY} מתקדם?\n"
	.string "אה, את{EMIT_HEY} ליד {STR_VAR_2}?\p"
	.string "אוי, טוב, אם כן את{EMIT_HEY} לא חושב ש\n"
	.string "צריכים להילחם?\p"
	.string "אל תגרום לי לחכות יותר מדי זמן!$"

MatchCall_SameRouteBattleRequestText10::
	.string "אוי, {PLAYER}{KUN}, שלום…\n"
	.string "זה {STR_VAR_1}.\p"
	.string "מה שלומך?\n"
	.string "אוי, את{EMIT_HEY} ליד {STR_VAR_2}.\p"
	.string "אנחנו צריכים להילחם עכשיו, אם כן.\p"
	.string "אני מוכן ומחכ{EMIT_HEY}{ADD_YUD}.\n"
	.string "תזדרז!$"

MatchCall_SameRouteBattleRequestText11::
	.string "אה, {PLAYER}{KUN}.\n"
	.string "זה {STR_VAR_1}.\p"
	.string "אה, אז איפה שאת{EMIT_HEY} נמצא עכשיו זה\n"
	.string "{STR_VAR_2}?\p"
	.string "טוב, אם כן, אנחנו פשוט חייבים\n"
	.string "להילחם, את{EMIT_HEY} לא חושב?\p"
	.string "אני אחכ{EMIT_HEY}{ADD_YUD} לך בסביבה!\n"
	.string "נתראה ממש מהר!$"

MatchCall_SameRouteBattleRequestText12::
	.string "שלום, {PLAYER}{KUN}.\n"
	.string "זה אני, {STR_VAR_1}.\l"
	.string "איפה את{EMIT_HEY} נמצא עכשיו?\p"
	.string "{STR_VAR_2}?\n"
	.string "זה די קרוב!\p"
	.string "מה תגיד שנילחם\n"
	.string "עכשיו?\p"
	.string "אני יכול לחכות.\n"
	.string "נתראה!$"

MatchCall_SameRouteBattleRequestText13::
	.string "אה, שלום, {PLAYER}{KUN}!\n"
	.string "זה {STR_VAR_1}!\p"
	.string "אני מקווה שאת{EMIT_HEY} שומר על עצמך.\n"
	.string "אה, את{EMIT_HEY} ליד {STR_VAR_2}?\p"
	.string "מכיוון שזה לא מאוד רחוק,\n"
	.string "בוא{ADD_YUD} לראות אותי לקרב.\p"
	.string "אני אחכ{EMIT_HEY}{ADD_YUD} לך.\n"
	.string "ביי לעת עתה.$"

MatchCall_SameRouteBattleRequestText14::
	.string "אוי, היי, {PLAYER}{KUN}.\n"
	.string "זה {STR_VAR_1}.\p"
	.string "את{EMIT_HEY} מה? …{STR_VAR_2}?\n"
	.string "זה מאוד קרוב.\p"
	.string "את{EMIT_HEY} לא חושב שאנחנו צריכים\n"
	.string "להילחם?\p"
	.string "אני אחפש אותך!\n"
	.string "ביי ביי!$"

MatchCall_DifferentRouteBattleRequestText1::
	.string "היי! {PLAYER}, שלום!\n"
	.string "זה {STR_VAR_1}.\p"
	.string "רוצה להילחם איתי?\p"
	.string "אני אחכ{EMIT_HEY}{ADD_YUD} לך בסביבת\n"
	.string "{STR_VAR_2}!$"

MatchCall_DifferentRouteBattleRequestText2::
	.string "שלום, {PLAYER}!\n"
	.string "זו {STR_VAR_1}.\p"
	.string "תרצה להילחם\n"
	.string "איתי שוב?\p"
	.string "את{EMIT_HEY} יכול למצוא אותי בסביבת\n"
	.string "{STR_VAR_2}. אני אחכ{EMIT_HEY}{ADD_YUD}!$"

MatchCall_DifferentRouteBattleRequestText3::
	.string "היי {PLAYER}!\n"
	.string "זה אני, {STR_VAR_1}.\p"
	.string "הפוקימונים שלי התחזקו הרבה\n"
	.string "מאז הפעם האחרונה.\p"
	.string "אני רוצה לראות כמה חזקים הם\n"
	.string "נהיו מול הפוקימונים שלך, {PLAYER}.\p"
	.string "אז, בוא{ADD_YUD} נילחם!\p"
	.string "אני אחכ{EMIT_HEY}{ADD_YUD} לך בסביבת\n"
	.string "{STR_VAR_2}.$"

MatchCall_DifferentRouteBattleRequestText4::
	.string "היי, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} כאן.\l"
	.string "מה שלומך?\p"
	.string "הפוקימונים שלי נהיו די\n"
	.string "חזקים לאחרונה.\p"
	.string "היי, מה דעתך על\n"
	.string "עוד קרב איתי?\p"
	.string "בוא{ADD_YUD} ניפגש בסביבת\n"
	.string "{STR_VAR_2}, בסדר?$"

MatchCall_DifferentRouteBattleRequestText5::
	.string "היי, {PLAYER}{KUN}!\n"
	.string "זו {STR_VAR_1}.\p"
	.string "הפוקימונים שלי גדלים בצורה\n"
	.string "ראויה.\p"
	.string "אני ממש רוצה עוד\n"
	.string "קרב איתך.\p"
	.string "אני אשגיח עליך בסביבת\n"
	.string "{STR_VAR_2}. נתראה בקרוב!$"

MatchCall_DifferentRouteBattleRequestText6::
	.string "היי, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} כאן.\l"
	.string "אני מקווה שאת{EMIT_HEY} מטפל בעניינים.\p"
	.string "חשבתי שאני רוצה עוד\n"
	.string "קרב איתך. מה דעתך?\p"
	.string "אם מתחשק לך קרב,\n"
	.string "בוא{ADD_YUD} ל{STR_VAR_2}.\p"
	.string "נתראה!$"

MatchCall_DifferentRouteBattleRequestText7::
	.string "…אה, {PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} כאן…\l"
	.string "נו? הפוקימונים שלך גדלים?\p"
	.string "שלי בטוח התחזקו.\n"
	.string "אני רוצה להראות לך.\p"
	.string "אני אהיה בסביבת {STR_VAR_2}.\n"
	.string "בוא{ADD_YUD} לראות אותי לקרב.\p"
	.string "נתראה בסביבה.$"

MatchCall_DifferentRouteBattleRequestText8::
	.string "אוי, {PLAYER}{KUN}, מה שלומך?\n"
	.string "זו {STR_VAR_1} מדברת.\p"
	.string "אני מקווה שאת{EMIT_HEY} עושה חיל.\n"
	.string "הפוקימונים שלי מאוד שובבים.\p"
	.string "אם את{EMIT_HEY} אי פעם באזור, בבקשה\n"
	.string "תביא לי קרב חוזר.\p"
	.string "אני אהיה בסביבת {STR_VAR_2}.\n"
	.string "עד אז, להתראות!$"

MatchCall_DifferentRouteBattleRequestText9::
	.string "אוי, {PLAYER}{KUN}, היי!\n"
	.string "זו {STR_VAR_1}!\l"
	.string "מה שלום הפוקימונים שלך?\p"
	.string "הפוקימונים שלי ממשיכים להשתפר.\n"
	.string "אני רוצה להראות לך, {PLAYER}{KUN}.\p"
	.string "אני בסביבת {STR_VAR_2} עכשיו,\n"
	.string "אז בוא{ADD_YUD} נילחם אם את{EMIT_HEY} קרוב.\p"
	.string "מקווה לראות אותך בקרוב!$"

MatchCall_DifferentRouteBattleRequestText10::
	.string "אוי, {PLAYER}{KUN}, שלום…\n"
	.string "זה {STR_VAR_1}.\l"
	.string "אז, מה שלומך?\p"
	.string "הפוקימונים שלי התחזקו הרבה\n"
	.string "מאשר קודם.\p"
	.string "אני אשמח לעוד קרב איתך,\n"
	.string "{PLAYER}{KUN}.\p"
	.string "אני אהיה בסביבת {STR_VAR_2}.\n"
	.string "בוא{ADD_YUD} לראות אותי אם את{EMIT_HEY} קרוב.$"

MatchCall_DifferentRouteBattleRequestText11::
	.string "אה, {PLAYER}{KUN}.\n"
	.string "זה {STR_VAR_1}.\l"
	.string "איפה את{EMIT_HEY} נמצא עכשיו?\p"
	.string "הפוקימונים שלי מלאים בחיים.\n"
	.string "הם נראים כאילו מצפים\l"
	.string "לראות את הפוקימונים שלך, {PLAYER}{KUN}.\p"
	.string "אני בסביבת {STR_VAR_2} עכשיו.\n"
	.string "אני מקווה שתחפש אותנו.$"

MatchCall_DifferentRouteBattleRequestText12::
	.string "שלום, {PLAYER}{KUN}.\n"
	.string "זה אני, {STR_VAR_1}.\p"
	.string "אני צריך לספר לך, הפוקימונים שלי\n"
	.string "גדלו להיות די חסונים לאחרונה.\p"
	.string "אני רוצה לראות אותם בקרב\n"
	.string "איתך, {PLAYER}{KUN}.\p"
	.string "אנחנו נהיה בסביבת {STR_VAR_2}.\n"
	.string "בוא{ADD_YUD} לראות אותנו מתי שתרצה!$"

MatchCall_DifferentRouteBattleRequestText13::
	.string "אה, שלום, {PLAYER}{KUN}!\n"
	.string "זה {STR_VAR_1}!\l"
	.string "האם הפוקימונים שלך שומרים על עצמם?\p"
	.string "הפוקימונים שלי היו כל כך בריאים,\n"
	.string "הם לא נראים מסוגלים להפסיד!\p"
	.string "אני בטח אשמח לעוד\n"
	.string "קרב איתך.\p"
	.string "אם את{EMIT_HEY} ליד {STR_VAR_2},\n"
	.string "בוא{ADD_YUD} לבקר אותנו.$"

MatchCall_DifferentRouteBattleRequestText14::
	.string "אוי, היי, {PLAYER}{KUN}.\n"
	.string "זה {STR_VAR_1}.\l"
	.string "אני מקווה שאת{EMIT_HEY} שומר על עצמך.\p"
	.string "אה, כן! הפוקימונים שלי\n"
	.string "הרבה יותר חזקים מבעבר.\p"
	.string "את{EMIT_HEY} לא חושב שאנחנו צריכים\n"
	.string "להילחם, {PLAYER}{KUN}?\p"
	.string "אנחנו נחכ{EMIT_HEY}{ADD_YUD} לך בסביבת\n"
	.string "{STR_VAR_2}.\p"
	.string "בוא{ADD_YUD} לראות אותנו מתי שתרצה, בסדר?$"

MatchCall_PersonalizedText1::
	.string "זה אני, אוהב ההרים\n"
	.string "{STR_VAR_1}!\p"
	.string "טוב, מאז שנפגשנו, האם גדלת\n"
	.string "להעריך את ההרים יותר?\p"
	.string "אני בקושי רואה אותך בהרים…\p"
	.string "בפעם הבאה, ניפגש איפשהו\n"
	.string "בסביבת {STR_VAR_2}.$"

MatchCall_PersonalizedText2::
	.string "זה {STR_VAR_1}.\n"
	.string "שלום.\p"
	.string "בדיוק סיפרתי למאמן חדש\n"
	.string "עליך.\p"
	.string "סיפרתי לה על מאמן חזק\n"
	.string "שמגדל פוקימונים בזהירות.\p"
	.string "אני מקווה שתהפוך למאמן\n"
	.string "שכולם יעריצו.\p"
	.string "אני מקווה שניפגש שוב!$"

MatchCall_PersonalizedText3::
	.string "שלום! זו {STR_VAR_1}.\p"
	.string "אני אוהב את המקום שבו אני נמצא עכשיו.\n"
	.string "זה נעים עם ניחוחות מתוקים!\p"
	.string "אני חושב שמישהו שתל פירות יער,\n"
	.string "והם פרחו.\p"
	.string "נתראה שוב מתישהו!$"

MatchCall_PersonalizedText4::
	.string "שלום! שלושים שנות חקירה,\n"
	.string "{STR_VAR_1} לשירותך!\p"
	.string "נראה שאת{EMIT_HEY} מטייל באנרגטיות\n"
	.string "הנה והנה.\p"
	.string "האם גילית חורבות חדשות?\n"
	.string "בבקשה ספר אם כן!\p"
	.string "עכשיו, אם תסלח לי,\n"
	.string "יש לי חורבות לחקור.$"

MatchCall_PersonalizedText5::
	.string "זו {STR_VAR_1}!\p"
	.string "יודע מה אני עושה היום?\n"
	.string "צופה בגלים מהחוף!\p"
	.string "אנחה… הגלים כולם מבריקים.\n"
	.string "הים הוא הכי יפה מכאן.\l"
	.string "אני נהיה רעב, אז ביי ביי!$"

MatchCall_PersonalizedText6::
	.string "לועס-מכרסם…\n"
	.string "אה, היי, זה {STR_VAR_1}.\l"
	.string "אני אוהב לאכול על החוף.\p"
	.string "אני והפוקימון שלי עושים\n"
	.string "מצוין. אנחנו מתודלקים לגמרי!\l"
	.string "אני הולך לשחות. ביי!$"

MatchCall_PersonalizedText7::
	.string "שלום, זה {STR_VAR_1}…\p"
	.string "קצת נמאס לי מכל הדבר הזה\n"
	.string "של מאמןמגניב…\p"
	.string "כולם חושבים שאני מאמן\n"
	.string "מושלם, וזה גורם לי לנסות\l"
	.string "לעמוד בציפייה הזו.\p"
	.string "אבל אני מניח שזה בא עם להיות\n"
	.string "מאמןמגניב.\p"
	.string "אני פשוט אצטרך להתאמץ…\n"
	.string "ולחרוק שיניים.\p"
	.string "את{EMIT_HEY} האדם היחיד שיכולתי\n"
	.string "לספר לו סוד כזה.\p"
	.string "אבל כשאראה אותך בפעם הבאה,\n"
	.string "אל תדאג, אני לא אתלונן!$"

MatchCall_PersonalizedText8::
	.string "יהו, זה {STR_VAR_1}!\n"
	.string "מה שלומך?\p"
	.string "אני מאמן את הפוקימונים שלי\n"
	.string "כשאת{EMIT_HEY} המטרה.\p"
	.string "אני לא מתכוון להפסיד כשנ\n"
	.string "ילחם שוב.\p"
	.string "זה לא נהדר שיש חברים\n"
	.string "מאמנים? בוא{ADD_YUD} ניפגש שוב!$"

MatchCall_PersonalizedText9::
	.string "זה {STR_VAR_1}…\n"
	.string "ממש עכשיו, מאחוריך…\l"
	.string "האם לא היה שם משהו…?\p"
	.string "הכוח של הפוקימונים ש\n"
	.string "ישנים כאן בהר המוקד…\p"
	.string "הוא מספר לי עליך…\p"
	.string "את{EMIT_HEY} צריך להתרחק במהירות ו\n"
	.string "אף פעם לא להסתכל אחורה…\p"
	.string "גיגול…\n"
	.string "להתראות…$"

MatchCall_PersonalizedText10::
	.string "זה {STR_VAR_1}.\n"
	.string "מה שלומך?\p"
	.string "זה לא נוח שאנחנו יכולים\n"
	.string "לשוחח ככה מרחוק?\p"
	.string "בעבר, אם רציתי לדבר עם\n"
	.string "מישהו, אבא שלי היה צריך\l"
	.string "להסיע אותי…\p"
	.string "אני צריך ללכת עכשיו.\n"
	.string "אני שמח ששוחחנו.$"

MatchCall_PersonalizedText11::
	.string "זו {STR_VAR_1}!\n"
	.string "תקשיב לזה?\p"
	.string "אני אוהב את אזור הספארי מאוד,\n"
	.string "אבל בכל פעם שאני הולך, אני הולך לאיבוד!\p"
	.string "כל הדשא הגבוה הזה!\n"
	.string "וזה מפוזר מדי!\p"
	.string "אני מרגיש יותר טוב שהורדתי את זה\n"
	.string "מהחזה שלי!\p"
	.string "אני יוצא שוב לאזור הספארי!\n"
	.string "נתפוס אותך!$"

MatchCall_PersonalizedText12::
	.string "שלום, {STR_VAR_1} כאן.\n"
	.string "כן, נכון, אני עשיר, כן.\p"
	.string "אני צריך לספר לך, העושר שלי\n"
	.string "גדל מאז שנפגשנו לאחרונה.\p"
	.string "מה גם, הפוקימונים שלי גם\n"
	.string "התחזקו.\p"
	.string "אני לא יכול לנער את התחושה ש\n"
	.string "העולם הזה קיים בשבילי!\p"
	.string "אוי, אין צורך להגיד מילה!\n"
	.string "כולם יודעים שזה נכון!\p"
	.string "אוי, את{EMIT_HEY} חייב{ADD_TAF} לסלוח לי, יש לי ארוחת\n"
	.string "ערב רשמית להשתתף בה.$"

MatchCall_PersonalizedText13::
	.string "אופופופופו…\n"
	.string "זו אני, {STR_VAR_1}…\p"
	.string "את{EMIT_HEY} יכול לנחש מה אני רואה?\n"
	.string "זוג {STR_VAR_2} בקרב.\p"
	.string "אולי אני אנסה לתפוס את המנצח…\n"
	.string "אופופופופופו…\p"
	.string "אני… אני קצת עסוק עכשיו.\n"
	.string "אני חייב ללכת.$"

MatchCall_PersonalizedText14::
	.string "אוי, זה {STR_VAR_1}!\p"
	.string "בדיוק חשבתי שמשעמם לי עם\n"
	.string "הספינה הנטושה.\p"
	.string "אבל מכיוון שאני כבר כאן,\n"
	.string "ואני רוצה לנצח אותך פעם אחת,\l"
	.string "אני אשאר בסביבה עוד קצת.\p"
	.string "אם את{EMIT_HEY} מרגיש דחף, למה שלא\n"
	.string "תבוא{ADD_YUD} לראות אותי?\p"
	.string "אני חושב שהיום זה היום שבו\n"
	.string "אני סוף סוף אתגר את האיש ליד\l"
	.string "הדלת לקרב.\p"
	.string "להתראות!$"

MatchCall_PersonalizedText15::
	.string "אני {STR_VAR_1}!\n"
	.string "איש הים!\p"
	.string "את{EMIT_HEY} יודע{ADD_TAF} מה אני חושב?\p"
	.string "המאמנים בים הם\n"
	.string "הקשוחים שבקשוחים!\p"
	.string "את{EMIT_HEY} צריך ללמוד ממני ולהתאמן\n"
	.string "בים…\p"
	.string "אופס, גל ענק עולה!\p"
	.string "זו הזדמנות אימון נהדרת!\n"
	.string "מצטער, אבל אני חייב ללכת!$"

MatchCall_PersonalizedText16::
	.string "זה {STR_VAR_1}! תקשיב, אני מלמד\n"
	.string "קראטה את הפוקימונים שלי.\p"
	.string "אבל עכשיו הם טובים ממני!\n"
	.string "לא עשיתי כלום חוץ מלהפסיד להם!\p"
	.string "אבל למרות שאני עשוי להפסיד ל\n"
	.string "פוקימונים, אני לא אפסיד למאמן\l"
	.string "אחר, לא אדוני!\p"
	.string "אנחנו חייבים להילחם שוב!\n"
	.string "אוגוואאה!$"

MatchCall_PersonalizedText17::
	.string "זה אני, {STR_VAR_1}.\n"
	.string "איך הטיולים שלך מתפתחים?\p"
	.string "…וואו, זה נכון?\n"
	.string "נשמע מעורר מאוד!\p"
	.string "אני חושב שאני יכול לכתוב שיר על\n"
	.string "אחד מהפרקים שלך.\p"
	.string "…אוי, היי, אני מרגיש את זה.\n"
	.string "אני שומע את הריפים בראש שלי.\p"
	.string "מוטב שאכתוב את המנגינה הזו כמו שצריך,\n"
	.string "אז אני חייב לעוף! נדבר אחר כך!$"

MatchCall_PersonalizedText18::
	.string "זה {STR_VAR_1}…\n"
	.string "תשמע את השיר החדש שלי.\p"
	.string "ללהלה, {STR_VAR_2}, {STR_VAR_2}!\n"
	.string "למה את{EMIT_HEY} ה{STR_VAR_2} הזה?\l"
	.string "למה אני לא יכול להיות את{EMIT_HEY}, {STR_VAR_2}?\l"
	.string "ללה, {STR_VAR_2} ו{STR_VAR_1},\l"
	.string "{STR_VAR_1} ו{STR_VAR_2}…\p"
	.string "חוזרים על הפזמון, דועך…$"

MatchCall_PersonalizedText19::
	.string "אני {STR_VAR_1}, את{EMIT_HEY} יודע{ADD_TAF},\n"
	.string "מומחה הקמפינג!\p"
	.string "כאשר נלחמנו, לא יכולתי שלא\n"
	.string "להפסיד לך.\p"
	.string "בסופו של דבר, המומחיות שלי היא ב\n"
	.string "קמפינג.\p"
	.string "אבל ניצחון או הפסד, אני אוהב להילחם\n"
	.string "כשאני בקמפינג.\p"
	.string "תילחם איתנו שוב, בסדר?\n"
	.string "אה, ובוא{ADD_YUD} נלך לקמפינג, גם!$"

MatchCall_PersonalizedText20::
	.string "זה אני, אני, {STR_VAR_1}!\p"
	.string "האמת היא שהייתי רוצה לטפס על\n"
	.string "הרים אחרים חוץ מזה.\p"
	.string "אבל אני לא בטוח אם יהיו\n"
	.string "גברות כמו האלה בהר הארובה.\p"
	.string "אם את{EMIT_HEY} יודע{ADD_TAF} על הר אחר\n"
	.string "שיש בו גברות בסביבה, תגיד לי!\p"
	.string "אחחחח, נתראה בסביבה!$"

MatchCall_PersonalizedText21::
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "זה {STR_VAR_1}…\p"
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "זה הכל להיום…$"

MatchCall_PersonalizedText22::
	.string "זה {STR_VAR_1}. היום, הייתה לי\n"
	.string "התחושה הזו שאני אשוחח איתך.\p"
	.string "הרצון שלי להביס אותך נבנה\n"
	.string "יום ולילה.\p"
	.string "יש לך יריב כזה, נכון?\n"
	.string "הלוואי שזה היה אני…\p"
	.string "אני שמח שהקשבת לי.\n"
	.string "נתראה!$"

MatchCall_PersonalizedText23::
	.string "זה {STR_VAR_1}.\p"
	.string "כשיש מאמן חזק\n"
	.string "בסביבה, אני יכול לפעמים לחוש בזה\l"
	.string "איכשהו.\p"
	.string "האם עברת קרוב, {PLAYER}{KUN}?\n"
	.string "אולי זה היית את{EMIT_HEY}.\p"
	.string "אני אחכ{EMIT_HEY}{ADD_YUD} לביקור שלך.\n"
	.string "ביי!$"

MatchCall_PersonalizedText24::
	.string "שלום, זה {STR_VAR_1}.\n"
	.string "את{EMIT_HEY} נשמע טוב, {PLAYER}{KUN}.\p"
	.string "טיילתי ברחבי העולם,\n"
	.string "אבל אני חייב לומר שמאוד\l"
	.string "אהבתי את האזור הזה.\p"
	.string "אני מתכנן להישאר כאן לזמן מה.\n"
	.string "אולי נוכל להיפגש שוב?\p"
	.string "לא שכחתי את הטכניקות\n"
	.string "המדהימות שלך.\p"
	.string "אני אכן מקווה לקרב חוזר.$"

MatchCall_PersonalizedText25::
	.string "יבבה… זה… {STR_VAR_1}…\n"
	.string "…בכי…\p"
	.string "רוקסן נזפה בי בשיעור\n"
	.string "היום.\p"
	.string "אבל אני לא לא אוהב אותה או משהו.\p"
	.string "רוקסן אומרת לי בדיוק מה\n"
	.string "עשיתי לא בסדר כדי שאוכל ללמוד מזה.\p"
	.string "את{EMIT_HEY} יכול להיות בטוח שאני אלך\n"
	.string "לבית הספר למאמנים מחר!\p"
	.string "נתראה מאוחר יותר!$"

MatchCall_PersonalizedText26::
	.string "זו {STR_VAR_1}!\p"
	.string "רוקסן נתנה לי להילחם איתה\n"
	.string "אתמול.\p"
	.string "התוצאות…\n"
	.string "נוראיות, כאילו היית צריך לשאול.\p"
	.string "אבל הייתי מאושר שרוקסן\n"
	.string "בכלל נתנה לי לאתגר אותה!\p"
	.string "את{EMIT_HEY} לא תאמין כמה\n"
	.string "יותר אני מעריץ אותה!\p"
	.string "אני הולך ממש להתמקד ולעבוד!\n"
	.string "מוטב שאלך!$"

MatchCall_PersonalizedText27::
	.string "היי, זו אנה! אני עם השותף\n"
	.string "הזוטר שלי מג שוב היום.\p"
	.string "אני ממש אוהבת לדאוג למג\n"
	.string "ולפוקימונים. הם כל כך חמודים!\p"
	.string "אני רוצה שאוכל לטפל בהם\n"
	.string "כאילו היו אחים שלי!\p"
	.string "אוי, היי, מג!\n"
	.string "הבאת את הלחמניות?\p"
	.string "הא? לא, לא, אני לא מתייחסת אליך\n"
	.string "כמו לעבד אישי שלי!\p"
	.string "הפסדת בקרב, אז את{EMIT_HEY} צריך\n"
	.string "ללכת לקנות את הלחם כעונש!\p"
	.string "לא הייתי מתייחסת אליך כמו לעבד,\n"
	.string "מג! את{EMIT_HEY} יותר מדי מיוחד בשבילי!\p"
	.string "אני חייבת ללכת עכשיו.\n"
	.string "זה הזמן לחטיף שלנו!$"

MatchCall_PersonalizedText28::
	.string "אני אוהב פוקימונים!\n"
	.string "זה {STR_VAR_1} ממועדון המעריצים!\p"
	.string "את{EMIT_HEY} חייב{ADD_TAF} לשמוע את זה!\n"
	.string "הפוקימון המתוק שלי…\p"
	.string "נחירה! וואהאהא!\n"
	.string "אני לא יכול להגיד יותר! זה סוד!\l"
	.string "זה פשוט חמוד מכדי לבטא במילים!\p"
	.string "אוי, ה{STR_VAR_2} המתוק שלי מתחנן\n"
	.string "לפוקיגוש!\p"
	.string "זו תמונה של חמידות!\p"
	.string "מצטער, אבל אני לא יכול לדבר עכשיו!\n"
	.string "תצטרך לשמוע את זה בפעם הבאה!$"

MatchCall_PersonalizedText29::
	.string "אוהוהו!\p"
	.string "זו {STR_VAR_1}! אני לא יכולה לחכות\n"
	.string "לספר לך על הפוקימון המתוק שלי!\p"
	.string "בבקשה, את{EMIT_HEY} חייב{ADD_TAF} להקשיב לזה.\n"
	.string "זה על ה{STR_VAR_2} המתוק שלי.\p"
	.string "בכל פעם שמישהו מרים אותו,\n"
	.string "הוא קופץ ישר לזרועותיי!\p"
	.string "אוי… אוי… האם יכול להיות משהו\n"
	.string "יותר מאושר מזה?\p"
	.string "אוי, זה מרגיש כל כך שמימי!\p"
	.string "אני כל כך שמחה שיכולתי לחלוק קצת\n"
	.string "מהאושר שלי איתך.\p"
	.string "טוב, אני חייבת ללכת.\n"
	.string "ביי, עכשיו!$"

MatchCall_PersonalizedText30::
	.string "אני… {STR_VAR_1}.\n"
	.string "אנשים קוראים לי מומחה.\p"
	.string "אבל יש דבר אחד שאני יודע.\n"
	.string "לא יכולתי להיות מומחה בכוחות\l"
	.string "עצמי.\p"
	.string "רק בעזרת פוקימונים יכול\n"
	.string "מאמן להפוך למומחה.\p"
	.string "המפ! אני מאמין שאולי אמרתי\n"
	.string "משהו עמוק ומשמעותי!\p"
	.string "אני אעזוב אותך במצב רוח טוב!$"

MatchCall_PersonalizedText31::
	.string "זו {STR_VAR_1}.\n"
	.string "אני שמח לשוחח איתך!\p"
	.string "אני מרגיש חי ורענן\n"
	.string "שוקע באמבטיית המעיין החם הזו.\p"
	.string "נלחמתי במאמנים צעירים\n"
	.string "מאז שנפגשנו, אבל את{EMIT_HEY} עדיין\l"
	.string "הטוב ביותר מכולם.\p"
	.string "אני משער שתהפוך למומחה\n"
	.string "בזקנתך! אוהוהוהו…$"

MatchCall_PersonalizedText32::
	.string "יאיי! זה {STR_VAR_1}!\n"
	.string "מה חדש?\p"
	.string "אני יכול לדמיין את זה, אבל כשאני\n"
	.string "מנצח קרבות, נראה שהמכנסיים הקצרים שלי\l"
	.string "מרגישים, כאילו, יותר טוב. חומרית.\p"
	.string "מה אני מתכוון בזה?\n"
	.string "זה קצת קשה להסביר, אבל…\l"
	.string "איך אני אגיד את זה עכשיו…\l"
	.string "המכנסיים הקצרים שלי מרגישים משייים יותר!\p"
	.string "וכשנלחמתי בך, {PLAYER}{KUN},\n"
	.string "המכנסיים הקצרים שלי הרגישו דביקים ומחוספסים.\p"
	.string "… … … … … …\n"
	.string "לא באמת האמנת לזה?\l"
	.string "אחחחח, זה הכל! ביי עכשיו!$"

MatchCall_PersonalizedText33::
	.string "אהוי!\n"
	.string "{STR_VAR_1} כאן!\p"
	.string "כרגיל, אני דג בפראות\n"
	.string "חסרת מעצורים!\p"
	.string "האם יש מקומות אחרים שבהם אני יכול לדוג\n"
	.string "חוץ מהים והנהרות?\p"
	.string "יש לי דחפים חזקים\n"
	.string "לדוג כמעט בכל מקום!\p"
	.string "אוי, אלוהים, ארור זה!\n"
	.string "החוט שלי הסתבך!\p"
	.string "חייב ללכת!\n"
	.string "תמצא לי מקומות דיג חדשים!$"

MatchCall_PersonalizedText34::
	.string "היי, מה קורה! זה {STR_VAR_1}.\n"
	.string "את{EMIT_HEY} לוקח את זה בקלות?\p"
	.string "מאז שהייתי ילד, את{EMIT_HEY} יודע{ADD_TAF},\n"
	.string "תמיד הייתי רגוע, הא?\p"
	.string "אף פעם לא הייתי מישהו שמתעצבן\n"
	.string "או ממהר דברים.\p"
	.string "אבל לא תאמין,\n"
	.string "עכשיו אני טריאתלט.\p"
	.string "את{EMIT_HEY} פשוט לא יכול לדעת לאן החיים\n"
	.string "ייקחו אותך, אם את{EMIT_HEY} מבין למה אני מתכוון.\p"
	.string "את{EMIT_HEY} מאמן עכשיו, אבל מי\n"
	.string "יודע מה העתיד טומן בחובו, הא?\p"
	.string "תאר לעצמך כמורה,\n"
	.string "או אולי אמן. מגניב, הא?\p"
	.string "אבל, היי, תהיה רגוע. קח את זה בקלות.\n"
	.string "נתראה בסביבה.$"

MatchCall_PersonalizedText35::
	.string "זה {STR_VAR_1}!\n"
	.string "אני רוכב על אופניים עכשיו.\p"
	.string "אני אוהב לשחות ולרוץ,\n"
	.string "אבל רכיבה על אופניים היא אהבתי הראשונה!\p"
	.string "זה גורם לכל הגוף שלי להרגיש\n"
	.string "כאילו אני אחד עם הרוח.\p"
	.string "זה מרומם אותי כאילו אני\n"
	.string "עף!\p"
	.string "אוקיי! היום, אני הולך לקבוע שיא חדש\n"
	.string "בדרך האופניים!\p"
	.string "את{EMIT_HEY} צריך לקבל את האתגר, גם!\n"
	.string "נתראה!$"

MatchCall_PersonalizedText36::
	.string "יו, זה {STR_VAR_1}! אני ממש\n"
	.string "במהלך טריאתלון!\p"
	.string "אבל, היי, תמיד יש לי זמן\n"
	.string "לפטפט!\p"
	.string "להתאמן עם פוקימונים מרגיש\n"
	.string "ממש טוב!\p"
	.string "מבלי להחליף מילים, אנחנו מסנכרנים\n"
	.string "כאילו חלקנו לב אחד.\p"
	.string "זה מעורר השראה!\p"
	.string "נשימה… לשוחח בזמן ריצה…\n"
	.string "אני מתעייף…\l"
	.string "נשימה… חייב… ללכת…$"

MatchCall_PersonalizedText37::
	.string "היי, זה {STR_VAR_1}.\n"
	.string "אם את{EMIT_HEY} רוצה לשפר סיבולת,\l"
	.string "אימון בגובה רב זה הדבר!\p"
	.string "תנס{EMIT_HEY}{ADD_YUD} לרוץ על פסגת הר.\n"
	.string "את{EMIT_HEY} תתנשף תוך זמן קצר!\p"
	.string "גם אני מתחיל להיות חסר חמצן, גם!\n"
	.string "נתראה!$"

MatchCall_PersonalizedText38::
	.string "אוי, זה {STR_VAR_1}, שלום.\p"
	.string "שחיתי הרבה אבל אני עדיין\n"
	.string "לא מצליח להגיע לאבר גרנדה.\p"
	.string "אולי אני פשוט מסתובב במעגלים.\p"
	.string "לא, לא, זה לא יכול להיות אפשרי.\n"
	.string "וואהאהאהא.\l"
	.string "שמ{EMIT_VAV}ר{ADD_YUD} על עצמך!$"

MatchCall_PersonalizedText39::
	.string "היי, זה {STR_VAR_1}…\n"
	.string "אופס!\p"
	.string "התזה!\p"
	.string "בלופ-בלופ-בלופ-בלופ…\p"
	.string "שפריץ!\p"
	.string "שאיפה-שאיפה! שאיפה-שאיפה!\p"
	.string "היי! סליחה על זה!\n"
	.string "בדיוק שמתי שמן שיזוף.\p"
	.string "אז הפוקינווט שלי החליק\n"
	.string "לי מהיד ונפל למים!\p"
	.string "אבל, היי, הפוקינווט של דבון בנוי\n"
	.string "קשוח. הוא שרד את הטבילה הזו!\p"
	.string "בכל מקרה, אני עסוק בשיזוף,\n"
	.string "אז בוא{ADD_YUD} נשוחח בפעם אחרת.$"

MatchCall_PersonalizedText40::
	.string "שלום, זה {STR_VAR_1}.\p"
	.string "מתוך שלושת אירועי הטריאתלון,\n"
	.string "אני הכי אוהב שחייה.\p"
	.string "אבל אם אני אשאר בים יותר מדי זמן,\n"
	.string "אני לא אהפוך למקומט כולו?\p"
	.string "אוי, טריאתלון זה מבחן מפרך\n"
	.string "של סיבולת אנושית! ביי!$"

MatchCall_PersonalizedText41::
	.string "שלום, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} כאן.\p"
	.string "מה שלום הפוקימונים שלך?\p"
	.string "פוקימוני הדרקון שלי נראים\n"
	.string "בכושר שיא. ביי לעת עתה.$"

MatchCall_PersonalizedText42::
	.string "{STR_VAR_1} כאן.\p"
	.string "ה{STR_VAR_2} שלי גדל להיות אפילו יותר\n"
	.string "קשוח מאשר בפעם האחרונה.\p"
	.string "אני לא הולך להפסיד לך שוב.\n"
	.string "חכ{EMIT_HEY}{ADD_YUD} עד הפעם הבאה!\p"
	.string "נתראה בסביבה!$"

MatchCall_PersonalizedText43::
	.string "זה {STR_VAR_1} כאן.\p"
	.string "המשכתי בלימודים שלי\n"
	.string "באומנות ההסתרה.\p"
	.string "אבל הצלחתי יותר מדי.\n"
	.string "אף אחד לא הצליח למצוא אותי.\l"
	.string "ההצלחה שלי גורמת לי להיות בודד…\p"
	.string "כמו עשן אני נעלם!\n"
	.string "להתראות!$"

MatchCall_PersonalizedText44::
	.string "זה {STR_VAR_1}.\n"
	.string "המשכתי באימונים שלי מאז שנפגשנו.\p"
	.string "ה{STR_VAR_2} שלי נהיה די\n"
	.string "קשוח.\p"
	.string "אימונים על החוף יעילים,\n"
	.string "בדיוק כפי שחשבתי. ביי עכשיו!$"

MatchCall_PersonalizedText45::
	.string "מה שלומך?\n"
	.string "זה {STR_VAR_1}.\p"
	.string "אני תוהה מתי האפר הוולקני\n"
	.string "המגעיל הזה יפסיק לרדת?\p"
	.string "אם הוא יהיה עמוק מדי, הוא יכסה\n"
	.string "את הדוגמה על השמשייה שלי…\p"
	.string "בוא{ADD_YUD} נבטיח שניפגש שוב!$"

MatchCall_PersonalizedText46::
	.string "היי, {STR_VAR_1} כאן.\p"
	.string "ידעת שיותר קל לצוף\n"
	.string "בים מאשר בבריכה?\p"
	.string "רק על ידי שכיבה בשקט, הגוף שלך\n"
	.string "יצוף לבד.\p"
	.string "אבל אם את{EMIT_HEY} צף יותר מדי זמן,\n"
	.string "שים לב שלא תיסחף\l"
	.string "רחוק מדי החוצה.\p"
	.string "…איפה אני, בכלל?\n"
	.string "מוטב שאלך!$"

MatchCall_PersonalizedText47::
	.string "אוי, {PLAYER}{KUN}, שלום!\n"
	.string "זו {STR_VAR_1}.\l"
	.string "אני למעלה בהרים עכשיו.\p"
	.string "אבל הקרקע יותר מדי משובשת.\n"
	.string "אני לא יכול להקים כאן את האוהל שלי…\p"
	.string "אוי, היה לי רעיון מבריק!\p"
	.string "אולי אני יכול לבקש מהפוקימונים שלי\n"
	.string "לדחוס את הקרקע פה!\p"
	.string "אני הולך לנסות את זה!\n"
	.string "ביי ביי!$"

MatchCall_PersonalizedText48::
	.string "אוי, היי, היי, זו {STR_VAR_1}!\p"
	.string "אני מגדל פוקימונים עם ליב!\n"
	.string "אנחנו מנסים מאוד קשה!\p"
	.string "אם ננסה יותר, נוכל להפוך\n"
	.string "למספר אחת? ביי ביי!$"

MatchCall_PersonalizedText49::
	.string "{STR_VAR_1} כאן!\p"
	.string "אני מלח, אבל אני לא על סירה\n"
	.string "עכשיו.\p"
	.string "זה גורם לי לתהות: איך צריך\n"
	.string "לקרוא למלח ביבשה?\p"
	.string "זה מה שחשבתי\n"
	.string "תוך כדי בהייה בגלים.\p"
	.string "טוב, בפעם הבאה!$"

MatchCall_PersonalizedText50::
	.string "זה {STR_VAR_1}.\n"
	.string "נו? השגת עוד פוקימונים?\p"
	.string "אם תתפוס פוקימון חדש,\n"
	.string "את{EMIT_HEY} חייב{ADD_TAF} לבוא להראות לי.\p"
	.string "אני לא אתלונן בשבילו, בכנות.\n"
	.string "אני אחכ{EMIT_HEY}{ADD_YUD}. נתראה.$"

MatchCall_PersonalizedText51::
	.string "זה {STR_VAR_1}.\p"
	.string "האם את{EMIT_HEY} מגדל את הפוקימונים שלך\n"
	.string "בצורה האופטימלית?\p"
	.string "האוויר נקי במקום שבו אני נמצא.\n"
	.string "זו הסביבה המושלמת ל\l"
	.string "גידול פוקימונים.\p"
	.string "אם את{EMIT_HEY} הולך להתמקד בגידול\n"
	.string "פוקימונים, את{EMIT_HEY} צריך לצאת ל\l"
	.string "{STR_VAR_2}. שמ{EMIT_VAV}ר{ADD_YUD} על עצמך עכשיו.$"

MatchCall_PersonalizedText52::
	.string "היי, זה {STR_VAR_1}.\p"
	.string "נתתי פוקיגוש ל{STR_VAR_2} שלי.\n"
	.string "נראה שהוא נהנה מזה מאוד.\p"
	.string "נראה שלפוקימונים יש\n"
	.string "מה שהם אוהבים ומה שהם לא אוהבים בפוקיגושS.\p"
	.string "אני מוצא את זה די מרתק.\n"
	.string "אנא שמ{EMIT_VAV}ר{ADD_YUD} על עצמך.$"

MatchCall_PersonalizedText53::
	.string "{STR_VAR_1} כאן.\p"
	.string "אם את{EMIT_HEY} משתף פעולה עם פוקימונים,\n"
	.string "אפשר להיות בנוח בטבע.\p"
	.string "כולם צריכים להבין את זה ו\n"
	.string "לשתף פעולה עם פוקימונים יותר.\p"
	.string "זה יהיה אידיאלי.\n"
	.string "אני באמת חושב כך.\p"
	.string "אני חושב שאת{EMIT_HEY} בדרך הנכונה!\n"
	.string "נתפוס אותך מאוחר יותר!$"

MatchCall_PersonalizedText54::
	.string "היי, זה {STR_VAR_1}. את{EMIT_HEY} יודע{ADD_TAF},\n"
	.string "המאמן שתמיד מוכן!\p"
	.string "{PLAYER}{KUN}, האם יש לך מספיק פריטים?\n"
	.string "האם הפוקימונים שלך מוכנים לפעולה?\p"
	.string "לשמ{EMIT_VAV}ר{ADD_YUD} על הכל מושלם סביבך\n"
	.string "כל הזמן זו הסוד לשמירה על\l"
	.string "המסע שלך מתמשך.\p"
	.string "מוטב שאלך לבדוק את הציוד שלי!\n"
	.string "היה ערני!$"

MatchCall_PersonalizedText55::
	.string "זה {STR_VAR_1}!\n"
	.string "זה {STR_VAR_1}!\p"
	.string "{STR_VAR_2} הוא כביש ראשי\n"
	.string "מאוד עמוס, אז אני מקבל אתגרים\l"
	.string "מכל מיני מאמנים כל יום.\p"
	.string "היום, ניצחתי בחמישה קרבות והפסדתי\n"
	.string "רק בשלושה!\p"
	.string "איך עבר עליך היום?\n"
	.string "ספר לי על זה בפעם הבאה, בסדר?$"

MatchCall_PersonalizedText56::
	.string "זה אני, {STR_VAR_1}.\p"
	.string "אני פופולרי כי יש לי הרבה\n"
	.string "פוקימוני חרקים, נכון?\p"
	.string "טוב, לקחתי חבורה של החרקים\n"
	.string "האהובים עליי לבית הספר היום.\p"
	.string "הבחורה שאני מחבב התחילה לבכות!\n"
	.string "קדימה, תצחק אם את{EMIT_HEY} רוצה.\p"
	.string "אני חייב לנסות ללמד אותה מה\n"
	.string "הופך את פוקימוני החרק לכל כך מושכים.\p"
	.string "יבבה…\n"
	.string "נתראה!$"

MatchCall_PersonalizedText57::
	.string "הא! הא! הא! הא!\p"
	.string "היי! זה {STR_VAR_1}! הא! הא!\p"
	.string "לנסות לשוחח…\n"
	.string "בזמן טיפוס…\l"
	.string "זה תרגיל קשה… הא! הא!\p"
	.string "אורג! אוף…\n"
	.string "זה תלול יותר עכשיו…\l"
	.string "נשוחח… בפעם אחרת…\l"
	.string "הא! הא! הא!$"

MatchCall_PersonalizedText58::
	.string "אוי, היי!\p"
	.string "אני עדיין מחפש אוצרות\n"
	.string "עם קירה!\p"
	.string "אולי אין כאן בכלל\n"
	.string "שום אוצר…\p"
	.string "אבל הדבר החשוב הוא שאני\n"
	.string "אחפש לצד קירה.\p"
	.string "אוי, היי, קירה!\n"
	.string "למ… למה את כועסת?\p"
	.string "אני לא מתעלם ממך, מותק!\n"
	.string "את האחת והיחידה שלי!\p"
	.string "…{PLAYER}, אני חייב ללכת, ביי!$"

MatchCall_PersonalizedText59::
	.string "זה {STR_VAR_1}!\p"
	.string "הלכתי שוב למכון של דופורד\n"
	.string "בשביל אימונים.\p"
	.string "בראולי, מנהיג המכון, נראה\n"
	.string "יותר קשוח עכשיו.\p"
	.string "משהו על כך שהתחשל\n"
	.string "על ידי הגלים הפראיים…\p"
	.string "אבל הוא עדיין קול כתמיד.\n"
	.string "הגברות מעריצות אותו!\l"
	.string "זה גורם לי לקנא, בכנות.\p"
	.string "אני תוהה… האם חבר שלו ברונו\n"
	.string "הוא באותו סגנון כמו בראולי?\p"
	.string "את{EMIT_HEY} יודע{ADD_TAF}, מזיע או מסריח כולו,\n"
	.string "ונוטה לקרוא לאנשים\l"
	.string "”גל גדול“, דברים כאלה.\p"
	.string "אבל, היי, עניין הקנאה הזה לא\n"
	.string "מכובד במיוחד, נכון?\p"
	.string "תשכח{ADD_YUD} שהשיחה הזו אי פעם התרחשה,\n"
	.string "מה דעתך? להתראות!$"

MatchCall_PersonalizedText60::
	.string "זה תענוג לשוחח עם\n"
	.string "מאמן צעיר כמוך.\p"
	.string "אני משער שתמשיך ל\n"
	.string "ליהנות מפוקימונים בכל גיל.\p"
	.string "האם זה לא יהיה טוב אם תהיה לך\n"
	.string "שותפות כמו שלנו?\p"
	.string "כמובן, {PLAYER}{KUN}, את{EMIT_HEY} כבר\n"
	.string "נהנה מהאמון והחברות\l"
	.string "של הפוקימונים שלך עכשיו.\p"
	.string "יש לך את הכלים למערכות יחסים\n"
	.string "ארוכות ומתמשכות כבר עכשיו!\p"
	.string "הא! הא! הא!\n"
	.string "אל תתייאש לעולם!$"

MatchCall_PersonalizedText61::
	.string "היי, זו {STR_VAR_1}!\n"
	.string "בדיוק ניצחנו בקרב!\p"
	.string "אנחנו לא מנצחים לעיתים קרובות, אבל זה היה\n"
	.string "בחור שחיין קול.\p"
	.string "אחותי רתחה!\p"
	.string "היא רצתה להעמיד פנים שהיא\n"
	.string "חלשה כדי לעשות רושם!\p"
	.string "היא תמיד נוזפת בי בין\n"
	.string "שננצח ובין שנפסיד!\p"
	.string "{PLAYER}{KUN}, את{EMIT_HEY} יכול להגיד לה משהו\n"
	.string "בפעם הבאה?\p"
	.string "אוקיי, נתראה!$"

MatchCall_PersonalizedText62::
	.string "{STR_VAR_1} כאן, כן.\n"
	.string "יצאתי לים אתמול.\p"
	.string "קיוויתי למצוא חורבה\n"
	.string "חדשה לחקור.\p"
	.string "אבל הגאות משום מה נראת{EMIT_HEY}\n"
	.string "כאילו היא מחזירה אותי למקום שהתחלתי.\p"
	.string "אני עדיין חלש בקרבות, גם…\n"
	.string "תרגיש חופשי ללעוג לי…\l"
	.string "אבל אני לא אוותר.\p"
	.string "יומי יגיע כשאגלה\n"
	.string "חורבה חדשה!\p"
	.string "זה כל מה שיש לי לומר!\n"
	.string "להתראות לעת עתה!$"

MatchCall_PersonalizedText63::
	.string "אהוי שם!\n"
	.string "זה אני, {STR_VAR_1}!\l"
	.string "אני בדרך 801 עכשיו!\l"
	.string "במילים אחרות, איפה שאני תמיד נמצא!\p"
	.string "היום, שחיינית יפהפייה\n"
	.string "שחתה לידי!\p"
	.string "אז הבהלתי אותה בצעקה!\p"
	.string "והיא נתנה לי מבט מרושע!\p"
	.string "זה הכל מדרך 801!\n"
	.string "הובא אליך על ידי {STR_VAR_1}!$"

MatchCall_PersonalizedText64::
	.string "זה {STR_VAR_1}!\p"
	.string "אני קצת עסוק, אבל חשבתי\n"
	.string "שכדאי שאעדכן אותך שניצחתי\l"
	.string "חמישה מאמנים שוב היום.\p"
	.string "אם אני אמשיך בקצב הזה, אני כנראה\n"
	.string "אוכל לנצח אותך בפעם הבאה.\p"
	.string "אני חושב שנהיה יריבים טובים,\n"
	.string "את{EMIT_HEY} ואני. להתראות לעת עתה!$"

MatchCall_BattleFrontierStreakText1::
	.string "היי! זו {STR_VAR_1}.\n"
	.string "שמעתי את החדשות!\p"
	.string "אומרים שהצטיינת ב\n"
	.string "ה{STR_VAR_2}.\p"
	.string "זה מדהים, {STR_VAR_3} ניצחונות רצופים?\n"
	.string "נתראה!$"

MatchCall_BattleFrontierStreakText2::
	.string "שלום, זו {STR_VAR_1}!\n"
	.string "שמעתי עליך!\p"
	.string "הם אמרו שניצחת {STR_VAR_3} קרבות\n"
	.string "רצופים ב{STR_VAR_2}.\p"
	.string "זה מיוחד! אני צריך לנסות\n"
	.string "יותר קשה, גם! נתראה!$"

MatchCall_BattleFrontierStreakText3::
	.string "היי {PLAYER}!\n"
	.string "זה אני, {STR_VAR_1}.\p"
	.string "שמעתי שעשית מהפך ב\n"
	.string "ה{STR_VAR_2}!\p"
	.string "רצף של {STR_VAR_3} ניצחונות גדול…\n"
	.string "זה שיא גדול, לא?\p"
	.string "מוטב שאתארגן על עצמי, גם!\n"
	.string "נתפוס אותך בקרוב!$"

MatchCall_BattleFrontierStreakText4::
	.string "היי, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} כאן. מה קורה?\p"
	.string "יש שמועה שמסתובבת ש\n"
	.string "שרשרת {STR_VAR_3} ניצחונות רצופים\l"
	.string "ב{STR_VAR_2}.\p"
	.string "מוטב שאעלה רמה, גם.\n"
	.string "נתראה!$"

MatchCall_BattleFrontierStreakText5::
	.string "היי, {PLAYER}{KUN}!\n"
	.string "זו {STR_VAR_1}.\p"
	.string "היית ב{STR_VAR_2}\n"
	.string "וניצחת {STR_VAR_3} קרבות ברצף?\l"
	.string "זה משהו!\p"
	.string "מוטב שאעבוד על הפוקימונים שלי יותר.\n"
	.string "נתראה בקרוב!$"

MatchCall_BattleFrontierStreakText6::
	.string "היי, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} כאן. מה שלומך?\p"
	.string "דרך אגב, שמעתי שביצעת\n"
	.string "את ההישג של {STR_VAR_3} ניצחונות רצופים\l"
	.string "ב{STR_VAR_2}.\p"
	.string "זה מעורר בי השראה להתמקד ב\n"
	.string "אימון הצוות שלי.$"

MatchCall_BattleFrontierStreakText7::
	.string "…אה, {PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} כאן…\p"
	.string "אה, כן, היית ב\n"
	.string "ה{STR_VAR_2}, נכון?\p"
	.string "וניצחת {STR_VAR_3} קרבות ברצף.\p"
	.string "אוי, הנה פוקימון נדיר!\n"
	.string "אני חייב ללכת!$"

MatchCall_BattleFrontierStreakText8::
	.string "אוי, {PLAYER}{KUN}, מה שלומך?\n"
	.string "זו {STR_VAR_1} מדברת.\l"
	.string "אני מקווה שאת{EMIT_HEY} עושה חיל.\p"
	.string "אוי, אבל, את{EMIT_HEY} כן. שמעתי ש\n"
	.string "ניצחת {STR_VAR_3} קרבות ברצף ב\l"
	.string "ה{STR_VAR_2}.\p"
	.string "זה מאוד מרשים!\n"
	.string "אני מקווה שתמשיך להצליח.$"

MatchCall_BattleFrontierStreakText9::
	.string "אוי, {PLAYER}{KUN}, היי!\n"
	.string "זה {STR_VAR_1}!\p"
	.string "שמעתי! רצף {STR_VAR_3} הניצחונות שלך\n"
	.string "ב{STR_VAR_2}!\p"
	.string "זה כל כך קול!\n"
	.string "מוטב שגם אני אנסה יותר חזק!$"

MatchCall_BattleFrontierStreakText10::
	.string "אוי, {PLAYER}{KUN}, שלום…\n"
	.string "זה {STR_VAR_1}.\p"
	.string "ניצחת {STR_VAR_3} קרבות רצופים\n"
	.string "ב{STR_VAR_2}?\p"
	.string "זה הישג לא מבוטל.\n"
	.string "אני צריך לעבוד קשה יותר.$"

MatchCall_BattleFrontierStreakText11::
	.string "אה, {PLAYER}{KUN}.\n"
	.string "זה {STR_VAR_1}.\p"
	.string "אני שומע שאת{EMIT_HEY} האימה של\n"
	.string "ה{STR_VAR_2}?\p"
	.string "ניצחת, כמה, {STR_VAR_3} קרבות\n"
	.string "ברצף?\p"
	.string "את{EMIT_HEY} טוב, את{EMIT_HEY}.\n"
	.string "אני תוהה בכמה אני יכול לנצח?$"

MatchCall_BattleFrontierStreakText12::
	.string "שלום, {PLAYER}{KUN}.\n"
	.string "זה אני, {STR_VAR_1}.\l"
	.string "את{EMIT_HEY} שומר על עצמך?\p"
	.string "מישהו העביר לי מילה עליך.\n"
	.string "איך ניצחת {STR_VAR_3} קרבות רצופים\l"
	.string "במקום בשם {STR_VAR_2}?\p"
	.string "זה סיפור לא מבוטל.\n"
	.string "נתראה!$"

MatchCall_BattleFrontierStreakText13::
	.string "אה, שלום, {PLAYER}{KUN}!\n"
	.string "זה {STR_VAR_1}.\l"
	.string "אני מקווה שאת{EMIT_HEY} שומר על עצמך.\p"
	.string "הם אומרים שניצחת {STR_VAR_3} קרבות רצופים\n"
	.string "ב{STR_VAR_2}.\p"
	.string "אני מעריץ את האנרגיה שלך!\n"
	.string "ביי עכשיו.$"

MatchCall_BattleFrontierStreakText14::
	.string "אוי, היי, {PLAYER}{KUN}.\n"
	.string "זה {STR_VAR_1}.\p"
	.string "שמעתי עליך!\n"
	.string "לא ניצחת {STR_VAR_3} קרבות ברצף\l"
	.string "ב{STR_VAR_2}?\p"
	.string "את{EMIT_HEY} השראה!\n"
	.string "ביי ביי!$"

MatchCall_BattleFrontierRecordStreakText1::
	.string "היי! זו {STR_VAR_1}.\n"
	.string "שמעתי את החדשות!\p"
	.string "אומרים שהצטיינת ב\n"
	.string "ה{STR_VAR_2}.\p"
	.string "זה מדהים, {STR_VAR_3} ניצחונות רצופים?\n"
	.string "נתראה!$"

MatchCall_BattleFrontierRecordStreakText2::
	.string "שלום, זו {STR_VAR_1}!\n"
	.string "שמעתי עליך!\p"
	.string "הם אמרו שניצחת {STR_VAR_3} קרבות\n"
	.string "רצופים ב{STR_VAR_2}.\p"
	.string "זה מיוחד! אני צריך לנסות\n"
	.string "יותר קשה, גם! נתראה!$"

MatchCall_BattleFrontierRecordStreakText3::
	.string "היי {PLAYER}!\n"
	.string "זה אני, {STR_VAR_1}.\p"
	.string "שמעתי שעשית מהפך ב\n"
	.string "ה{STR_VAR_2}!\p"
	.string "רצף של {STR_VAR_3} ניצחונות גדול…\n"
	.string "זה שיא גדול, לא?\p"
	.string "מוטב שאתארגן על עצמי, גם!\n"
	.string "נתפוס אותך בקרוב!$"

MatchCall_BattleFrontierRecordStreakText4::
	.string "היי, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} כאן. מה קורה?\p"
	.string "יש שמועה שמסתובבת ש\n"
	.string "שרשרת {STR_VAR_3} ניצחונות רצופים\l"
	.string "ב{STR_VAR_2}.\p"
	.string "מוטב שאעלה רמה, גם.\n"
	.string "נתראה!$"

MatchCall_BattleFrontierRecordStreakText5::
	.string "היי, {PLAYER}{KUN}!\n"
	.string "זו {STR_VAR_1}.\p"
	.string "היית ב{STR_VAR_2}\n"
	.string "וניצחת {STR_VAR_3} קרבות ברצף?\l"
	.string "זה משהו!\p"
	.string "אני? הייתי אומר שאני מתקדם.\n"
	.string "נתראה בקרוב!$"

MatchCall_BattleFrontierRecordStreakText6::
	.string "היי, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} כאן. מה שלומך?\p"
	.string "דרך אגב, שמעתי שביצעת\n"
	.string "את ההישג של {STR_VAR_3} ניצחונות רצופים\l"
	.string "ב{STR_VAR_2}.\p"
	.string "מוטב שאנסה יותר קשה בעצמי!\n"
	.string "נתראה בקרוב!$"

MatchCall_BattleFrontierRecordStreakText7::
	.string "…אה, {PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} כאן…\p"
	.string "אה, כן, היית ב\n"
	.string "ה{STR_VAR_2}, נכון?\p"
	.string "וניצחת {STR_VAR_3} קרבות ברצף.\p"
	.string "אוי, הנה פוקימון נדיר!\n"
	.string "אני חייב ללכת!$"

MatchCall_BattleFrontierRecordStreakText8::
	.string "אוי, {PLAYER}{KUN}, מה שלומך?\n"
	.string "זו {STR_VAR_1} מדברת.\l"
	.string "אני מקווה שאת{EMIT_HEY} עושה חיל.\p"
	.string "אוי, אבל, את{EMIT_HEY} כן. שמעתי ש\n"
	.string "ניצחת {STR_VAR_3} קרבות ברצף ב\l"
	.string "ה{STR_VAR_2}.\p"
	.string "זה מאוד מרשים!\n"
	.string "מוטב שאעבוד על הפוקימונים שלי, גם!$"

MatchCall_BattleFrontierRecordStreakText9::
	.string "אוי, {PLAYER}{KUN}, היי!\n"
	.string "זו {STR_VAR_1}!\p"
	.string "שמעתי! רצף {STR_VAR_3} הניצחונות שלך ב\n"
	.string "ה{STR_VAR_2}!\p"
	.string "זה כל כך קול!\n"
	.string "מוטב שאנסה יותר קשה, גם!$"

MatchCall_BattleFrontierRecordStreakText10::
	.string "אוי, {PLAYER}{KUN}, שלום…\n"
	.string "זה {STR_VAR_1}.\p"
	.string "ניצחת {STR_VAR_3} קרבות רצופים ב\n"
	.string "ה{STR_VAR_2}?\p"
	.string "זה הישג לא מבוטל.\n"
	.string "אני צריך לעבוד קשה יותר.$"

MatchCall_BattleFrontierRecordStreakText11::
	.string "אה, {PLAYER}{KUN}.\n"
	.string "זה {STR_VAR_1}.\p"
	.string "אני שומע שאת{EMIT_HEY} האימה של\n"
	.string "ה{STR_VAR_2}?\p"
	.string "ניצחת, כמה, {STR_VAR_3} קרבות\n"
	.string "ברצף?\p"
	.string "את{EMIT_HEY} טוב, את{EMIT_HEY}.\n"
	.string "אני תוהה בכמה אני יכול לנצח?$"

MatchCall_BattleFrontierRecordStreakText12::
	.string "שלום, {PLAYER}{KUN}.\n"
	.string "זה אני, {STR_VAR_1}.\l"
	.string "את{EMIT_HEY} שומר על עצמך?\p"
	.string "מישהו העביר לי מילה עליך.\n"
	.string "איך ניצחת {STR_VAR_3} קרבות רצופים\l"
	.string "במקום בשם {STR_VAR_2}?\p"
	.string "זה סיפור לא מבוטל.\n"
	.string "נתראה!$"

MatchCall_BattleFrontierRecordStreakText13::
	.string "אה, שלום, {PLAYER}{KUN}!\n"
	.string "זה {STR_VAR_1}.\l"
	.string "אני מקווה שאת{EMIT_HEY} שומר על עצמך.\p"
	.string "הם אומרים שניצחת {STR_VAR_3} קרבות רצופים\n"
	.string "ב{STR_VAR_2}.\p"
	.string "אני מעריץ את האנרגיה שלך!\n"
	.string "ביי עכשיו.$"

MatchCall_BattleFrontierRecordStreakText14::
	.string "אוי, היי, {PLAYER}{KUN}.\n"
	.string "זה {STR_VAR_1}.\l"
	.string "שמעתי עליך!\p"
	.string "לא ניצחת {STR_VAR_3} קרבות\n"
	.string "ברצף ב{STR_VAR_2}?\p"
	.string "את{EMIT_HEY} השראה!\n"
	.string "ביי ביי!$"

MatchCall_BattleDomeText1::
	.string "היי! {PLAYER}?\n"
	.string "שלום, זו {STR_VAR_1}!\l"
	.string "שמעתי את החדשות!\p"
	.string "הפכת לאלוף ב\n"
	.string "ה{STR_VAR_2} {STR_VAR_3} פעמים?\p"
	.string "זה מדהים! אני חייב להשתפר!\n"
	.string "נתראה!$"

MatchCall_BattleDomeText2::
	.string "שלום, זו {STR_VAR_1}!\n"
	.string "שמעתי עליך!\p"
	.string "הם אמרו שניצחת {STR_VAR_3} תארים\n"
	.string "ב{STR_VAR_2}.\p"
	.string "זה סופר! אני תוהה אם אני יכול\n"
	.string "להפוך לאלוף?$"

MatchCall_BattleDomeText3::
	.string "היי {PLAYER}!\n"
	.string "זה אני, {STR_VAR_1}!\l"
	.string "מה קורה?\p"
	.string "שמעתי שניצחת אירועים {STR_VAR_3} פעמים\n"
	.string "ב{STR_VAR_2}!\p"
	.string "תעשה את זה פעם אחת נוספת בפעם הבאה!\n"
	.string "נתפוס אותך בקרוב!$"

MatchCall_BattleDomeText4::
	.string "היי, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} כאן.\p"
	.string "שמעתי שהפכת לאלוף\n"
	.string "ב{STR_VAR_2} {STR_VAR_3} פעמים.\p"
	.string "נשמע שאת{EMIT_HEY} עובד קשה.\n"
	.string "אני אנסה לעמוד בקצב!$"

MatchCall_BattleDomeText5::
	.string "היי, {PLAYER}{KUN}!\n"
	.string "זו {STR_VAR_1}.\p"
	.string "שמעתי שניצחת {STR_VAR_3} פעמים\n"
	.string "ממש ב{STR_VAR_2}.\p"
	.string "מוטב שאתחיל גם אני!\n"
	.string "נתראה בקרוב!$"

MatchCall_BattleDomeText6::
	.string "היי, {PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} כאן. מה שלומך?\p"
	.string "דרך אגב, שמעתי שהפכת\n"
	.string "לאלוף {STR_VAR_3} פעמים ב\l"
	.string "ה{STR_VAR_2}.\p"
	.string "מוטב שאאמן את הפוקימונים שלי לפני\n"
	.string "שאת{EMIT_HEY} מתרחק יותר מדי.$"

MatchCall_BattleDomeText7::
	.string "{PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} כאן.\p"
	.string "היית ב{STR_VAR_2}\n"
	.string "והפכת לאלוף {STR_VAR_3} פעמים?\p"
	.string "זה נחמד. דרך אגב, תפסת\n"
	.string "פוקימונים נדירים לאחרונה?\p"
	.string "אה, זה נכון.\n"
	.string "אוקיי, ביי.$"

MatchCall_BattleDomeText8::
	.string "אוי, {PLAYER}{KUN}, מה שלומך?\n"
	.string "זו {STR_VAR_1} מדברת.\l"
	.string "אני מקווה שאת{EMIT_HEY} עושה חיל.\l"
	.string "אוי, אבל, את{EMIT_HEY} כן.\p"
	.string "שמעתי שניצחת {STR_VAR_3} תארים\n"
	.string "ב{STR_VAR_2}.\p"
	.string "אני חייב לאמן את הפוקימונים שלי כמוך.\n"
	.string "נתראה שוב.$"

MatchCall_BattleDomeText9::
	.string "אוי, {PLAYER}{KUN}, היי!\n"
	.string "זו {STR_VAR_1}!\p"
	.string "שמעתי! לקחת את התואר\n"
	.string "{STR_VAR_3} פעמים ב{STR_VAR_2}!\p"
	.string "זה כל כך קול!\n"
	.string "מוטב שאנסה יותר קשה, גם!$"

MatchCall_BattleDomeText10::
	.string "אוי, {PLAYER}{KUN}, שלום.\n"
	.string "זה {STR_VAR_1}.\p"
	.string "ניצחת {STR_VAR_3} פעמים רצופות ב\n"
	.string "ה{STR_VAR_2}?\p"
	.string "זה הישג לא מבוטל.\n"
	.string "אני צריך לעבוד קשה יותר.$"

MatchCall_BattleDomeText11::
	.string "אה, {PLAYER}{KUN}.\n"
	.string "זה {STR_VAR_1}.\p"
	.string "אני שומע שאת{EMIT_HEY} האימה של\n"
	.string "ה{STR_VAR_2}?\p"
	.string "ניצחת, כמה, {STR_VAR_3} פעמים רצופות\n"
	.string "עכשיו?\p"
	.string "אני תוהה אם אני אי פעם אוכל להפוך\n"
	.string "לאלוף?\p"
	.string "…די בלתי אפשרי?\n"
	.string "טוב, נתראה!$"

MatchCall_BattleDomeText12::
	.string "שלום, {PLAYER}{KUN}.\n"
	.string "זה אני, {STR_VAR_1}.\l"
	.string "את{EMIT_HEY} שומר על עצמך?\p"
	.string "ניצחת {STR_VAR_3} אירועים במקום\n"
	.string "בשם {STR_VAR_2}?\p"
	.string "זה סיפור לא מבוטל.\n"
	.string "נתראה!$"

MatchCall_BattleDomeText13::
	.string "אה, שלום, {PLAYER}{KUN}!\n"
	.string "זה {STR_VAR_1}.\l"
	.string "אני מקווה שאת{EMIT_HEY} שומר על עצמך.\p"
	.string "הם אומרים שניצחת {STR_VAR_3} אירועים\n"
	.string "ב{STR_VAR_2}?\p"
	.string "אני מעריץ את האנרגיה שלך!\n"
	.string "ביי עכשיו.$"

MatchCall_BattleDomeText14::
	.string "אוי, היי, {PLAYER}{KUN}.\n"
	.string "זה {STR_VAR_1}.\l"
	.string "שמעתי עליך!\p"
	.string "לא ניצחת {STR_VAR_3} תארים\n"
	.string "ב{STR_VAR_2}?\p"
	.string "את{EMIT_HEY} השראה!\n"
	.string "נתראה שוב!$"

MatchCall_BattlePikeText1::
	.string "היי! {PLAYER}?\n"
	.string "שלום, זו {STR_VAR_1}!\l"
	.string "שמעתי את החדשות!\p"
	.string "עברת {STR_VAR_3} חדרים\n"
	.string "ב{STR_VAR_2}!\p"
	.string "זה מדהים!\n"
	.string "נתראה!$"

MatchCall_BattlePikeText2::
	.string "שלום, זו {STR_VAR_1}!\n"
	.string "שמעתי עליך!\p"
	.string "הם אמרו שניצחת את דרכך דרך\n"
	.string "{STR_VAR_3} חדרים ב{STR_VAR_2}.\p"
	.string "אני חייב לנסות הרבה יותר קשה!\n"
	.string "ביי!$"

MatchCall_BattlePikeText3::
	.string "היי {PLAYER}!\n"
	.string "זה אני, {STR_VAR_1}!\l"
	.string "מה קורה?\p"
	.string "שמעתי שניצחת את דרכך דרך {STR_VAR_3} חדרים\n"
	.string "ב{STR_VAR_2}!\p"
	.string "תנס{EMIT_HEY}{ADD_YUD} להצליח אפילו יותר בפעם הבאה!\n"
	.string "נתפוס אותך בקרוב!$"

MatchCall_BattlePikeText4::
	.string "היי, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} כאן.\p"
	.string "שמעתי שהעפת {STR_VAR_3} חדרים\n"
	.string "ב{STR_VAR_2}.\p"
	.string "מוטב שאאמן את הפוקימונים שלי ו\n"
	.string "אנסה לעמוד בקצב!$"

MatchCall_BattlePikeText5::
	.string "היי, {PLAYER}{KUN}!\n"
	.string "זו {STR_VAR_1}.\p"
	.string "שמעתי שעברת {STR_VAR_3} חדרים\n"
	.string "ב{STR_VAR_2}.\p"
	.string "מוטב שאתחיל גם אני!\n"
	.string "נתראה בקרוב!$"

MatchCall_BattlePikeText6::
	.string "היי, {PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} כאן. מה שלומך?\p"
	.string "דרך אגב, שמעתי שעברת\n"
	.string "{STR_VAR_3} חדרים ב{STR_VAR_2}.\p"
	.string "מוטב שאאמן את הפוקימונים שלי לפני\n"
	.string "שאת{EMIT_HEY} מתרחק יותר מדי.$"

MatchCall_BattlePikeText7::
	.string "{PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} כאן.\p"
	.string "היית ב{STR_VAR_2}\n"
	.string "וניצחת את דרכך מעבר ל{STR_VAR_3} חדרים?\p"
	.string "זה מדהים.\p"
	.string "אוי, הנה פוקימון נדיר!\n"
	.string "אוקיי, ביי.$"

MatchCall_BattlePikeText8::
	.string "אוי, {PLAYER}{KUN}, מה שלומך?\n"
	.string "זו {STR_VAR_1} מדברת.\l"
	.string "אני מקווה שאת{EMIT_HEY} עושה חיל.\l"
	.string "אוי, אבל, את{EMIT_HEY} כן.\p"
	.string "שמעתי שעברת\n"
	.string "{STR_VAR_3} חדרים ב{STR_VAR_2}.\p"
	.string "זה די מרשים!\n"
	.string "אני חייב לאמן את הפוקימונים שלי כמוך.\l"
	.string "נתראה שוב.$"

MatchCall_BattlePikeText9::
	.string "אוי, {PLAYER}{KUN}, היי!\n"
	.string "זו {STR_VAR_1}!\p"
	.string "שמעתי! ניצחת את דרכך דרך\n"
	.string "{STR_VAR_3} חדרים ב{STR_VAR_2}!\p"
	.string "זה כל כך קול!\n"
	.string "מוטב שאנסה יותר קשה, גם!$"

MatchCall_BattlePikeText10::
	.string "אוי, {PLAYER}{KUN}, שלום.\n"
	.string "זה {STR_VAR_1}.\p"
	.string "ניצחת את דרכך מעבר ל{STR_VAR_3} חדרים\n"
	.string "ב{STR_VAR_2}?\p"
	.string "זה הישג לא מבוטל.\n"
	.string "אני צריך לעבוד קשה יותר.$"

MatchCall_BattlePikeText11::
	.string "אה, {PLAYER}{KUN}.\n"
	.string "זה {STR_VAR_1}.\p"
	.string "אני שומע שאת{EMIT_HEY} האימה של\n"
	.string "ה{STR_VAR_2}?\p"
	.string "עברת דרך, כמה, {STR_VAR_3} חדרים?\n"
	.string "זה בטח נחשב למשהו.\p"
	.string "אני תוהה אם אני אי פעם אוכל להפוך\n"
	.string "לאלוף?\p"
	.string "…די בלתי אפשרי?\n"
	.string "טוב, נתראה!$"

MatchCall_BattlePikeText12::
	.string "שלום, {PLAYER}{KUN}.\n"
	.string "זה אני, {STR_VAR_1}.\l"
	.string "את{EMIT_HEY} שומר על עצמך?\p"
	.string "ניצחת דרך {STR_VAR_3} חדרים ב\n"
	.string "מקום בשם {STR_VAR_2}?\p"
	.string "זה סיפור לא מבוטל.\n"
	.string "נתראה!$"

MatchCall_BattlePikeText13::
	.string "אה, שלום, {PLAYER}{KUN}!\n"
	.string "זה {STR_VAR_1}.\l"
	.string "אני מקווה שאת{EMIT_HEY} שומר על עצמך.\p"
	.string "הם אומרים שניצחת ב{STR_VAR_3} חדרים\n"
	.string "ב{STR_VAR_2}?\p"
	.string "אני מעריץ את האנרגיה שלך!\n"
	.string "ביי עכשיו.$"

MatchCall_BattlePikeText14::
	.string "אוי, היי, {PLAYER}{KUN}.\n"
	.string "זה {STR_VAR_1}.\l"
	.string "שמעתי עליך!\p"
	.string "לא עברת {STR_VAR_3} חדרים\n"
	.string "ב{STR_VAR_2}?\p"
	.string "את{EMIT_HEY} השראה!\n"
	.string "נתראה שוב!$"

MatchCall_BattlePyramidText1::
	.string "היי! {PLAYER}?\n"
	.string "שלום, זו {STR_VAR_1}!\l"
	.string "שמעתי את החדשות!\p"
	.string "טיפסת {STR_VAR_3} קומות בתוך\n"
	.string "ה{STR_VAR_2}, נכון?\p"
	.string "זה מדהים!\n"
	.string "אני צריך לנסות את האתגר הזה.$"

MatchCall_BattlePyramidText2::
	.string "שלום, זו {STR_VAR_1}!\n"
	.string "שמעתי עליך!\p"
	.string "הם אמרו שניצחת את דרכך דרך\n"
	.string "{STR_VAR_3} קומות ב{STR_VAR_2}.\p"
	.string "וואו, זה פנטסטי!\n"
	.string "מוטב שאאמן את הפוקימונים שלי, גם!$"

MatchCall_BattlePyramidText3::
	.string "היי {PLAYER}!\n"
	.string "זה אני, {STR_VAR_1}!\l"
	.string "מה קורה?\p"
	.string "שמעתי שטיפסת {STR_VAR_3} קומות\n"
	.string "ב{STR_VAR_2}!\p"
	.string "תנס{EMIT_HEY}{ADD_YUD} להצליח אפילו יותר בפעם הבאה!\n"
	.string "נתפוס אותך בקרוב!$"

MatchCall_BattlePyramidText4::
	.string "היי, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} כאן.\p"
	.string "שמעתי שטיפסת {STR_VAR_3} קומות\n"
	.string "ב{STR_VAR_2}.\p"
	.string "מוטב שאעבוד קשה ואנסה\n"
	.string "לעמוד בקצב!$"

MatchCall_BattlePyramidText5::
	.string "היי, {PLAYER}{KUN}!\n"
	.string "זו {STR_VAR_1}.\p"
	.string "שמעתי שטיפסת {STR_VAR_3} קומות\n"
	.string "ב{STR_VAR_2}.\p"
	.string "מוטב שאתחיל גם אני!\n"
	.string "נתראה בקרוב!$"

MatchCall_BattlePyramidText6::
	.string "היי, {PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} כאן. מה שלומך?\p"
	.string "דרך אגב, שמעתי שעברת\n"
	.string "{STR_VAR_3} קומות ב{STR_VAR_2}.\p"
	.string "מוטב שאאמן את הפוקימונים שלי לפני\n"
	.string "שאת{EMIT_HEY} מתרחק יותר מדי.$"

MatchCall_BattlePyramidText7::
	.string "{PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} כאן.\p"
	.string "היית ב{STR_VAR_2}\n"
	.string "וניצחת את דרכך למעלה {STR_VAR_3} קומות?\p"
	.string "נחמד. היו שם פוקימונים נדירים\n"
	.string "שם?\p"
	.string "לא, הא?\n"
	.string "אוקיי, ביי.$"

MatchCall_BattlePyramidText8::
	.string "אוי, {PLAYER}{KUN}, מה שלומך?\n"
	.string "זו {STR_VAR_1} מדברת.\l"
	.string "אני מקווה שאת{EMIT_HEY} עושה חיל.\l"
	.string "אוי, אבל, את{EMIT_HEY} כן.\p"
	.string "שמעתי שעברת\n"
	.string "{STR_VAR_3} קומות ב{STR_VAR_2}.\p"
	.string "זה די מרשים!\n"
	.string "אני חייב לאמן את הפוקימונים שלי כמוך.\l"
	.string "נתראה שוב.$"

MatchCall_BattlePyramidText9::
	.string "אוי, {PLAYER}{KUN}, היי!\n"
	.string "זו {STR_VAR_1}!\p"
	.string "שמעתי! ניצחת את דרכך דרך\n"
	.string "{STR_VAR_3} קומות ב{STR_VAR_2}!\p"
	.string "זה כל כך קול!\n"
	.string "מוטב שאנסה יותר קשה, גם!$"

MatchCall_BattlePyramidText10::
	.string "אוי, {PLAYER}{KUN}, שלום.\n"
	.string "זה {STR_VAR_1}.\p"
	.string "טיפסת {STR_VAR_3} קומות בתוך\n"
	.string "ה{STR_VAR_2}?\p"
	.string "זה הישג לא מבוטל.\n"
	.string "אני צריך לעבוד קשה יותר.$"

MatchCall_BattlePyramidText11::
	.string "אה, {PLAYER}{KUN}.\n"
	.string "זה {STR_VAR_1}.\p"
	.string "אני שומע שאת{EMIT_HEY} האימה של\n"
	.string "ה{STR_VAR_2}?\p"
	.string "עלית דרך, כמה, {STR_VAR_3} קומות?\n"
	.string "זה בטח נחשב למשהו.\p"
	.string "אני תוהה אם אני אי פעם אוכל להפוך\n"
	.string "לאלוף?\p"
	.string "…די בלתי אפשרי?\n"
	.string "טוב, נתראה!$"

MatchCall_BattlePyramidText12::
	.string "שלום, {PLAYER}{KUN}.\n"
	.string "זה אני, {STR_VAR_1}.\l"
	.string "את{EMIT_HEY} שומר על עצמך?\p"
	.string "ניצחת דרך {STR_VAR_3} קומות ב\n"
	.string "מקום בשם {STR_VAR_2}?\p"
	.string "זה סיפור לא מבוטל.\n"
	.string "נתראה!$"

MatchCall_BattlePyramidText13::
	.string "אה, שלום, {PLAYER}{KUN}!\n"
	.string "זה {STR_VAR_1}.\l"
	.string "אני מקווה שאת{EMIT_HEY} שומר על עצמך.\p"
	.string "הם אומרים שטיפסת {STR_VAR_3} קומות\n"
	.string "ב{STR_VAR_2}?\p"
	.string "אני מעריץ את האנרגיה שלך!\n"
	.string "ביי עכשיו.$"

MatchCall_BattlePyramidText14::
	.string "אוי, היי, {PLAYER}{KUN}.\n"
	.string "זה {STR_VAR_1}.\l"
	.string "שמעתי עליך!\p"
	.string "לא עברת {STR_VAR_3} קומות\n"
	.string "ב{STR_VAR_2}?\p"
	.string "את{EMIT_HEY} השראה!\n"
	.string "נתראה שוב!$"

MatchCall_Text_Mom1::
	.string "אמא: אבא שלך ואת{EMIT_HEY}…\n"
	.string "כולם מוקסמים מפוקימונים.\p"
	.string "מה הקסם של פוקימון?\p"
	.string "אני?\n"
	.string "אני מעריצה פוקימונים שעוזרים לי ב\l"
	.string "מטלות היומיום שלי.$"

MatchCall_Text_Mom2::
	.string "אמא: היי, {PLAYER}!\n"
	.string "אבא שלך מסתגר\l"
	.string "במכון פטלבורג.\p"
	.string "הוא חוזר הביתה מדי פעם.\n"
	.string "אבל הוא חוזר למכון כש\l"
	.string "הוא אכל כל מה שהוא יכול.\p"
	.string "אני מניחה שההפסד לך\n"
	.string "היה מכה קשה לגאווה שלו!$"

MatchCall_Text_Mom3::
	.string "אמא: {PLAYER}…\n"
	.string "אל תדאג לגבי או לגבי הבית.\p"
	.string "תנעלי את נעלי הריצה האלה עד\n"
	.string "שהן יתפרקו, מותק!$"

MatchCall_Text_Roxanne_Preparing::
	.string "רוקסן: אוי, שלום, {PLAYER}!\p"
	.string "עבדתי קשה על אימון מחדש\n"
	.string "מאז שנפגשנו.\p"
	.string "אני עדיין אצטרך עוד קצת זמן\n"
	.string "לפני שאוכל לפתוח מחדש את המכון.\p"
	.string "אבל כשאעשה זאת, בבקשה בקר במכון שלי\n"
	.string "לקרב חוזר!$"

MatchCall_Text_Roxanne_PreparingPostGame::
	.string "רוקסן: זה {PLAYER}?\n"
	.string "ברכות!\l"
	.string "אני שומעת עליך!\p"
	.string "לגבי, אני עדיין צריכה עוד קצת זמן\n"
	.string "לפני שאוכל לפתוח מחדש את המכון.\p"
	.string "אבל כשאעשה זאת, בבקשה בקר במכון שלי\n"
	.string "לקרב חוזר!$"

MatchCall_Text_Roxanne_RematchReady::
	.string "רוקסן: {PLAYER}!\n"
	.string "המכון שלי מוכן!\p"
	.string "בבקשה בקר ברסטבורו בכל פעם\n"
	.string "שתוכל!$"

MatchCall_Text_Roxanne_PostRematch::
	.string "רוקסן: במכון רסטבורו,\n"
	.string "העובדה שנלחמנו, {PLAYER},\l"
	.string "היא עניין של גאווה.$"

MatchCall_Text_Brawly_Preparing::
	.string "בראולי: היי, {PLAYER}{KUN}!\p"
	.string "למדתי הרבה מהקרב שהיה לנו\n"
	.string "יחד.\p"
	.string "אני מתכוון לעשות את האימונים שלי מחדש,\n"
	.string "ואז לפתוח מחדש את המכון.\p"
	.string "זה הולך לקחת זמן עד\n"
	.string "שאני אהיה מוכן להפעיל את המכון שוב.\p"
	.string "אבל אם אני אוכל לפתוח מחדש את המכון,\n"
	.string "אני רוצה שתאתגר אותנו שוב.$"

MatchCall_Text_Brawly_PreparingPostGame::
	.string "בראולי: היי, {PLAYER}{KUN}!\n"
	.string "ברכות!\p"
	.string "השמועות על מעשיך הגיעו\n"
	.string "על גלי הים!\p"
	.string "נראה כאילו אני צריך לעבוד על\n"
	.string "האימונים שלי עוד קצת.\p"
	.string "זה הולך לקחת זמן עד\n"
	.string "שאני אהיה מוכן להפעיל את המכון שוב.\p"
	.string "אבל אם אני אוכל לפתוח מחדש את המכון,\n"
	.string "אני רוצה שתאתגר אותנו שוב.$"

MatchCall_Text_Brawly_RematchReady::
	.string "בראולי: היי, {PLAYER}{KUN}!\n"
	.string "המכון שלי מוכן לפעולה!\p"
	.string "תחזור לדיופורד בכל עת\n"
	.string "לאתגר נוסף!$"

MatchCall_Text_Brawly_PostRematch::
	.string "בראולי: {PLAYER}{KUN}, אני לא חושב\n"
	.string "שאני אי פעם אשתעמם מלהילחם בך!$"

MatchCall_Text_Wattson_Preparing::
	.string "ווטסון: אוי, זה את{EMIT_HEY}!\p"
	.string "אחרי שעזבת, אני עושה מחדש\n"
	.string "את האימונים שלי מהתחלה.\p"
	.string "הייתי אומר שאני צריך עוד קצת\n"
	.string "זמן כדי לפתוח מחדש את המכון שלי.\p"
	.string "תצטרך לחכות עד אז!\n"
	.string "וואהאהאהא!$"

MatchCall_Text_Wattson_PreparingPostGame::
	.string "ווטסון: וואהאהאהא!\p"
	.string "את{EMIT_HEY} באמת עשית את זה, לא?\n"
	.string "אני מקבל שמועות עליך!\p"
	.string "נראה שאני צריך להתאמן\n"
	.string "עוד קצת.\p"
	.string "הייתי אומר שאני צריך עוד קצת\n"
	.string "זמן כדי לפתוח מחדש את המכון שלי.\p"
	.string "תצטרך לחכות עד אז!\n"
	.string "וואהאהאהא!$"

MatchCall_Text_Wattson_RematchReady::
	.string "ווטסון: אוי, זה את{EMIT_HEY}!\n"
	.string "המכון שלי מוכן!\p"
	.string "בקר במאוביל בכל עת!\n"
	.string "וואהאהאהא!$"

MatchCall_Text_Wattson_PostRematch::
	.string "ווטסון: וואהאהאהא!\p"
	.string "קרב איתך תמיד טעון\n"
	.string "בכוח מזעזע!$"

MatchCall_Text_Flannery_Preparing::
	.string "פלאנרי: {PLAYER}…\p"
	.string "כאשר נלחמנו, למדתי בדיוק\n"
	.string "כמה ילדותית אני.\p"
	.string "אבל עוד לא סיימתי!\p"
	.string "אני הולכת לעשות את האימונים שלי מחדש ו\n"
	.string "לפתוח מחדש את המכון.\p"
	.string "כשיגיע הזמן, {PLAYER},\n"
	.string "בבקשה תאתגר אותנו שוב.$"

MatchCall_Text_Flannery_PreparingPostGame::
	.string "פלאנרי: שלום, {PLAYER}?\n"
	.string "ברכות!\p"
	.string "שמועות על הצלחתך הגיעו\n"
	.string "אלינו כמו חום של הר געש!\p"
	.string "האימונים שלנו מתקדמים מאוד\n"
	.string "כאן.\p"
	.string "כשהמכון יהיה מוכן, יופיע סימן\n"
	.string "ליד השם שלי ברשימת\l"
	.string "השיחות המותאמות.$"

MatchCall_Text_Flannery_RematchReady::
	.string "פלאנרי: אוי, {PLAYER}?\n"
	.string "המכון שלנו מוכן!\p"
	.string "בוא{ADD_YUD} ללברידג' להשרות\n"
	.string "במעיין החם ולאתגר!$"

MatchCall_Text_Flannery_PostRematch::
	.string "פלאנרי: {PLAYER}…\n"
	.string "אני בטוחה שאת{EMIT_HEY} ממשיך להשתפר\l"
	.string "באימונים בכל פעם.$"

MatchCall_Text_Winona_Preparing::
	.string "וינונה: שלום, {PLAYER}!\p"
	.string "תודה על הקרב שלנו, הגעתי ל\n"
	.string "הבנה של נקודות החולשה שלי!\p"
	.string "כשאני אפתח מחדש את המכון, אני לא\n"
	.string "אפסיד שוב!$"

MatchCall_Text_Winona_PreparingPostGame::
	.string "וינונה: עשית את זה, {PLAYER}!\p"
	.string "חדשות על האלוף החדש\n"
	.string "הגיעו אלינו בפורטרי!\p"
	.string "אבל… בפעם הבאה שנילחם,\n"
	.string "זה לא יסתיים באותה צורה.$"

MatchCall_Text_Winona_RematchReady::
	.string "וינונה: זה {PLAYER}?\n"
	.string "המכון שלנו חזר לפעולה!\p"
	.string "אנחנו מחכים לך בפורטרי!$"

MatchCall_Text_Winona_PostRematch::
	.string "וינונה: {PLAYER}…\n"
	.string "למרות שהפסדתי, הכנפיים שלי\l"
	.string "לעולם לא יישברו.\p"
	.string "כן, בדיוק באותה דרך שבה\n"
	.string "את{EMIT_HEY} אף פעם לא איבדת את החזון שלך.$"

MatchCall_Text_TateLiza_Preparing::
	.string "טייט: אוי! את{EMIT_HEY}…\n"
	.string "ליזה: {PLAYER}!\p"
	.string "טייט: אנחנו שוב באימונים…\n"
	.string "ליזה: כדי שנוכל לפתוח מחדש את המכון שלנו!\p"
	.string "טייט: כשהמכון שלנו יהיה מוכן…\n"
	.string "ליזה: כשהמכון שלנו יהיה מוכן…\p"
	.string "טייט: יופיע סימן ליד השם שלנו…\n"
	.string "ליזה: ברשימת השיחות המותאמות.$"

MatchCall_Text_TateLiza_PreparingPostGame::
	.string "טייט: {PLAYER}, ברכות!\n"
	.string "ליזה: {PLAYER}, ברכות!\p"
	.string "טייט: שנינו…\n"
	.string "ליזה: עדיין באימונים!\p"
	.string "טייט: אנחנו צריכים עוד קצת זמן, אבל…\n"
	.string "ליזה: כשהמכון שלנו יהיה מוכן…\p"
	.string "טייט: יופיע סימן ליד השם שלנו…\n"
	.string "ליזה: ברשימת השיחות המותאמות.$"

MatchCall_Text_TateLiza_RematchReady::
	.string "טייט: {PLAYER}!\n"
	.string "ליזה: {PLAYER}!\p"
	.string "טייט: המכון שלנו מוכן!\n"
	.string "ליזה: המכון שלנו מוכן!\p"
	.string "טייט: בבקשה בוא{ADD_YUD} לבקר ב…\n"
	.string "ליזה: מוסדיפ בכל עת!$"

MatchCall_Text_TateLiza_PostRematch::
	.string "טייט: {PLAYER}, הקרב שהיה לנו…\n"
	.string "ליזה: הוא חוויה שלא יסולא בפז.\p"
	.string "טייט: זה יהיה נחמד אם…\n"
	.string "ליזה: נוכל להילחם שוב כולנו!$"

MatchCall_Text_Juan_Preparing::
	.string "חואן: הממ…\n"
	.string "{PLAYER}{KUN}… זה את{EMIT_HEY}?\p"
	.string "הקרב שהיה לנו יחד, הוא\n"
	.string "העלה בי זיכרונות מלפני\l"
	.string "שפגשתי את וולאס.\p"
	.string "אולי את{EMIT_HEY} גאון שאולי\n"
	.string "יעלה על וולאס!$"

MatchCall_Text_Juan_PreparingPostGame::
	.string "חואן: פופו… {PLAYER}{KUN}…\n"
	.string "סוף סוף השגת את מטרתך.\p"
	.string "חוש ההערכה שלי לכישרון לא\n"
	.string "טעה…\p"
	.string "אני מייחל להזדמנות נוספת לפגוש\n"
	.string "אותך, כי טיפסת לפסגת\l"
	.string "הכוח והיוקרה.$"

MatchCall_Text_Juan_RematchReady::
	.string "חואן: הוהו… {PLAYER}{KUN}…\p"
	.string "מכון סוטופוליס שלנו סוף סוף\n"
	.string "נפתח מחדש.\p"
	.string "אם את{EMIT_HEY} רוצה לראות אותי, את{EMIT_HEY}\n"
	.string "מוזמן לבקר בכל עת.$"

MatchCall_Text_Juan_PostRematch::
	.string "חואן: {PLAYER}{KUN}…\p"
	.string "כמו המוזיקה המשובחת ביותר, הקרבות\n"
	.string "שאנו מנהלים יחד מנגנים נימים\l"
	.string "של השראה בלבי…\p"
	.string "כשאני עוצם את העיניים, אני רואה חזיונות\n"
	.string "שלך מרקיע עם המנגינה…$"

MatchCall_Text_Sidney::
	.string "סידני: היי, {PLAYER}!\p"
	.string "אם את{EMIT_HEY} רוצה להילחם איתי\n"
	.string "שוב, את{EMIT_HEY} מוזמן לחזור בכל עת\l"
	.string "שתרצה לליגת הפוקימונים.\p"
	.string "אני תמיד אהיה כאן!\n"
	.string "אני אחכ{EMIT_HEY}{ADD_YUD}!$"

MatchCall_Text_Phoebe::
	.string "פיבי: היי, {PLAYER}!\p"
	.string "מה דעתך לחזור לכאן שוב\n"
	.string "מתישהו?\p"
	.string "אני רוצה לראות כמה ההקשר שלך\n"
	.string "עם הפוקימונים שלך התחזק.$"

MatchCall_Text_Glacia::
	.string "גלסייה: שלום, {PLAYER}.\p"
	.string "אני סומכת על כך שלא נהיית\n"
	.string "שאנן עם הכוח שלך?\p"
	.string "אם את{EMIT_HEY} מרגיש צורך לצנן את\n"
	.string "הרגשות החמים שלך רק קצת, בוא\l"
	.string "לליגת הפוקימונים…$"

MatchCall_Text_Drake::
	.string "דרייק: הקול הזה… {PLAYER}, זה את{EMIT_HEY}?\n"
	.string "את{EMIT_HEY} נשמע טוב…\p"
	.string "אני מבין שעכשיו יש\n"
	.string "מתקן שנקרא חזית הקרב\l"
	.string "שבוחן את כישורי\l"
	.string "המאמנים.\p"
	.string "עם זאת, אם את{EMIT_HEY} רוצה קרבות אמיתיים,\n"
	.string "אין תחליף ל\l"
	.string "ליגת הפוקימונים!\p"
	.string "את{EMIT_HEY} לא מסכים, {PLAYER}?$"

MatchCall_Text_Wallace::
	.string "וולאס: שלום, {PLAYER}{KUN}.\n"
	.string "האם פגשת את סטיבן?\p"
	.string "הוא…\n"
	.string "למעשה מיומן להפליא.\p"
	.string "עם זאת, הוא נשמה מוזרה ש\n"
	.string "לעתים רחוקות נלחמת.\p"
	.string "במקום זאת, הוא מעדיף לחפש\n"
	.string "אבנים נדירות.\p"
	.string "אני בטוח שהוא חופר במערה או\n"
	.string "בהר סלעי איפשהו.\p"
	.string "אבל מה זו בדיוק אבן נדירה?\n"
	.string "כל מה שאני יכול לחשוב עליו זה מטאוריט…$"

MatchCall_Text_MayRayquazaCall:
	.string "… … … … … …\n"
	.string "… … … … … ביפ!\p"
	.string "מאי: היי, {PLAYER}{KUN}!\p"
	.string "בדיוק הייתי בפסיפידלוג\n"
	.string "לפני זמן קצר.\p"
	.string "ראיתי פוקימון ירוק ענק\n"
	.string "טס גבוה בשמיים.\p"
	.string "אני…\n"
	.string "אף פעם לא ראיתי דבר כזה.\p"
	.string "אני תוהה מה זה היה.\n"
	.string "אולי זו תגלית גדולה?\p"
	.string "… … … … … …\n"
	.string "… … … … … קליק!$"

MatchCall_Text_BrendanRayquazaCall:
	.string "… … … … … …\n"
	.string "… … … … … ביפ!\p"
	.string "ברנדן: היי, {PLAYER}!\n"
	.string "הייתי בפסיפידלוג ממש עכשם.\p"
	.string "ראיתי את הפוקימון הירוק הענק הזה\n"
	.string "טס מעבר לשמיים.\p"
	.string "אף פעם לא ראיתי דבר\n"
	.string "מדהים כזה לפני כן.\p"
	.string "הלוואי שיכולת לראות את זה,\n"
	.string "{PLAYER}.\p"
	.string "… … … … … …\n"
	.string "… … … … … קליק!$"

MatchCall_Text_May1::
	.string "מאי: היי, {PLAYER}{KUN}!\p"
	.string "מר ברייני פרש כמלח,\n"
	.string "אבל אני עדיין רואה אותו בים\l"
	.string "עם חיית המחמד שלו פיקו לפעמים.\p"
	.string "הוא בטח עדיין אוהב את הים.$"

MatchCall_Text_May2::
	.string "מאי: היי, {PLAYER}{KUN}!\p"
	.string "את{EMIT_HEY} יודע{ADD_TAF} איך לעיירות קטנות כמו\n"
	.string "פטלבורג ודופורד יש מכונים?\p"
	.string "משום מה, לנמל הגדול של\n"
	.string "סלייטפורט אין מכון.\p"
	.string "כאשר סוף סוף יבנו שם מכון,\n"
	.string "אני צריכה לבקש להיות המנהיגה.$"

MatchCall_Text_May3::
	.string "מאי: היי, {PLAYER}{KUN}!\p"
	.string "את{EMIT_HEY} זוכר איש בשם\n"
	.string "החותך ברסטבורו?\l"
	.string "הייתה לו שם בית, זוכר?\p"
	.string "טוב, גיליתי שאחיו הצעיר\n"
	.string "גר במוויל.\p"
	.string "את{EMIT_HEY} יכול לנחש את שמו?\p"
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "האיש של ריסוק הסלע!$"

MatchCall_Text_May4::
	.string "מאי: {PLAYER}{KUN}?\p"
	.string "מנהרת רסטרף…\n"
	.string "הם קראו לה כך מכיוון שהיא\l"
	.string "מחברת את רסטבורו ואת ורדנטרף.$"

MatchCall_Text_May5::
	.string "מאי: {PLAYER}{KUN}, מה שלומך?\p"
	.string "אני בדרך 111 עכשיו.\p"
	.string "אני הולכת לנוח בבית של\n"
	.string "אישה זקנה.\p"
	.string "היא גרה ממש מצפון\n"
	.string "למדבר.$"

MatchCall_Text_May6::
	.string "מאי: היי, {PLAYER}{KUN}!\p"
	.string "ידעת על מגדל מיראז'\n"
	.string "במדבר?\p"
	.string "הם אומרים, כמו מיראז', שהוא נראה\n"
	.string "ומסתורין בא והולך.\p"
	.string "הלוואי שיכולתי לראות אותו.$"

MatchCall_Text_May7::
	.string "מאי: {PLAYER}{KUN}, יהו!\n"
	.string "אני בדרך 911 עכשיו.\p"
	.string "יש כאן נהר גדול, ו\n"
	.string "יורד גשם לעיתים קרובות.\p"
	.string "נרטבתי לגמרי!$"

MatchCall_Text_May8::
	.string "מאי: {PLAYER}{KUN}, היי.\p"
	.string "הר המוקד הוא זיכרון לפוקימונים\n"
	.string "שחייהם הסתיימו.\p"
	.string "אולי כתוצאה מכך, הוא נגוע\n"
	.string "בהרבה פוקימוני רוח!$"

MatchCall_Text_May9::
	.string "מאי: היי, {PLAYER}{KUN}!\p"
	.string "חשבתי ללכת למעיין החם\n"
	.string "בלברידג'.\p"
	.string "אבל בדרך, בסביבת\n"
	.string "מעבר משונן, נתקלתי בכמה\l"
	.string "דמויות שנראו רע. האווירה הייתה מכוערת!$"

MatchCall_Text_May10::
	.string "מאי: היי, {PLAYER}{KUN}!\n"
	.string "ראית את החדשות?\p"
	.string "הם אומרים שקפטן סטרן גילה\n"
	.string "את מערת קרקעית הים בזמן\l"
	.string "מסע הצוללת שלו.$"

MatchCall_Text_May11::
	.string "מאי: היי, {PLAYER}{KUN}!\n"
	.string "את{EMIT_HEY} לא חושב שזה נחמד?\p"
	.string "גם אם אין לך סירה,\n"
	.string "את{EMIT_HEY} יכול לחצות את הים באמצעות\l"
	.string "מהלך של פוקימון.\p"
	.string "ידעת שיש עוד?\p"
	.string "יש מהלך פוקימון שמאפשר\n"
	.string "לך לרדת לקרקעית הים.$"

MatchCall_Text_May12::
	.string "מאי: היי, {PLAYER}{KUN}!\n"
	.string "מקווה שהכל בסדר!\p"
	.string "האם היית בים ו\n"
	.string "מצאת את דרכך לצד השני חסומה?\l"
	.string "חצומה?\p"
	.string "תנס{EMIT_HEY}{ADD_YUD} לצלול עמוק מתחת למים\n"
	.string "ולעקוב אחרי תעלות.\p"
	.string "כשתגיע לצד השני,\n"
	.string "תעלה לפני השטח. קל!$"

MatchCall_Text_May13::
	.string "מאי: היי, {PLAYER}{KUN}!\p"
	.string "מה קורה?\n"
	.string "את{EMIT_HEY} ממלא את הפוקידע שלך?\p"
	.string "שמעתי שמועה שיש\n"
	.string "פוקימונים עתיקים במיוחד שם בחוץ.\l"
	.string "ויש שלושה מהם!\p"
	.string "הייתי רוצה לראות אפילו אחד…$"

MatchCall_Text_May14::
	.string "מאי: {PLAYER}{KUN}!\n"
	.string "שמעתי את השמועות!\p"
	.string "ניצחת את מנהיג מכון\n"
	.string "סוטופוליס?\p"
	.string "זה אומר שלא נשאר לך הרבה\n"
	.string "ללכת, נכון?$"

MatchCall_Text_May15::
	.string "מאי: אין אף מאמן\n"
	.string "שנותר בהואן שלא יודע מי\l"
	.string "את{EMIT_HEY}, {PLAYER}{KUN}!\p"
	.string "כשאני מספרת לאנשים שאני חברה\n"
	.string "שלך, {PLAYER}{KUN}, כולם\l"
	.string "מופתעים!$"

MatchCall_Text_Brendan1::
	.string "ברנדן: היי, {PLAYER}!\p"
	.string "מר ברייני פרש כמלח,\n"
	.string "אבל אני עדיין רואה אותו בים\l"
	.string "עם חיית המחמד שלו פיקו לפעמים.\p"
	.string "אני מניח שהוא בטח עדיין אוהב\n"
	.string "את הים.$"

MatchCall_Text_Brendan2::
	.string "ברנדן: היי, {PLAYER}!\p"
	.string "אני לא מבין איך לעיירות קטנות כמו\n"
	.string "פטלבורג ודופורד יש מכונים.\p"
	.string "כלומר, לא כאשר לנמל הגדול של\n"
	.string "סלייטפורט אין מכון.\p"
	.string "כאשר סוף סוף יבנו שם מכון,\n"
	.string "אני צריך לבקש להיות המנהיג.$"

MatchCall_Text_Brendan3::
	.string "ברנדן: יו, {PLAYER}!\p"
	.string "את{EMIT_HEY} זוכר בחור בשם\n"
	.string "החותך ברסטבורו?\l"
	.string "הייתה לו שם בית, נכון?\p"
	.string "טוב, מסתבר שאחיו הקטן\n"
	.string "גר במוויל.\p"
	.string "את{EMIT_HEY} יכול לנחש את שמו?\p"
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "האיש של ריסוק הסלע!$"

MatchCall_Text_Brendan4::
	.string "ברנדן: הקול הזה… {PLAYER}?\p"
	.string "הם נתנו למנהרת רסטרף את שמה\n"
	.string "מכיוון שהיא מחברת את רסטבורו\l"
	.string "ואת ורדנטרף.\p"
	.string "ידעת את זה?$"

MatchCall_Text_Brendan5::
	.string "ברנדן: {PLAYER}, מה קורה?\p"
	.string "היי, אני בדרך 111 עכשיו.\p"
	.string "אני הולך לנוח בבית של\n"
	.string "אישה זקנה מצפון למדבר.\p"
	.string "אם את{EMIT_HEY} באזור, את{EMIT_HEY} צריך\n"
	.string "לבקר אותה, גם.$"

MatchCall_Text_Brendan6::
	.string "ברנדן: היי, {PLAYER}!\p"
	.string "ידעת על מגדל מיראז'\n"
	.string "במדבר?\p"
	.string "הם אומרים, כמו מיראז', שאפשר\n"
	.string "לראות אותו רק לפעמים.\p"
	.string "הייתי רוצה לראות את זה!$"

MatchCall_Text_Brendan7::
	.string "ברנדן: מי זה? אוי, {PLAYER}?\n"
	.string "נחש מה? אני בדרך 119 עכשיו.\p"
	.string "יש כאן נהר גדול, ו\n"
	.string "יורד גשם כל הזמן.\p"
	.string "נרטבתי עד העצם!$"

MatchCall_Text_Brendan8::
	.string "ברנדן: {PLAYER}!\p"
	.string "הר המוקד הוא זיכרון לפוקימונים\n"
	.string "שחייהם הסתיימו.\p"
	.string "זו כנראה הסיבה שהוא נגוע\n"
	.string "בהרבה פוקימוני רוח!$"

MatchCall_Text_Brendan9::
	.string "ברנדן: היי, {PLAYER}.\p"
	.string "הייתי בדרכי חזרה למעיין\n"
	.string "החם בלברידג'.\p"
	.string "אבל בסביבת מעבר משונן, נתקלתי\n"
	.string "בכמה דמויות שנראו מגעילות.\p"
	.string "היצורים האלה…\n"
	.string "אני חושב שהם היו צוות מגמה.$"

MatchCall_Text_Brendan10::
	.string "ברנדן: היי, {PLAYER}!\p"
	.string "ראית את החדשות?\p"
	.string "הם אומרים שקפטן סטרן גילה\n"
	.string "את מערת קרקעית הים בזמן\l"
	.string "מסע הצוללת שלו.$"

MatchCall_Text_Brendan11::
	.string "ברנדן: היי, {PLAYER}!\p"
	.string "את{EMIT_HEY} לא חושב שזה מדהים?\p"
	.string "גם אם אין לך סירה,\n"
	.string "את{EMIT_HEY} יכול לחצות את הים באמצעות\l"
	.string "מהלך של פוקימון.\p"
	.string "וגם, יש מהלך שמאפשר לך\n"
	.string "לנסוע לקרקעית הים.\p"
	.string "בן אדם, פוקימונים יכולים לעשות הכל!$"

MatchCall_Text_Brendan12::
	.string "ברנדן: שלום, {PLAYER}!\n"
	.string "איך את{EMIT_HEY} מחזיק מעמד?\p"
	.string "אי פעם מצאת את דרכך לצד\n"
	.string "השני חסומה כשאת{EMIT_HEY} בים?\p"
	.string "תנס{EMIT_HEY}{ADD_YUD} לצלול עמוק מתחת למים\n"
	.string "ולעקוב אחרי תעלות בקרקעית.\p"
	.string "כשתגיע לצד השני,\n"
	.string "תעלה לפני השטח. פשוט!$"

MatchCall_Text_Brendan13::
	.string "ברנדן: היי, {PLAYER}!\p"
	.string "מה קורה? ממלא את\n"
	.string "הפוקידע שלך בהצלחה?\p"
	.string "שמעתי שמועה שיש\n"
	.string "פוקימונים עתיקים במיוחד שם בחוץ.\l"
	.string "ולא רק אחד--שלושה!\p"
	.string "הייתי רוצה לתפוס אפילו אחד…$"

MatchCall_Text_Brendan14::
	.string "ברנדן: {PLAYER}!\n"
	.string "שמעתי את השמועות!\p"
	.string "ניצחת את מנהיג מכון\n"
	.string "סוטופוליס? מדהים!\p"
	.string "את{EMIT_HEY} מתקרב מאוד עכשיו!$"

MatchCall_Text_Brendan15::
	.string "ברנדן: אין מאמן ב\n"
	.string "כל הואן שלא יודע מי\l"
	.string "את{EMIT_HEY}, {PLAYER}!\p"
	.string "כשאני מספר לאנשים שאני חבר\n"
	.string "שלך, {PLAYER}, הם נהיים די\l"
	.string "קנאים!$"

MatchCall_Text_Wally1::
	.string "וואלי: אוי, {PLAYER}!\p"
	.string "אני נהיה בריא יותר\n"
	.string "בכושר גופני.\p"
	.string "אני מקווה שאני אוכל להפוך למאמן כמו\n"
	.string "את{EMIT_HEY} בקרוב, {PLAYER}!$"

MatchCall_Text_Wally2::
	.string "וואלי: {PLAYER}, שלום!\p"
	.string "אחרי שמנהרת רסטרף\n"
	.string "נפתחה, וונדה הייתה מאוד שמחה!$"

MatchCall_Text_Wally3::
	.string "וואלי: אוי, {PLAYER}!\p"
	.string "אני… עזבתי את המקום של דודי\n"
	.string "בורדנטרף בלי לספר לאף אחד.\p"
	.string "אני תוהה אם הוא זועם עליי…\p"
	.string "{PLAYER}, את{EMIT_HEY} מבין איך\n"
	.string "אני מרגיש, נכון?$"

MatchCall_Text_Wally4::
	.string "{PLAYER}?\n"
	.string "זה אני, וואלי!\p"
	.string "עולם המאמנים הוא מדהים!\p"
	.string "כשהפוקימון שלי איתי,\n"
	.string "כל מיני אנשים אומרים שלום!\p"
	.string "זה כאילו שכולם מתחברים\n"
	.string "דרך פוקימונים!$"

MatchCall_Text_Wally5::
	.string "וואלי: {PLAYER}? זה מדהים!\n"
	.string "הראלטס שתפסנו יחד?\l"
	.string "הוא התפתח, {PLAYER}!\p"
	.string "אולי אני מוכשר…\p"
	.string "אוי, אבל אני לא צריך לקבל ראש גדול\n"
	.string "כזה!\p"
	.string "בסופו של דבר, זה הפוקימון ש\n"
	.string "צריך לקבל שבחים!$"

MatchCall_Text_Wally6::
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "נראה שוואלי מחוץ\n"
	.string "לאזור השירות של הפוקינווט…$"

MatchCall_Text_Wally7::
	.string "וואלי: אוי, {PLAYER}!\p"
	.string "לפני שפגשתי אותך, בקושי\n"
	.string "יצאתי מהבית שלי…\p"
	.string "אבל עכשיו, אני בהרפתקה עם\n"
	.string "הפוקימון האישי שלי…\p"
	.string "{PLAYER}…\n"
	.string "תודה לך…$"

MatchCall_Text_Scott1::
	.string "סקוט: שלום, {PLAYER}{KUN}!\p"
	.string "את{EMIT_HEY} יודע{ADD_TAF} איך אפשר למצוא פוקימונים\n"
	.string "בכל מקום?\p"
	.string "כמו בהרים, בים,\n"
	.string "בדשא גבוה בכל מקום?\p"
	.string "בדיוק כמו פוקימונים, את{EMIT_HEY} יכול למצוא\n"
	.string "מאמנים בכל מקום, גם.\p"
	.string "כתוצאה מכך, אני צריך למהר\n"
	.string "לכל מקום, גם. עסוק, עסוק!$"

MatchCall_Text_Scott2::
	.string "סקוט: אני בדרך 119 ממש עכשיו.\n"
	.string "זה שורץ מאמנים!\p"
	.string "זה גם מלא בדשא גבוה\n"
	.string "בכל מקום, כך נראה.\p"
	.string "להסתובב כאן במכנסיים קצרים\n"
	.string "גורם לי לדגדוג!$"

MatchCall_Text_Scott3::
	.string "סקוט: היי, היי, {PLAYER}{KUN}!\p"
	.string "האם הייתה לך הזדמנות לטפס\n"
	.string "על הר המוקד?\p"
	.string "המקום הוא זיכרון לפוקימונים\n"
	.string "שנפטרו.\p"
	.string "זה מקום שכל מאמן\n"
	.string "צריך לטפס לפסגתו פעם אחת.$"

MatchCall_Text_Scott4::
	.string "סקוט: היי, {PLAYER}{KUN}!\p"
	.string "שמעתי על הכנופיות המוזרות האלה\n"
	.string "שהן מטרד.\p"
	.string "צוות מגמה וצוות אקווה,\n"
	.string "אני חושב שהם היו.\p"
	.string "הייתי חושב שיש כמה\n"
	.string "מאמנים מיומנים ביניהם.\p"
	.string "…אבל אם הם בריונים…$"

MatchCall_Text_Scott5::
	.string "סקוט: אוי, היי, {PLAYER}{KUN}.\p"
	.string "האם ייתכן שיש מאמנים קשוחים\n"
	.string "בקרקעית הים?\p"
	.string "אני לא יכול ללכת לבדוק בעצמי.\n"
	.string "אני לא יודע לשחות, למשל.\l"
	.string "ואני לא מגדל פוקימונים…$"

MatchCall_Text_Scott6::
	.string "סקוט: היי, היי, {PLAYER}{KUN}!\p"
	.string "את{EMIT_HEY} יודע{ADD_TAF} שאת{EMIT_HEY} יכול לאתגר\n"
	.string "את ליגת הפוקימונים כאשר את{EMIT_HEY}\l"
	.string "אוסף את כל תגי המכון?\p"
	.string "עם הכישרון שלך, להפוך לאלוף\n"
	.string "זה לא חלום רחוק.\p"
	.string "אבל ידעת?\n"
	.string "יש מקום אפילו טוב יותר.\p"
	.string "אבל, זה כל מה שאני מוכן לומר\n"
	.string "לעת עתה.\p"
	.string "זה משהו שאת{EMIT_HEY} יכול לצפות\n"
	.string "לו.\p"
	.string "כאשר ניצחת את דרכך דרך\n"
	.string "ליגת הפוקימונים אל היכל\l"
	.string "התהילה!$"

MatchCall_Text_Scott7::
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "נראה שסקוט מחוץ\n"
	.string "לאזור השירות של הפוקינווט…$"

MatchCall_Text_Norman1::
	.string "אבא: ברסטבורו, יש איש\n"
	.string "שקורא לעצמו בשם המוזר\l"
	.string "החותך.\p"
	.string "אם את{EMIT_HEY} באזור, את{EMIT_HEY} צריך\n"
	.string "לבקר אותו.$"

MatchCall_Text_Norman2::
	.string "אבא: הממ… לאט לאט, אבל גם\n"
	.string "בטח, את{EMIT_HEY} נהיה\l"
	.string "יותר קשוח, {PLAYER}.\p"
	.string "ככל שאת{EMIT_HEY} נהיה חזק יותר, כך את{EMIT_HEY} מרקיע\n"
	.string "רחוק יותר וגבוה יותר מ\l"
	.string "אמא וממני…\p"
	.string "התחושה הזו קשה להסבר.$"

MatchCall_Text_Norman3::
	.string "אבא: אני רואה…\n"
	.string "אספת ארבעה תגי מכון…\p"
	.string "אין מנוס מזה עכשיו.\n"
	.string "אנחנו נילחם כפי שהבטחתי.\p"
	.string "בוא{ADD_YUD} בכל עת.\n"
	.string "כולנו נחכ{EMIT_HEY}{ADD_YUD} לך!$"

MatchCall_Text_Norman4::
	.string "אבא: {PLAYER}! מוטב שתלך לבקר\n"
	.string "את אמא מדי פעם.\p"
	.string "אני הולך להישאר כאן ו\n"
	.string "להכפיל את האימונים שלי.\p"
	.string "דרך הלחימה היא עמוקה\n"
	.string "ולא סלחנית!$"

MatchCall_Text_Norman5::
	.string "אבא: אוי, היי, {PLAYER}!\p"
	.string "מה זה? סמל מגמה?\n"
	.string "אני לא יודע במה מדובר.\p"
	.string "אבל עם שם כזה, זה אולי\n"
	.string "קשור איכשהו להר געש!$"

MatchCall_Text_Norman_Preparing::
	.string "אבא: הייא! האא! דווא!\p"
	.string "…אוי? {PLAYER}!\p"
	.string "תפסת אותי ממש באמצע\n"
	.string "אימון פוקימונים!$"

MatchCall_Text_Norman_PreparingPostGame::
	.string "אבא: {PLAYER}!\p"
	.string "מי היה מאמין שתהפוך\n"
	.string "לאלוף ליגת הפוקימונים…\p"
	.string "אוקיי!\n"
	.string "אני לא אשאר מאחור!$"

MatchCall_Text_Norman_RematchReady::
	.string "אבא: הממ? {PLAYER}?\n"
	.string "איזה תזמון טוב!\p"
	.string "הפעם, אני הולך לאתגר\n"
	.string "אותך לקרב.\p"
	.string "אני מחכ{EMIT_HEY}{ADD_YUD} במכון פטלבורג.\n"
	.string "קבל את האתגר שלי בכל עת!$"

MatchCall_Text_Norman_PostRematch::
	.string "אבא: …את{EMIT_HEY} מדהים אותי, {PLAYER}.\n"
	.string "כמה גבוה יותר תרקיע?$"

MatchCall_Text_Steven1::
	.string "סטיבן: היי, {PLAYER}{KUN}!\p"
	.string "האם כבר היית במוויל\n"
	.string "כבר?\p"
	.string "את{EMIT_HEY} צריך לבקר בחנות האופניים\n"
	.string "ולקבל אופני מאך.\p"
	.string "ואז, נס{EMIT_HEY}{ADD_YUD} לחקור את\n"
	.string "מערת הגרניט ביסודיות.\p"
	.string "אולי תגלה תגלית חדשה\n"
	.string "שם.$"

MatchCall_Text_Steven2::
	.string "סטיבן: היי, {PLAYER}{KUN}!\p"
	.string "פגשתי הרבה מאמנים\n"
	.string "שונים עד כה.\p"
	.string "אבל את{EMIT_HEY} אחד מיוחד.\n"
	.string "את{EMIT_HEY} לא כמו אף אחד אחר.$"

MatchCall_Text_Steven3::
	.string "סטיבן: היי, {PLAYER}{KUN}!\p"
	.string "כשאת{EMIT_HEY} בהרפתקה עם\n"
	.string "הפוקימונים שלך, מה את{EMIT_HEY} חושב?\p"
	.string "האם את{EMIT_HEY} מחשיב אותם לשותפים חזקים?\p"
	.string "האם את{EMIT_HEY} חושב עליהם כעל חברים\n"
	.string "כיפיים?\p"
	.string "בהתאם לאיך שאת{EMIT_HEY} חושב, המשמעות\n"
	.string "של ההרפתקה שלך משתנה.$"

MatchCall_Text_Steven4::
	.string "סטיבן: שלום?\n"
	.string "{PLAYER}{KUN}?\p"
	.string "אני מעורב בצרות קטנות\n"
	.string "במרכז החלל.\p"
	.string "אני מצטער, אבל אני לא יכול לדבר עכשיו.\n"
	.string "ביי!$"

MatchCall_Text_Steven5::
	.string "סטיבן: אוי!\n"
	.string "{PLAYER}{KUN}!\p"
	.string "אין צורך לדבר.\n"
	.string "זה עבר את הזמן לדיבורים.\p"
	.string "את{EMIT_HEY} חייב{ADD_TAF} להאמין בעצמך\n"
	.string "ולעשות מה שנכון.$"

MatchCall_Text_Steven6::
	.string "… … … … … …\p"
	.string "נראה שסטיבן לא\n"
	.string "מקבל את השיחה…$"

MatchCall_Text_Steven7::
	.string "סטיבן: {PLAYER}{KUN}… ברכות\n"
	.string "על כניסתך להיכל התהילה.\p"
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "אני מקווה שנוכל להיפגש שוב\n"
	.string "איפשהו!$"

MatchCall_Text_BirchRegisterCall:
	.string "פרופסור בירץ': אוי, {PLAYER}{KUN}!\n"
	.string "כבר שמעתי עליך!\p"
	.string "נראה שהפוקינווט שלך שודרג\n"
	.string "עם שיחות מותאמות.\p"
	.string "טוב, אני צריך להירשם, גם!\p"
	.string "כך, אני אוכל לבחון\n"
	.string "את הפוקידע שלך אפילו כשאת{EMIT_HEY}\l"
	.string "בשטח.\p"
	.string "… … … … … …$"

MatchCall_Text_RegisteredBirch:
	.string "פרופסור בירץ' נרשם\n"
	.string "בפוקינווט.$"

MatchCall_Text_UnusedProfBirch:
	.string "פרופסור בירץ': כשיש גם\n"
	.string "את הפוקידע וגם את הפוקינווט, לימוד\l"
	.string "פוקימונים הופך למהנה יותר, אה?$"

MatchCall_Text_MrStone1::
	.string "מר סטון: אוי? {PLAYER}{KUN}!\p"
	.string "מכיוון שהתקשרת אליי, הפוקינווט\n"
	.string "בטח עובד כראוי!\p"
	.string "אנשים אחרים יירשמו,\n"
	.string "אז תנס{EMIT_HEY}{ADD_YUD} להתקשר גם אליהם!\p"
	.string "טוב! טוב!\n"
	.string "נראה שאת{EMIT_HEY} די שמח!\p"
	.string "הממ…\n"
	.string "איך אני יכול לדעת את זה?\p"
	.string "זה בגלל שאני מסתכל עליך\n"
	.string "מלמעלה מחלון המשרד שלי!\p"
	.string "וואהאהאהא!\n"
	.string "נתראה שוב!$"

MatchCall_Text_MrStone2::
	.string "מר סטון: אוי? {PLAYER}{KUN}!\p"
	.string "מה לא בסדר? שכחת\n"
	.string "את הסידור הקטן שלי?\p"
	.string "אני צריך שתמסור את המכתב שלי\n"
	.string "לסטיבן בדופורד.\p"
	.string "אחרי זה, תמסור את החבילה שלנו\n"
	.string "לקפטן סטרן בסלייטפורט.\p"
	.string "את{EMIT_HEY} זוכר, נכון?\p"
	.string "עכשיו, מכיוון שאני נשיא עסוק,\n"
	.string "אני חייב ללכת! ביי ביי!$"

MatchCall_Text_MrStone3::
	.string "מר סטון: אוי! {PLAYER}{KUN}!\p"
	.string "אה, אז פגשת את סטיבן!\n"
	.string "מוטב שאגמול לך, אם כן!\p"
	.string "כשתבקר ברסטובור שוב,\n"
	.string "בוא{ADD_YUD} לראות אותי במשרד שלי.\p"
	.string "אני אחכ{EMIT_HEY}{ADD_YUD} לך!$"

MatchCall_Text_MrStone4::
	.string "מר סטון: אוי! {PLAYER}{KUN}!\p"
	.string "ידעת שדבון חפרו\n"
	.string "את מנהרת רסטרף?\p"
	.string "אבל סגרנו את המבצע כדי\n"
	.string "להגן על הפוקימונים באזור.\p"
	.string "זה מובן מאליו, באמת.\p"
	.string "יותר חשוב לתת לפוקימונים\n"
	.string "לחיות בשלווה מאשר לדאוג\l"
	.string "לנוחות שלנו.$"

MatchCall_Text_MrStone5::
	.string "מר סטון: שלום, שלום, {PLAYER}{KUN}!\p"
	.string "שמעתי ממישהו בפטלבורג\n"
	.string "שאת{EMIT_HEY} הילד{ADD_HEY} של נורמן!\p"
	.string "לא פלא שאת{EMIT_HEY} ישות כל כך\n"
	.string "מוכשר{ADD_TAF}!$"

MatchCall_Text_MrStone6::
	.string "מר סטון: מה זה?\p"
	.string "נלחמת באבא שלך ו\n"
	.string "הבסת אותו?\p"
	.string "זה מדהים!\p"
	.string "לא ידעתי שהתיידדתי\n"
	.string "עם מישהו כל כך מיוחד! וואהאהא!$"

MatchCall_Text_MrStone7::
	.string "שלום!\n"
	.string "זה תאגיד דבון…\l"
	.string "אוי, שלום, {PLAYER}!\p"
	.string "הנשיא שלנו היה כאן לפני זמן\n"
	.string "קצר, אבל הוא יצא.\p"
	.string "הנשיא שלנו עסוק, אבל את{EMIT_HEY}\n"
	.string "נראה עסוק לא פחות, {PLAYER}.$"

MatchCall_Text_MrStone8::
	.string "…הא? …מה זה?\p"
	.string "גראו… כן? …דון?\p"
	.string "את{EMIT_HEY} מתנתק…\n"
	.string "…לא שומע…\p"
	.string "בזזזז…$"

MatchCall_Text_MrStone9::
	.string "…הא? …מה זה?\p"
	.string "קרקעית… כן? …מערה…?\p"
	.string "את{EMIT_HEY} מתנתק…\n"
	.string "…לא שומע…\p"
	.string "בזזזז…$"

MatchCall_Text_MrStone10::
	.string "מר סטון: {PLAYER}{KUN}! זה אני!\p"
	.string "כנראה היית מעורב בכל\n"
	.string "מיני דברים, אבל אני, בהיותי עסוק,\l"
	.string "אין לי מושג בדיוק מה!\p"
	.string "עם זאת, אני מפציר בך לקחת\n"
	.string "את הדרך שבה את{EMIT_HEY} מאמין וללכת בה.\p"
	.string "אני תמיד אהיה בפינה שלך!\n"
	.string "שמ{EMIT_VAV}ר{ADD_YUD} על עצמך!$"

MatchCall_Text_MrStone11::
	.string "מר סטון: … … … … … …\n"
	.string "זה אולי {PLAYER}{KUN}?\p"
	.string "הקול שלך כל כך מלא ביטחון,\n"
	.string "שלא זיהיתי אותך מיד!\p"
	.string "הממ! את{EMIT_HEY} חייב{ADD_TAF} לבוא לבקר אותנו\n"
	.string "בדבון מתישהו!$"
