Route102_Text_CalvinIntro:
	.string "אם יש לך פוקימון איתך,\n"
	.string "את{EMIT_HEY} מאמ{SWAP_NUN}{ADD_TAF} פוקימון רשמי{ADD_TAF}!\l"
	.string "לא תוכל{ADD_YUD} לסרב לאתגר שלי!$"

Route102_Text_CalvinDefeated:
	.string "אחח, הפסדתי…\n"
	.string "הייתי צריך לאמן את הפוקימונים שלי יותר…$"

Route102_Text_CalvinPostBattle:
	.string "תקשיב{ADD_YUD} את{EMIT_HEY}, אם את{EMIT_HEY} חזק{ADD_HEY},\n"
	.string "היית צרי{SWAP_CHAF}{ADD_HEY} להגיד לי קודם!$"

Route102_Text_CalvinRegister:
	.string "עבדתי על זה קשה מאז\n"
	.string "שפגשתי אותך קודם.\p"
	.string "אשמח להילחם שוב, אז\n"
	.string "האם תוכל{ADD_YUD} לרשום אותי בפוקינווט שלך?$"

Route102_Text_CalvinRegisterShort:
	.string "אשמח להילחם שוב, אז\n"
	.string "האם תוכל לרשום{ADD_YUD} אותי בפוקינווט שלך?$"

Route102_Text_CalvinRematchIntro:
	.string "מאז שהפסדתי לך, אימנתי את\n"
	.string "הפוקימונים שלי ביתר שאת.\l"
	.string "לא תוכל{ADD_YUD} לסרב לאתגר שלי!$"

Route102_Text_CalvinRematchDefeated:
	.string "אוי, הפסדתי…\n"
	.string "אולי שיטת האימון שלי לא נכונה?$"

Route102_Text_CalvinRematchPostBattle:
	.string "אם את{EMIT_HEY} עומד{ADD_TAF} להתחזק,\n"
	.string "גם אני אתחזק.$"

Route102_Text_AllenIntro:
	.string "האם רק עכשיו הפכת למאמ{SWAP_NUN}{ADD_TAF}?\n"
	.string "אנחנו שנינו מתחילים!$"

Route102_Text_AllenDefeated:
	.string "קראתי לך כי חשבתי\n"
	.string "שאני אצליח להביס אותך…$"

Route102_Text_AllenPostBattle:
	.string "עוד לא ניצחתי פעם אחת…\n"
	.string "הלוואי שאנצח בקרוב…$"

Route102_Text_RickIntro:
	.string "האהא! המבט שלנו נפגש!\n"
	.string "אני אתמודד מולך בעזרת הפוקימון חרק שלי!$"

Route102_Text_RickDefeated:
	.string "אאו! מופל לקרשים!$"

Route102_Text_RickPostBattle:
	.string "כשעיניך ננעלות עם מאמן,\n"
	.string "חייבים לאתגר! זה חוק!$"

Route102_Text_TianaIntro:
	.string "אני הולכת להמשיך לנצח ולשאוף\n"
	.string "להיות המאמנת הטובה ביותר.\p"
	.string "עז{EMIT_VAV}ר{ADD_YUD} לי לקדם את הקריירה שלי!$"

Route102_Text_TianaDefeated:
	.string "בסוף קידמתי את הקריירה שלך…$"

Route102_Text_TianaPostBattle:
	.string "כדי להמשיך לנצח ולהתקדם, אני רואה\n"
	.string "שעלי לתפוס עוד פוקימונים.$"

Route103_Text_DaisyIntro:
	.string "האם הרגשת את משיכת\n"
	.string "הריח המרגיע שלנו?$"

Route103_Text_DaisyDefeated:
	.string "הריח שלנו לא הוביל אותך שולל…$"

Route103_Text_DaisyPostBattle:
	.string "ארומתרפיה היא שיטת ריפוי מנטלית\n"
	.string "העובדת באמצעות ריחות.$"

Route103_Text_AmyIntro:
	.string "איימי: אני איימי.\n"
	.string "וזו אחותי הקטנה ליב.\l"
	.string "אנחנו נלחמות יחד!$"

Route103_Text_AmyDefeated:
	.string "איימי: או או, הפסדנו.$"

Route103_Text_AmyPostBattle:
	.string "איימי: צריך לחשוב על כל מיני דברים\n"
	.string "כשנלחמים נגד שני מאמנים.$"

Route103_Text_AmyNotEnoughPokemon:
	.string "איימי: אופס, יש לך רק פוקימון\n"
	.string "אחד איתך.\l"
	.string "אי אפשר להילחם בנו ככה.$"

Route103_Text_LivIntro:
	.string "ליב: אנחנו נלחמות יחד כצוות אחד.$"

Route103_Text_LivDefeated:
	.string "ליב: או, הפסדנו, אחות גדולה…$"

Route103_Text_LivPostBattle:
	.string "ליב: אנחנו עובדות מושלם יחד,\n"
	.string "אני ואחותי הגדולה…\p"
	.string "אבל בכל זאת הפסדנו…$"

Route103_Text_AmyLivRegister:
	.string "ליב: באמת, אנחנו הרבה יותר טובות…\n"
	.string "זה נכון! נראה לך בפעם הבאה!$"

Route103_Text_LivNotEnoughPokemon:
	.string "ליב: אם את{EMIT_HEY} רוצה להילחם בנו,\n"
	.string "את{EMIT_HEY} חייב{ADD_TAF} שיהיו לך שני פוקימונים!\l"
	.string "זה לא הוגן אם אין!$"

Route103_Text_AmyRematchIntro:
	.string "איימי: אני איימי.\n"
	.string "וזו אחותי הקטנה ליב.\l"
	.string "אנחנו נלחמות יחד!$"

Route103_Text_AmyRematchDefeated:
	.string "איימי: אוי, חבל!\n"
	.string "לא הצלחנו לנצח שוב…$"

Route103_Text_AmyRematchPostBattle:
	.string "איימי: צריך לחשוב על כל מיני דברים\n"
	.string "כשנלחמים נגד שני מאמנים.$"

Route103_Text_AmyRematchNotEnoughPokemon:
	.string "אמי: אופס, יש לך רק פוקימון\n"
	.string "אחד איתך.\l"
	.string "אי אפשר להילחם בנו ככה.$"

Route103_Text_LivRematchIntro:
	.string "ליב: אנחנו נלחמות יחד כצוות אחד.$"

Route103_Text_LivRematchDefeated:
	.string "ליב: אוי, הפסדנו שוב…\n"
	.string "אחות גדולה…$"

Route103_Text_LivRematchPostBattle:
	.string "ליב: אנחנו עובדות מושלם יחד,\n"
	.string "אני ואחותי הגדולה…\p"
	.string "אבל למה הפסדנו שוב?$"

Route103_Text_LivRematchNotEnoughPokemon:
	.string "ליב: אם את{EMIT_HEY} רוצה להילחם בנו,\n"
	.string "את{EMIT_HEY} חייב{ADD_TAF} שיהיו לך שני פוקימונים!\l"
	.string "זה לא הוגן אם אין!$"

Route103_Text_AndrewIntro:
	.string "גאא! חכת הדייג שלי הסתבכה!\n"
	.string "אני מתעצבן ומתאכזר!\l"
	.string "זהו זה! תאתגר{ADD_YUD} אותי!$"

Route103_Text_AndrewDefeated:
	.string "גאא! הפסדתי!\n"
	.string "עכשיו אני אפילו יותר עצבני!$"

Route103_Text_AndrewPostBattle:
	.string "גאא, אני עדיין רותח מזעם…\n"
	.string "גררררר…$"

Route103_Text_MiguelIntro:
	.string "הפוקימון שלי מקסים מתמיד!\n"
	.string "אל תתבייש{ADD_YUD}--אראה לך!$"

Route103_Text_MiguelDefeated:
	.string "או, אלוהים!\n"
	.string "הפוקימון היקר שלי!$"

Route103_Text_MiguelPostBattle:
	.string "הפוקימון החמוד שלי נראה מתוק\n"
	.string "אפילו כשהוא מעולף!$"

Route103_Text_MiguelRegister:
	.string "אני אביא אותך לראות ולהשגיח\n"
	.string "על הפוקימון החמוד שלי שוב!$"

Route103_Text_MiguelRematchIntro:
	.string "היי, את{EMIT_HEY}! הפוקימון החמוד שלי\n"
	.string "נהיה אפילו מקסים יותר!$"

Route103_Text_MiguelRematchDefeated:
	.string "אה!\n"
	.string "הפוקימון היקר שלי!$"

Route103_Text_MiguelRematchPostBattle:
	.string "ככל שאני מבלה איתו יותר,\n"
	.string "הפוקימון שלי נעשה חמוד יותר.$"

Route103_Text_PeteIntro:
	.string "מרחק כזה…\n"
	.string "פשוט תשח{EMIT_HEY}{ADD_YUD} אותו!$"

Route103_Text_PeteDefeated:
	.string "או, כל הכבוד!$"

Route103_Text_PetePostBattle:
	.string "או, עכשיו אני מבין מאיפה את{EMIT_HEY} מגיע{ADD_HEY}.\p"
	.string "אם היה לי פוקימון כזה נאמן,\n"
	.string "גם אני הייתי רוצה לגלוש עליו!$"

Route103_Text_IsabelleIntro:
	.string "שי{SWAP_MEM}{ADD_YUD} לב לאן את{EMIT_HEY} הול{SWAP_CHAF}{ADD_TAF}!\n"
	.string "אנחנו עומדים להתרסק!$"

Route103_Text_IsabelleDefeated:
	.string "אוף…$"

Route103_Text_IsabellePostBattle:
	.string "אני שחיינית רעה אז התאמנתי…\n"
	.string "סליחה שכמעט התנגשתי בך.$"

Route103_Text_RhettIntro:
	.string "וואה!\n"
	.string "איך נכנסת למקום כל כך קטן?$"

Route103_Text_RhettDefeated:
	.string "וואה!\n"
	.string "הילד{ADD_HEY} חזק{ADD_HEY}!$"

Route103_Text_RhettPostBattle:
	.string "את{EMIT_HEY} אוהב{ADD_TAF} מרחבים צפופים\n"
	.string "כמו אלה?$"

Route103_Text_MarcosIntro:
	.string "האם יללת הגיטרה שלי משכה אותך?$"

Route103_Text_MarcosDefeated:
	.string "המופע האישי שלי נהרס…$"

Route103_Text_MarcosPostBattle:
	.string "ניגנתי בגיטרה במקום שבו היו מעט אנשים,\n"
	.string "אבל התקבצו כאן הרבה מעריצים.\l"
	.string "הא, אולי כדאי שאהיה מקצוען.$"

Route104_Text_GinaIntro:
	.string "ג'ינה: אוקיי, בוא{ADD_YUD} נלחם עם הפוקימונים\n"
	.string "שלנו!$"

Route104_Text_GinaDefeat:
	.string "ג'ינה: ההפסד מעציב אותי!$"

Route104_Text_GinaPostBattle:
	.string "ג'ינה: את{EMIT_HEY} חזק{ADD_HEY}!\n"
	.string "עלינו להתאמן הרבה יותר!$"

Route104_Text_GinaNotEnoughMons:
	.string "ג'ינה: אה? רק פוקימון אחד?\n"
	.string "אז, לא נילחם איתך.\p"
	.string "אם יש רק פוקימון אחד, הוא יהיה\n"
	.string "בודד. זה לא נעים.$"

Route104_Text_MiaIntro:
	.string "מיה: אנחנו תאומות, אז אנחנו נלחמות\n"
	.string "בפוקימונים יחד!$"

Route104_Text_MiaDefeat:
	.string "מיה: לחמנו יחד, אבל שנינו\n"
	.string "הפסדנו…$"

Route104_Text_MiaPostBattle:
	.string "מיה: נאמן את הפוקימונים שלנו יותר\n"
	.string "ונהיה חזקים כמוך.$"

Route104_Text_MiaNotEnoughMons:
	.string "מיה: רוצה להילחם איתנו?\p"
	.string "אסור לך אם אין לך שני\n"
	.string "פוקימונים איתך.\l"
	.string "אנחנו חזקים מדי בשבילך!$"

Route104_Text_IvanIntro:
	.string "למה לשמור את זה בסוד?\n"
	.string "אני המומחה לפוקימוני מים!\p"
	.string "הא?\n"
	.string "את{EMIT_HEY} לא מכיר{ADD_HEY} אותי?$"

Route104_Text_IvanDefeat:
	.string "חשבתי שאני לא רע, אם להודות,\n"
	.string "אבל כנראה שלא… בלאא…$"

Route104_Text_IvanPostBattle:
	.string "השתקעתי מדי בדייג.\n"
	.string "שכחתי שעליי לאמן את הפוקימונים שלי…$"

Route104_Text_BillyIntro:
	.string "להשאיר טביעות רגל בחול זה\n"
	.string "ממש כיף!$"

Route104_Text_BillyDefeat:
	.string "וואה! החול נכנס לנעלי הספורט שלי!\n"
	.string "הן כל כך מלאות בחול!$"

Route104_Text_BillyPostBattle:
	.string "אני רוצה להשאיר את טביעות הרגל\n"
	.string "שלי בחול בכל מקום, אבל הן\l"
	.string "נעלמות מהר…$"

Route104_Text_HaleyIntro:
	.string "האם אני צריכה…\n"
	.string "או שלא?\p"
	.string "אוקיי, בטח, אתמודד!$"

Route104_Text_HaleyDefeat:
	.string "לא הייתי צריכה להילחם…$"

Route104_Text_HaleyPostBattle:
	.string "אם את{EMIT_HEY} ניצב{ADD_TAF} בפני החלטה\n"
	.string "ומאפשר{ADD_TAF} למישהו אחר לבחור עבורך,\l"
	.string "תתחרט{ADD_YUD} על התוצאה, לא משנה\l"
	.string "כיצד היא תסתיים.$"

Route104_Text_HaleyRegister1:
	.string "את{EMIT_HEY} חזק{ADD_HEY}, אבל האם עליי\n"
	.string "לרשום אותך בפוקינווט שלי?\l"
	.string "אולי לא כדאי לי…\p"
	.string "טוב, בסדר, ארשום אותך!$"

Route104_Text_HaleyRegister2:
	.string "את{EMIT_HEY} חזק{ADD_HEY}, אבל האם עליי\n"
	.string "לרשום אותך בפוקינווט שלי?\l"
	.string "אולי לא כדאי לי…\p"
	.string "טוב, בסדר, ארשום אותך!$"

Route104_Text_HaleyRematchIntro:
	.string "בוא{ADD_YUD}, תילח{SWAP_MEM}{ADD_YUD} מולי!$"

Route104_Text_HaleyRematchDefeat:
	.string "אחח…\n"
	.string "חשבתי שאוכל לנצח…$"

Route104_Text_HaleyPostRematch:
	.string "החלטתי להילחם, לכן\n"
	.string "אני יכולה לקבל את ההפסד בזכות.\p"
	.string "אבל אני עדיין כועסת על ההפסד!$"

Route104_Text_WinstonIntro:
	.string "או, בסדר, אקבל את האתגר שלך.\n"
	.string "יש לי הרבה כסף.$"

Route104_Text_WinstonDefeat:
	.string "למה לא הצלחתי לנצח?$"

Route104_Text_WinstonPostBattle:
	.string "יש דברים שכסף לא יכול לקנות.\n"
	.string "זה פוקימון…$"

Route104_Text_WinstonRegister1:
	.string "המ?\n"
	.string "אה, קיבלת פוקינווט.\p"
	.string "אשמח לרשום אותך.\n"
	.string "אחרי הכל, יש לי הרבה כסף.$"

Route104_Text_WinstonRegister2:
	.string "המ?\n"
	.string "אה, קיבלת פוקינווט.\p"
	.string "אשמח לרשום אותך.\n"
	.string "אחרי הכל, יש לי הרבה כסף.$"

Route104_Text_WinstonRematchIntro:
	.string "אחרי שהפסדתי לך, למדתי הרבה\n"
	.string "דברים על פוקימונים.$"

Route104_Text_WinstonRematchDefeat:
	.string "הפסדתי שוב?\n"
	.string "למה לא הצלחתי לנצח?$"

Route104_Text_WinstonPostRematch:
	.string "אני עשיר להפליא, אבל\n"
	.string "עדיין לא מצליח לנצח בפוקימון…\p"
	.string "עולם הפוקימונים כל כך עמוק…$"

Route104_Text_CindyIntro:
	.string "כנראה היינו מיועדים להיפגש.\n"
	.string "האם אפשר לבקש ממך קרב?$"

Route104_Text_CindyDefeat:
	.string "אוי, לי!$"

Route104_Text_CindyPostBattle:
	.string "”שלום“ הוא תחילתו של ”להתראות“.\n"
	.string "אני מקווה שניפגש שוב.$"

Route104_Text_CindyRegister1:
	.string "שלום, נפגשנו שוב.\p"
	.string "נראה שאנחנו נמשכים זה לזה.\n"
	.string "בוא{ADD_YUD} נרשום זה את זה בפוקינווט שלנו.$"

Route104_Text_CindyRegister2:
	.string "עלינו לציין כיצד נמשכנו זה לזה.\p"
	.string "בוא{ADD_YUD} נרשום זה את זה בפוקינווט שלנו.$"

Route104_Text_CindyRematchIntro:
	.string "שלום, נפגשנו שוב.\n"
	.string "האם אפשר לבקש ממך קרב?$"

Route104_Text_CindyRematchDefeat:
	.string "אוי, לי…\n"
	.string "עשיתי כמיטב יכולתי…$"

Route104_Text_CindyPostRematch:
	.string "”שלום“ הוא תחילתו של ”להתראות“.\n"
	.string "אני מקווה שניפגש שוב.$"

Route104_Text_DarianIntro:
	.string "דגתי פוקימון שנראה קשוח!\p"
	.string "יש בו איזו תכונה קסומה!\n"
	.string "הוא באמת נראה קשוח, ללא ספק!$"

Route104_Text_DarianDefeat:
	.string "מה זה…$"

Route104_Text_DarianPostBattle:
	.string "היי,{STR_VAR_1}, את{EMIT_HEY} ממש לא עומד\n"
	.string "למצופה משמך, נכון?$"

Route105_Text_FosterIntro:
	.string "נאמר שיש כאן סלע מסתורי\n"
	.string "מסתובב בסביבה.\l"
	.string "את{EMIT_HEY} יודע{ADD_TAF} משהו עליו?$"

Route105_Text_FosterDefeated:
	.string "חשבתי יותר מדי על הסלע הזה\n"
	.string "והפוקימונים שלי נשארו חלשים…$"

Route105_Text_FosterPostBattle:
	.string "אני יכול להעביר שעות על גבי שעות\n"
	.string "בלהביט בסלע יפה בלי להשתעמם.$"

Route105_Text_LuisIntro:
	.string "פיו! חששתי שילד טובע כשראיתי אותך.\p"
	.string "נראה שאת{EMIT_HEY} בסדר, אז מה דעתך\n"
	.string "על קרב?$"

Route105_Text_LuisDefeated:
	.string "גלוב… גלוב…$"

Route105_Text_LuisPostBattle:
	.string "אם את{EMIT_HEY} טובע{ADD_TAF}, האות הוא לנופף\n"
	.string "ביד אחת לכיוון החוף.$"

Route105_Text_DominikIntro:
	.string "השחייה בים הכחול העמוק…\n"
	.string "מרגישה הכי מדהים!$"

Route105_Text_DominikDefeated:
	.string "הפסדתי…\n"
	.string "עכשיו אני מרגיש עצוב…$"

Route105_Text_DominikPostBattle:
	.string "למה הים כחול?\p"
	.string "למדתי על זה במוזיאון בסלייטפורט,\n"
	.string "אבל שכחתי.$"

Route105_Text_BeverlyIntro:
	.string "גופי מרגיש קל יותר במים.\n"
	.string "כאילו שהרזיתי!$"

Route105_Text_BeverlyDefeated:
	.string "אני צף…$"

Route105_Text_PostBattle:
	.string "משקל גופך קטן לעשירית בלבד\n"
	.string "במים.\p"
	.string "זה יהפוך אותי ל…\n"
	.string "אופס! אני לא מגלה את המשקל שלי!$"

Route105_Text_ImaniIntro:
	.string "השמיים הכחולים כחולים…\n"
	.string "הים העצום…\l"
	.string "זה כל כך מרגיע…$"

Route105_Text_ImaniDefeated:
	.string "הפסדתי בזמן שהתבטלתי!$"

Route105_Text_ImaniPostBattle:
	.string "אני רוצה שיגידו שאני נינוחה להיות\n"
	.string "עם. צחקוק.$"

Route105_Text_AndresIntro:
	.string "אני בטוח שהים שומר\n"
	.string "סודות מפנינו.$"

Route105_Text_AndresDefeated:
	.string "כן…\n"
	.string "אני לא טוב בקרבות…$"

Route105_Text_AndresPostBattle:
	.string "אני בטוח שיש הרבה סודות\n"
	.string "לגלות בימים של העולם.\p"
	.string "אני מתכוון למצוא את כולם!$"

Route105_Text_AndresRegister:
	.string "הא? אני כל כך חלש, אבל את{EMIT_HEY} מוכ{SWAP_NUN}{ADD_HEY}\n"
	.string "לרשום אותי בפוקינווט שלך?$"

Route105_Text_AndresRematchIntro:
	.string "אמרתי לך שאני חלש…\n"
	.string "את{EMIT_HEY} בטוח{ADD_HEY} שאת{EMIT_HEY} רוצה לעשות את זה?$"

Route105_Text_AndresRematchDefeated:
	.string "כן…\n"
	.string "לא ציפיתי שאוכל לנצח.$"

Route105_Text_AndresRematchPostBattle:
	.string "אולי אני חלש בקרב, אבל\n"
	.string "הרצון שלי לחקור בלתי נשבר.\p"
	.string "אטייל בימים מסביב לעולם!$"

Route105_Text_JosueIntro:
	.string "אני מותש מהשחייה.\n"
	.string "אני פשוט לא רגיל לזה.\p"
	.string "אני צריך קרב לשינוי הקצב!$"

Route105_Text_JosueDefeated:
	.string "הפסדתי כי נלחמתי בים.$"

Route105_Text_JosuePostBattle:
	.string "כן, בשבילי השמיים הרבה יותר\n"
	.string "מתאימים מהים.$"

Route106_Text_ElliotIntro:
	.string "מה את{EMIT_HEY} מעדיף, לדוג בים\n"
	.string "או בנחל?$"

Route106_Text_ElliotDefeated:
	.string "כמו בדייג ימי עמוק, הפסדתי\n"
	.string "באופן מרהיב!$"

Route106_Text_ElliotPostBattle:
	.string "הדייג הוא נהדר בין אם זה\n"
	.string "בים או בנחל.\l"
	.string "את{EMIT_HEY} מסכי{SWAP_MEM}{ADD_HEY} איתי, נכון?$"

Route106_Text_ElliotRegister:
	.string "הדיHג נהדר, אבל גם הקרב.\n"
	.string "אם אין לך בעיה, נוכל להיפגש שוב?$"

Route106_Text_ElliotRematchIntro:
	.string "תפסתי המון פוקימונים בדיג.\n"
	.string "אראה לך בקרב מרשים!$"

Route106_Text_ElliotRematchDefeated:
	.string "הפסדתי שוב באופן מרהיב!$"

Route106_Text_ElliotRematchPostBattle:
	.string "ניצחון או הפסד, פוקימונים הם הטובים ביותר!\n"
	.string "את{EMIT_HEY} מסכי{SWAP_MEM}{ADD_HEY} איתי, כן?$"

Route106_Text_NedIntro:
	.string "מה עושים אנשים אם הם צריכים\n"
	.string "ללכת לשירותים?\p"
	.string "מה אם החכה שלי תתפוס אחד גדול בזמן\n"
	.string "שהייתי בשירותים? אני פשוט לא יכול…$"

Route106_Text_NedDefeated:
	.string "הפסדתי כי ניסיתי לא ללכת\n"
	.string "לשירותים…$"

Route106_Text_NedPostBattle:
	.string "או, לא! יש לי הרגשה שאני אתפוס\n"
	.string "אחד גדול!$"

Route106_Text_DouglasIntro:
	.string "האהאהא! אני רץ גרוע, אבל במים\n"
	.string "את{EMIT_HEY} לא תוכל{ADD_YUD} לתפוס אותי!$"

Route106_Text_DouglasDefeated:
	.string "אני מוותר!$"

Route106_Text_DouglasPostBattle:
	.string "אני לא הייתי מפסיד בתחרות שחייה…$"

Route106_Text_KylaIntro:
	.string "הים הוא החצר האחורית שלי.\n"
	.string "לא אקל עליך רק כי את{EMIT_HEY} ילד{ADD_HEY}!$"

Route106_Text_KylaDefeated:
	.string "האם הקלת עלי אולי?$"

Route106_Text_KylaPostBattle:
	.string "ההיסחפות עם הגלים…\n"
	.string "אני אוהבת את זה! למה שלא תנס{EMIT_HEY}{ADD_YUD}?$"

Route107_Text_DarrinIntro:
	.string "פיהוק…\p"
	.string "כנראה נרדמתי בזמן שנסחפתי בגלים.$"

Route107_Text_DarrinDefeated:
	.string "אהאהא, הפסדתי…\n"
	.string "אני חושב שאתפוס נמנום עכשיו…$"

Route107_Text_DarrinPostBattle:
	.string "לצוף ולהתנדנד על הגלים--\n"
	.string "זה כמו לישון במיטה רכה\l"
	.string "ונעימה.$"

Route107_Text_TonyIntro:
	.string "הים הוא כמו החצר האחורית שלי.\n"
	.string "בוא{ADD_YUD} נילחם!$"

Route107_Text_TonyDefeated:
	.string "הפסדתי בבית שלי…\n"
	.string "אני בהלם!$"

Route107_Text_TonyPostBattle:
	.string "אני שוחה בימים עם לב מלא\n"
	.string "בחלומות…\p"
	.string "זה כמו שיר!\n"
	.string "בכל מקרה, אני ממשיך לשחות.$"

Route107_Text_TonyRegister:
	.string "הדהמת אותי עד העצמות!\n"
	.string "אז שלא תשכח{ADD_YUD} אותי…$"

Route107_Text_TonyRematchIntro:
	.string "בשחייה בים הרחב והעצום,\n"
	.string "הפוקימונים שלי התחזקו!$"

Route107_Text_TonyRematchDefeated:
	.string "איזו תמיהה!\p"
	.string "הפוקימונים שלי התחזקו, אבל\n"
	.string "אני נשארתי חלש כמאמן!$"

Route107_Text_TonyRematchPostBattle:
	.string "מה שלומדים בקרב הופך אותך\n"
	.string "למאמ{SWAP_NUN}{ADD_TAF} חזק{ADD_HEY} יותר.\l"
	.string "הגלים לימדו אותי את זה.$"

Route107_Text_DeniseIntro:
	.string "האם את{EMIT_HEY} מכיר{ADD_HEY} עיירה קטנה בשם\n"
	.string "דופורד?$"

Route107_Text_DeniseDefeated:
	.string "אני שונאת את זה!$"

Route107_Text_DenisePostBattle:
	.string "אמרה מוזרה הופכת לטרנד\n"
	.string "באולם דופורד.$"

Route107_Text_BethIntro:
	.string "האם רצית להילחם איתי?\n"
	.string "בטח, אני אלך איתך!$"

Route107_Text_BethDefeated:
	.string "לא הייתי מספיק טובה בשבילך.$"

Route107_Text_BethPostBattle:
	.string "אני חושבת שתמשי{SWAP_CHAF}{ADD_YUD} להשתפר.\n"
	.string "גם אני אלך על זה!$"

Route107_Text_LisaIntro:
	.string "ליסה: אנחנו מאתגרות אותך כאחות ואח!$"

Route107_Text_LisaDefeated:
	.string "ליסה: מדהים.\n"
	.string "את{EMIT_HEY} ברמה אחרת של חוזק.$"

Route107_Text_LisaPostBattle:
	.string "ליסה: יש לך חברים שילכו\n"
	.string "לחוף איתך?$"

Route107_Text_LisaNotEnoughPokemon:
	.string "ליסה: אם את{EMIT_HEY} רוצה להילחם איתנו,\n"
	.string "תביא{ADD_YUD} עוד פוקימונים.$"

Route107_Text_RayIntro:
	.string "ריי: אנחנו תמיד נלחמים בפוקימונים,\n"
	.string "אני והאחות שלי.\p"
	.string "אני תמיד מפסיד, אבל אנחנו\n"
	.string "נוכל להביס אותך בקרב 2 נגד 2!$"

Route107_Text_RayDefeated:
	.string "ריי: וואו, את{EMIT_HEY} ברמה גבוהה\n"
	.string "יותר מאיתנו!$"

Route107_Text_RayPostBattle:
	.string "ריי: האחות שלי נתנה לי את הפוקימון שלי.\n"
	.string "גידלתי אותו, ועכשיו הוא\l"
	.string "שותף חשוב שלי!$"

Route107_Text_RayNotEnoughPokemon:
	.string "ריי: אם את{EMIT_HEY} רוצה להילחם איתנו,\n"
	.string "תביא{ADD_YUD} עוד פוקימונים!$"

Route107_Text_CamronIntro:
	.string "אני באמצע טריאתלון,\n"
	.string "אבל אני לא קרוב להתעייף!$"

Route107_Text_CamronDefeated:
	.string "זה התיש אותי…$"

Route107_Text_CamronPostBattle:
	.string "עדיין נשאר לי שחייה וריצה\n"
	.string "לאחר מכן.\p"
	.string "האם אני אסתדר?$"

Route108_Text_JeromeIntro:
	.string "החלום שלי הוא לשחות בשבע מימי\n"
	.string "העולם!$"

Route108_Text_JeromeDefeated:
	.string "לא אצליח לשחות בשבע הימים\n"
	.string "כך…$"

Route108_Text_JeromePostBattle:
	.string "להתעסק עם פוקימוני ים הוא אחד\n"
	.string "מתענוגות השחייה!$"

Route108_Text_MatthewIntro:
	.string "אהוי! גם את{EMIT_HEY} יוצא{ADD_TAF}\n"
	.string "לספינה הנטושה?$"

Route108_Text_MatthewDefeated:
	.string "אני טובע!\n"
	.string "גלוב… גלוב…$"

Route108_Text_MatthewPostBattle:
	.string "יש אנשים שמסתובבים אפילו בתוך\n"
	.string "הספינה הנטושה.$"

Route108_Text_TaraIntro:
	.string "בן הזוג השקרן שלי אמר שאני\n"
	.string "נראית נפלא בביקיני…$"

Route108_Text_TaraDefeated:
	.string "או, בו!$"

Route108_Text_TaraPostBattle:
	.string "אפילו אם זה שקר, אני אוהבת לשמוע\n"
	.string "שאני נראית טוב…\l"
	.string "אנחנו בנות כל כך מורכבות…$"

Route108_Text_MissyIntro:
	.string "אני אוהבת את הים!\n"
	.string "שכחתי מכל הדאגות כשאני שוחה!$"

Route108_Text_MissyDefeated:
	.string "כשאני מפסידה בקרב, אני נלחצת!$"

Route108_Text_MissyPostBattle:
	.string "לשחרר את הלחץ בשחייה!\n"
	.string "זה כל כך בריא!$"

Route108_Text_CoryIntro:
	.string "אני אוהב פוקימוני סוג מים.\n"
	.string "אני אוהב גם פוקימונים אחרים!$"

Route108_Text_CoryDefeated:
	.string "וואאה! הפסדתי!\n"
	.string "וואאה! וואאה!$"

Route108_Text_CoryPostBattle:
	.string "לצעוק עושה לי טוב!\n"
	.string "זה מרומם אותי!$"

Route108_Text_CoryRegister:
	.string "אני אוהב גם מאמנים קשוחים!\n"
	.string "רש{EMIT_VAV}{SWAP_MEM}{ADD_YUD} אותי בפוקינווט שלך!$"

Route108_Text_CoryRematchIntro:
	.string "מנצח או מפסיד, אני אוהב להילחם בים!$"

Route108_Text_CoryRematchDefeated:
	.string "וואאה! הפסדתי שוב!\n"
	.string "וואאה! וואאה!$"

Route108_Text_CoryRematchPostBattle:
	.string "אם את{EMIT_HEY} ניצב{ADD_TAF} בפני אתגר,\n"
	.string "נס{EMIT_HEY}{ADD_YUD} לצעוק לים!$"

Route108_Text_CarolinaIntro:
	.string "אני גאה מאוד בפוקימונים שלי.\n"
	.string "נראה לך קרב אחד מהיר!$"

Route108_Text_CarolinaDefeated:
	.string "זה לא היה חמוד בכלל.$"

Route108_Text_CarolinaPostBattle:
	.string "מכיוון שאני בים ככה, לא אכפת לי\n"
	.string "ללבוש בגד ים ורוד מגונדר…$"

Route109_Text_DavidIntro:
	.string "הייא! תסתכל{ADD_YUD} על השרירים החטובים שלי!\n"
	.string "זה מה שקוראים לו ”חתיך“!$"

Route109_Text_DavidDefeated:
	.string "איהא!\n"
	.string "נכשלתי!$"

Route109_Text_DavidPostBattle:
	.string "הייא!\p"
	.string "השרירים החטובים שלי לא קשורים\n"
	.string "לקרבות פוקימון!$"

Route109_Text_AliceIntro:
	.string "האם את{EMIT_HEY} מוג{SWAP_NUN}{ADD_TAF} כראוי מפני השמש?$"

Route109_Text_AliceDefeated:
	.string "אאוץ', אאוץ', אאוץ'!$"

Route109_Text_AlicePostBattle:
	.string "הלחיים נוטות להישרף הכי הרבה!$"

Route109_Text_HueyIntro:
	.string "עגנתי בנמלים מסביב לעולם,\n"
	.string "אבל סלייטפורט היא הטובה ביותר.$"

Route109_Text_HueyDefeated:
	.string "את{EMIT_HEY} הכי טוב{ADD_HEY}!$"

Route109_Text_HueyPostBattle:
	.string "בנמל הטוב ביותר נמצא המאמ{SWAP_NUN}{ADD_TAF}\n"
	.string "הטוב{ADD_HEY} ביותר…$"

Route109_Text_EdmondIntro:
	.string "אורררפפפ…\n"
	.string "קרב? איתי?$"

Route109_Text_EdmondDefeated:
	.string "אורפ… אווווו…\n"
	.string "אורררפפפ…$"

Route109_Text_EdmondPostBattle:
	.string "בדרך כלל אני חזק יותר מזה!\n"
	.string "אני רק חולה ים כמו כלב!\p"
	.string "אני מלח, אבל…$"

Route109_Text_RickyIntro:
	.string "אני צמא… יכול להתאים לי סודה\n"
	.string "בבית החוף…$"

Route109_Text_RickyDefeated:
	.string "אנקה…$"

Route109_Text_RickyPostBattle:
	.string "אני משתוקק לאוכל… האבוב שחייה\n"
	.string "שלי נראה כמו סופגניה ענקית…$"

Route109_Text_RickyRegister:
	.string "תעש{EMIT_HEY}{ADD_YUD} עוד קרב איתי\n"
	.string "כשלא אהיה כולי צמא?$"

Route109_Text_RickyRematchIntro:
	.string "אני רעב, אבל יש לי מספיק אנרגיה\n"
	.string "לקרב!$"

Route109_Text_RickyRematchDefeated:
	.string "הפסדתי…\n"
	.string "זה כי אני רעב…$"

Route109_Text_RickyRematchPostBattle:
	.string "כשאוכלים בחוף, הכל נראה\n"
	.string "טעים קצת יותר.$"

Route109_Text_LolaIntro:
	.string "האם שמשיה בחוף לא נראית\n"
	.string "כמו פרח ענק?$"

Route109_Text_LolaDefeated:
	.string "אמא!$"

Route109_Text_LolaPostBattle:
	.string "אם מסתכלים על החוף מהשמיים,\n"
	.string "הוא נראה כמו גן פרחים ענק!$"

Route109_Text_LolaRegister:
	.string "אני?\n"
	.string "אני פה כל יום!$"

Route109_Text_LolaRematchIntro:
	.string "אני לא אפסיד לך שוב!\n"
	.string "לכן יש לי את אבוב השחייה שלי!$"

Route109_Text_LolaRematchDefeated:
	.string "אמא!$"

Route109_Text_LolaRematchPostBattle:
	.string "אם יש לי אבוב שחייה, אני\n"
	.string "והפוקימונים שלי הופכים לחמודים יותר!$"

Route109_Text_AustinaIntro:
	.string "אני לא יכולה לשחות בלי אבוב השחייה,\n"
	.string "אבל לא אפסיד בפוקימון!$"

Route109_Text_AustinaDefeated:
	.string "האם הפסדתי בגלל שיש לי אבוב\n"
	.string "שחייה?$"

Route109_Text_AustinaPostBattle:
	.string "אבוב השחייה שלי הוא פריט אופנה.\n"
	.string "אני לא יכולה להיראות בלעדיו.$"

Route109_Text_GwenIntro:
	.string "היי, מאמ{SWAP_NUN}{ADD_TAF} גדול{ADD_HEY}.\n"
	.string "תרצ{EMIT_HEY}{ADD_YUD} להילחם מולי?$"

Route109_Text_GwenDefeated:
	.string "או, את{EMIT_HEY} חזק{ADD_HEY}.$"

Route109_Text_GwenPostBattle:
	.string "איך הגעת להיות כל כך חזק{ADD_HEY}?$"

Route109_Text_CarterIntro:
	.string "ואהאהאה! הבחור הזה הולך לתפוס אחד\n"
	.string "גדול לעצמו!$"

Route109_Text_CarterDefeated:
	.string "הבחור הזה בדיוק הפסיד אחד…$"

Route109_Text_CarterPostBattle:
	.string "הבחור הזה חושב שאת{EMIT_HEY} גדול{ADD_HEY}.\n"
	.string "לא, את{EMIT_HEY} תהי{EMIT_HEY}{ADD_YUD} גדול{ADD_HEY}!$"

Route109_Text_PaulIntro:
	.string "פול: טוב, זה הורס את האווירה.\p"
	.string "הלוואי שלא תפריע לזמן היקר\n"
	.string "שאנחנו מקדישים זה לזה.$"

Route109_Text_PaulDefeated:
	.string "פול: ובכן, אני מוותר.$"

Route109_Text_PaulPostBattle:
	.string "פול: ובכן, אל תגיד{ADD_YUD} לאיש שאנחנו כאן.\l"
	.string "זה רק העולם הפרטי שלנו לזוג!$"

Route109_Text_PaulNotEnoughPokemon:
	.string "פול: אנחנו מאוהבים עד השמיים.\n"
	.string "לכן הפוקימונים שלנו נלחמים\l"
	.string "יחד.$"

Route109_Text_MelIntro:
	.string "מל: אנחנו, כאילו, לגמרי מאוהבים.\n"
	.string "הרומנטיקה שלנו מדליקה את כל הואן!$"

Route109_Text_MelDefeated:
	.string "מל: הפסדנו, וזה באשמתי!\n"
	.string "פול ישנא אותי!$"

Route109_Text_MelPostBattle:
	.string "מל: אמ, פול, האם את{EMIT_HEY} כועס עלי?\n"
	.string "בבקשה אל תהיה כועס.$"

Route109_Text_MelNotEnoughPokemon:
	.string "מל: אנחנו באמת מאוד מאוהבים.\n"
	.string "לכן הפוקימונים שלנו נלחמים\l"
	.string "יחד.$"

Route109_Text_ChandlerIntro:
	.string "טאדאה! רואה?\n"
	.string "אבוב השחייה שלי עגול!$"

Route109_Text_ChandlerDefeated:
	.string "או, או!\n"
	.string "איזה חבל!$"

Route109_Text_ChandlerPostBattle:
	.string "גם אחרי שהראיתי לך את האבוב\n"
	.string "העגול שלי…$"

Route109_Text_HaileyIntro:
	.string "אני לא יודעת לשחות, אז אני מעמידה\n"
	.string "פנים שאני שוחה.$"

Route109_Text_HaileyDefeated:
	.string "חשבתי כך!\n"
	.string "לא חשבתי שנצליח לנצח.$"

Route109_Text_HaileyPostBattle:
	.string "כשאלמד לשחות, אני חושבת\n"
	.string "שהפוקימונים שלי יהפכו לחזקים יותר.$"

Route109_Text_ElijahIntro:
	.string "לחסון כמוני, סוג כזה של\n"
	.string "פוקימון הוא התאמה מושלמת!$"

Route109_Text_ElijahDefeated:
	.string "אני מגניב גם בהפסד, היי?$"

Route109_Text_ElijahPostBattle:
	.string "לחסון כמוני, נמל הוא המקום המושלם!\p"
	.string "נראה שאלך לסלייטפורט.$"

Route110_Text_JacobIntro:
	.string "וואו! תיזהר{ADD_YUD}!\n"
	.string "נראה שאינך רגיל למירוצי אופניים.$"

Route110_Text_JacobDefeated:
	.string "וואה!\n"
	.string "הבלמים שלי נכשלו!$"

Route110_Text_JacobPostBattle:
	.string "תקר בגלגל או בעיות בבלמים\n"
	.string "יכולות לגרום לפציעה קשה!\l"
	.string "בד{EMIT_VAV}ק{ADD_YUD} את האופניים שלך מבעיות!$"

Route110_Text_AnthonyIntro:
	.string "יו, את{EMIT_HEY}!\n"
	.string "את{EMIT_HEY} יכול{ADD_HEY} לעמוד בקצב המהירות שלי?$"

Route110_Text_AnthonyDefeated:
	.string "התנגשות והתפוצצות!$"

Route110_Text_AnthonyPostBattle:
	.string "המהירות לבדה לא תספיק לנצח בפוקימון.\n"
	.string "אני צריך לשקול את זה מחדש…$"

Route110_Text_BenjaminIntro:
	.string "אל תבהל{ADD_YUD} אם האופניים שלך נוסעים מהר!$"

Route110_Text_BenjaminDefeated:
	.string "לא הייתי צריך להבהל בקרבות\n"
	.string "פוקימון…$"

Route110_Text_BenjaminPostBattle:
	.string "אין צורך להבהל או להילחץ.\n"
	.string "תירגע{ADD_YUD}. יש מספיק זמן.$"

Route110_Text_BenjaminRegister:
	.string "אמשיך קדימה בלי לדאוג.\n"
	.string "תגיד לי אם תרצה קרב נוסף.$"

Route110_Text_BenjaminRematchIntro:
	.string "האם את{EMIT_HEY} לא קצת מהיר{ADD_HEY} מדי?\n"
	.string "תירגע{ADD_YUD} ובוא{ADD_YUD} נילחם.$"

Route110_Text_BenjaminRematchDefeated:
	.string "לא נכנסתי לפאניקה, אבל עדיין הפסדתי…$"

Route110_Text_BenjaminRematchPostBattle:
	.string "אין צורך להיבהל או להילחץ.\n"
	.string "תירגע{ADD_YUD}. יש מספיק זמן.$"

Route110_Text_AbigailIntro:
	.string "הטריאתלון קשה עד הקצה.\p"
	.string "עליך להשלים את שלושת האירועים של\n"
	.string "שחייה, רכיבה וריצה.$"

Route110_Text_AbigailDefeated:
	.string "גם קרבות פוקימון קשים!$"

Route110_Text_AbigailPostBattle:
	.string "אני מותשת, אני צריכה הפסקה.\n"
	.string "חשוב לנוח כראוי.$"

Route110_Text_AbigailRegister:
	.string "את{EMIT_HEY} יודע{ADD_TAF}, אני מחבבת אותך!\n"
	.string "בוא{ADD_YUD} נעשה קרב חוזר בשביל האופניים.$"

Route110_Text_AbigailRematchIntro:
	.string "זה לא מגניב לקיים קרב בזמן\n"
	.string "רכיבה? $"

Route110_Text_AbigailRematchDefeated:
	.string "ואו…\n"
	.string "איך יכול להיות שאת{EMIT_HEY} כל כך חזק{ADD_HEY}?$"

Route110_Text_AbigailRematchPostBattle:
	.string "האם ניסית לשבור שיא?\p"
	.string "סליחה אם עצרתי אותך!$"

Route110_Text_JasmineIntro:
	.string "רכבתי ללא הפסקה.\n"
	.string "ירכיי קשים כמו סלעים!$"

Route110_Text_JasmineDefeated:
	.string "אני דואגת לכיווצי שרירים…$"

Route110_Text_JasminePostBattle:
	.string "אה, יש לך כמה תגי מכונים?\n"
	.string "לא פלא שאת{EMIT_HEY} כל כך חזק{ADD_HEY}!$"

Route110_Text_EdwardIntro:
	.string "חזיתי בכוונות שלך!\n"
	.string "איני יכול להפסיד!$"

Route110_Text_EdwardDefeated:
	.string "לא חזיתי את סוף דרכי!$"

Route110_Text_EdwardPostBattle:
	.string "אני רואה את עתידך…\p"
	.string "הממ…\n"
	.string "אני רואה אור קורן…$"

Route110_Text_JaclynIntro:
	.string "אהאהאהא!\n"
	.string "אפיל אותך בפלאיי!$"

Route110_Text_JaclynDefeated:
	.string "הפסדתי באופן פלאי!$"

Route110_Text_JaclynPostBattle:
	.string "הצלחת לנצח רק כי זה היה\n"
	.string "פלא! כן, פלא!\l"
	.string "אל תחש{EMIT_VAV}ב{ADD_YUD} שתוכל{ADD_YUD} לנצח כל הזמן!$"

Route110_Text_EdwinIntro:
	.string "האם אוכל לראות את הפוקימונים שלך?\n"
	.string "רק מבט אחד, בבקשה?$"

Route110_Text_EdwinDefeated:
	.string "רציתי להשלים\n"
	.string "את האוסף שלי…$"

Route110_Text_EdwinPostBattle:
	.string "כשאני רואה פוקימון שאני לא מכיר,\n"
	.string "התשוקה שלי כאספן מתעוררת!$"

Route110_Text_EdwinRegister:
	.string "אני אוהב לאסוף גם\n"
	.string "רשומות של שיחת קרב…$"

Route110_Text_EdwinRematchIntro:
	.string "היי, תפסת פוקימונים חדשים?\p"
	.string "האם אוכל לראות את הפוקימונים שלך?\n"
	.string "רק מבט אחד, בבקשה?$"

Route110_Text_EdwinRematchDefeated:
	.string "הפוקימונים שלך…\n"
	.string "אני מקנא בך.$"

Route110_Text_EdwinRematchPostBattle:
	.string "אה, אני משתוקק שכל הפוקימונים\n"
	.string "הנדירים יהיו שלי!$"

Route110_Text_DaleIntro:
	.string "היי!\n"
	.string "אל תתגנב{ADD_YUD} אליי מאחורה ככה!$"

Route110_Text_DaleDefeated:
	.string "הפסדתי!\n"
	.string "חבל!$"

Route110_Text_DalePostBattle:
	.string "הדיג הוא עניין של ריכוז.\n"
	.string "עליך להתרכז במצוף!$"

Route110_Text_IsabelIntro:
	.string "אהאהא! אלך לכל מקום כדי להראות\n"
	.string "את הפוקימונים המתוקים שלי.$"

Route110_Text_IsabelDefeated:
	.string "או, יקיר{ADD_TAF}י, זה לא מסתדר.$"

Route110_Text_IsabelPostBattle:
	.string "במקום להילחם, אולי אציג את\n"
	.string "הפוקימונים שלי במועדון המעריצים.$"

Route110_Text_IsabelRegister:
	.string "זה כלל לא היה ההצגה המלאה של\n"
	.string "הפוקימונים שלי.\p"
	.string "אהפוך אותך לקהל שבוי שלי\n"
	.string "לעיתים קרובות ככל האפשר!$"

Route110_Text_IsabelRematchIntro:
	.string "אהאהאהא! אשמח להראות את הפוקימונים\n"
	.string "שלי כל פעם שתרצ{EMIT_HEY}{ADD_YUD}!$"

Route110_Text_IsabelRematchDefeated:
	.string "או, יקיר{ADD_TAF}י, זה לא מסתדר.$"

Route110_Text_IsabelRematchPostBattle:
	.string "אני לא חושבת שאוכל להפסיק\n"
	.string "להציג את הפוקימונים שלי.\p"
	.string "אבל גם אני אוהבת להילחם!$"

Route110_Text_TimmyIntro:
	.string "מצאתי כמה פוקימונים מגניבים בדשא\n"
	.string "כאן בסביבה!$"

Route110_Text_TimmyDefeated:
	.string "להיות מגניב לא מספיק כדי לנצח…$"

Route110_Text_TimmyPostBattle:
	.string "קשה להילחם עם פוקימונים שתפסת\n"
	.string "הרגע.$"

Route110_Text_AlyssaIntro:
	.string "נפלתי משביל האופניים…\p"
	.string "אתגבר על המבוכה שלי באמצעות\n"
	.string "קרב מולך!$"

Route110_Text_AlyssaDefeated:
	.string "אופס!\n"
	.string "בסופו של דבר הפסדתי!$"

Route110_Text_AlyssaPostBattle:
	.string "נפילה… הפסד…\n"
	.string "זה כל-כך מביש עבורי!$"

Route110_Text_JosephIntro:
	.string "בסדר! עכשיו במלוא העוצמה! אם את{EMIT_HEY} לא\n"
	.string "נכנס{ADD_TAF} לקצב, את{EMIT_HEY} נשאר{ADD_TAF} מאחור!$"

Route110_Text_JosephDefeated:
	.string "הצלחת באמת להיכנס לקצב…$"

Route110_Text_JosephPostBattle:
	.string "זה לא ישפיל אותי!\n"
	.string "ההפסד עשה אותי לאדם טוב יותר!$"

Route110_Text_KalebIntro:
	.string "כשפוקימונים חמודים עוזרים זה לזה…\n"
	.string "לא תרא{EMIT_HEY}{ADD_YUD} מראה חמוד יותר מזה!$"

Route110_Text_KalebDefeated:
	.string "האם אין בך חמלה או רחמים?$"

Route110_Text_KalebPostBattle:
	.string "אוקיי, אוקיי, עשיתם כמיטב יכולתכם,\n"
	.string "יפים שלי.$"

Route111_Text_DrewIntro:
	.string "או, היי! המשקפי מגן האלה מתאימים לך.\n"
	.string "אבל אני חושב שהם נראים טוב יותר עליי.\p"
	.string "בוא{ADD_YUD} נחליט מי נראה איתם טוב יותר\n"
	.string "עם קרב!$"

Route111_Text_DrewDefeat:
	.string "לא הצלחתי לראות מה קורה בצדדים שלי\n"
	.string "בגלל המשקפי מגן.$"

Route111_Text_DrewPostBattle:
	.string "המשקפי מגן מאפשרים לעבור דרך סופות חול.\l"
	.string "זה משמח אותי!$"

Route111_Text_HeidiIntro:
	.string "אני עושה פיקניק במדבר.\p"
	.string "אפשר תמיד למצוא מאמן,\n"
	.string "אז גם כאן אפשר להנות מקרב!$"

Route111_Text_HeidiDefeat:
	.string "אוו! את{EMIT_HEY} מרושע{ADD_TAF}!$"

Route111_Text_HeidiPostBattle:
	.string "כשנלחמים בסופת חול,\n"
	.string "שימו לב לנח של הפוקימונים שלכם.\p"
	.string "הם עלולים ליפול אם לא תשימו\n"
	.string "לב אליהם!$"

Route111_Text_BeauIntro:
	.string "להיות עם משקפי מגן גורם לי להרגיש כמו גיבור-על.\l"
	.string "כרגע, אף אחד לא יכול להביס אותי!$"

Route111_Text_BeauDefeat:
	.string "אני לא יכול לנצח רק ברוחי…$"

Route111_Text_BeauPostBattle:
	.string "יום אחד אהיה גיבור אמיתי.\n"
	.string "אעבוד יותר קשה כדי לחזק את עצמי\l"
	.string "ואת הפוקימונים שלי.$"

Route111_Text_BeckyIntro:
	.string "שמעתי שיש מאובנים שנית{SWAP_NUN}{ADD_YUD} למצוא\n"
	.string "במדבר. איפה הם יכולים להיות?$"

Route111_Text_BeckyDefeat:
	.string "לא הצלחתי…$"

Route111_Text_BeckyPostBattle:
	.string "אם אפשר למצוא מאובנים במדבר,\n"
	.string "זה בוודאי היה פעם ים.$"

Route111_Text_DustyIntro:
	.string "חיפשתי חורבות עתיקות במשך שלושים שנה!\l"
	.string "האם עומדים לאתגר אותי?$"

Route111_Text_DustyDefeat:
	.string "בעודי חיפשתי חורבות,\n"
	.string "לא חיפשתי אחרי פוקימונים חזקים.$"

Route111_Text_DustyPostBattle:
	.string "חיפשתי חורבות עתיקות במשך שלושים שנה!\p"
	.string "לא, רגע, האם זה היה ארבעים שנה?\n"
	.string "כמה זה היה עכשיו?$"

Route111_Text_DustyRegister:
	.string "לא חיפשתי אחר פוקימונים חזקים.\p"
	.string "אבל, מסיבה כלשהי, אני ממש אוהב\n"
	.string "את הפוקינווט.$"

Route111_Text_DustyRematchIntro:
	.string "חיפשתי חורבות עתיקות במשך שלושים שנה!\p"
	.string "לא, רגע, האם זה היה ארבעים שנה?\n"
	.string "בכל מקרה, האם עומדים לאתגר אותי?$"

Route111_Text_DustyRematchDefeat:
	.string "לא מצאתי חורבות, וגם לא מצאתי\n"
	.string "פוקימונים חזקים…$"

Route111_Text_DustyPostRematch:
	.string "חיפשתי חורבות עתיקות במשך שלושים שנה!\p"
	.string "לא, רגע, האם חיפשתי ארבעים שנה?\p"
	.string "הממ… אולי אפילו חמישים…\n"
	.string "כמה זמן אני כבר עושה זאת?$"

Route111_Text_TravisIntro:
	.string "אני מלא באנרגיה!\n"
	.string "והפוקימונים שלי מלאי אנרגיה גם הם!$"

Route111_Text_TravisDefeat:
	.string "הפוקימונים שלי איבדו\n"
	.string "את האנרגיה שלהם…$"

Route111_Text_TravisPostBattle:
	.string "כשאני רואה מאמ{SWAP_NUN}{ADD_TAF} עם הרבה אנרגיה,,\n"
	.string "אני לא יכול שלא להסתכל.$"

Route111_Text_IreneIntro:
	.string "אני לא יודעת לאן את{EMIT_HEY} הול{SWAP_CHAF}{ADD_TAF},\n"
	.string "אבל את{EMIT_HEY} רוצה קרב?$"

Route111_Text_IreneDefeat:
	.string "או, את{EMIT_HEY} טוב{ADD_HEY} בצורה מגעילה!$"

Route111_Text_IrenePostBattle:
	.string "אני חושבת שאולי עליי לעלות\n"
	.string "להר הארובה, אבל הנוף כאן\l"
	.string "גם נחמד מאוד.$"

Route111_Text_DaisukeIntro:
	.string "כדי להתאמן, אני מאתגר את כל\n"
	.string "מי שאני פוגש!$"

Route111_Text_DaisukeDefeat:
	.string "דוד! אני מודה בהפסד!$"

Route111_Text_DaisukePostBattle:
	.string "כל שנשאר לי הוא להמשיך להתאמן עד\n"
	.string "שאני אוכל להביס מאמנים חזקים\l"
	.string "כמוך.$"

Route111_Text_WiltonIntro:
	.string "הרא{EMIT_HEY}{ADD_YUD} לי כמה חיזקת את\n"
	.string "הפוקימונים שלך.$"

Route111_Text_WiltonDefeat:
	.string "רואה, חיזקת אותם\n"
	.string "באופן ניכר.$"

Route111_Text_WiltonPostBattle:
	.string "פוקימונים ומאמנים לומדים המון\n"
	.string "מקרבות.\p"
	.string "החשוב הוא לא לוותר אף פעם,\n"
	.string "גם אם תפסיד{ADD_YUD}.$"

Route111_Text_WiltonRegister:
	.string "יש הרבה מה ללמוד מסגנון\n"
	.string "האימון שלך.\p"
	.string "אבקש קרב חוזר אם זה\n"
	.string "נשמע לך מתאים.$"

Route111_Text_WiltonRematchIntro:
	.string "אנחנו מתאמנים כאן כדי לקחת את\n"
	.string "הרמה שלנו לשלב הבא.\l"
	.string "הישאר{ADD_YUD} והתאמ{SWAP_NUN}{ADD_YUD} איתנו!$"

Route111_Text_WiltonRematchDefeat:
	.string "אוו, את{EMIT_HEY} די טוב{ADD_HEY}!$"

Route111_Text_WiltonPostRematch:
	.string "מכיוון שאת{EMIT_HEY} כל כך חזק{ADD_HEY}, עליך\n"
	.string "לשאוף לליגת הפוקימונים.$"

Route111_Text_BrookeIntro:
	.string "או, הפוקימונים שלך נראים כמו\n"
	.string "שחקנים רציניים.\l"
	.string "אני חייבת לבקש ממך קרב!$"

Route111_Text_BrookeDefeat:
	.string "הם לא רק נראו חזקים,\n"
	.string "הם באמת חזקים!$"

Route111_Text_BrookePostBattle:
	.string "חשבתי שאני מגדלת את הפוקימונים\n"
	.string "בשקידה, אבל, אוי, יש עוד הרבה\l"
	.string "לעשות.$"

Route111_Text_BrookeRegister:
	.string "הלוואי והייתי יכולה להיות חברה\n"
	.string "של עוד אנשים חזקים כמוך!$"

Route111_Text_BrookeRematchIntro:
	.string "את{EMIT_HEY} יכול{ADD_HEY} לחזק או להחליש פוקימונים\n"
	.string "תלוי במהלכים שאת{EMIT_HEY} מלמד{ADD_TAF} אותם.\p"
	.string "אילו סוגי מהלכים הפוקימונים שלך\n"
	.string "יודעים?$"

Route111_Text_BrookeRematchDefeat:
	.string "לימדת אותם מהלכים טובים!$"

Route111_Text_BrookePostRematch:
	.string "אולי היה עליי לעצור את\n"
	.string "התפתחות הפוקימונים שלי עד שהם\l"
	.string "ילמדו מהלכים טובים יותר…$"

Route111_Text_CeliaIntro:
	.string "לא הייתי צריכה להגיע למקום כזה\n"
	.string "על מנת לערוך פיקניק!$"

Route111_Text_CeliaDefeat:
	.string "אוו!\n"
	.string "באמת שלא הייתי צריכה להגיע!$"

Route111_Text_CeliaPostBattle:
	.string "בסופת חול כזו, אני לא יכולה להכין\n"
	.string "את המקום לפיקניק אפילו עם המשקפי\l"
	.string "מיגון שלי…$"

Route111_Text_BryanIntro:
	.string "כמה את{EMIT_HEY} חזק{ADD_HEY}?\n"
	.string "נגלה את הסוד הזה!$"

Route111_Text_BryanDefeat:
	.string "או! העוצמה שלך!\n"
	.string "היא עטופה מסתורין!$"

Route111_Text_BryanPostBattle:
	.string "המדבר הזה מכיל מסתורין בחול\n"
	.string "הנודד שלו!$"

Route111_Text_BrandenIntro:
	.string "את{SWAP_NUN}{ADD_YUD} לך קצת מהכריך שלי\n"
	.string "אם תפסיד{ADD_YUD}.$"

Route111_Text_BrandenDefeat:
	.string "טח! חשבתי שכריך יספיק כשוחד…$"

Route111_Text_BrandenPostBattle:
	.string "ה{STR_VAR_1} שלי אוהב לאכול\n"
	.string "את הכריכים שלי.$"

Route111_Text_TyronIntro:
	.string "זהו סוג הפוקימון האהוב עליי!$"

Route111_Text_TyronDefeat:
	.string "חכ{EMIT_HEY}{ADD_YUD}!\n"
	.string "הסתכלת טוב על הפוקימונים שלי?$"

Route111_Text_TyronPostBattle:
	.string "כשאני נלחם, אני נהנה להציג\n"
	.string "את הפוקימונים שלי.\p"
	.string "אני מניח שכל אחד מרגיש ככה כשהוא\n"
	.string "נכנס לקרב!$"

Route111_Text_CelinaIntro:
	.string "הרא{EMIT_HEY}{ADD_YUD} לי איך להכניס קצת ריגוש\n"
	.string "לחיי.$"

Route111_Text_CelinaDefeat:
	.string "אוי… לי…\n"
	.string "זה היה יותר מדי מרגש.$"

Route111_Text_CelinaPostBattle:
	.string "הדופק שלי עדיין גבוה.\n"
	.string "את{EMIT_HEY} מאמ{SWAP_NUN}{ADD_TAF} נהדר{ADD_TAF}.$"

Route111_Text_HaydenIntro:
	.string "כשאת{EMIT_HEY} רעב{ADD_HEY} כמוני,\n"
	.string "אין מקום לרחמים!$"

Route111_Text_HaydenDefeat:
	.string "אנקה…$"

Route111_Text_HaydenPostBattle:
	.string "הבטן שלי מקרקרת!\n"
	.string "אולי אצליח לצלות קצת פירות יער…$"

Route111_Text_BiancaIntro:
	.string "האם הגעת ממוויל?\n"
	.string "אז את{EMIT_HEY} בטח מלא{ADD_HEY} אנרגיה!$"

Route111_Text_BiancaDefeat:
	.string "אוו לה לה!\n"
	.string "זה היה הרבה לעכל!$"

Route111_Text_BiancaPostBattle:
	.string "הדרך הזו…\n"
	.string "עוד יש לך דרך ארוכה למסע.$"

Route112_Text_BriceIntro:
	.string "האהאהאהא!\n"
	.string "מה דעתך על קרב?\l"
	.string "אני ואת{EMIT_HEY}!\l"
	.string "האהאהאהא!$"

Route112_Text_BriceDefeat:
	.string "הפסדתי!\n"
	.string "האהאהאהא!$"

Route112_Text_BricePostBattle:
	.string "האהאהאהא! משהו נשאב לי לאף!\n"
	.string "האהאהאהא-הצ'ו!$"

Route112_Text_TrentIntro:
	.string "הרגליים שלי חזקות מההליכות\n"
	.string "בהרים.\p"
	.string "הן לא יתעייפו בקלות, חבר{ADD_HEY}!$"

Route112_Text_TrentDefeat:
	.string "אאוץ'! הרגליים שלי התכווצו!$"

Route112_Text_TrentPostBattle:
	.string "נס{EMIT_HEY}{ADD_YUD} לטייל בשבילי ההר האלו, ואני מתכוון\n"
	.string "לצעוד חזק עם תרמיל כבד ששוקל\l"
	.string "עשרות קילו.\p"
	.string "זה, חבר{ADD_TAF}י, יכניס את הגוף שלך\n"
	.string "למבנה רציני.$"

Route112_Text_TrentRegister:
	.string "אאו, הרגליים שלי התכווצו.\n"
	.string "תוכל{ADD_YUD} לשלוף לי תחבושות מהתרמיל שלי?\p"
	.string "לא, זה הפוקינווט שלי!\n"
	.string "טוב, נו, אז ארשום אותך.$"

Route112_Text_TrentRematchIntro:
	.string "שמרתי על כושר על ידי טיולים.\n"
	.string "כוח יש לי בשפע!$"

Route112_Text_TrentRematchDefeat:
	.string "הפסדתי בכוח?$"

Route112_Text_TrentRematchPostBattle:
	.string "שמעתי שיש מאמנים חזקים באמת\n"
	.string "על פסגת הר הארובה.\p"
	.string "אני מתכוון לעלות לשם ולאתגר\n"
	.string "אותם!$"

Route112_Text_LarryIntro:
	.string "אני חזק.\n"
	.string "אני לא אבכה אם אפסיד.$"

Route112_Text_LarryDefeat:
	.string "וואאאאה!$"

Route112_Text_LarryPostBattle:
	.string "אני לא בוכה כי אני מתגעגע לאמא!\n"
	.string "בכי…$"

Route112_Text_CarolIntro:
	.string "כשאת{EMIT_HEY} בפיקניק, את{EMIT_HEY} פשוט חייב{ADD_TAF} לשיר!\l"
	.string "בוא{ADD_YUD}, שיר{ADD_YUD} איתי!$"

Route112_Text_CarolDefeat:
	.string "או, את{EMIT_HEY} כל כך חזק{ADD_HEY}!$"

Route112_Text_CarolPostBattle:
	.string "לא משנה אם את{EMIT_HEY} טוב{ADD_HEY} או רע{ADD_HEY}\n"
	.string "בשירה או בקרבות.\p"
	.string "אם את{EMIT_HEY} הכי נהנ{EMIT_HEY}{ADD_TAF}, את{EMIT_HEY} המנצח{ADD_TAF}!$"

Route112_Text_BryantIntro:
	.string "תפסתי פוקימונים חמים במעבר הלוהט!\n"
	.string "תרא{EMIT_HEY}{ADD_YUD}!$"

Route112_Text_BryantDefeat:
	.string "איזה רכיבה קופצנית זאת הייתה!$"

Route112_Text_BryantPostBattle:
	.string "אני אוהב את סגנון הקרב שלך.\n"
	.string "יש בו משהו אופייני וייחודי.$"

Route112_Text_ShaylaIntro:
	.string "או, האם אינך מאמ{SWAP_NUN}{ADD_TAF} חמוד{ADD_HEY}!\n"
	.string "בבקשה, אני רוצה קרב רומנטי!\l"
	.string "אני די טובה!$"

Route112_Text_ShaylaDefeat:
	.string "או, כמה את{EMIT_HEY} חזק{ADD_HEY}!\n"
	.string "נתת לי הלם רציני!$"

Route112_Text_ShaylaPostBattle:
	.string "האם את{EMIT_HEY} עסוק{ADD_HEY} עכשיו?\n"
	.string "חשבתי שאולי נחזור על הקרב עכשיו…\l"
	.string "אבל זה בסדר אם את{EMIT_HEY} עסוק{ADD_HEY}.$"

Route113_Text_JaylenIntro:
	.string "את{EMIT_HEY} יכול{ADD_HEY} לנחש למה כל כך קר\n"
	.string "פה בסביבה?$"

Route113_Text_JaylenDefeat:
	.string "פיווו!\n"
	.string "זה מבאס!$"

Route113_Text_JaylenPostBattle:
	.string "האפר הוולקני חוסם את השמש,\n"
	.string "כך שלא מתחמם פה כל כך.\p"
	.string "זה טוב בשבילי--אני לא סובל חום!$"

Route113_Text_DillonIntro:
	.string "התפרצות הר הגעש היא הוכחה\n"
	.string "שהאדמה חיה.$"

Route113_Text_DillonDefeat:
	.string "את{EMIT_HEY} סוג של חזק{ADD_HEY} במיוחד!$"

Route113_Text_DillonPostBattle:
	.string "אאוץ'! אאו! אני לא רואה!\n"
	.string "נכנס לי אפרים לריסים!\p"
	.string "הבנת? אפרים וריסים?\p"
	.string "אוקי, זה היה גרוע, סליחה…$"

Route113_Text_MadelineIntro:
	.string "אני משתמשת במטריה הזו כדי לדחות\n"
	.string "את אפר הגעש המלוכלך הזה מעל\l"
	.string "ה{STR_VAR_1} היקר שלי.$"

Route113_Text_MadelineDefeat:
	.string "האף, האף…\n"
	.string "אני מותשת…$"

Route113_Text_MadelinePostBattle:
	.string "את{EMIT_HEY} טוב{ADD_HEY} בזה מאוד.\n"
	.string "אני חייבת לומר שאני התרשמתי!$"

Route113_Text_MadelineRegister:
	.string "בוא{ADD_YUD} תחליק תחת המטריה שלי.\n"
	.string "ת{SWAP_NUN}{ADD_YUD} לי לרשום אותך בפוקינווט שלי.$"

Route113_Text_MadelineRematchIntro:
	.string "או, הלו, זה לא היה זמן מה?\n"
	.string "אוכל להזמין אותך לקרב?$"

Route113_Text_MadelineRematchDefeat:
	.string "או, כמה נפלא!$"

Route113_Text_MadelinePostRematch:
	.string "את{EMIT_HEY} נשארת טוב בזה מאוד.\n"
	.string "אני חייבת לומר שאני התרשמתי!$"

Route113_Text_LaoIntro:
	.string "מתוך האפר אני יוצא! הייהא!\n"
	.string "אני מאתגר אותך!$"

Route113_Text_LaoDefeat:
	.string "בכבוד אני מודה בהפסד!$"

Route113_Text_LaoPostBattle:
	.string "עליי לשפר את אומנות ההסוואה.\n"
	.string "אני נפרד ממך.$"

Route113_Text_LaoRegister:
	.string "ייהאה! רא{EMIT_HEY}{ADD_YUD} את טכניקת הנינג'ה העתיקה\n"
	.string "של רישום בפוקינווט!$"

Route113_Text_LaoRematchIntro:
	.string "מתוך האפר אני יוצא! הייהא!\n"
	.string "אני מאתגר אותך!$"

Route113_Text_LaoRematchDefeat:
	.string "בכבוד אני מודה בהפסד!$"

Route113_Text_LaoPostRematch:
	.string "ההסוואה המושלמת שלי נחלשה\n"
	.string "בגלל כישורי הקרב הלא בוגרים שלי…\p"
	.string "אני נפרד ממך.$"

Route113_Text_LungIntro:
	.string "תודה שמצאת אותי!\n"
	.string "אבל עדיין עלינו להילחם!$"

Route113_Text_LungDefeat:
	.string "אשתמש בנינג'יצו שלי עליך…\n"
	.string "”סיבוב אפר געשי מוסתר“!\p"
	.string "…מה?\n"
	.string "זה כבר נגמר?$"

Route113_Text_LungPostBattle:
	.string "את{EMIT_HEY} יודע{ADD_TAF} מה רע בהסתתרות?\n"
	.string "זה בודד אם אף אחד לא מגיע.$"

Route113_Text_ToriIntro:
	.string "טורי: שנינו אוספים אפר.\n"
	.string "אנחנו נלחם בפוקימונים גם כן.$"

Route113_Text_ToriDefeat:
	.string "טורי: הפסדנו… זה משעמם, אז אני\n"
	.string "אאסוף עוד אפר.$"

Route113_Text_ToriPostBattle:
	.string "טורי: כמה אפר יש לנו?\n"
	.string "מקווה שזה מספיק בשביל חליל לבן.$"

Route113_Text_ToriNotEnoughMons:
	.string "טורי: אנחנו רוצים להילחם 2 נגד 2.\n"
	.string "אם לא, היינו מפסידים!$"

Route113_Text_TiaIntro:
	.string "טיא: שנינו אוספים אפר.\n"
	.string "אנחנו נלחם בפוקימונים גם כן.$"

Route113_Text_TiaDefeat:
	.string "טיא: לא הצלחנו לנצח… זה משעמם,\n"
	.string "אז אני אלך לאסוף עוד אפר.$"

Route113_Text_TiaPostBattle:
	.string "טיא: יש לנו הרבה אפר!\n"
	.string "אולי זה מספיק עבור חליל לבן!$"

Route113_Text_TiaNotEnoughMons:
	.string "טיא: אנחנו רוצים להילחם 2 נגד 2.\n"
	.string "אם לא, לא ננצח!$"

Route113_Text_CobyIntro:
	.string "פפף, עם הכנפיים האלה אני יכול\n"
	.string "לנגב אותך הצידה!$"

Route113_Text_CobyDefeat:
	.string "א… מה?$"

Route113_Text_CobyPostBattle:
	.string "אני לא יודע מה לומר כשמביסים אותי\n"
	.string "ככה בקלות…$"

Route113_Text_SophieIntro:
	.string "החום כאן עושה לי תרדמת.\n"
	.string "תתמודד{ADD_YUD} מולי כדי שאשאר ערה.$"

Route113_Text_SophieDefeat:
	.string "זה חלום.\n"
	.string "אני בטוחה בזה…$"

Route113_Text_SophiePostBattle:
	.string "הפסד מכעיס אותי…\n"
	.string "אני פשוט אלך לישון כאן!\l"
	.string "זזז!$"

Route113_Text_LawrenceIntro:
	.string "האם אולי היית באמצע\n"
	.string "איסוף אפר געשי?$"

Route113_Text_LawrenceDefeat:
	.string "איהיהי.\n"
	.string "הובלנו להפסד ברור.$"

Route113_Text_LawrencePostBattle:
	.string "צריך גם להסתתר מתחת לאפר.$"

Route113_Text_WyattIntro:
	.string "ר-רצית להילחם מולי?\n"
	.string "גם כשרק תפסתי את הפוקימון שלי?$"

Route113_Text_WyattDefeat:
	.string "א-את{EMIT_HEY} כל כך שמח{ADD_HEY} מהניצחון?\n"
	.string "גם כשזה רק אני?$"

Route113_Text_WyattPostBattle:
	.string "אה, עכשיו את{EMIT_HEY} רוצה לומר מילה\n"
	.string "למפסיד?\p"
	.string "כמה מגניב{ADD_HEY} את{EMIT_HEY}?\n"
	.string "האמף!$"

Route114_Text_LennyIntro:
	.string "יודלאייהוו!\p"
	.string "… …\p"
	.string "את{EMIT_HEY} אמור{ADD_HEY} לצעוק\n"
	.string "”יודלאייהוו“ כי זה לא מהדהד פה!$"

Route114_Text_LennyDefeat:
	.string "יודלאייהוו!$"

Route114_Text_LennyPostBattle:
	.string "כשהייתי קטן, חשבתי שמישהו מחקה אותי\n"
	.string "וצועק חזרה ”יודלאייהוו.“$"

Route114_Text_LucasIntro:
	.string "אם את{EMIT_HEY} לא מוכ{SWAP_NUN}{ADD_HEY}, לא כדאי שתהי{EMIT_HEY}{ADD_YUD}\n"
	.string "בגבהי ההרים!$"

Route114_Text_LucasDefeat:
	.string "ההרים לא סלחניים…$"

Route114_Text_LucasPostBattle:
	.string "בחורף ההרים הופכים לקטלניים\n"
	.string "עם סופות שלגים ומפולות שלגים.$"

Route114_Text_ShaneIntro:
	.string "מחנאות זה כיף! את{EMIT_HEY} יכול{ADD_HEY} לדוג,\n"
	.string "לקלות מרשמלו ולספר סיפורים מפחידים!\p"
	.string "אבל הכי טוב זה הקרבות פוקימונים!$"

Route114_Text_ShaneDefeat:
	.string "חזק מדי!$"

Route114_Text_ShanePostBattle:
	.string "אני חושב שזה מעולה שאני יכול\n"
	.string "לצאת למחנאות עם הפוקימונים שלי.$"

Route114_Text_NancyIntro:
	.string "אני צריכה להתאמן אחרי ארוחה.\n"
	.string "בוא{ADD_YUD} נערוך קרב!$"

Route114_Text_NancyDefeat:
	.string "או, לא!$"

Route114_Text_NancyPostBattle:
	.string "הרגע אכלתי ארוחה טעימה.\n"
	.string "אני מתנמנמת…$"

Route114_Text_SteveIntro:
	.string "אופופופו…\n"
	.string "רוצה להילחם מול הפוקימונים שלי?$"

Route114_Text_SteveDefeat:
	.string "ההפוקימונים שלי…$"

Route114_Text_StevePostBattle:
	.string "גוף גדול קשה ומכוסה בליטות,\n"
	.string "קרניים ענקיות וניבים אכזריים…\p"
	.string "אופופופו…\n"
	.string "הלוואי והיה לי כזה פוקימון…$"

Route114_Text_SteveRegister:
	.string "אל תשכח{ADD_YUD} מה שעשית לי!\n"
	.string "אגרום לכך שלא תשכח{ADD_YUD}!$"

Route114_Text_SteveRematchIntro:
	.string "אופופופופו…\n"
	.string "קדימה, קרב מול הפוקימונים שלי…$"

Route114_Text_SteveRematchDefeat:
	.string "אני מרגיש כל כך בר מזל לראות את\n"
	.string "הפוקימונים שלך…$"

Route114_Text_StevePostRematch:
	.string "אופופופופו…\p"
	.string "כשאני רואה קרבות פוקימונים, אני ממש\n"
	.string "משקשק ורועד…$"

Route114_Text_BernieIntro:
	.string "אם את{EMIT_HEY} מדליק{ADD_HEY} מדורה,\n"
	.string "וודא{ADD_YUD} שיש לך מים בקרבת מקום.$"

Route114_Text_BernieDefeat:
	.string "תודה שהכבת את האש שלי!$"

Route114_Text_BerniePostBattle:
	.string "את{EMIT_HEY} באמת צרי{SWAP_CHAF}{ADD_HEY} להיזהר מאוד מכל אש ביער.\p"
	.string "אף פעם אל תמעיט{ADD_YUD} מעוצמת האש.$"

Route114_Text_BernieRegister:
	.string "הצתת את רוחי.\n"
	.string "בוא{ADD_YUD} נרשם זה את זה!$"

Route114_Text_BernieRematchIntro:
	.string "למדת לשמור על מים קרוב למדורה?$"

Route114_Text_BernieRematchDefeat:
	.string "כיבו אותי לפני שהספקתי\n"
	.string "להתלהב, כנראה.$"

Route114_Text_BerniePostRematch:
	.string "את{EMIT_HEY} באמת צרי{SWAP_CHAF}{ADD_HEY} להיזהר מאוד מכל אש ביער.\p"
	.string "אף פעם אל תמעיט{ADD_YUD} מעוצמת האש.$"

Route114_Text_ClaudeIntro:
	.string "אם היינו דגים, לא היה לך סיכוי\n"
	.string "מולי.\l"
	.string "אז, של{EMIT_VAV}{SWAP_PEY}{ADD_YUD} את הפוקימונים שלך!$"

Route114_Text_ClaudeDefeat:
	.string "אם היינו דגים, הייתי מנצח…$"

Route114_Text_ClaudePostBattle:
	.string "אני חושב שאנסה את מזלי לתפוס\n"
	.string "אחד גדול במפלי המטאור.\p"
	.string "חייב להיות שם משהו.\n"
	.string "אני פשוט מרגיש כך.$"

Route114_Text_NolanIntro:
	.string "אני אוהב לדוג. אבל גם אוהב\n"
	.string "להילחם!\p"
	.string "אם מישהו אתגר אותי, אני שם,\n"
	.string "גם כשאני דג.$"

Route114_Text_NolanDefeat:
	.string "אני אוהב להילחם, אבל זה לא\n"
	.string "אומר שאני טוב בזה…$"

Route114_Text_NolanPostBattle:
	.string "הפעם אצליח!\p"
	.string "אני תמיד חושב ככה, אז לא יכול\n"
	.string "להתרחק מדייג או מפוקימון.$"

Route114_Text_TyraIntro:
	.string "טירא: טוב, כמובן.\n"
	.string "אני במצב רוח לזה.\l"
	.string "אלמד לךאותך קצת על פוקימונים.$"

Route114_Text_TyraDefeat:
	.string "טירא: איזה סגנון קרב מדהים!$"

Route114_Text_TyraPostBattle:
	.string "טירא: הייתי מלמדת את אייוי\n"
	.string "הצעירה שלי על פוקימונים.$"

Route114_Text_TyraNotEnoughMons:
	.string "טירא: צחקוק…\n"
	.string "אם את{EMIT_HEY} רוצה להילחם מולנו, רק פוקימון\l"
	.string "אחד לא מספיק!$"

Route114_Text_IvyIntro:
	.string "אייוי: מי לימד אותך על פוקימונים?$"

Route114_Text_IvyDefeat:
	.string "אייוי: איזה סגנון קרב מדהים!$"

Route114_Text_IvyPostBattle:
	.string "אייוי: התחלתי לאמן פוקימונים\n"
	.string "כי טירא, המנטורית שלי,\l"
	.string "לימדה אותי!$"

Route114_Text_IvyNotEnoughMons:
	.string "אייוי: האם יש לך רק פוקימון אחד?\n"
	.string "זה בטח מרגיש בודד.$"

Route114_Text_KaiIntro:
	.string "תפסתי אחד גדול!\n"
	.string "ענק, אני אומר לך!$"

Route114_Text_KaiDefeat:
	.string "מה זה היה עכשיו?\n"
	.string "האם שלי הפסיד בגודל?$"

Route114_Text_KaiPostBattle:
	.string "אוקיי!\n"
	.string "אז פשוט אדוג אחד גדול יותר!$"

Route114_Text_CharlotteIntro:
	.string "אני!\n"
	.string "אני לא רק פרצוף יפה!$"

Route114_Text_CharlotteDefeat:
	.string "זה בכלל לא היה חמוד!$"

Route114_Text_CharlottePostBattle:
	.string "אני לא רוצה פוקימון שהוא\n"
	.string "רק חמוד.\p"
	.string "אני מעריצה חמודים שיש להם ייחוד\n"
	.string "או שניים!$"

Route114_Text_AngelinaIntro:
	.string "האם גרמת לפוקימונים שלך\n"
	.string "להתפתח הרבה?$"

Route114_Text_AngelinaDefeat:
	.string "אה, אני מבינה.\n"
	.string "טוב לדעת.$"

Route114_Text_AngelinaPostBattle:
	.string "יש פוקימונים שמשתנים כל כך\n"
	.string "כשמתפתחים, זה מפתיע!$"

Route115_Text_TimothyIntro:
	.string "המ…\n"
	.string "נראה שאת{EMIT_HEY} די מסוגל{ADD_TAF}…\l"
	.string "ת{SWAP_NUN}{ADD_YUD} לי להצטרף אליך!$"

Route115_Text_TimothyDefeat:
	.string "את{EMIT_HEY} הרבה יותר חזק{ADD_HEY}\n"
	.string "ממה שדמיינתי!$"

Route115_Text_TimothyPostBattle:
	.string "אין דבר כזה גאון מולד.\n"
	.string "הכול תלוי במאמץ!\l"
	.string "זו האמונה שלי…$"

Route115_Text_TimothyRegister:
	.string "הממ… הפסד כה מוחץ היה\n"
	.string "זיכרון רחוק.\p"
	.string "אם תאפשר{ADD_YUD}, אשמח להזדמנות\n"
	.string "נוספת לקרב.$"

Route115_Text_TimothyRematchIntro:
	.string "המ… כמו תמיד, הזריזות שלך מדברת\n"
	.string "בעד עצמה.\l"
	.string "בוא{ADD_YUD}, תארח{ADD_YUD} לי חברה!$"

Route115_Text_TimothyRematchDefeat:
	.string "חזק כרגיל!$"

Route115_Text_TimothyPostRematch:
	.string "כל מה שצריך זה מאמץ!\p"
	.string "הפסדתי כי לא השקענו מספיק\n"
	.string "מאמץ!$"

Route115_Text_KoichiIntro:
	.string "את{EMIT_HEY}!\p"
	.string "ה{STR_VAR_1} שלי!\p"
	.string "דורש קרב!$"

Route115_Text_KoichiDefeat:
	.string "אאוץ', אאוץ', אאוץ'!$"

Route115_Text_KoichiPostBattle:
	.string "צוות ה{STR_VAR_1}ים שלי!\p"
	.string "כל עוד הם מחפשים כוח, אני\n"
	.string "אתחזק יחד איתם!$"

Route115_Text_NobIntro:
	.string "היכולת החזקה ביותר שלי היא לשבור\n"
	.string "לבנים עם המצח שלי!$"

Route115_Text_NobDefeat:
	.string "אוגוואאאאה!\n"
	.string "הראש שלי נשבר!$"

Route115_Text_NobPostBattle:
	.string "אני מלמד את הפוקימונים שלי קראטה.\p"
	.string "נראה שהם ישתפרו הרבה יותר\n"
	.string "ממני. זה מרגש אותי.$"

Route115_Text_NobRegister:
	.string "הרשמת אותי! ת{SWAP_NUN}{ADD_YUD} לי קרב חוזר\n"
	.string "אחרי שאחזור על האימון שלי!$"

Route115_Text_NobRematchIntro:
	.string "אחרי שהבסת אותי, התאמנו חזק\n"
	.string "כדי לשפר את הכישורים שלנו.\l"
	.string "קדימה, ת{SWAP_NUN}{ADD_YUD} לנו קרב חוזר!$"

Route115_Text_NobRematchDefeat:
	.string "אוגוואאאאה!\n"
	.string "הפסדנו שוב!$"

Route115_Text_NobPostRematch:
	.string "הפוקימונים שלי יתחזקו!\n"
	.string "אני אכפיל את האימון שלי!$"

Route115_Text_CyndyIntro:
	.string "החוף הזה הוא מקום האימון הסודי שלי!\n"
	.string "אל תפריע{ADD_YUD}!$"

Route115_Text_CyndyDefeat:
	.string "אני לא התאמנתי מספיק!$"

Route115_Text_CyndyPostBattle:
	.string "החול משמש כריפוד להפחתת\n"
	.string "המכה ומניעת פציעה.\l"
	.string "זה המקום המושלם לאימון.$"

Route115_Text_CyndyRegister:
	.string "אוקיי, בסדר, את{EMIT_HEY} יכול{ADD_HEY} לבוא לכאן.\n"
	.string "בתמורה, אני אשמח לקרב נוסף איתך.$"

Route115_Text_CyndyRematchIntro:
	.string "אוקיי, בוא{ADD_YUD} נתחיל את הקרב הזה!$"

Route115_Text_CyndyRematchDefeat:
	.string "אני יודעת להילחם אבל הפוקימונים שלי…$"

Route115_Text_CyndyPostRematch:
	.string "גם כשאני מפסידה, אני עדיין\n"
	.string "נהנית מזה.\l"
	.string "זה בטח כי אני אוהבת פוקימונים.$"

Route115_Text_HectorIntro:
	.string "יש לי פוקימון נדיר!\n"
	.string "תרצ{EMIT_HEY}{ADD_YUD} שאראה לך?$"

Route115_Text_HectorDefeat:
	.string "את{EMIT_HEY}{ADD_YUD}…\n"
	.string "את{EMIT_HEY} רוצה את הפוקימון שלי, נכון?$"

Route115_Text_HectorPostBattle:
	.string "יש לי פוקימון נדיר זה.\n"
	.string "זה מספיק לשביעות רצוני.$"

Route115_Text_KyraIntro:
	.string "אני אלחם בזמן שאני רצה!\n"
	.string "תנס{EMIT_HEY}{ADD_YUD} לעמוד בקצב שלי!$"

Route115_Text_KyraDefeat:
	.string "נשיפה, נשיפה…$"

Route115_Text_KyraPostBattle:
	.string "עשיתי טעות בניסיון להילחם\n"
	.string "בזמן ריצה!\p"
	.string "אני צריכה לרוץ כדי להירגע…$"

Route115_Text_JaidenIntro:
	.string "קח{ADD_YUD} את זה!\n"
	.string "מתקפת נינג'ה אולטרה פוקימון!$"

Route115_Text_JaidenDefeat:
	.string "ואאאה!\n"
	.string "האסטרטגיה שלנו נכשלה!$"

Route115_Text_JaidenPostBattle:
	.string "אבל הפוקימונים שלי היו אולטרה,\n"
	.string "נכון?$"

Route115_Text_HeleneIntro:
	.string "לפוקימונים שלי יש עוצמה ברמת חגורה שחורה!$"

Route115_Text_HeleneDefeat:
	.string "זה משפיל מדי!$"

Route115_Text_HelenePostBattle:
	.string "נדיר שאני פוגשת מישהו שהוא טוב ממני…\p"
	.string "עכשיו אני מבינה!\n"
	.string "את{EMIT_HEY} כנראה מנהיג{ADD_TAF} מכון, לא?$"

Route115_Text_AlixIntro:
	.string "המבט שלנו נפגש!\n"
	.string "כבר לא תוכל{ADD_YUD} להימלט!$"

Route115_Text_AlixDefeat:
	.string "גאה!\n"
	.string "לא רע!$"

Route115_Text_AlixPostBattle:
	.string "או, ובכן.\n"
	.string "אולי אשתגר הביתה.$"

Route115_Text_MarleneIntro:
	.string "הפרעת למדיטציה שלי…\n"
	.string "את{EMIT_HEY} תענש{ADD_YUD} על כך.$"

Route115_Text_MarleneDefeat:
	.string "את{EMIT_HEY} שברת לי את הריכוז!$"

Route115_Text_MarlenePostBattle:
	.string "התאמנתי במדיטציה עם הפוקימונים שלי.\n"
	.string "אבל המקום הזה לא ממש שקט…$"

Route116_Text_ClarkIntro:
	.string "אם המנהרה לא עוברת, אז\n"
	.string "אני פשוט אעבור מעליה.$"

Route116_Text_ClarkDefeat:
	.string "נשיפה… נשיפה…\n"
	.string "ההפסד עשה אותי עייף…$"

Route116_Text_ClarkPostBattle:
	.string "אין בעיה אם אין מנהרה.\n"
	.string "לצייד, ההרים הם דרכים!$"

Route116_Text_JoeyIntro:
	.string "הפוקימונים שלי שולטים!\n"
	.string "תסתכל{ADD_YUD} עליהם!$"

Route116_Text_JoeyDefeat:
	.string "אאוץ'! שפשוף!\n"
	.string "אני צריך לשים תחבושת!$"

Route116_Text_JoeyPostBattle:
	.string "תחבושות זה סימן לקשיחות!\n"
	.string "יש לי עוד אחת!$"

Route116_Text_JoseIntro:
	.string "הפוקימונים החרקים שלי חזקים!\n"
	.string "בוא{ADD_YUD} נילחם!$"

Route116_Text_JoseDefeat:
	.string "הפסדתי!\n"
	.string "חשבתי שהצלחתי לגבור עליך!$"

Route116_Text_JosePostBattle:
	.string "פוקימוני חרק מתפתחים מהר.\n"
	.string "לכן הם גם מתחזקים במהירות.$"

Route116_Text_JaniceIntro:
	.string "ת{SWAP_NUN}{ADD_YUD} לי ללמד אותך כמה הפוקימונים\n"
	.string "החמודים שלי חזקים!$"

Route116_Text_JaniceDefeat:
	.string "את{EMIT_HEY} מעלי בדרגה…$"

Route116_Text_JanicePostBattle:
	.string "פוקימונים שיש בהם חמידות\n"
	.string "וכוח, זה אידיאלי, לדעתי.$"

Route116_Text_JerryIntro:
	.string "אנחנו לומדים כל מיני דברים בבית\n"
	.string "הספר למאמנים.\p"
	.string "אני רוצה לבדוק את זה בפועל!$"

Route116_Text_JerryDefeat:
	.string "התעצלתי בלימודים…\n"
	.string "לכן הפסדתי.$"

Route116_Text_JerryPostBattle:
	.string "אצטרך לשנן כמה קורסים בבית\n"
	.string "הספר למאמנים.\l"
	.string "אם לא, רוקסן תכעס.$"

Route116_Text_JerryRegister1:
	.string "אני למדתי בבית הספר למאמנים\n"
	.string "שפוקינווט יכול לרשום מאמנים.\p"
	.string "אני לא ממש מבין מה זה אומר,\n"
	.string "אז אני יכול לנסות את זה?$"

Route116_Text_JerryRegister2:
	.string "אני למדתי בבית הספר למאמנים\n"
	.string "שפוקינווט יכול לרשום מאמנים.\p"
	.string "אני לא ממש מבין מה זה אומר,\n"
	.string "אז אני יכול לנסות את זה?$"

Route116_Text_JerryRematchIntro:
	.string "למדתי ברצינות בבית הספר למאמנים.\l"
	.string "אני לא אפסיד כמו בפעם הקודמת.$"

Route116_Text_JerryRematchDefeat:
	.string "הא?\n"
	.string "אני למדתי בהתמדה.$"

Route116_Text_JerryPostRematch:
	.string "אני אצטרך לשנן כמה קורסים בבית\n"
	.string "הספר למאמנים.\l"
	.string "אם לא, רוקסן תכעס.$"

Route116_Text_KarenIntro:
	.string "אני לומדת בבית הספר, ואני לומדת\n"
	.string "גם בדרך הביתה!$"

Route116_Text_KarenDefeat:
	.string "אני בהלם--הפסדתי?$"

Route116_Text_KarenPostBattle:
	.string "אוו, לעולם לא אהיה מאמנת אלגנטית\n"
	.string "כמו רוקסן ככה!$"

Route116_Text_KarenRegister1:
	.string "או, ואו! האם זה לא פוקינווט?\n"
	.string "גם לי יש אחד! בבקשה תרש{EMIT_VAV}{SWAP_MEM}{ADD_YUD} אותי!$"

Route116_Text_KarenRegister2:
	.string "או, ואו! האם זה לא פוקינווט?\n"
	.string "גם לי יש אחד! בבקשה תרש{EMIT_VAV}{SWAP_MEM}{ADD_YUD} אותי!$"

Route116_Text_KarenRematchIntro:
	.string "אני למדתי המון מאז שראיתי אותך.\n"
	.string "את{EMIT_HEY} חייב{ADD_TAF} לראות את ההישגים שלי!$"

Route116_Text_KarenRematchDefeat:
	.string "אני בהלם.\n"
	.string "הפסדתי שוב?$"

Route116_Text_KarenPostRematch:
	.string "את{EMIT_HEY} הבסת את רוקסן?\n"
	.string "אז אני לא יכולה להביס אותך. לא עדיין.$"

Route116_Text_SarahIntro:
	.string "למען הידיעה, מעולם לא הובסתי\n"
	.string "על ידי אף אחד בכלום.$"

Route116_Text_SarahDefeat:
	.string "אוי, אלוהים.\n"
	.string "זו חוויה חדשה בשבילי.$"

Route116_Text_SarahPostBattle:
	.string "חיי המותרות נותנים לי כל מה\n"
	.string "שאני יכולה לרצות.\p"
	.string "אבל בכל הנוגע לפוקימונים,\n"
	.string "העושר שלי חסר משמעות.$"

Route116_Text_DawsonIntro:
	.string "כשתביט בפרווה המהממת של הפוקימונים\n"
	.string "שלי, היופי שלהם ישאיר אותך\l"
	.string "חסר אונים!$"

Route116_Text_DawsonDefeat:
	.string "או, תינוק{ADD_TAF}, תגיד{ADD_YUD} שזה לא כך!$"

Route116_Text_DawsonPostBattle:
	.string "או, לא, לא, לא!\n"
	.string "שיגעת את הפרווה של הפוקימונים שלי!\l"
	.string "הרסת גם את התסרוקת שלי!\l"
	.string "אני צריך לקרוא למעצב השיער שלי עכשיו!$"

Route116_Text_DevanIntro:
	.string "אנחנו נזעזע אותך חזק!$"

Route116_Text_DevanDefeat:
	.string "איייי!\n"
	.string "אין בכלל תחרות!$"

Route116_Text_DevanPostBattle:
	.string "עליי לנסות סוגי פוקימונים\n"
	.string "שונים, זה מה שעליי לעשות.$"

Route116_Text_JohnsonIntro:
	.string "זה מבוי סתום כאן למעלה.\n"
	.string "משעמם לי, אז אפשר להילחם?$"

Route116_Text_JohnsonDefeat:
	.string "זה היה כיף אפילו שהפסדתי.$"

Route116_Text_JohnsonPostBattle:
	.string "רוצה להישאר כאן לארח\n"
	.string "לי חברה?$"

Route117_Text_IsaacIntro:
	.string "תשמע{ADD_YUD}, האם תוכל{ADD_YUD} להילחם\n"
	.string "בפוקימונים שאני מגדל?$"

Route117_Text_IsaacDefeat:
	.string "את{EMIT_HEY} גידלת אותם בצורה מעולה…$"

Route117_Text_IsaacPostBattle:
	.string "פוקימון זה לא הכל כוח.\p"
	.string "ללטש תכונה ייחודית של אופי\n"
	.string "זו דרך נוספת להנות מפוקימונים.$"

Route117_Text_IsaacRegister:
	.string "אני אכפיל את האימון שלי.\n"
	.string "האם תוכל{ADD_YUD} לבוא לראות אותנו?$"

Route117_Text_IsaacRematchIntro:
	.string "הפוקימונים שאני מגדל נראים טוב,\n"
	.string "כמו קודם.$"

Route117_Text_IsaacRematchDefeat:
	.string "את{EMIT_HEY} יודע{ADD_TAF} לגדל אותם נכון.\n"
	.string "אולי יש לך כישורי מעון…$"

Route117_Text_IsaacPostRematch:
	.string "הפוקימונים שלך מתפתחים טוב!\n"
	.string "כדאי לך להכניס אותם לתחרויות.$"

Route117_Text_LydiaIntro:
	.string "אנא אפשר{ADD_YUD} לי להעריך אם\n"
	.string "גידלת את הפוקימונים בצורה נכונה.$"

Route117_Text_LydiaDefeat:
	.string "כן, הם גדלים כראוי.$"

Route117_Text_LydiaPostBattle:
	.string "נס{EMIT_HEY}{ADD_YUD} לגדל פוקימונים עם תשומת\n"
	.string "לב לתכונות האופי שלהם.$"

Route117_Text_LydiaRegister:
	.string "אני שמחתי לפגוש מאמ{SWAP_NUN}{ADD_TAF} נהדר{ADD_TAF} בך.\n"
	.string "אני מקווה לראות אותך שוב.$"

Route117_Text_LydiaRematchIntro:
	.string "אפשר לי להעריך שוב אם\n"
	.string "גידלת את הפוקימונים בצורה נכונה.$"

Route117_Text_LydiaRematchDefeat:
	.string "הם גדלים באופן מרשים.$"

Route117_Text_LydiaPostRematch:
	.string "נראה שפוקימונים אוהבים סוגים שונים\n"
	.string "של פוקיגושים, בהתאם לאופיים.$"

Route117_Text_DylanIntro:
	.string "אני באמצע טריאתלון, אבל\n"
	.string "בכל זאת, בוא{ADD_YUD} נעשה קרב!$"

Route117_Text_DylanDefeat:
	.string "נגמר לי האנרגיה!$"

Route117_Text_DylanPostBattle:
	.string "ייתכן שהרסתי את זה…\p"
	.string "אולי עברתי להיות אחרון במהלך\n"
	.string "הקרב הזה…$"

Route117_Text_DylanRegister:
	.string "פוקימונים צריכים להיות חזקים גם הם?\n"
	.string "אני אשמח אם תאמ{SWAP_NUN}{ADD_YUD} אותי!$"

Route117_Text_DylanRematchIntro:
	.string "אני באמצע טריאתלון, אבל\n"
	.string "אני מוביל בנוחיות.\l"
	.string "בוא{ADD_YUD} נעשה קרב קצר!$"

Route117_Text_DylanRematchDefeat:
	.string "נגמר לי האנרגיה שוב!$"

Route117_Text_DylanPostRematch:
	.string "הייתי מצוין בשחייה ובאופניים,\n"
	.string "אבל עדיין לא בטוח כל כך לגבי\l"
	.string "פוקימונים.$"

Route117_Text_MariaIntro:
	.string "אני עושה אימוני טריאתלון עם פוקימונים,\n"
	.string "לכן אני בטוחה במהירות שלי.$"

Route117_Text_MariaDefeat:
	.string "אני צריכה להתאמן יותר,\n"
	.string "נראה לי.$"

Route117_Text_MariaPostBattle:
	.string "אימון משמעותי רק אם\n"
	.string "ממשיכים בו בקביעות.\p"
	.string "טוב! אני אחזור לאימון!\n"
	.string "מחר!$"

Route117_Text_MariaRegister:
	.string "נראה שאת{EMIT_HEY} מתאמ{SWAP_NUN}{ADD_TAF} כראוי…\n"
	.string "אם תרצ{EMIT_HEY}{ADD_YUD}, אלחם מולך מאוחר יותר!$"

Route117_Text_MariaRematchIntro:
	.string "האם את{EMIT_HEY} מתמיד{ADD_HEY} באימונים?\n"
	.string "אני בטח כן!\l"
	.string "ת{SWAP_NUN}{ADD_YUD} לי להראות הוכחות!$"

Route117_Text_MariaRematchDefeat:
	.string "אני צריכה להתאמן יותר,\n"
	.string "נראה לי.$"

Route117_Text_MariaPostRematch:
	.string "אני אחזור לאימון מחר.\n"
	.string "בוא{ADD_YUD} נלחם שוב מתישהו!$"

Route117_Text_DerekIntro:
	.string "פעם לוכד חרקים!\n"
	.string "ועכשיו חולה על פוקימוני חרק!\p"
	.string "אבל האהבה שלי לפוקימונים\n"
	.string "לא השתנתה!$"

Route117_Text_DerekDefeat:
	.string "חוסר המיומנות שלי נשאר\n"
	.string "כמו קודם…$"

Route117_Text_DerekPostBattle:
	.string "פשוט הלכתי אחרי ליבי, ועכשיו\n"
	.string "קוראים לי חולה על חרקים…\p"
	.string "עדיין, אני מומחה לפוקימוני חרק,\n"
	.string "ולכן זה טבעי שיקראו לי כך.$"

Route117_Text_AnnaIntro:
	.string "אנה: אני עם בת הזוג הסטודנטית\n"
	.string "החביבה שלי. אני חייבת להצליח!$"

Route117_Text_AnnaDefeat:
	.string "אנה: אני עם בת הזוג הסטודנטית\n"
	.string "החביבה שלי! ת{SWAP_NUN}{ADD_YUD} לי לנצח!$"

Route117_Text_AnnaPostBattle:
	.string "אנה: לפוקימונים שלך יש כמה\n"
	.string "קומבינציות טובות.\p"
	.string "אני אומרת שאת{EMIT_HEY} רק שני{ADD_YUD}{ADD_HEY} אחרינו!$"

Route117_Text_AnnaAndMegRegister:
	.string "אנה: אנחנו לא נוכל לקבל את זה בשקט!\n"
	.string "את{EMIT_HEY} תחז{EMIT_VAV}ר{ADD_YUD}, נכון?$"

Route117_Text_AnnaNotEnoughMons:
	.string "אנה: אם את{EMIT_HEY} רוצה להילחם מולנו,\n"
	.string "הב{ADD_YUD}א{ADD_YUD} שני פוקימונים איתך.$"

Route117_Text_MegIntro:
	.string "מג: אני אתגבש עם בת הזוג הותיקה שלי\n"
	.string "ואנצח אותך!$"

Route117_Text_MegDefeat:
	.string "מג: או, לא!\n"
	.string "אני מצטערת, אנה! אכזבתי אותך…$"

Route117_Text_MegPostBattle:
	.string "מג: גררתי את אנה למטה…\n"
	.string "אם לא, היא הייתה מנצחת!$"

Route117_Text_MegNotEnoughMons:
	.string "מג: האם יש לך רק פוקימון אחד?\n"
	.string "אם כן, לא נוכל להילחם איתך.\p"
	.string "אנחנו רוצים קרב 2 נגד 2.$"

Route117_Text_AnnaRematchIntro:
	.string "אנה: אני לא יכולה להמשיך להפסיד\n"
	.string "לפני בת הזוג שלי, נכון?$"

Route117_Text_AnnaRematchDefeat:
	.string "אנה: לא הצלחתי להיכנס לקצב.$"

Route117_Text_AnnaPostRematch:
	.string "אנה: לפוקימונים שלך יש קומבינציות\n"
	.string "טובות.\p"
	.string "אני אומרת שאת{EMIT_HEY} רק שני{ADD_YUD}{ADD_HEY} אחרינו!$"

Route117_Text_AnnaRematchNotEnoughMons:
	.string "אנה: אם את{EMIT_HEY} רוצה להילחם מולנו,\n"
	.string "הב{ADD_YUD}א{ADD_YUD} שני פוקימונים איתך.$"

Route117_Text_MegRematchIntro:
	.string "מג: אני אצטרף לבת הזוג הוותיקה שלי\n"
	.string "וננצח הפעם!$"

Route117_Text_MegRematchDefeat:
	.string "מג: חזק מדי!$"

Route117_Text_MegPostRematch:
	.string "מג: נלחמתי יחד עם בת הזוג הוותיקה, אך\n"
	.string "הפסדנו…\p"
	.string "זה ממש מתסכל…$"

Route117_Text_MegRematchNotEnoughMons:
	.string "מג: האם יש לך רק פוקימון אחד?\n"
	.string "אם כן, לא נוכל להילחם איתך.\p"
	.string "אנחנו רוצים קרב 2 נגד 2.$"

Route117_Text_MelinaIntro:
	.string "זה לא נחמד? להילחם תוך כדי מבט\n"
	.string "על פרחים יפים?$"

Route117_Text_MelinaDefeat:
	.string "או, זה די מרשים!$"

Route117_Text_MelinaPostBattle:
	.string "נעים לצאת לריצה\n"
	.string "בעודך מסתכל{ADD_TAF} על פרחים.$"

Route117_Text_BrandiIntro:
	.string "ת{SWAP_NUN}{ADD_YUD} לי להדגים את הכוח\n"
	.string "החבוי בתוך פוקימון על חושי!$"

Route117_Text_BrandiDefeat:
	.string "מדהים!$"

Route117_Text_BrandiPostBattle:
	.string "פוקימונים על חושי מורכבים.\n"
	.string "עליך לנסות לתפוס כמה.$"

Route117_Text_AishaIntro:
	.string "התמקד{ADD_YUD} בניצחון.\n"
	.string "כך אני נלחמת!$"

Route117_Text_AishaDefeat:
	.string "אני לא מבזבזת זמן בכעס על\n"
	.string "ההפסד--עדיף לי להתאמן.$"

Route117_Text_AishaPostBattle:
	.string "אני חושבת שאם את{EMIT_HEY} דואג{ADD_TAF} להפסד,\n"
	.string "סביר יותר שתפסיד{ADD_YUD}.$"

Route118_Text_RoseIntro:
	.string "ניחוח הפרחים מחזיק כוח קסום.\n"
	.string "הוא מטהר את הגוף והנפש.$"

Route118_Text_RoseDefeat:
	.string "או, אוי לי.\n"
	.string "נראה שהפסדתי.$"

Route118_Text_RosePostBattle:
	.string "פרחים, פוקימונים…\n"
	.string "אני אוהבת כל מה שריחו נעים.\p"
	.string "דברים מסריחים…\n"
	.string "אני אוותר.$"

Route118_Text_RoseRegister:
	.string "רחרוח… הריח הזה--זה פוקינווט!\n"
	.string "עלינו לרשום אחד את השני!$"

Route118_Text_RoseRematchIntro:
	.string "האם נמשכת לכאן בעקבות הניחוח\n"
	.string "המתוק?$"

Route118_Text_RoseRematchDefeat:
	.string "כוח הניחוח…\n"
	.string "לא נראתה לו השפעה רבה.$"

Route118_Text_RosePostRematch:
	.string "אם תשתמש{ADD_YUD} בניחוח מתוק נכון,\n"
	.string "פוקימונים יימשכו אליו.$"

Route118_Text_PerryIntro:
	.string "פוקימונים מעופפים שמרחפים בשמיים…\n"
	.string "הם הטובים ביותר!$"

Route118_Text_PerryDefeat:
	.string "אחחח…\n"
	.string "התנגשתי…$"

Route118_Text_PerryPostBattle:
	.string "יש לך פוקימונים מעולים.\n"
	.string "אני אצטרך לאמן את שלי יותר טוב.$"

Route118_Text_ChesterIntro:
	.string "עלו לאוויר!\n"
	.string "הפוקימונים המעופפים שלי!$"

Route118_Text_ChesterDefeat:
	.string "הם אכן המריאו…$"

Route118_Text_ChesterPostBattle:
	.string "אם הם היו מתחזקים, הם היו יכולים\n"
	.string "לעוף בחופשיות רבה יותר…$"

Route118_Text_BarnyIntro:
	.string "אני דייג, אבל גם מאמן.\n"
	.string "אני מגדל את הפוקימונים שתפסתי.$"

Route118_Text_BarnyDefeat:
	.string "חשבתי שאני מסתדר באימונים שלי…$"

Route118_Text_BarnyPostBattle:
	.string "לא הצלחתי לנצח כשאימנתי פוקימונים\n"
	.string "בזמן שדגתי…\p"
	.string "האם פעלתי בחצי האמצעים?$"

Route118_Text_WadeIntro:
	.string "לדייגים, הציוד הוא המפתח.\p"
	.string "אבל למאמנים, המרכיבים המרכזיים\n"
	.string "הם פוקימונים ולב, כמובן!$"

Route118_Text_WadeDefeat:
	.string "הפסדתי בלב?$"

Route118_Text_WadePostBattle:
	.string "כשחושבים על זה, דייג הוא קרב\n"
	.string "בין דייג לפוקימון.$"

Route118_Text_DaltonIntro:
	.string "ת{SWAP_NUN}{ADD_YUD} למנגינה שלי לנער את נשמתך!$"

Route118_Text_DaltonDefeat:
	.string "לה-לללה…$"

Route118_Text_DaltonPostBattle:
	.string "גיטרה חשמלית לא תמיד חייבת\n"
	.string "להיות רועשת…\p"
	.string "אפשר לפרוט בה כדי לשלוף\n"
	.string "מנגינה מעוררת לבבות…$"

Route118_Text_DaltonRegister:
.string "כשאלחין מנגינות טובות יותר,\n"		
	.string "את{EMIT_HEY} חייב{ADD_TAF} לבוא להקשיב, בסדר?$"

Route118_Text_DaltonRematchIntro:
	.string "מנגינה מהפוקימונים שלי ואני…\n"
	.string "ת{SWAP_NUN}{ADD_YUD} לה להגיע לנשמתך.$"

Route118_Text_DaltonRematchDefeat:
	.string "לה-לללה…$"

Route118_Text_DaltonPostRematch:
	.string "כשאני מנגן, רגשותיי אמורים\n"
	.string "להגיע אליך דרך הגיטרה החשמלית…$"

Route118_Text_DeandreIntro:
	.string "קדימה, קדימה, קדימה!\n"
	.string "פוקימון 1, 2, ו-3!$"

Route118_Text_DeandreDefeat:
	.string "הכנסו, פוקימונים! אתם בסדר?\n"
	.string "פוקימון 1, 2, ו-3?!$"

Route118_Text_DeandrePostBattle:
	.string "זה לא מגניב שיש לי צוות קרב פוקימונים?\p"
	.string "את{EMIT_HEY} יכול לחקות אותי--לא אכפת לי!$"

Route119_Text_BrentIntro:
	.string "אנחנו מעגל החיקוי!\n"
	.string "אנחנו מחקים את מה שאת{EMIT_HEY} עושה!$"

Route119_Text_BrentDefeat:
	.string "אופס!\n"
	.string "הפסדתי!$"

Route119_Text_BrentPostBattle:
	.string "מה כל כך טוב בהתחקות?\p"
	.string "פופופו…\n"
	.string "לעולם לא תבי{SWAP_NUN}{ADD_YUD}…$"

Route119_Text_DonaldIntro:
	.string "אז, סוף סוף אנחנו נפגשים!\n"
	.string "פוקימוני החרק שלי ילוו אותך!$"

Route119_Text_DonaldDefeat:
	.string "הלוואי שלא היינו פוגשים…$"

Route119_Text_DonaldPostBattle:
	.string "אני רוצה להעתיק אותך עוד קצת.\n"
	.string "את{EMIT_HEY} יכול{ADD_HEY} לזוז כבר?$"

Route119_Text_TaylorIntro:
	.string "אם את{EMIT_HEY} מתקד{SWAP_MEM}{ADD_TAF}, אנחנו מתקדמים.\p"
	.string "אם את{EMIT_HEY} פונה ימינה, גם אנחנו פונים…$"

Route119_Text_TaylorDefeat:
	.string "אבל אם את{EMIT_HEY} מנצח{ADD_TAF}, אני מפסיד…$"

Route119_Text_TaylorPostBattle:
	.string "אני לא יכול לחקות את ניצחונך.\n"
	.string "זה פשוט בלתי אפשרי…\l"
	.string "זה צורב אותי מבפנים…$"

Route119_Text_DougIntro:
	.string "כן, סוף סוף תפסת אותי!\n"
	.string "או שניסית להימנע ממני?$"

Route119_Text_DougDefeat:
	.string "וופ, זה היה קרב נהדר!$"

Route119_Text_DougPostBattle:
	.string "אנחנו מעגל החיקוי!\n"
	.string "אני מקווה שנהנית מההופעה שלנו.$"

Route119_Text_GregIntro:
	.string "את{EMIT_HEY} לא יודע{ADD_TAF} מי אני, נכון?\p"
	.string "ואני גם לא מכיר אותך.\n"
	.string "אז נלחם!$"

Route119_Text_GregDefeat:
	.string "את{EMIT_HEY} די חזק{ADD_HEY}!$"

Route119_Text_GregPostBattle:
	.string "עד שתמשי{SWAP_CHAF}{ADD_YUD} הלאה, נמשיך\n"
	.string "להעתיק כל תנועה שלך.$"

Route119_Text_KentIntro:
	.string "מעגל החיקוי הוקם על ידי אנשים\n"
	.string " שאוהבים לחקות.\p"
	.string "הקרב מתחיל ברגע שאנחנו נפגשים!$"

Route119_Text_KentDefeat:
	.string "אני מוותר!$"

Route119_Text_KentPostBattle:
	.string "האם לא תצטר{SWAP_PEY}{ADD_YUD} למעגל החיקוי שלנו?$"

Route119_Text_JacksonIntro:
	.string "מי מחזיק בידע ובטכניקה להישרדות?\p"
	.string "שומרי פוקימון, זה מי!$"

Route119_Text_JacksonDefeat:
	.string "לא היה לי מספיק ידע על פוקימונים…$"

Route119_Text_JacksonPostBattle:
	.string "להתרחק מהציביליזציה ולעורר\n"
	.string "את הרוח הפראית שבפנים!\p"
	.string "זה החזון שלנו.$"

Route119_Text_JacksonRegister:
	.string "אני מקווה שתת{SWAP_NUN}{ADD_YUD} לי קרב חוזר בלי\n"
	.string "ללעוג לחוסר הידע שלי.$"

Route119_Text_JacksonRematchIntro:
	.string "אני הולך לשחזר את הרוח הפראית על ידי\n"
	.string "שהייה עם פוקימונים.$"

Route119_Text_JacksonRematchDefeat:
	.string "נשארת חזק!$"

Route119_Text_JacksonPostRematch:
	.string "תאמי{SWAP_NUN}{ADD_YUD} בפוקימונים שלך.\n"
	.string "תאמי{SWAP_NUN}{ADD_YUD} בעצמך.\p"
	.string "הדרך תתגלה עבורך.$"

Route119_Text_CatherineIntro:
	.string "אה? תרא{EMIT_HEY}{ADD_YUD} אותך.\p"
	.string "למישהו בהרפתקה,\n"
	.string "את{EMIT_HEY} מטייל{ADD_TAF} בקלות מדאיגה.$"

Route119_Text_CatherineDefeat:
	.string "תאונות קורות כשאת{EMIT_HEY} לא\n"
	.string "מוכ{SWAP_NUN}{ADD_HEY}!$"

Route119_Text_CatherinePostBattle:
	.string "את{EMIT_HEY} מטיילת בקלות אבל יש לך\n"
	.string "את כל מה שצרי{SWAP_CHAF}{ADD_HEY}.\p"
	.string "את{EMIT_HEY} על הדברים גם מנטלית\n"
	.string "וגם פיזית.$"

Route119_Text_CatherineRegister:
	.string "יש לך פוקינווט?\n"
	.string "זה כלי שצריך כל מאמן.\p"
	.string "אה, יש לך אחד!\n"
	.string "בוא{ADD_YUD} נרשום זה את זה!$"

Route119_Text_CatherineRematchIntro:
	.string "איך הולכת ההרפתקה שלך עם פוקימונים?$"

Route119_Text_CatherineRematchDefeat:
	.string "עדיין חסר לי משהו…$"

Route119_Text_CatherinePostRematch:
	.string "באותו אופן שבו את{EMIT_HEY}, כמאמ{SWAP_NUN}{ADD_TAF},\n"
	.string "סומ{SWAP_CHAF}{ADD_TAF} על הפוקימונים שלך,\l"
	.string "גם הם סומכים עליך.$"

Route119_Text_HughIntro:
	.string "מרחבי השמיים טומנים בחובם הבטחה עצומה!\p"
	.string "שום דבר לא משתווה לעוצמת ההתרגשות שבטיסה!$"

Route119_Text_HughDefeat:
	.string "מופל לקרשים!$"

Route119_Text_HughPostBattle:
	.string "הפוקימונים המעופפים שלי הפכו\n"
	.string "את החלומות שלי לעוף למציאות!$"

Route119_Text_PhilIntro:
	.string "אני אקרא לך את הפוטנציאל האמיתי שלי\n"
	.string "ושל הפוקימונים המעופפים שלי!$"

Route119_Text_PhilDefeat:
	.string "חסר לנו הפוטנציאל…$"

Route119_Text_PhilPostBattle:
	.string "מגיל קטן תמיד הערצתי\n"
	.string "פוקימונים מעופפים…$"

Route119_Text_YasuIntro:
	.string "להסתתר בצללים ולחיות\n"
	.string "בחושך… זה גורלי.\p"
	.string "אאתגר אותך!$"

Route119_Text_YasuDefeat:
	.string "אני מודה בהפסד!$"

Route119_Text_YasuPostBattle:
	.string "המפסידים בקרב חזרו אל הצללים\n"
	.string "בשקט.\l"
	.string "גם זה גורל…$"

Route119_Text_TakashiIntro:
	.string "אם אינך על המשמר,\n"
	.string "תהי{EMIT_HEY}{ADD_YUD} מוכ{SWAP_NUN}{ADD_HEY} לכאב!$"

Route119_Text_TakashiDefeat:
	.string "את{EMIT_HEY} טוב{ADD_HEY} באופן מפתיע!$"

Route119_Text_TakashiPostBattle:
	.string "המתקפה המפתיעה שלי נכשלה…$"

Route119_Text_HideoIntro:
	.string "כדי להסתיר עץ, השתמש{ADD_YUD} ביער!$"

Route119_Text_HideoDefeat:
	.string "אני משתחווה מול עליונותך.$"

Route119_Text_HideoPostBattle:
	.string "כדי להסתיר עץ, השתמש{ADD_YUD} ביער!$"
	.string "כדי להסתיר פוקימון, השתמש{ADD_YUD} בפוקימון!\p"
	.string "אין כאן משמעות עמוקה נסתרת.$"

Route119_Text_ChrisIntro:
	.string "פנית אליי…\n"
	.string "אז את{EMIT_HEY} רוצה לאתגר אותי!\p"
	.string "כמובן! אשתמש בפוקימונים שנתפסו\n"
	.string "בגלישה!$"

Route119_Text_ChrisDefeat:
	.string "אין לי מושג מה צריך כדי\n"
	.string "לנצח.$"

Route119_Text_ChrisPostBattle:
	.string "גולש על הפוקימון שלי…\p"
	.string "ואז תופס דג מעל גבו…\p"
	.string "זו חוויה מפנקת שאין לתאר!$"

Route119_Text_FabianIntro:
	.string "ת{SWAP_NUN}{ADD_YUD} לי תו כוח!\n"
	.string "הניצחון שלי!\l"
	.string "הגיע הזמן של זריחתי, וואה, כן!$"

Route119_Text_FabianDefeat:
	.string "את{EMIT_HEY} הראית לי מי הבוס!\n"
	.string "עלינו לקבל את ההפסד, או, לא!$"

Route119_Text_FabianPostBattle:
	.string "ת{SWAP_NUN}{ADD_YUD} לי עוד תו כוח!\n"
	.string "עז{EMIT_VAV}ב{ADD_YUD} אותי!\l"
	.string "את הניצחון שלך ת{SWAP_NUN}{ADD_YUD} לכבודי!$"

Route119_Text_DaytonIntro:
	.string "הוהוהו!\n"
	.string "אני אוהב מאמני ילדים!\l"
	.string "בוא{ADD_YUD} נעשה קרב טוב!$"

Route119_Text_DaytonDefeat:
	.string "את{EMIT_HEY} ממש מדהי{SWAP_MEM}{ADD_HEY}!\n"
	.string "הוהוהו!$"

Route119_Text_DaytonPostBattle:
	.string "הוהוהו!\n"
	.string "אני אנסה לחקות את האנרגיה של\l"
	.string "מאמני ילדים כמוך!$"

Route119_Text_RachelIntro:
	.string "בכל מקום ובכל זמן,\n"
	.string "תמיד יש לי מטריה ביד.$"

Route119_Text_RachelDefeat:
	.string "או, אבל…\n"
	.string "זה לא הוגן.$"

Route119_Text_RachelPostBattle:
	.string "את{EMIT_HEY} שואל{ADD_TAF} אם המטריה שלי כבדה?\n"
	.string "התיק שלך מלא בזבל יותר ממה\l"
	.string "שאאחסן אי פעם.$"

Route120_Text_ColinIntro:
	.string "יש לך מהלכים שיכולים\n"
	.string "לפגוע בפוקימון מעופף?$"

Route120_Text_ColinDefeat:
	.string "התרוממת מעליי!$"

Route120_Text_ColinPostBattle:
	.string "המהלך תעופה הוא נוח, לא כך?\p"
	.string "כשפוקימון מעופף,\n"
	.string "מעט מהלכים יכולים לפגוע בו.$"

Route120_Text_RobertIntro:
	.string "הפוקימונים שלי חזקים!\n"
	.string "מה עם שלך?$"

Route120_Text_RobertDefeat:
	.string "הפוקימונים שלך היו חזקים יותר…$"

Route120_Text_RobertPostBattle:
	.string "פוקימון שגדל בהתמדה הוא כזה\n"
	.string "שאפשר לסמוך עליו.$"

Route120_Text_RobertRegister:
	.string "אפשר לסמוך שתשתפר{ADD_YUD}.\n"
	.string "אשמח לרשום אותך בפוקינווט שלי!$"

Route120_Text_RobertRematchIntro:
	.string "פוקימון שגדל בהתמדה הוא כזה\n"
	.string "שאפשר לסמוך עליו.$"

Route120_Text_RobertRematchDefeat:
	.string "הפוקימונים שלך באמת חזקים.$"

Route120_Text_RobertPostRematch:
	.string "הפוקימונים שלי מתחזקים.\n"
	.string "גם אני צריך להתחזק.$"

Route120_Text_LorenzoIntro:
	.string "אני אבדוק את הפוקימונים שלך כדי לראות\n"
	.string "אם הם מתאימים לשטח.$"

Route120_Text_LorenzoDefeat:
	.string "עם פוקימונים כאלה חזקים,\n"
	.string "את{EMIT_HEY} לא תזדקק{ADD_YUD} להצלה!$"

Route120_Text_LorenzoPostBattle:
	.string "לנסוע לכל מקום שתרצה עם פוקימונים…\l"
	.string "זו שמחת היותו של מאמן.$"

Route120_Text_JennaIntro:
	.string "מה מצב הכושר שלך?\n"
	.string "אם אינך בכושר, תתקש{EMIT_HEY}{ADD_YUD} במצבים קשים.$"

Route120_Text_JennaDefeat:
	.string "אני בכושר, אבל…$"

Route120_Text_JennaPostBattle:
	.string "אימוני כושר הם שגרתי.\n"
	.string "אני תמיד רצה עם הפוקימונים שלי.$"

Route120_Text_JeffreyIntro:
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "רוצה להילחם?$"

Route120_Text_JeffreyDefeat:
	.string "הפסדתי את זה…$"

Route120_Text_JeffreyPostBattle:
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "אשתדל יותר…$"

Route120_Text_JeffreyRegister:
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "יש לך פוקינווט…?$"

Route120_Text_JeffreyRematchIntro:
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "רוצה להילחם שוב?$"

Route120_Text_JeffreyRematchDefeat:
	.string "… … … … … …\n"
	.string "הפסדתי שוב…$"

Route120_Text_JeffreyPostRematch:
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "אני אשתדל יותר…\l"
	.string "בשביל פוקימוני חרק היקרים שלי…$"

Route120_Text_JenniferIntro:
	.string "לפוקימונים יש יכולות מיוחדות רבות.\n"
	.string "אם ברצונך להיות מאמ{SWAP_NUN}{ADD_TAF} מובחר{ADD_TAF},\l"
	.string "למד{ADD_YUD} עליהן.$"

Route120_Text_JenniferDefeat:
	.string "את{EMIT_HEY} כמובן חושב{ADD_TAF}. $"

Route120_Text_JenniferPostBattle:
	.string "היכולות המיוחדות של פוקימונים\n"
	.string "משנות את סגנון הקרב.$"

Route120_Text_ChipIntro:
	.string "מי את{EMIT_HEY} יכול{ADD_HEY} להיות?\p"
	.string "האם את{EMIT_HEY} מחפש{ADD_TAF} חורבות עתיקות שמספרים\n"
	.string "שייתכן והן קיימות לפי האגדה?$"

Route120_Text_ChipDefeat:
	.string "איזו אכזבה מביכה…$"

Route120_Text_ChipPostBattle:
	.string "הסלע הענק ההוא… אני רוצה\n"
	.string "להאמין שהוא מחזיק חורבות עתיקות.\l"
	.string "אבל איני רואה כניסה.$"

Route120_Text_ClarissaIntro:
	.string "מדוע אני נושאת את המטריה הזו?\p"
	.string "אגלה לך אם תצליח{ADD_YUD} לנצח אותי.$"

Route120_Text_ClarissaDefeat:
	.string "מטריה לא תבלום\n"
	.string "מתקפות פוקימונים…$"

Route120_Text_ClarissaPostBattle:
	.string "אני לא חושבת ששמש חזקה טובה\n"
	.string "לפוקימונים שלי.\l"
	.string "לכן אני מגינה עליהם עם המטריה.$"

Route120_Text_AngelicaIntro:
	.string "אני, פוקימונים והמטריה שלי…\p"
	.string "אם אחד מהם יחסר, תמונת היופי\n"
	.string "תהיה הרוסה.$"

Route120_Text_AngelicaDefeat:
	.string "הרסת לגמרי את היופי שלי…$"

Route120_Text_AngelicaPostBattle:
	.string "מטריה לא תתאים לך בכלל.\p"
	.string "משהו כזה רק יעצור אותך.$"

Route120_Text_KeigoIntro:
	.string "אני אאמץ מהלכים של פוקימונים\n"
	.string "ואצור טכניקות נינג'ה חדשות.$"

Route120_Text_KeigoDefeat:
	.string "יצירת טכניקות נינג'ה חדשות\n"
	.string "היא רק חלום רחוק…$"

Route120_Text_KeigoPostBattle:
	.string "אולי עליי להתלמד אצל סנסיי נינג'ה.$"

Route120_Text_RileyIntro:
	.string "אנחנו נינג'ות מסתתרים מתחת\n"
	.string "לשמיכות ההסוואה שלנו.\l"
	.string "אני בטוח שלא ידעת איפה אני!$"

Route120_Text_RileyDefeat:
	.string "הפסדתי!\n"
	.string "עליי להסוות את הבושה שלי!$"

Route120_Text_RileyPostBattle:
	.string "שמיכות ההסוואה שלנו כולן\n"
	.string "מעשה ידינו.$"

Route120_Text_CallieIntro:
	.string "אם לא תשקיע{ADD_YUD} תשומת לב,\n"
	.string "את{EMIT_HEY} עלול{ADD_HEY} להיפצע!$"

Route120_Text_CallieDefeat:
	.string "אאוץ'!\n"
	.string "אני זה שנפגעתי.$"

Route120_Text_CalliePostBattle:
	.string "אני תוהה… האם עליי לפתח את הפוקימונים שלי?\n"
	.string "הם חמודים כפי שהם, בכל זאת.$"

Route120_Text_LeonelIntro:
	.string "הפוקימונים בקבוצתך…\n"
	.string "האם יש לך סוגים שונים?$"

Route120_Text_LeonelDefeat:
	.string "אני ראיתי את האסטרטגיה שלך בפעולה!$"

Route120_Text_LeonelPostBattle:
	.string "אני חושב שזה נפלא שאת{EMIT_HEY} כל כך חזק{ADD_HEY}\n"
	.string "להלחם עם הפוקימונים האהובים עליך.$"

Route121_Text_VanessaIntro:
	.string "האם תשחק{ADD_YUD} עם הפוקימונים המהנים והיפים\n"
	.string "שלי$"

Route121_Text_VanessaDefeat:
	.string "זה לא מה שהתכוונתי!$"

Route121_Text_VanessaPostBattle:
	.string "אני הולכת להשתתף בתחרות בליליקוב.\p"
	.string "לפוקימונים שלי לא תהיה בעיה\n"
	.string "לכבוש את דרגת המאסטר.$"

Route121_Text_WalterIntro:
	.string "עם הפוקימונים שלי טיילתי\n"
	.string "בפינות שונות של העולם.\p"
	.string "אפשר לומר שיש לי ביטחון\n"
	.string "ביכולותיי.$"

Route121_Text_WalterDefeat:
	.string "אה, משחק יפה.$"

Route121_Text_WalterPostBattle:
	.string "אני ארצה להקיף את הגלובוס פעם נוספת\n"
	.string "עם הפוקימונים שלי.$"

Route121_Text_WalterRegister:
	.string "הכישרון שלך עם פוקימונים מרשים.\n"
	.string "אפשר לרשום אותך כמזכרת?$"

Route121_Text_WalterRematchIntro:
	.string "עם הפוקימונים שלי טיילתי\n"
	.string "בפינות שונות של העולם.\p"
	.string "אפשר לומר שיש לי ביטחון\n"
	.string "ביכולותיי.$"

Route121_Text_WalterRematchDefeat:
	.string "אה, משחק יפה.$"

Route121_Text_WalterPostRematch:
	.string "את{EMIT_HEY} והפוקימונים שלך…\p"
	.string "הכוח שלכם יחד ייחשב\n"
	.string "לחזק גם מעבר לים.$"

Route121_Text_TammyIntro:
	.string "יש כוחות שבעולם שמעבר\n"
	.string "להבנתנו…$"

Route121_Text_TammyDefeat:
	.string "הפסדתי…$"

Route121_Text_TammyPostBattle:
	.string "הר המוקד…\n"
	.string "שם פועל כוח מסתורי…$"

Route121_Text_KateIntro:
	.string "קייט: יחד, אנחנו ללא פחד!\n"
	.string "קייט: אנחנו נראה לך כמה אנחנו קשוחים!$"

Route121_Text_KateDefeat:
	.string "קייט: נכשלתי מול השותפה\n"
	.string "הסטודנטית שלי…$"

Route121_Text_KatePostBattle:
	.string "קייט: כשמישהו מסתמך עליי,\n"
	.string "עולה בי הרצון להיראות מגניבה\l"
	.string "מולו…$"

Route121_Text_KateNotEnoughMons:
	.string "קייט: אם יש לך רק פוקימון אחד,\n"
	.string "אנחנו לא יכולים להילחם מולך.\p"
	.string "זה יהיה בריונות.$"

Route121_Text_JoyIntro:
	.string "ג'וי: יחד, אנחנו ללא פחד!\n"
	.string "ג'וי: אנחנו נראה לך כמה אנחנו קשוחים!$"

Route121_Text_JoyDefeat:
	.string "ג'וי: סלחי לי, קייט!$"

Route121_Text_JoyPostBattle:
	.string "ג'וי: היהיהי, אני אצטרך להתאמן שוב עם קייט,\n"
	.string "השותפה הוותיקה שלי.$"

Route121_Text_JoyNotEnoughMons:
	.string "ג'וי: את{EMIT_HEY} צרי{SWAP_CHAF}{ADD_HEY} לפחות שני פוקימונים\n"
	.string "אם את{EMIT_HEY} רוצה לאתגר אותנו!$"

Route121_Text_JessicaIntro:
	.string "הפס{ADD_YUD}ק{ADD_YUD}! הב{ADD_YUD}ט{ADD_YUD} טוב בפוקימונים\n"
	.string " היקרים שלי!$"

Route121_Text_JessicaDefeat:
	.string "או, איך העזת!\n"
	.string "אל תקח{ADD_YUD} את זה יותר מדי ברצינות!$"

Route121_Text_JessicaPostBattle:
	.string "אולי אלך לתפוס עוד פוקימונים\n"
	.string "בספארי.$"

Route121_Text_JessicaRegister:
	.string "הקלתי עליך הפעם!\n"
	.string "ככה לא יהיה בפעם הבאה!$"

Route121_Text_JessicaRematchIntro:
	.string "הפוקימונים היקרים שלי גדלו!\n"
	.string "תסתכל{ADD_YUD} מקרוב!$"

Route121_Text_JessicaRematchDefeat:
	.string "או, איך העזת!\n"
	.string "את{EMIT_HEY} עדיין לא מקל{ADD_HEY} עליי!$"

Route121_Text_JessicaPostRematch:
	.string "אולי אלך לתפוס עוד פוקימונים\n"
	.string "בספארי.$"

Route121_Text_CristinIntro:
	.string "יש לי שגרה.\n"
	.string "להביס חמישה מאמנים ביום.\l"
	.string "נחש{ADD_YUD} מה? את{EMIT_HEY} מספר חמש!$"

Route121_Text_CristinDefeat:
	.string "לא!\n"
	.string "את{EMIT_HEY} נורא{ADD_YUD}{ADD_TAF}!$"

Route121_Text_CristinPostBattle:
	.string "לא ציפיתי להפסיד כל כך בקלות…\n"
	.string "אני אנצח בפעם הבאה!$"

Route121_Text_CristinRegister:
	.string "זו הייתה השפלה מוחלטת!\n"
	.string "אני לא אשכח אותך…\l"
	.string "תביא{ADD_YUD} את הפוקינווט שלך!$"

Route121_Text_CristinRematchIntro:
	.string "יש לי שגרה חדשה.\n"
	.string "להביס עשרה מאמנים ביום.\l"
	.string "נחש מה? את{EMIT_HEY} מספר עשר!$"

Route121_Text_CristinRematchDefeat:
	.string "חכ{EMIT_HEY}{ADD_YUD}! זה נורא!\n"
	.string "אני דורשת קרב חוזר!$"

Route121_Text_CristinPostRematch:
	.string "יריב{ADD_HEY} שאני פשוט לא יכולה להביס…\n"
	.string "בכי…\l"
	.string "אני לא מאמינה שזה קורה…$"

Route121_Text_CaleIntro:
	.string "האם את{EMIT_HEY} לא רואה את כל הדברים\n"
	.string "איתי?\p"
	.string "למרות זאת את{EMIT_HEY} מתעקש{ADD_TAF}\n"
	.string "שנילחם?$"

Route121_Text_CaleDefeat:
	.string "כמובן שהפסדתי!\n"
	.string "אני מחזיק דברים בשתי הידיים!$"

Route121_Text_CalePostBattle:
	.string "קניתי יותר מדי בחנות הכלבו בליליקוב.\p"
	.string "זה ממש על הדרך מפה.\n"
	.string "הלוואי והיה לי תיק כמוך.$"

Route121_Text_MylesIntro:
	.string "אין דבר שאני אוהב יותר מלבד\n"
	.string "להסתכל על פוקימונים של אחרים!$"

Route121_Text_MylesDefeat:
	.string "מדהים לגמרי!$"

Route121_Text_MylesPostBattle:
	.string "הפוקימונים שלך מעולים!\n"
	.string "איך את{EMIT_HEY} מגדל{ADD_TAF} אותם?$"

Route121_Text_PatIntro:
	.string "אני רוצה שכולם יראו את\n"
	.string "הפוקימונים שגידלתי!$"

Route121_Text_PatDefeat:
	.string "ואו!\n"
	.string "מרהיב!$"

Route121_Text_PatPostBattle:
	.string "אני מטפל בכל פוקימון באותה\n"
	.string "אהבה וטיפול--אין מועדפים.$"

Route121_Text_MarcelIntro:
	.string "הפוקימון שלי מעולם לא טעם תבוסה!\n"
	.string "בניצחון הבא שלהם, אכניס אותם\l"
	.string "לתחרויות.$"

Route121_Text_MarcelDefeat:
	.string "או, מה קרה כאן עכשיו?$"

Route121_Text_MarcelPostBattle:
	.string "אני אולי אצטרך לאמן את הכנופייה קצת יותר\n"
	.string "לפני שאכנס לתחרות כלשהי.$"

Route123_Text_WendyIntro:
	.string "רוצה לבדוק כמה את{EMIT_HEY} חזק{ADD_HEY}?\n"
	.string "אני אהיה המבחן!$"

Route123_Text_WendyDefeat:
	.string "עברת בהצלחה רבה!$"

Route123_Text_WendyPostBattle:
	.string "להביס אפילו אותי…\n"
	.string "כוחך מרהיב!$"

Route123_Text_BraxtonIntro:
	.string "נראה שיש לך אוסף גדול\n"
	.string "של של תגי מכון.\p"
	.string "ת{SWAP_NUN}{ADD_YUD} לי לראות אם את{EMIT_HEY} באמת ראוי{ADD_HEY}\n"
	.string "לתגים האלו!$"

Route123_Text_BraxtonDefeat:
	.string "אה, את{EMIT_HEY} אכן ראוי{ADD_HEY}!$"

Route123_Text_BraxtonPostBattle:
	.string "נתת כבוד לתגיך בקרב הזה!$"

Route123_Text_VioletIntro:
	.string "אומרים שרגעים טובים מלאים\n"
	.string "בניחוחות נעימים.$"

Route123_Text_VioletDefeat:
	.string "או…\n"
	.string "אני מריחה את ריח המרירות…$"

Route123_Text_VioletPostBattle:
	.string "גן מומחה הפירות יער מלא\n"
	.string "בניחוחות שמרוממים את הרוח.$"

Route123_Text_CameronIntro:
	.string "להיות על חושי זה עניין של כוח רצון.\p"
	.string "הכרחתי את עצמי שלא אפסיד\n"
	.string "לאף אחד. זה מחזק אותי!$"

Route123_Text_CameronDefeat:
	.string "אני מרגיש עצוב…$"

Route123_Text_CameronPostBattle:
	.string "להיות על חושי זה עניין של כוח רצון.\n"
	.string "חשבתי שלא אפסיד לך…$"

Route123_Text_CameronRegister:
	.string "אני מרגיש את זה!\n"
	.string "את{EMIT_HEY} ואני נילחם שוב!\l"
	.string "אבל אינני יודע אם אנצח…\p"
	.string "בוא{ADD_YUD} נראה את הפוקינווט שלך.$"

Route123_Text_CameronRematchIntro:
	.string "שכנעתי את עצמי שלא אפסיד\n"
	.string "עוד. זה מחזק אותי!$"

Route123_Text_CameronRematchDefeat:
	.string "אני מרגיש עצוב…$"

Route123_Text_CameronPostRematch:
	.string "עליי להתאמן בהר המוקד…"
	.string "ככה לעולם לא אצליח לנצח אותך…$"

Route123_Text_JackiIntro:
	.string "אל תשמח{ADD_YUD} יותר מדי אם הפוקימון\n"
	.string "שלך מפתח כוחות על חושיים.\p"
	.string "עליך ללטש כוחות אלה\n"
	.string "כדי שהם יהיו שימושיים באמת.$"

Route123_Text_JackiDefeat:
	.string "מוצף!$"

Route123_Text_JackiPostBattle:
	.string "כולנו נושאים כוחות על חושיים.\n"
	.string "פשוט שכחנו איך להשתמש בהם.$"

Route123_Text_JackiRegister:
	.string "אני רוצה להילחם בך שוב.\n"
	.string "זה בסדר מבחינתך?$"

Route123_Text_JackiRematchIntro:
	.string "האם עוררת בתוכך את הכוחות\n"
	.string "העל חושיים?$"

Route123_Text_JackiRematchDefeat:
	.string "מדהים!$"

Route123_Text_JackiPostRematch:
	.string "הכוח שלך עם פוקימון…\n"
	.string "זה יכול להיות גם כוח על חושי.$"

Route123_Text_MiuIntro:
	.string "מיו: שלום, מאמ{SWAP_NUN}{ADD_TAF}. אני מקווה\n"
	.string "שהפוקימונים שלך לא יבכו כשהם יפסידו.$"

Route123_Text_MiuDefeat:
	.string "מיו: או או, הפסדנו.$"

Route123_Text_MiuPostBattle:
	.string "מיו: מאמנ{SWAP_NUN}{ADD_TAF}, הפוקימונים שלך\n"
	.string "חזקים כי אתם חברים.$"

Route123_Text_MiuNotEnoughMons:
	.string "מיו: זה לא כיף להילחם אם אין לך\n"
	.string "שני פוקימונים.$"

Route123_Text_YukiIntro:
	.string "יוקי: אוקיי!\n"
	.string "אנחנו מביסים את הפוקימון של המאמ{SWAP_NUN}{ADD_TAF} הזה!$"

Route123_Text_YukiDefeat:
	.string "יוקי: או או, הפסדנו.$"

Route123_Text_YukiPostBattle:
	.string "יוקי: למה את{EMIT_HEY} כל כך חזק{ADD_HEY}?\n"
	.string "אנחנו מעולם לא הפסדנו קודם.$"

Route123_Text_YukiNotEnoughMons:
	.string "יוקי: זה לא כיף להילחם אם אין לך\n"
	.string "שני פוקימונים.$"

Route123_Text_KindraIntro:
	.string "הר המוקד…\n"
	.string "שם רוחות הפוקימון ישנות…\l"
	.string "האם הפוקימונים שלך ישנו?$"

Route123_Text_KindraDefeat:
	.string "מוצף בחיוניות…$"

Route123_Text_KindraPostBattle:
	.string "הר המוקד…\n"
	.string "שם רוחות הפוקימון ישנות…\p"
	.string "זה בוודאי מוצף בכוח שמרגיע\n"
	.string "את הרוחות…$"

Route123_Text_FernandoIntro:
	.string "אני אכבה לך את האורות\n"
	.string "כששאני נהנה מהמנגינה הזו!$"

Route123_Text_FernandoDefeat:
	.string "היי, חכ{EMIT_HEY}{ADD_YUD}!\n"
	.string "אני עדיין הייתי באמצע הפתיח!$"

Route123_Text_FernandoPostBattle:
	.string "את{EMIT_HEY} סלע יציב.\n"
	.string "אשמח לכתוב מנגינה עליך.$"

Route123_Text_FernandoRegister:
	.string "בפעם הבאה, הקש{ADD_YUD}ב{ADD_YUD} למנגינה במלואו, כן?$"

Route123_Text_FernandoRematchIntro:
	.string "היום זה היום שאעשה זאת!\n"
	.string "אני אכבה את האור שלך לפני\l"
	.string "שאסיים לשיר את שירי!$"

Route123_Text_FernandoRematchDefeat:
	.string "הי, חכ{EMIT_HEY}{ADD_YUD}!\n"
	.string "אני אפילו לא הגעתי לפזמון!$"

Route123_Text_FernandoPostRematch:
	.string "חשבתי שתתפלא{ADD_YUD} כל כך מהמנגינה שלי\n"
	.string "כך שתפסידי.$"

Route123_Text_DavisIntro:
	.string "זה הפוקימון חרק המדהים שלי!\n"
	.string "האח הגדול שלי השיג אותו בשבילי.$"

Route123_Text_DavisDefeat:
	.string "וואאאאאה!\n"
	.string "איזה רע{ADD_HEY} את{EMIT_HEY}!$"

Route123_Text_DavisPostBattle:
	.string "אל תגיד{ADD_YUD} לאחי שהפסדתי.\n"
	.string "עליך לשמור את זה בסוד!$"

Route123_Text_JazmynIntro:
	.string "הביטחון העצמי שלי יעלה\n"
	.string "כשאני אביס מישהו חזק בבירור!$"

Route123_Text_JazmynDefeat:
	.string "הביטחון שלי אבד…$"

Route123_Text_JazmynPostBattle:
	.string "אומרים שאי אפשר לשפוט אדם\n"
	.string "מפי מראהו.\p"
	.string "אבל לעיתים המראה לא משקר…$"

Route123_Text_FrederickIntro:
	.string "שלום, ילד{ADD_HEY}!\n"
	.string "האם תוכל{ADD_YUD} להקדיש מעט זמן?$"

Route123_Text_FrederickDefeat:
	.string "אה, ילד{ADD_HEY} מוכשר{ADD_TAF}!\n"
	.string "ת{SWAP_NUN}{ADD_YUD} לי לתרום לקצבתך.$"

Route123_Text_FrederickPostBattle:
	.string "לתרום לקצבה שלך?\n"
	.string "האם פרס הכסף לא הספיק?$"

Route123_Text_AlbertoIntro:
	.string "אני חייב להגיד לך, פוקימוני ציפור\n"
	.string "הם האובססיה שלי!\p"
	.string "ציפורים זה מגניב!\n"
	.string "הן הכי טובות!$"

Route123_Text_AlbertoDefeat:
	.string "אפילו בהפסד, פוקימוני ציפור מגניבים!$"

Route123_Text_AlbertoPostBattle:
	.string "אני אוסף נוצות של פוקימוני ציפור\n"
	.string "שעפות בקרבות.\p"
	.string "אני הולך לעשות כובע מנוצות\n"
	.string "של פוקימוני ציפור.$"

Route123_Text_EdIntro:
	.string "כשאין מאמנים בסביבה,\n"
	.string "אני משאיר את הפוקימונים שלי\l"
	.string "להיות זה עם זה וצופה בהם.$"

Route123_Text_EdDefeat:
	.string "אני די אוהב את הפוקימונים שלך.$"

Route123_Text_EdPostBattle:
	.string "חהחה, אני לוקח את רעיונות הקרב שלך!\n"
	.string "אולי זה יהפוך אותי לטוב יותר.$"

Route123_Text_JonasIntro:
	.string "אני מתצפת במארב, ומאמ{SWAP_NUN}{ADD_TAF} נפל{ADD_HEY}\n"
	.string "למלכודת שלי!$"

Route123_Text_JonasDefeat:
	.string "אם את{EMIT_HEY} לא מפסיד{ADD_HEY}, איך אני אמור\n"
	.string "להנות מלהיות נינג'ה?$"

Route123_Text_JonasPostBattle:
	.string "אני הולך לארוב למאמן שנראה\n"
	.string "חלש יותר בפעם הבאה.$"

Route123_Text_KayleyIntro:
	.string "קניתי זה עתה את המטרייה הזו.\n"
	.string "החמידות שלי עלתה בשליש!$"

Route123_Text_KayleyDefeat:
	.string "את{EMIT_HEY} טוב{ADD_HEY} ממני בערך\n"
	.string "חמש פעמים!$"

Route123_Text_KayleyPostBattle:
	.string "שימוש נכון באביזרים הוא\n"
	.string "הסוד של הופעה אופנתית.$"

Route124_Text_SpencerIntro:
	.string "הי, האם את{EMIT_HEY} אבוד{ADD_HEY} בים?\p"
	.string "אם תצליח{ADD_HEY} להביס את הפוקימונים שלי,\n"
	.string "אני אוכל להיות ההגאי שלך.$"

Route124_Text_SpencerDefeat:
	.string "איבדתי את הכיוון בקרב!$"

Route124_Text_SpencerPostBattle:
	.string "הרבה אנשים מאבדים כיוון בים.\p"
	.string "אם את{EMIT_HEY} כזה, כדאי לך להסתכל\n"
	.string "על מפת הפוקינווט.$"

Route124_Text_RolandIntro:
	.string "המ! את{EMIT_HEY} רוכב{ADD_TAF} על פוקימון במקום\n"
	.string "לשחות בעצמך…\p"
	.string "אני מקנא!$"

Route124_Text_RolandDefeat:
	.string "או!\n"
	.string "אני לא יכול…$"

Route124_Text_RolandPostBattle:
	.string "אני מרגיש קר…\n"
	.string "הייתי במים יותר מדי זמן…\p"
	.string "הלוואי והייתי יכול לרכב על פוקימון כמוך…$"

Route124_Text_JennyIntro:
	.string "אם את{EMIT_HEY} פשוט צ{SWAP_PEY}{ADD_HEY} כך בים,\n"
	.string "פוקימונים יבואו לשחק סביבך.$"

Route124_Text_JennyDefeat:
	.string "או, חבל.\n"
	.string "ניסיתי והפסדתי.$"

Route124_Text_JennyPostBattle:
	.string "בזמן השחייה שמתי לב שחלק מהפוקימונים\n"
	.string "תוקפים וחלק רק צופים.\p"
	.string "נראה שלפוקימונים יש\n"
	.string "אישיות משלהם.$"

Route124_Text_JennyRegister:
	.string "זה רק פתאום, אבל אולי אבקש\n"
	.string "שתרש{EMIT_VAV}{SWAP_MEM}{ADD_YUD} אותי בפוקינווט שלך.$"

Route124_Text_JennyRematchIntro:
	.string "אם את{EMIT_HEY} צ{SWAP_PEY}{ADD_HEY} כך בים,\n"
	.string "מאמנים יאתגרו אותך!$"

Route124_Text_JennyRematchDefeat:
	.string "זה מוזר…\n"
	.string "הפסדתי שוב…$"

Route124_Text_JennyPostRematch:
	.string "זה לא קשור לכלום,\n"
	.string "אבל אולי אבקר בבית הטריקים.$"

Route124_Text_GraceIntro:
	.string "נמאס לי כבר לשחות…\n"
	.string "מה עם קרב?$"

Route124_Text_GraceDefeat:
	.string "לא ידעתי שאת{EMIT_HEY} כל כך\n"
	.string "חזק{ADD_HEY}!$"

Route124_Text_GracePostBattle:
	.string "כל המאמץ שלך בטח הפך אותך\n"
	.string "לקשוח{ADD_HEY} כזה.$"

Route124_Text_ChadIntro:
	.string "פופופופו… אני צולל עמוק מתחת למים\n"
	.string "כדי להסתוות.\l"
	.string "צלילה לעומק זה המומחיות שלי!$"

Route124_Text_ChadDefeat:
	.string "בלופ, בלופ, בלופ…\n"
	.string "אני טובע…$"

Route124_Text_ChadPostBattle:
	.string "יש לי מידע מהימן שיש כאן נקודת צלילה.\p"
	.string "זה מעורר בי את הנטייה להיכנס\n"
	.string "לעומק שוב…$"

Route124_Text_LilaIntro:
	.string "לילה: אנחה…\p"
	.string "הנה אני בים, אבל מי לצידי?\n"
	.string "אחי הקטן!\p"
	.string "בוא{ADD_YUD} נילחם כדי שלא אהרהר\n"
	.string "על זה!$"

Route124_Text_LilaDefeat:
	.string "לילה: רוי! זו אשמתך שהפסדנו!\n"
	.string "תראה מה מחכה לך אחר כך!$"

Route124_Text_LilaPostBattle:
	.string "לילה: אנחה…\p"
	.string "הלוואי שלידי לא היה אחי הקטן\n"
	.string "אלא חבר נחמד…$"

Route124_Text_LilaNotEnoughMons:
	.string "לילה: את{EMIT_HEY} מתכנ{SWAP_NUN}{ADD_TAF} להילחם בנו?\n"
	.string "לא אלא אם יש לך שני פוקימונים.$"

Route124_Text_RoyIntro:
	.string "רוי: אחותי הגדולה קשוחה בפוקימון!\p"
	.string "אל תבכה כשאת{EMIT_HEY} תפסיד{ADD_YUD}!$"

Route124_Text_RoyDefeat:
	.string "רוי: או או…\n"
	.string "אחותי הגדולה תכעס עליי…$"

Route124_Text_RoyPostBattle:
	.string "רוי: אחותי הגדולה מפחידה מאוד\n"
	.string "כשהיא כועסת.\p"
	.string "לכן אין לה חבר כרגע.$"

Route124_Text_LilaRoyRegister:
	.string "רוי: את{EMIT_HEY} תילח{SWAP_MEM}{ADD_YUD} בנו שוב?\n"
	.string "אבל קח{ADD_YUD} זאת בקלות יותר הפעם, אוקיי?$"

Route124_Text_RoyNotEnoughMons:
	.string "רוי: את{EMIT_HEY} רצית להילחם בנו?\n"
	.string "אז הב{ADD_YUD}א{ADD_YUD} שני פוקימונים.$"

Route124_Text_LilaRematchIntro:
	.string "לילה: אנחה…\p"
	.string "הנה אני בים, אבל מי לצידי?\n"
	.string "אחי הקטן!\p"
	.string "או, הי, כבר מזמן לא נפגשנו. בוא{ADD_YUD}\n"
	.string "נלחם כדי שלא אהרהר על דברים!$"

Route124_Text_LilaRematchDefeat:
	.string "לילה: רוי!\n"
	.string "זו אשמתך שהפסדנו שוב!\p"
	.string "יהיו לנו אימונים אחר כך!$"

Route124_Text_LilaPostRematch:
	.string "לילה: אנחה…\p"
	.string "לו היה לי חבר נחמד, היינו מנצחים\n"
	.string "את כולם בשילובים מקסימים…$"

Route124_Text_LilaRematchNotEnoughMons:
	.string "לילה: את{EMIT_HEY} מתכוו{SWAP_NUN}{ADD_TAF} להילחם בנו?\n"
	.string "לא אלא אם יש לך שני פוקימונים.$"

Route124_Text_RoyRematchIntro:
	.string "רוי: אם נפסיד, יקחו את מקומי.\n"
	.string "אני הולך להילחם בכל הכוח!$"

Route124_Text_RoyRematchDefeat:
	.string "רוי: או או…\n"
	.string "אחותי תכעס עליי שוב.$"

Route124_Text_RoyPostRematch:
	.string "רוי: אחותי הגדולה מפחידה כשהיא כועסת.\p"
	.string "היא תכריח אותי להתאמן קשה\n"
	.string "עם הפוקימונים מאוחר יותר…$"

Route124_Text_RoyRematchNotEnoughMons:
	.string "רוי: את{EMIT_HEY} רצית להילחם בנו?\n"
	.string "אז הב{ADD_YUD}א{ADD_YUD} שני פוקימון.$"

Route124_Text_DeclanIntro:
	.string "הנה אני שוחה לבד\n"
	.string "על הים הרחב והיפה הזה.\p"
	.string "אין מילים אחרות.\n"
	.string "זה עלוב!$"

Route124_Text_DeclanDefeat:
	.string "אני מרגיש מדוכדך.\n"
	.string "כחול כמו השמיים…$"

Route124_Text_DeclanPostBattle:
	.string "עליי לפתח שיחה עם השחייניות\n"
	.string "ולהזמין אותן לשחייה ארוכה.$"

Route124_Text_IsabellaIntro:
	.string "אני לא הולכת להפסיד למאמ{SWAP_NUN}{ADD_TAF}\n"
	.string "גלישה כזה.$"

Route124_Text_IsabellaDefeat:
	.string "יש לי רק זיעה בעיניים!\n"
	.string "אני לא בוכה!$"

Route124_Text_IsabellaPostBattle:
	.string "כאן אפשר למצוא רסיסים\n"
	.string "של חפצים בצבעים יפים.$"

Route125_Text_NolenIntro:
	.string "שמעתי אותך מתקרב{ADD_TAF}, אז המתנתי\n"
	.string "לך כאן!$"

Route125_Text_NolenDefeat:
	.string "אני נכנע!$"

Route125_Text_NolenPostBattle:
	.string "הקול עובר במים מהר יותר\n"
	.string "מאשר באוויר.$"

Route125_Text_StanIntro:
	.string "היי שם!\n"
	.string "תסתכל{ADD_YUD} על הפוקימון המתוק שלי!$"

Route125_Text_StanDefeat:
	.string "כשלתי…$"

Route125_Text_StanPostBattle:
	.string "הקסם של {STR_VAR_1} היכה בי,\n"
	.string "ואז גם אני התחלתי לשחות.$"

Route125_Text_TanyaIntro:
	.string "נמאס לי לשחות.\n"
	.string "האם תרצ{EMIT_HEY}{ADD_YUD} להילחם מולי?$"

Route125_Text_TanyaDefeat:
	.string "את{EMIT_HEY} פשוט יותר מדי!$"

Route125_Text_TanyaPostBattle:
	.string "ווהו…\n"
	.string "לאיזה כיוון זה לעיר מוסדיפ?$"

Route125_Text_SharonIntro:
	.string "רוצה להתמודד מול הפוקימון מסוג\n"
	.string "מים שגידלתי?$"

Route125_Text_SharonDefeat:
	.string "איבדתי את זה…$"

Route125_Text_SharonPostBattle:
	.string "הכוח שלך… את{EMIT_HEY} הדבר האמיתי.\n"
	.string "אני מופתעת!$"

Route125_Text_ErnestIntro:
	.string "אהוי! אני מלח חזק וקשוח!\n"
	.string "חציתי את הימים של העולם!$"

Route125_Text_ErnestDefeat:
	.string "גוררוווואר!\n"
	.string "לא הצלחתי לנצח!$"

Route125_Text_ErnestPostBattle:
	.string "הגל עולה ויורד בתוך מערת השרטון.\p"
	.string "אגב, בין גאות לשפל עוברים שש שעות.\n"
	.string "האם ידעת?$"

Route125_Text_ErnestRegister:
	.string "רש{EMIT_VAV}{SWAP_MEM}{ADD_YUD} אותי בפוקינווט שלך,\n"
	.string "ואגיד לך משהו מועיל.$"

Route125_Text_ErnestRematchIntro:
	.string "הגיע הזמן שאקבל את נקמתי ממך!\n"
	.string "בוא{ADD_YUD}, אנחנו נלחמים!$"

Route125_Text_ErnestRematchDefeat:
	.string "אני לא הצלחתי לנצח!\n"
	.string "אני באמת שלא הצלחתי לנצח!$"

Route125_Text_ErnestRematchPostBattle:
	.string "מערת השרטון…\p"
	.string "יש מקומות שאליהם אפשר ולא אפשר\n"
	.string "להגיע בהתאם לעלייה וירידת\l"
	.string "הגאות ושפל.\p"
	.string "אגב, בין גאות לשפל יש שש שעות?\n"
	.string "אל תשכח{ADD_YUD}!$"

Route125_Text_KimIntro:
	.string "קים: איש זקן ומצחיק גר במערת השרטון.\n"
	.string "מישהו אמר לי כך.\l"
	.string "את{EMIT_HEY} גם עומד{ADD_TAF} לראות אותו?$"

Route125_Text_KimDefeat:
	.string "קים: חשבתי שננצח.$"

Route125_Text_KimPostBattle:
	.string "קים: איש זקן ומצחיק גר במערת השרטון, לא כך?\p"
	.string "בוא{ADD_YUD} נלך לראות אותו, איריס!$"

Route125_Text_KimNotEnoughMons:
	.string "קים: לא, לא, לא! את{EMIT_HEY} צרי{SWAP_CHAF}{ADD_HEY} שני פוקימונים,\n"
	.string "או שזה פשוט לא טוב!$"

Route125_Text_IrisIntro:
	.string "איריס: קים, האם תוכל להגיד לי מה\n"
	.string "אנחנו מחפשים כאן?$"

Route125_Text_IrisDefeat:
	.string "איריס: היינו קרובים בערך.$"

Route125_Text_IrisPostBattle:
	.string "איריס: קים, אנחנו באמת נכנסים\n"
	.string "למערת השרטון?\l"
	.string "אנחנו נירטב כולנו.$"

Route125_Text_IrisNotEnoughMons:
	.string "איריס: או, לעולם לא נוכל לעשות\n"
	.string "קרב 2-על-1 כזה.$"

Route125_Text_PresleyIntro:
	.string "מדוע שומר ציפורים כמוני\n"
	.string "יגיע לים?$"

Route125_Text_PresleyDefeat:
	.string "אוקיי.\n"
	.string "אני אגיד לך מדוע הגעתי לכאן.$"

Route125_Text_PresleyPostBattle:
	.string "שמתי הודעה בבקבוק וזרקתי\n"
	.string "אותו לים.\p"
	.string "אני בטוח ששחיינית תמצא אותו!$"

Route125_Text_AuronIntro:
	.string "היי! זה את{EMIT_HEY} שהשלכת זבל\n"
	.string "לים?$"

Route125_Text_AuronDefeat:
	.string "אה, את{EMIT_HEY} לא זרקת זבל לים.$"

Route125_Text_AuronPostBattle:
	.string "מצאתי בקבוק מכוער צף בגלים קודם.\p"
	.string "זה מכעיס אותי שמישהו מזהם את הים!$"

Route126_Text_BarryIntro:
	.string "שחייה היא אימון לכל הגוף!\n"
	.string "את{EMIT_HEY} תיכנס{ADD_YUD} לכושר!$"

Route126_Text_BarryDefeat:
	.string "אני מודה בזה!\n"
	.string "את{EMIT_HEY} מנצח{ADD_TAF}!$"

Route126_Text_BarryPostBattle:
	.string "תודות לשגרת השחייה היומית שלי…\n"
	.string "תרא{EMIT_HEY}{ADD_YUD}! תתענג{ADD_YUD} בעיניך במבנה הגוף הזה!$"

Route126_Text_DeanIntro:
	.string "ההר הלבן והגבוה הזה\n"
	.string "הוא העיר סוטופוליס.$"

Route126_Text_DeanDefeat:
	.string "האם הובסתי?$"

Route126_Text_DeanPostBattle:
	.string "אני לא מצליח למצוא את הכניסה\n"
	.string "לסוטופוליס. איפה היא יכולה להיות?$"

Route126_Text_NikkiIntro:
	.string "אופופופו!\n"
	.string "אני בת ים!$"

Route126_Text_NikkiDefeat:
	.string "הפנטזיה שלי התפוצצה כאילו הייתה בועה!\n"
	.string "בלופ, בלופ, בלופ…$"

Route126_Text_NikkiPostBattle:
	.string "הכית בי… אני רוצה\n"
	.string "להיעלם בגל של ייאוש…$"

Route126_Text_BrendaIntro:
	.string "שלום, ילדון!\n"
	.string "רוצה קרב איתי?$"

Route126_Text_BrendaDefeat:
	.string "או, לאאאאאא!$"

Route126_Text_BrendaPostBattle:
	.string "אני אוהבת לשחק עם פוקימון\n"
	.string "בים ככה!$"

Route126_Text_PabloIntro:
	.string "תסתכל על הגוף המפוסל הזה!\n"
	.string "אני אפילו חטוב יותר מחגורה שחורה!$"

Route126_Text_PabloDefeat:
	.string "וופס! חזק מדי!\n"
	.string "לא רע! לא רע בכלל!$"

Route126_Text_PabloPostBattle:
	.string "ההפסד ממך עורר את חושיי!\n"
	.string "אני אאמן אותי ואת הפוקימונים שלי חזק יותר!$"

Route126_Text_PabloRegister:
	.string "כן, את{EMIT_HEY} ממש לא רע{ADD_HEY}!\n"
	.string "אני אשמח להכיר אותך יותר!$"

Route126_Text_PabloRematchIntro:
	.string "תסתכל על הגוף היפה הזה!\n"
	.string "אני יותר מעוצב משחיין!$"

Route126_Text_PabloRematchDefeat:
	.string "וופס! באמת חזק מדי!\n"
	.string "לא רע! לא רע בכלל!$"

Route126_Text_PabloPostRematch:
	.string "אני אלמד להתאמן חזק עוד יותר!\n"
	.string "את{EMIT_HEY} מוטיבציה נהדרת!\l"
	.string "עליך לחזור שוב!$"

Route126_Text_LeonardoIntro:
	.string "שנה שעברה לא יכולתי לשחות,\n"
	.string "אבל עכשיו אני שוחה טוב.\p"
	.string "אני מרגיש שאני יכול הכל עכשיו.$"

Route126_Text_LeonardoDefeat:
	.string "אויש, תאוות הבצע לא עשתה לי שום טוב.$"

Route126_Text_LeonardoPostBattle:
	.string "אם מתאמנים במשהו,\n"
	.string "נהיים טובים בו.\p"
	.string "את{EMIT_HEY} צעיר{ADD_HEY}--אל תפחד{ADD_YUD}\n"
	.string "לנסות כל מיני דברים!$"

Route126_Text_IsobelIntro:
	.string "אם מי הים נכנסים לאף,\n"
	.string "זה לא מרגיש נוראי?$"

Route126_Text_IsobelDefeat:
	.string "אח! למה, את{EMIT_HEY}…\n"
	.string "בלופ!$"

Route126_Text_IsobelPostBattle:
	.string "אוו, נחנקתי מקצת מים!\n"
	.string "זה מר! זה מלוח!!$"

Route126_Text_SiennaIntro:
	.string "אני משקיעה את כל ליבי\n"
	.string "בזה!$"

Route126_Text_SiennaDefeat:
	.string "היה לך יותר נשמה!$"

Route126_Text_SiennaPostBattle:
	.string "אני צריכה להירגע עכשיו…\n"
	.string "אולי אלך לצלול.$"

Route127_Text_CamdenIntro:
	.string "אני רואה את זה בפניך.\n"
	.string "את{EMIT_HEY} רוצה לאתגר אותי.$"

Route127_Text_CamdenDefeat:
	.string "אואואוואואוא…$"

Route127_Text_CamdenPostBattle:
	.string "קרב מחושב משאיר אותי\n"
	.string "רענן ושלו.$"

Route127_Text_DonnyIntro:
	.string "האם יש לך יריב שאת{EMIT_HEY} פשוט\n"
	.string "שונא{ADD_TAF} להפסיד מולו?$"

Route127_Text_DonnyDefeat:
	.string "אחחח!\n"
	.string "אני שונא להפסיד!$"

Route127_Text_DonnyPostBattle:
	.string "אם יש לך יריב, האם זה לא מרגיש\n"
	.string "שחייבים להשתפר כל הזמן?$"

Route127_Text_JonahIntro:
	.string "באמצעות דיג הגעתי למצב\n"
	.string "של שלוות רוח…\p"
	.string "נא, הרש{EMIT_HEY}{ADD_YUD} לי להדגים…$"

Route127_Text_JonahDefeat:
	.string "למרות שהפסדתי, לבי נשאר\n"
	.string "שלו…$"

Route127_Text_JonahPostBattle:
	.string "זה לא משנה שלא תפסתי כלום.\n"
	.string "החכה עדיין במים…$"

Route127_Text_HenryIntro:
	.string "וופס! אל תגיד שדגתי\n"
	.string "פוקימון שגולש?$"

Route127_Text_HenryDefeat:
	.string "אני לא יכול לעמוד בקצב!$"

Route127_Text_HenryPostBattle:
	.string "זאת הייתה מעמסה אם הייתי תופס\n"
	.string "את הפוקימונים הקשוחים שלך!$"

Route127_Text_RogerIntro:
	.string "ובכן, היי! זה קרב בין אוהד פוקימון\n"
	.string "ולמקצוען דיג!$"

Route127_Text_RogerDefeat:
	.string "לא! החכה שלי הסתבכה!\n"
	.string "המסיבה נגמרה!$"

Route127_Text_RogerPostBattle:
	.string "חכת הדיג שלי רוקדת!\n"
	.string "טנגו הסתבכויות! האהאהא, נהמה!$"

Route127_Text_AidanIntro:
	.string "פוקימוני ציפור בעלי ראייה מעולה.\n"
	.string "הם מבחינים בטרף מגבהים עצומים.$"

Route127_Text_AidanDefeat:
	.string "ווהו… אני מוותר.$"

Route127_Text_AidanPostBattle:
	.string "יש כאן המון נקודות צלילה בים.\p"
	.string "תוכל{ADD_YUD} לזהות אותן בקלות מהשמיים\n"
	.string "בזכות צבען הכהה.$"

Route127_Text_KojiIntro:
	.string "ריצה יחפים.\n"
	.string "זה יחשל את כפות רגליך!$"

Route127_Text_KojiDefeat:
	.string "יאווץ'!\n"
	.string "נתקעה לי אבן מתחת לציפורן!$"

Route127_Text_KojiPostBattle:
	.string "ללכת יחף מרגיש נהדר.\n"
	.string "אבל נעלי הריצה שלך גם מגניבות.$"

Route127_Text_KojiRegister:
	.string "זה מה שעשיתי לאנשים שהביסו אותי!\n"
	.string "אני מקווה שנוכל לחזור על זה שוב.$"

Route127_Text_KojiRematchIntro:
	.string "אני עדיין רץ יחף מדי יום.\n"
	.string "כפות רגלי קשוחות!$"

Route127_Text_KojiRematchDefeat:
	.string "יאווץ'!\n"
	.string "אבנים נתקעו בין אצבעות רגליי!$"

Route127_Text_KojiPostRematch:
	.string "רוצה לרוץ יחף לזמן מה?\n"
	.string "כדי שאוכל לנסות את נעלי הריצה שלך?$"

Route127_Text_AthenaIntro:
	.string "עלינו לערוך משחק איטי ושיטתי\n"
	.string "כזה.$"

Route127_Text_AthenaDefeat:
	.string "לא נתת לי הזדמנות\n"
	.string "לחשוב על אסטרטגיה.$"

Route127_Text_AthenaPostBattle:
	.string "כשאני מוקפת בים ובשמיים הכחולים,\n"
	.string "זה מרגיש כאילו הזמן מאט.$"

Route128_Text_IsaiahIntro:
	.string "עיר אבר גרנדה עוד רחוקה\n"
	.string "ממש…$"

Route128_Text_IsaiahDefeat:
	.string "ניצחוני הראשון נראה גם הוא\n"
	.string "רחוק מדי…$"

Route128_Text_IsaiahPostBattle:
	.string "כל חיי היו על הפסד,\n"
	.string "אבל לעולם לא אתייאש!$"

Route128_Text_IsaiahRegister:
	.string "אני יודע שלא טוב כרגע, אבל\n"
	.string "אני יכול לנצח בסופו של דבר.\p"
	.string "רש{EMIT_VAV}{SWAP_MEM}{ADD_YUD} אותי בפוקינווט שלך.$"

Route128_Text_IsaiahRematchIntro:
	.string "אני עדיין מרגיש טוב. אני אמשיך לשחות\n"
	.string "לעבר עיר אבר גרנדה.$"

Route128_Text_IsaiahRematchDefeat:
	.string "אני עדיין לא טעמתי את ניצחוני הראשון…$"

Route128_Text_IsaiahPostRematch:
	.string "בסופו של דבר אגיע לעיר אבר גרנדה\n"
	.string "שם אוכל לנצח…$"

Route128_Text_KatelynIntro:
	.string "עליך לשחות, לרכוב ואז לרוץ\n"
	.string "מרתון בטריאתלון.\p"
	.string "זה מרוץ מקיף שמורכב\n"
	.string "משלוש תחרויות.$"

Route128_Text_KatelynDefeat:
	.string "קרב פוקימון גם הוא תובעני…$"

Route128_Text_KatelynPostBattle:
	.string "עליי לרכוב אופניים עכשיו, אבל…\n"
	.string "אני עומדת לוותר…$"

Route128_Text_KatelynRegister:
	.string "ובכן, כדאי שאתחיל להפיק\n"
	.string "את המיטב. אני אשמח לקרב חוזר בעתיד.$"

Route128_Text_KatelynRematchIntro:
	.string "טריאתלון ארוך. אבל כנראה שהדרך\n"
	.string "להיות אלוף הפוקימון\l"
	.string "גם היא ארוכה ומתישה.$"

Route128_Text_KatelynRematchDefeat:
	.string "קרב פוקימון הוא אכן קשוח\n"
	.string "ולא סלחני…$"

Route128_Text_KatelynPostRematch:
	.string "עליך לשקול ברצינות\n"
	.string "את האתגרים שבדרך הניצחון.$"

Route128_Text_AlexaIntro:
	.string "עבדנו קשה כדי לקחת חלק\n"
	.string "בליגת הפוקימון…\p"
	.string "אין לנו רשות להפסיד עכשיו!$"

Route128_Text_AlexaDefeat:
	.string "או!\n"
	.string "איך זה יכל לקרות?!$"

Route128_Text_AlexaPostBattle:
	.string "אחרי כל מה שעשיתי כדי להגיע הנה,\n"
	.string "אני לא אתייאש בגלל כישלון אחד.$"

Route128_Text_RubenIntro:
	.string "אין מאמן חזק ממני!$"

Route128_Text_RubenDefeat:
	.string "זה לא ייתכן!$"

Route128_Text_RubenPostBattle:
	.string "כנראה שאין מאמן חזק ממך!$"

Route128_Text_WayneIntro:
	.string "אני רוצה לבקר באבר גרנדה, לכן\n"
	.string "תפסתי פוקימון שיודע את המהלך\l"
	.string "מפל מים כדי לעלות את המפלים.$"

Route128_Text_WayneDefeat:
	.string "אני מתרסק!$"

Route128_Text_WaynePostBattle:
	.string "אווו, פוואי!\p"
	.string "הפוקימון שלי יודע מפל מים, אבל\n"
	.string "אין לי את תג המכון של סוטופוליס!$"

Route128_Text_HarrisonIntro:
	.string "את{EMIT_HEY} נראה נורא קשוח.\n"
	.string "אני תוהה אם אצליח לנצח?$"

Route128_Text_HarrisonDefeat:
	.string "אאוץ'!\n"
	.string "אני מניח שזה היה בלתי אפשרי לנצח.$"

Route128_Text_HarrisonPostBattle:
	.string "יש כאן המון מאמנים קשוחים\n"
	.string "סביב אבר גרנדה.\p"
	.string "אולי זה קצת מעל ליכולתי?$"

Route128_Text_CarleeIntro:
	.string "היום השמש פה נראית חזקה יותר\n"
	.string "באזור הזה.$"

Route128_Text_CarleeDefeat:
	.string "אני לא ראיתי היטב בגלל השמש\n"
	.string "הבוהקת.$"

Route128_Text_CarleePostBattle:
	.string "אני צריך לחזור בקרוב.\n"
	.string "אני חייבת למרוח שוב קרם הגנה.$"

Route129_Text_ChaseIntro:
	.string "זה הטריאתלון הראשון שלי.\n"
	.string "אני לחוץ וחרד!$"

Route129_Text_ChaseDefeat:
	.string "ורואאאר!\n"
	.string "אני לא הצלחתי לנצח!$"

Route129_Text_ChasePostBattle:
	.string "אם אני אהיה מתוח מדי, אני לא אצליח\n"
	.string "לתת את כל כולי.$"

Route129_Text_AllisonIntro:
	.string "אני באמצע טריאתלון,\n"
	.string "אבל בטח, למה שלא נלחם?$"

Route129_Text_AllisonDefeat:
	.string "הייתי בטוחה שאנצח!$"

Route129_Text_AllisonPostBattle:
	.string "את{EMIT_HEY} יודע{ADD_TAF} מה הדבר הכי מיוחד\n"
	.string "בטריאתלונים?\p"
	.string "לבדוק את גבולות הכוח\n"
	.string "והסיבולת שלך מול\l"
	.string "כוחות הטבע!$"

Route129_Text_ReedIntro:
	.string "תגיד{ADD_YUD} היי היי!\n"
	.string "בוא{ADD_YUD} נתחיל כבר!$"

Route129_Text_ReedDefeat:
	.string "כניעה, נכנעתי.\n"
	.string "זהו זה, נגמר!$"

Route129_Text_ReedPostBattle:
	.string "אין טעם להפסיד.\n"
	.string "זה הזמן שלי לחזור הביתה.$"

Route129_Text_TishaIntro:
	.string "מה הלחץ?\n"
	.string "בוא{ADD_YUD} ניקח את זה לאט ובקלות.$"

Route129_Text_TishaDefeat:
	.string "אוי, לי.\n"
	.string "רציתי להירגע עוד קצת…$"

Route129_Text_TishaPostBattle:
	.string "האם את{EMIT_HEY} לא שונא{ADD_TAF} לטעות כשאת{EMIT_HEY}\n"
	.string "ממהר{ADD_TAF}?\p"
	.string "בגלל זה אני מנסה לקחת את הדברים\n"
	.string "באיטיות.$"

Route129_Text_ClarenceIntro:
	.string "גלישה אינה קלה כפי שנדמה,\n"
	.string "נכון?$"

Route129_Text_ClarenceDefeat:
	.string "אין זה פשוט לזכות.$"

Route129_Text_ClarencePostBattle:
	.string "יש לך מטרה שהיא ליגת הפוקימון?\n"
	.string "תמשי{SWAP_CHAF}{ADD_YUD} כך!$"

Route130_Text_RodneyIntro:
	.string "איזו הפתעה! לא ציפיתי לראות\n"
	.string "מאמ{SWAP_NUN}{ADD_TAF} בים.\p"
	.string "נראה לי שעלינו להילחם!$"

Route130_Text_RodneyDefeat:
	.string "הילד{ADD_HEY} הזה חזק{ADD_HEY} להפליא…$"

Route130_Text_RodneyPostBattle:
	.string "לעיניך יש מראה של מישה{EMIT_VAV}{ADD_YUD}\n"
	.string "שעבר{ADD_HEY} אתגרים קשים וניצח{ADD_HEY}.\l"
	.string "זה מתאים לך מאד!$"

Route130_Text_KatieIntro:
	.string "בים הכחול והעמוק,\n"
	.string "הלב הכחול והמנופץ שלי מוצא\l"
	.string "נחמה בין הגלים.$"

Route130_Text_KatieDefeat:
	.string "כמו הים הכחול והרחב,\n"
	.string "עולם הפוקימון משתרע\l"
	.string "לעומקים שאי אפשר לתפוס.$"

Route130_Text_KatiePostBattle:
    .string "ילדי העולם חולמים\n"
    .string "שיום אחד יהפכו\l"
    .string "לאלופי הפוקימון.$"

Route130_Text_SantiagoIntro:
	.string "צף על הים הפתוח ככה…\n"
	.string "זה מרגיע.$"

Route130_Text_SantiagoDefeat:
	.string "הייתי צריך להיות קצת פחות רגוע!$"

Route130_Text_SantiagoPostBattle:
	.string "שחייה ולחימה כזו…\n"
	.string "אני בחור אחד שמח…$"

Route131_Text_RichardIntro:
	.string "הים מלא בפוקימון.\n"
	.string "זה לא קל לשחות, תאמי{SWAP_NUN}{ADD_YUD} לי.$"

Route131_Text_RichardDefeat:
	.string "פוקימונים שגודלו על ידי מאמנים\n"
	.string "הם קשוחים במיוחד…$"

Route131_Text_RichardPostBattle:
	.string "נשיפה… נשיפה…\n"
	.string "אני מרוקן כוחות…\p"
	.string "הדרך קלה. העזיבה\n"
	.string "היא החלק הקשה.\p"
	.string "האם יישאר לי כוח לחזור?$"

Route131_Text_HermanIntro:
	.string "הים… הים… הים…\n"
	.string "הים כמה שאפשר לראות בעיניים!\l"
	.string "נמאס לי מהים!$"

Route131_Text_HermanDefeat:
	.string "איכס!$"

Route131_Text_HermanPostBattle:
	.string "הים משעמם אותי, אבל עלי לשחות.\p"
	.string "נולדתי לשחות!\n"
	.string "זה מה שאני.$"

Route131_Text_SusieIntro:
	.string "היי מותק, חכ{EMIT_HEY}{ADD_YUD}!\n"
	.string "אנחנו צריכים להילחם, את{EMIT_HEY} ואני!$"

Route131_Text_SusieDefeat:
	.string "את{EMIT_HEY} חזק{ADD_HEY} למרות איך\n"
	.string "שאת{EMIT_HEY} נרא{EMIT_HEY}{ADD_TAF}!$"

Route131_Text_SusiePostBattle:
	.string "ראית את הבחור שם שמתלונן\n"
	.string "שנמאס לו מהים?\p"
	.string "זה רק דיבורים.\n"
	.string "הוא מאוהב בים ללא תקנה!$"

Route131_Text_KaraIntro:
	.string "למה גברים כל כך אוהבים בגדי ים?\p"
	.string "הם מביטים בי!$"

Route131_Text_KaraDefeat:
	.string "אני מחוץ לעומק שלי!$"

Route131_Text_KaraPostBattle:
	.string "אולי זה לא בגד הים שגורם\n"
	.string "לגברים להביט. זה בטח היופי שלי!$"

Route131_Text_ReliIntro:
	.string "רלי: נעבוד יחד כאחים\n"
	.string "כדי להילחם בך!$"

Route131_Text_ReliDefeat:
	.string "רלי: לא הצלחנו לנצח אף על פי\n"
	.string "שעבדנו יחד…$"

Route131_Text_ReliPostBattle:
	.string "רלי: אנשי פסיפידלוג חיים יחד\n"
	.string "עם הים ועם הפוקימון\l"
	.string "מרגע לידתם.$"

Route131_Text_ReliNotEnoughMons:
	.string "רלי: אין לך שני פוקימונים?\n"
	.string "אז לא נוכל להנות מקרב.$"

Route131_Text_IanIntro:
	.string "יאן: אני נותן את מיטב יכולתי יחד\n"
	.string "עם אחותי!$"

Route131_Text_IanDefeat:
	.string "יאן: עשיתי את המיטב עם אחותי,\n"
	.string "אבל עדיין לא הצלחנו לנצח…$"

Route131_Text_IanPostBattle:
	.string "יאן: את{EMIT_HEY} יודע{ADD_TAF} איך פסיפידלוג היא\n"
	.string "עיירה צפה?\p"
	.string "אז בכל מקום שיש ים,\n"
	.string "זה חלק מפסיפידלוג!$"

Route131_Text_IanNotEnoughMons:
	.string "יאן: אם יש לך שני פוקימונים,\n"
	.string "נלחם בך!$"

Route131_Text_TaliaIntro:
	.string "אם תוכל{ADD_YUD} לנצח אותי, אתן לך\n"
	.string "מידע מעולה!$"

Route131_Text_TaliaDefeat:
	.string "או?\n"
	.string "האם הפסדתי?$"

Route131_Text_TaliaPostBattle:
	.string "יש מקום מוזר בקרבה.\n"
	.string "יש שם מגדל ענק.\l"
	.string "למה שלא תבדוק אותו? $"

Route131_Text_KevinIntro:
	.string "תושבי פסיפידלוג הם\n"
	.string "אנשי שלווה.\p"
	.string "הם לא כועסים.\n"
	.string "גם אני כזה.$"

Route131_Text_KevinDefeat:
	.string "אופס!$"

Route131_Text_KevinPostBattle:
	.string "אחח! או, חכ{EMIT_HEY}{ADD_YUD}.\n"
	.string "אני לא כועס. באמת!\p"
	.string "אבל ילדון, את{EMIT_HEY} חזק{ADD_HEY}!\n"
	.string "האהאהא!$"

Route132_Text_GilbertIntro:
	.string "בילדותי נתקפתי מצינון כל הזמן,\n"
	.string "אבל נהייתי בכושר לחלוטין מאז\l"
	.string "שהתחלתי לשחות.$"

Route132_Text_GilbertDefeat:
	.string "אני משתוקק לעוד כוח…$"

Route132_Text_GilbertPostBattle:
	.string "מאמנים מטיילים בשדות\n"
	.string "וברכסי ההרים, לכן גם הם חייבים להיות\n"
	.string "בכושר.$"

Route132_Text_DanaIntro:
	.string "אני משתדל לא לשחות איפה שהזרמים\n"
	.string "חזקים מדי.$"

Route132_Text_DanaDefeat:
	.string "או, בבקשה, לא!$"

Route132_Text_DanaPostBattle:
	.string "אם איסחף החוצה, אאבד את\n"
	.string "תחושת המיקום שלי…$"

Route132_Text_RonaldIntro:
	.string "לנצחאו להפסיד -- לא תדע{ADD_YUD} עד\n"
	.string "שלא תנס{EMIT_HEY}{ADD_YUD}!$"

Route132_Text_RonaldDefeat:
	.string "ואאה!\n"
	.string "שקעתי בתבוסה!$"

Route132_Text_RonaldPostBattle:
	.string "אני לא נלחם כשאני יודע שאנצח.\n"
	.string "אני אוהב להילחם על הגבול הדק\l"
	.string "בין ניצחון לתבוסה!$"

Route132_Text_KiyoIntro:
	.string "אני חושב על פוקימון 42 שעות ביממה.\n"
	.string "איך תוכל{ADD_YUD} לנצח אותי בכלל?$"

Route132_Text_KiyoDefeat:
	.string "הפסדתי.\n"
	.string "אני מודה בתבוסה.$"

Route132_Text_KiyoPostBattle:
	.string "אחחח…\n"
	.string "את{EMIT_HEY} חולה על פוקימון, לא?\p"
	.string "את{EMIT_HEY} בטח חושב{ADD_TAF} על פוקימון 42 שעות\n"
	.string "ביממה, נכון?$"

Route132_Text_MakaylaIntro:
	.string "אני תמיד עם בעלי,\n"
	.string "אבל אני יכולה לנצח גם בלעדיו.$"

Route132_Text_MakaylaDefeat:
	.string "או, כנראה שלא הייתי טובה מספיק.$"

Route132_Text_MakaylaPostBattle:
	.string "הבחור ההוא נראה בדיוק כמו בעלי\n"
	.string "כשהיה צעיר.\p"
	.string "הוא גורם לי להאדים!$"

Route132_Text_JonathanIntro:
	.string "מישהו צפה בי בעין חדה.\n"
	.string "האם זה היית את{EMIT_HEY}?$"

Route132_Text_JonathanDefeat:
	.string "וואו!\n"
	.string "זה די חזק, כן!$"

Route132_Text_JonathanPostBattle:
	.string "אני לא מצליח להיפרד מהתחושה שמישהו\n"
	.string "צופה בי.\p"
	.string "אני לא מצליח להתרכז!$"

Route132_Text_PaxtonIntro:
	.string "לאן אשתי הלכה עכשיו?\n"
	.string "אני תמיד איתה.\l"
	.string "אני תוהה אם אצליח לנצח לבדי.$"

Route132_Text_PaxtonDefeat:
	.string "אה, אני רואה שלא הצלחתי\n"
	.string "לנצח לבדי אחרי הכל.$"

Route132_Text_PaxtonPostBattle:
	.string "אשתי בטח מחפשת אותי.\n"
	.string "עליי ללכת למצוא אותה מיד.$"

Route132_Text_DarcyIntro:
	.string "אני אהבתי להתאמן כאן לבד.\n"
	.string "זה נורא שכל האנשים האלה הגיעו!$"

Route132_Text_DarcyDefeat:
	.string "אוקיי! אני לא אתלונן על נוכחות\n"
	.string "האנשים כאן.$"

Route132_Text_DarcyPostBattle:
	.string "אני אולי אתחבר לאיש הזקן ההוא\n"
	.string "ואאתגר את הקבוצה האחרת.$"

Route133_Text_FranklinIntro:
	.string "האם הזרמים הביאו גם אותך לכאן?\n"
	.string "זה כנראה לגורל.\l"
	.string "בוא{ADD_YUD} נילחם!$"

Route133_Text_FranklinDefeat:
	.string "חזק!\n"
	.string "יותר מדי!$"

Route133_Text_FranklinPostBattle:
	.string "איזה מזל רע שמאמ{SWAP_NUN}{ADD_TAF} קשוח{ADD_HEY}\n"
	.string "כמוך נסחפה לכאן…\l"
	.string "אולי אני מקולל…$"

Route133_Text_DebraIntro:
	.string "חייתי חיים קשים ומלאי סבל…\n"
	.string "הורחקתי, וזה המקום שבו\l"
	.string "הגעתי לשוטט…$"

Route133_Text_DebraDefeat:
	.string "עוד הפסד…$"

Route133_Text_DebraPostBattle:
	.string "חיים בסחיפה…\n"
	.string "אני לא רוצה את זה יותר!$"

Route133_Text_LindaIntro:
	.string "שלום!\n"
	.string "ציפיתי לבואך!$"

Route133_Text_LindaDefeat:
	.string "לא! בבקשה!$"

Route133_Text_LindaPostBattle:
	.string "מאמ{SWAP_NUN}{ADD_TAF} ילד{ADD_HEY} חזק{ADD_HEY}…\n"
	.string "זה כל כך מציק!$"

Route133_Text_WarrenIntro:
	.string "אני רוצה לנצח כמו כולם, אבל\n"
	.string "אני לא אגדל פוקימון כמו כולם.$"

Route133_Text_WarrenDefeat:
	.string "לעזאזל!\n"
	.string "הדרך שלי עדיין רפויה מדי!$"

Route133_Text_WarrenPostBattle:
	.string "כיף יותר לעשות דברים בדרך שלי\n"
	.string "מאשר להיות כמו כולם. זה ברור!$"

Route133_Text_BeckIntro:
	.string "באתי עד הנה עם הפוקימון ציפור שלי.$"

Route133_Text_BeckDefeat:
	.string "את{EMIT_HEY}…\n"
	.string "את{EMIT_HEY} מדהי{SWAP_MEM}{ADD_HEY} להפליא!$"

Route133_Text_BeckPostBattle:
	.string "הייתי רוצה לחזור לפורטרי,\n"
	.string "אבל גם התרגלתי לאהוב את המקום הזה.$"

Route133_Text_MollieIntro:
	.string "אני בטח נלחמתי אלפי פעמים.\n"
	.string "איבדתי את הספירה.$"

Route133_Text_MollieDefeat:
	.string "אני אולי הפסדתי אלפים של פעמים,\n"
	.string "אבל הפסד עדיין כואב.$"

Route133_Text_MolliePostBattle:
	.string "המש{ADD_YUD}{SWAP_CHAF}{ADD_YUD} כך, צעיר{ADD_HEY}. כדי שתוכל{ADD_YUD}\n"
	.string "להיות כמו בעלי ואני.$"

Route133_Text_ConorIntro:
	.string "צעירים שמחים מדי ללכת עם הזרם.\n"
	.string "הם חסרי כיוון.$"

Route133_Text_ConorDefeat:
	.string "יש לך תחושת מטרה איתנה.$"

Route133_Text_ConorPostBattle:
	.string "אל תית{SWAP_NUN}{ADD_YUD} לאחרים להוליך אותך בדרך שגויה.\n"
	.string "אל תאבד{ADD_YUD} כיוון כשאת{EMIT_HEY} מתבגר{ADD_TAF}.$"

Route134_Text_JackIntro:
	.string "אפילו פוקימונים שיכולים לשחות\n"
	.string "נישאים לאורך הזרמים המהירים.$"

Route134_Text_JackDefeat:
	.string "אייייה!$"

Route134_Text_JackPostBattle:
	.string "אני חושב שפוקימונים נהנים מהזרמים\n"
	.string "המהירים באזור הזה.$"

Route134_Text_LaurelIntro:
	.string "ה{STR_VAR_1} שלי מחפש קרב מהנה.\n"
	.string "האם תצטר{SWAP_PEY}{ADD_YUD} אלינו?$"

Route134_Text_LaurelDefeat:
	.string "אוופסי!$"

Route134_Text_LaurelPostBattle:
	.string "יש אספן שהוא אחרי\n"
	.string "הקשקשים של {STR_VAR_1}.$"

Route134_Text_AlexIntro:
	.string "אוקידוקי! זה מספיק המנוחה, חברה!\n"
	.string "הגיע הזמן לקרב!$"

Route134_Text_AlexDefeat:
	.string "עייף שוב…$"

Route134_Text_AlexPostBattle:
	.string "הציפור פוקימון שלי מתעייף מהר\n"
	.string "אחרי טיסה ארוכה…$"

Route134_Text_HitoshiIntro:
	.string "את{EMIT_HEY} מאמ{SWAP_NUN}{ADD_TAF} פוקימונים.\n"
	.string "אין צורך במילים. נלחם עכשיו.$"

Route134_Text_HitoshiDefeat:
	.string "… … … … … …\n"
	.string "… … … … … …$"

Route134_Text_HitoshiPostBattle:
	.string "זה אני שאיתגרתי אותך, ובכל זאת\n"
	.string "הפסדתי. אני מתבייש…$"

Route134_Text_AaronIntro:
	.string "הזרמים פראיים כאן\n"
	.string "ומחזקים אותנו יותר מתמיד.$"

Route134_Text_AaronDefeat:
	.string "אני מוותר על הקרב מרצוני.$"

Route134_Text_AaronPostBattle:
	.string "אנחנו נחזור לאימוני במפלי המטאור.\p"
	.string "אם תרצ{EMIT_HEY}{ADD_YUD}, כדאי גם לך לבוא.\n"
	.string "זה יחשל אותך!$"

Route134_Text_KelvinIntro:
	.string "הסירה שלנו!\n"
	.string "הזרם סחף אותה!$"

Route134_Text_KelvinDefeat:
	.string "אווהווהה!\n"
	.string "בבקשה, עצ{EMIT_VAV}ר{ADD_YUD}! בבקשה!$"

Route134_Text_KelvinPostBattle:
	.string "אם אנחנו לא יכולים לגלוש, איך\n"
	.string "נחזור הביתה?\p"
	.string "למעשה, אני יודע שפוקימון שהתעלף\n"
	.string "עדיין יכול לגלוש, אבל זה מרגיש לא נכון.$"

Route134_Text_MarleyIntro:
	.string "האם הפוקימון שלך יכול להתחמק\n"
	.string "מהתקפות המהירות ברק שלנו?$"

Route134_Text_MarleyDefeat:
	.string "מעולם לא ידעתי שטכניקה כזו קיימת!\n"
	.string "ניצחת אותנו לגמרי.$"

Route134_Text_MarleyPostBattle:
	.string "אני לא איבדתי את התשוקה למהירות.\n"
	.string "אני אשתדל יותר.$"

Route134_Text_ReynaIntro:
	.string "הפוקימון שלי לא נופל\n"
	.string "בקלות!$"

Route134_Text_ReynaDefeat:
	.string "את{EMIT_HEY} צוחק{ADD_TAF} עליי!\n"
	.string "תסביר{ADD_YUD} איך הפסדתי!$"

Route134_Text_ReynaPostBattle:
	.string "האהא!\n"
	.string "ניצחת, בהחלט!\p"
	.string "אני אעלה חזרה למעלה על ידי להילחם\n"
	.string "במאמנים שאפגוש!$"

Route134_Text_HudsonIntro:
	.string "תקשיב{ADD_YUD}, ראית מלחים נוספים\n"
	.string "כאן באזור?$"

Route134_Text_HudsonDefeat:
	.string "עכשיו, זה משהו!$"

Route134_Text_HudsonPostBattle:
	.string "הסירה שלנו שטה לים.\p"
	.string "החבר שלי ביישן, אז אני\n"
	.string "דואג לו.$"
