LilycoveCity_ContestLobby_Text_InterviewRequest:
	.string "אה, שלום!\n"
	.string "השתתפת בתחרות פוקימון, נכון?\l"
	.string "קל לראות את זה מהפוקימון שלך.\p"
	.string "אני כתבת. אני עובדת על כתבה\n"
	.string "על תחרויות פוקימון.\p"
	.string "אם יורשה לי, תהיה מוכן לענות\n"
	.string "על כמה שאלות?$"

LilycoveCity_ContestLobby_Text_DescribeContest:
	.string "אה, כן?\n"
	.string "תודה.\p"
	.string "בקצרה, איך היית מתאר את\n"
	.string "התחרות שזה עתה נכנסת אליה?$"

LilycoveCity_ContestLobby_Text_WhatImageWhenYouHearX:
	.string "אה, אני מבינה.\n"
	.string "זו תגובה מחכימה מאוד.\p"
	.string "מקבלים תחושה טובה לגבי איך\n"
	.string "התחרות היתה.\p"
	.string "יש לי שאלה אחרונה.\p"
	.string "כשאתה שומע את המילה ”{STR_VAR_2}“,\n"
	.string "איזו תמונה עולה לך?$"

LilycoveCity_ContestLobby_Text_ThatsAllForInterview:
	.string "אני מבינה!\p"
	.string "כך אתה מדמיין את המושג\n"
	.string "של ”{STR_VAR_2}“.\p"
	.string "תודה!\n"
	.string "נתת לי כמה רעיונות טובים.\p"
	.string "אני חושבת שאני יכולה לכתוב עכשיו\n"
	.string "כתבה טובה על תחרויות פוקימון.\p"
	.string "אולי, רק אולי, הסיפור הזה אפילו\n"
	.string "יגיע לטלוויזיה.\l"
	.string "אני מקווה שתצפה לזה!$"

LilycoveCity_ContestLobby_Text_PleaseDoShareStoryWithMe:
	.string "אוי, חבל…\p"
	.string "טוב, אם אתה נתקל בסיפור טוב,\n"
	.string "בבקשה שתף אותי בו.$"

LilycoveCity_ContestLobby_Text_LookingForwardToNextContest:
	.string "אני אצפה בקוצר רוח לתחרות הפוקימון\n"
	.string "הבאה שלך.$"

gTVBravoTrainerText00::
	.string "כן!\n"
	.string "זה זמן בראבו מאמן!\p"
	.string "היום, אנחנו הולכים להציג פוקימון\n"
	.string "ששייך ל{STR_VAR_1}.\p"
	.string "עכשיו, הפוקימון הזה מתגאה בדרגת\n"
	.string "{STR_VAR_3} בקטגורית {STR_VAR_2}.$"

gTVBravoTrainerText01::
	.string "מציגים את {STR_VAR_2} ה{STR_VAR_1}!\p"
	.string "הכינוי {STR_VAR_2}…\p"
	.string "אפילו הכינוי משדר אווירה\n"
	.string "המכריזה ”{STR_VAR_3}“!$"

gTVBravoTrainerText02::
	.string "בכל מקרה, כאשר המאמן {STR_VAR_1}\n"
	.string "הכניס את הפוקימון לתחרות,\l"
	.string "הצלחנו לקבל כמה ציטוטים נלהבים\l"
	.string "על השותף הנאמן.$"

gTVBravoTrainerText03::
	.string "כשנשאל על התחרות לאחר מכן,\n"
	.string "{STR_VAR_1} השיב בשמחה עם חיוך גדול,\l"
	.string "”{STR_VAR_2}“!\p"
	.string "טוב, ברור, הפוקימון של {STR_VAR_1} הגיע\n"
	.string "למקום {STR_VAR_3} בתחרות.\p"
	.string "המשפט הזה מתאים באופן מושלם ל{STR_VAR_1}\n"
	.string "כרגע, הייתי אומר!$"

gTVBravoTrainerText04::
	.string "כשנשאל על התחרות לאחר מכן,\n"
	.string "{STR_VAR_1} השיב בטעם של מרירות,\l"
	.string "”{STR_VAR_2}“.\p"
	.string "טוב, ברור, הפוקימון של {STR_VAR_1} הגיע\n"
	.string "למקום {STR_VAR_3} בתחרות.\p"
	.string "האכזבה של {STR_VAR_1} עוברת\n"
	.string "ברור וחזק, הייתי אומר!$"

gTVBravoTrainerText05::
	.string "האם גם אתה לא היית רוצה לדעת מה\n"
	.string "{STR_VAR_1} מדמיין ש{STR_VAR_2} הוא?\p"
	.string "אתה יכול להיות בטוח שכן!\n"
	.string "אז שאלנו, כמובן!\p"
	.string "התשובה כולה מתומצתת בצורה מושלמת:\n"
	.string "”{STR_VAR_3}“!\p"
	.string "זה מה שהמושג {STR_VAR_2}\n"
	.string "מייצג עבור {STR_VAR_1}!$"

gTVBravoTrainerText06::
	.string "המהלך האחרון ש{STR_VAR_2} השתמש בו על ידי\n"
	.string "ה{STR_VAR_1} הוא כולו סביב\l"
	.string "”{STR_VAR_3}“!$"

gTVBravoTrainerText07::
	.string "בראבו, {STR_VAR_1}!\n"
	.string "בראבו, {STR_VAR_2}!\p"
	.string "אני מקווה שנוכל לסמוך על כך שנראה את\n"
	.string "{STR_VAR_1} מטפס לגבהים גדולים עוד יותר!\p"
	.string "זה כל הזמן שיש לנו!\n"
	.string "עד הפעם הבאה, להתראות!$"

gTVBravoTrainerText08::
	.string "מציגים את ה{STR_VAR_1} של המאמן!$"

BattleFrontier_BattleTowerLobby_Text_InterviewRequest::
	.string "שלום! אתה המאמן שזה עתה\n"
	.string "ניהל קרב, נכון?\p"
	.string "אני אוספת ראיונות עם מאמנים\n"
	.string "מכל רחבי המקום.\p"
	.string "האם אוכל לקבל ממך כמה מילים על\n"
	.string "התרשמותך מהקרב?$"

BattleFrontier_BattleTowerLobby_Text_HowDidBattleTowerTurnOut::
	.string "אתה תעשה את זה? באמת?\n"
	.string "תודה!\l"
	.string "אז, אה…\p"
	.string "איך הסתדרו העניינים במגדל הקרב\n"
	.string "היום?\p"
	.string "היית מרוצה מהקרב?\n"
	.string "או שאתה לא מרוצה?$"

BattleFrontier_BattleTowerLobby_Text_SorryWeDisturbedYou::
	.string "אה…\n"
	.string "מצטערים שהפרענו לך.\p"
	.string "אנא תן לנו ראיון בפעם הבאה\n"
	.string "שאתה מבקר במגדל הקרב.$"

BattleFrontier_BattleTowerLobby_Text_ObviousYouHadGreatBattle::
	.string "טוב, כמובן!\p"
	.string "המבט הברור הזה של סיפוק\n"
	.string "על הפנים שלך…\p"
	.string "ברור שהיה לך קרב\n"
	.string "נהדר.$"

BattleFrontier_BattleTowerLobby_Text_DifficultToMakeBattleTurnOutAsPlanned::
	.string "אה, אני מבינה…\p"
	.string "טוב, זה בהחלט קשה לגרום לקרב\n"
	.string "להתנהל בדיוק כפי שתוכנן.$"

BattleFrontier_BattleTowerLobby_Text_DescribeYourBattle::
	.string "אה, אה, האם אוכל לשאול עוד שאלה אחת?\p"
	.string "אם היית צריך לתאר את\n"
	.string "התרשמותיך מהקרב הזה ב\l"
	.string "משפט אחד, מה הוא היה?$"

BattleFrontier_BattleTowerLobby_Text_ThatsGreatLine::
	.string "אה, זה מדהים כמה שזה מגניב!\p"
	.string "זה משפט נהדר!\n"
	.string "אני מקווה שתצליח מאוד גם בפעם הבאה.\p"
	.string "אני מקווה לראותך שוב!$"

BattleFrontier_BattleTowerLobby_Text_SilentType::
	.string "אה, אני מבינה…\p"
	.string "בכל זאת, להיות הטיפוס השקט זה גם\n"
	.string "מגניב, לא?\p"
	.string "אני מקווה שתיתן לי את ההזדמנות\n"
	.string "לשתף את מחשבותיך שוב!$"

BattleFrontier_BattleTowerLobby_Text_LookingForwardToNextBattle::
	.string "אני אצפה בקוצר רוח לקרב\n"
	.string "הבא שלך!$"

BravoTrainerBattleTower_Text_Intro::
	.string "כן!\n"
	.string "זה זמן בראבו מאמן!\p"
	.string "היום, אנחנו הולכים להציג את {STR_VAR_1},\n"
	.string "שלקח את אתגר מגדל הקרב!\p"
	.string "עבור האתגר, {STR_VAR_1} הכניס\n"
	.string "פוקימון {STR_VAR_2} מרושע אחד.$"

BravoTrainerBattleTower_Text_NewRecord::
	.string "הזוג קבע שיא חדש של {STR_VAR_2} ניצחונות\n"
	.string "ברציפות בתחרות {STR_VAR_1}!\l"
	.string "בראבו, מאמן!$"

BravoTrainerBattleTower_Text_Lost::
	.string "הצמד לבסוף נכנע ל{STR_VAR_1}\n"
	.string "במשחק מספר {STR_VAR_2}.\l"
	.string "ניסיון יפה, מאמן!\p"
	.string "אבל, היי, זה פשוט מזל רע להיתקל ב{STR_VAR_1}\n"
	.string "כל כך מוקדם באתגר.\p"
	.string "שאלנו את המאמן לגבי התרשמותו\n"
	.string "מהקרב עם {STR_VAR_1}.$"

BravoTrainerBattleTower_Text_Won::
	.string "הצמד ניצח הכל על ידי הבסת\n"
	.string "ה{STR_VAR_2} של {STR_VAR_1} ביסודיות.\l"
	.string "בראבו, מאמן!\p"
	.string "להפיל אפילו את {STR_VAR_1}…\n"
	.string "זה מתנגד לאמונה! פשוט מדהים!\p"
	.string "שאלנו את המאמן לגבי התרשמותו\n"
	.string "מרגע התהילה.$"

BravoTrainerBattleTower_Text_LostFinal::
	.string "לאחר רצף של ניצחונות, הזוג לבסוף\n"
	.string "נכנע ל{STR_VAR_2} של {STR_VAR_1},\l"
	.string "המכשול האחרון שלהם.\p"
	.string "ניסיון יפה, מאמן!\p"
	.string "ובכל זאת, צריך לתת קרדיט.\n"
	.string "לא רואים הרבה שילובים מפורסמים\l"
	.string "כמו {STR_VAR_1} ו{STR_VAR_2}.\p"
	.string "שאלנו את המאמן לגבי התרשמותו\n"
	.string "מהקרב עם הזוג הסלבריטאי.$"

BravoTrainerBattleTower_Text_Satisfied::
	.string "זה מה שהמאמן אמר:\n"
	.string "”אני מרוצה!“\p"
	.string "עכשיו זו לא תגובה מרעננת?\n"
	.string "בראבו, מאמן!\p"
	.string "זה לא מדהים בפה מלא להיות\n"
	.string "מסוגל להילחם עד סיפוק מלא?\p"
	.string "גיליתי בדיוק כמה הוא מרוצה\n"
	.string "כששמעתי את המאמן אומר את זה:$"

BravoTrainerBattleTower_Text_Unsatisfied::
	.string "זה מה שהמאמן אמר:\n"
	.string "”אני לא מרוצה…“\p"
	.string "המאמן שלנו היה כמובן קצת מדוכא\n"
	.string "כאשר זה נאמר.\p"
	.string "ובכל זאת, זה לא קל להיות מסוגל להילחם\n"
	.string "בסיפוק מוחלט, אני צודק?\p"
	.string "בכל מקרה, גיליתי כמה לא מרוצה\n"
	.string "המאמן שלנו היה כששמעתי את זה:$"

BravoTrainerBattleTower_Text_None1::
	.string "אף אחד$"

BravoTrainerBattleTower_Text_None2::
	.string "אף אחד$"

BravoTrainerBattleTower_Text_None3::
	.string "אף אחד$"

BravoTrainerBattleTower_Text_None4::
	.string "אף אחד$"

BravoTrainerBattleTower_Text_Response::
	.string "”{STR_VAR_1}“.$"

BravoTrainerBattleTower_Text_ResponseSatisfied::
	.string "”{STR_VAR_1}“.\n"
	.string "עכשיו זה לא נהדר?\p"
	.string "זה באמת מבטא את השמחה של {STR_VAR_2},\n"
	.string "הייתי אומר.\p"
	.string "הקרב הזה עם {STR_VAR_3} בסוף…\n"
	.string "זה באמת היה מה שהיית קורא לו\l"
	.string "”{STR_VAR_1}“!$"

BravoTrainerBattleTower_Text_ResponseUnsatisfied::
	.string "”{STR_VAR_1}“.\n"
	.string "עכשיו זה לא מתאים?\p"
	.string "הקרב הזה עם {STR_VAR_3} בסוף…\n"
	.string "אתה לא יכול לתאר את זה בשום דבר\l"
	.string "אחר מלבד ”{STR_VAR_1}“!\p"
	.string "האכזבה של {STR_VAR_2} עוברת\n"
	.string "ברור וחזק, הייתי אומר!$"

BravoTrainerBattleTower_Text_Outro::
	.string "בראבו, {STR_VAR_1}!\n"
	.string "בראבו, {STR_VAR_2}!\p"
	.string "אני מקווה שנוכל לסמוך על כך שנראה את\n"
	.string "{STR_VAR_1} מטפס לגבהים גדולים עוד יותר!\p"
	.string "זה כל הזמן שיש לנו!\n"
	.string "עד הפעם הבאה, להתראות!$"

SlateportCity_PokemonFanClub_Text_InterviewRequestHasName:
	.string "וואו!\p"
	.string "קל לראות שאתה מרעיף את\n"
	.string "אהבתך על ה{STR_VAR_1} שלך.\p"
	.string "אוקי, קוראים לו {STR_VAR_2}.\p"
	.string "אפשר לבקש ממך טובה?\p"
	.string "אני כתבת טלוויזיה, ואני מנהלת\n"
	.string "סקר על פוקימונים.\p"
	.string "האם תהיה מוכן לענות לי על כמה\n"
	.string "שאלות פשוטות?$"

SlateportCity_PokemonFanClub_Text_HereGoesQuickAnswers::
	.string "נהדר! תודה!\p"
	.string "אוקי, הנה זה בא.\n"
	.string "אני צריכה רק תשובות מהירות, בסדר?$"

SlateportCity_PokemonFanClub_Text_DescribeFeelingsFirstMetMon:
	.string "כשפגשת לראשונה את {STR_VAR_1},\n"
	.string "מה הרגשת?\p"
	.string "איך היית מתאר את הרגשות שלך\n"
	.string "באותו זמן?$"

SlateportCity_PokemonFanClub_Text_LikenMonToSomethingYouLike:
	.string "על ה{STR_VAR_1} שלך מטפלים באהבה.\p"
	.string "אם היית צריך לדמות אותו למשהו\n"
	.string "שאתה אוהב, מה זה היה?$"

SlateportCity_PokemonFanClub_Text_WhatAttractedYouAboutMon:
	.string "שאלה זו קשורה גם ל{STR_VAR_1}\n"
	.string "האהוב שלך.\p"
	.string "מה היה ב{STR_VAR_1} ש\n"
	.string "משך אותך?$"

SlateportCity_PokemonFanClub_Text_WhatDoPokemonMeanToYou:
	.string "אוקי, זה הגיוני.\p"
	.string "השאלה הבאה עשויה להיות קצת\n"
	.string "קשה.\p"
	.string "הנה זה בא…\p"
	.string "מה פוקימונים אומרים לך?$"

SlateportCity_PokemonFanClub_Text_ThatsAllForInterview:
	.string "אני מבינה!\p"
	.string "הממ…\p"
	.string "אוקי!\n"
	.string "תודה שעזרת לי.\p"
	.string "זה היה כיף ומחכים\n"
	.string "לשוחח איתך.\p"
	.string "ייתכן שהראיון שלנו יופיע\n"
	.string "בטלוויזיה. כוון ובדוק!\p"
	.string "אוקי, זה הכל.\n"
	.string "ביי-ביי!$"

SlateportCity_PokemonFanClub_Text_HereIfYouGetUrgeToTellMe:
	.string "אה, אוקי…\p"
	.string "טוב, אם תרגיש דחף לספר לי\n"
	.string "על פוקימונים, אני אהיה כאן!$"

SlateportCity_PokemonFanClub_Text_EnjoyDoingInterviews:
	.string "אני נהנית מהעבודה הזו--אתה לומד\n"
	.string "על פוקימונים על ידי עריכת ראיונות.$"

SlateportCity_PokemonFanClub_Text_InterviewRequest:
	.string "היי, אתה נראה קרוב מאוד ל{STR_VAR_1}\n"
	.string "שלך.\p"
	.string "אתה יודע מה?\n"
	.string "אני כתבת טלוויזיה.\p"
	.string "אני נוסעת מסביב ומראיינת אנשים\n"
	.string "על פוקימונים.\p"
	.string "אני תוהה אם תהיה מוכן לספר\n"
	.string "לי קצת על ה{STR_VAR_1} שלך?$"

SlateportCity_PokemonFanClub_Text_TellMeAnythingAboutYourMon:
	.string "וואו, תודה!\p"
	.string "אוקי, אם כך, בבקשה ספר לי כל דבר\n"
	.string "שהיית רוצה על ה{STR_VAR_1} שלך.$"

SlateportCity_PokemonFanClub_Text_ThatsAllForInterview2:
	.string "וואו…\n"
	.string "זה סיפור מעניין.\p"
	.string "אתה באמת מחובר ל{STR_VAR_1},\n"
	.string "נכון?\p"
	.string "יש לי הרגשה שהסיפור שלך\n"
	.string "יהפוך לסיפור טלוויזיה נהדר.\p"
	.string "אני מבטיחה שאני אהפוך את זה\n"
	.string "לתוכנית מבדרת.\l"
	.string "שמור את עיניך פקוחות לזה.\p"
	.string "אוקי, זה הכל.\n"
	.string "ביי-ביי!$"

gTVFanClubOpinionsText00::
	.string "אנחנו מועדון המעריצים של הפוקימון!\p"
	.string "אנחנו בשידור!\p"
	.string "בתוכנית הזו, אנחנו מקבלים את דעותיכם,\n"
	.string "ואני צועק אותן בשמכם!\l"
	.string "זה לא רעיון פנטסטי לתוכנית?\p"
	.string "היום, אנו מביאים לכם את הדיווח הזה\n"
	.string "מהכתב שלנו, ששלחנו למועדון\l"
	.string "המעריצים של הפוקימון.\p"
	.string "אז, מי הוא המעריץ הפוקימוני המוצג\n"
	.string "של היום?\p"
	.string "… … … … … … … …\p"
	.string "{STR_VAR_1}!\p"
	.string "אז, בואו נשמע מה יש ל{STR_VAR_1} לומר\n"
	.string "על {STR_VAR_3} ה{STR_VAR_2}.\p"
	.string "ואני אצעק את מילות האהבה האלה\n"
	.string "בקול רם בטלוויזיה!\p"
	.string "הו-הא!\p"
	.string "בואו נצעק!$"

gTVFanClubOpinionsText01::
	.string "שאלנו את {STR_VAR_1}, ”כשפגשת\n"
	.string "לראשונה את {STR_VAR_2} שלך, מה היתה\l"
	.string "המחשבה הראשונית שלך?“\p"
	.string "”{STR_VAR_3}“!\p"
	.string "יהאה! זו צעקה אדירה!\p"
	.string "זה לא מחזיר זיכרונות מאותם\n"
	.string "ימים שחלפו מזמן?$"

gTVFanClubOpinionsText02::
	.string "שאלנו את {STR_VAR_1}, ”אם היית צריך\n"
	.string "לדמות את {STR_VAR_2} שלך למשהו,\l"
	.string "זה היה…“\p"
	.string "… … … … … … … …\p"
	.string "”{STR_VAR_3}“!\p"
	.string "וואו-הו, עכשיו זה רעיון מקורי!\p"
	.string "אתה בטוח יכול לחוש את עוצמת\n"
	.string "הרגשות שיש למאמן כלפי\l"
	.string "{STR_VAR_2}.$"

gTVFanClubOpinionsText03::
	.string "ואז נראה…\n"
	.string "מה היה ב{STR_VAR_2} הזה\l"
	.string "שכל כך משך את {STR_VAR_1}?\p"
	.string "… … … … … … … …\p"
	.string "”{STR_VAR_3}“!\p"
	.string "וואו! איזו הצהרה מרהיבה!\p"
	.string "האהבה של המאמן ל{STR_VAR_2}\n"
	.string "עוברת חזק וברור!$"

gTVFanClubOpinionsText04::
	.string "הממ? אה, יש עוד.\n"
	.string "בואו נבדוק את זה!\p"
	.string "בואו נראה, עכשיו…\p"
	.string "שאלנו את {STR_VAR_1}, ”מה פוקימונים\n"
	.string "אומרים לך?“\p"
	.string "… … … … … …\p"
	.string "”{STR_VAR_3}“!\p"
	.string "בראבו!\p"
	.string "זו הצעקה הטובה ביותר שהיתה לי כל היום!\p"
	.string "”{STR_VAR_3}“!\p"
	.string "זה גורם לך לרצות לצעוק את זה בקול רם\n"
	.string "שוב ושוב!\p"
	.string "עכשיו, לאחר שצעקנו נהדר, זה הזמן\n"
	.string "להיפרד עד הפעם הבאה!\p"
	.string "אז, בואו כולנו נצעק צעקה אחרונה!\n"
	.string "כולם יחד, עכשיו…\p"
	.string "”{STR_VAR_3}“!$"

gTVFanClubText00::
	.string "אנחנו מועדון המעריצים של הפוקימון!\p"
	.string "אנחנו בשידור!\p"
	.string "היום, אנחנו נתחיל עם פינת\n"
	.string "הסקר של הפוקימון.\p"
	.string "מכל הסיפורים ה\n"
	.string "שנרקמו על ידי פוקימונים ומאמנים, איזו דרמה חדשה\l"
	.string "מדהימה תמשוך את תשומת ליבנו היום?\p"
	.string "בואו נראה…\p"
	.string "את זה!\p"
	.string "נתחיל עם המכתב הזה!\p"
	.string "זה מכתב מ{STR_VAR_1} על\n"
	.string "{STR_VAR_2} אהוב.\p"
	.string "בואו נראה כמה בלהט הסופר שלנו\n"
	.string "יכול להביע אהבה ל{STR_VAR_2}!\l"
	.string "הממ…$"

gTVFanClubText01::
	.string "וואו!\n"
	.string "איזה מכתב מדהים!$"

gTVFanClubText02::
	.string "אהבתי את זה, אז הנה זה שוב!$"

gTVFanClubText03::
	.string "מכתב נהדר ראוי לקריאה\n"
	.string "שוב ושוב!$"

gTVFanClubText04::
	.string "הקטע ”{STR_VAR_3}“, זה באמת\n"
	.string "מבליט את ההשפעה הרגשית!\p"
	.string "זה מכתב נהדר שיש לו עומק\n"
	.string "כנה ואמיתי!$"

gTVFanClubText05::
	.string "במיוחד הקטע הזה ”{STR_VAR_3}“!\p"
	.string "אני אוהבת איך ש”{STR_VAR_3}“ משמש!$"

gTVFanClubText06::
	.string "דרך אגב, וזה לא חשוב,\n"
	.string "אבל ”{STR_VAR_3}“ זה משפט נהדר.\p"
	.string "השתמשתי ב”{STR_VAR_3}“ הרבה\n"
	.string "בשיחות בזמן האחרון.$"

gTVFanClubText07::
	.string "אם הייתי צריך לנקד את המכתב הזה,\n"
	.string "הייתי נותן לו {STR_VAR_3} נקודות.\p"
	.string "בפעם הבאה, אני אצפה למכתב אפילו\n"
	.string "טוב יותר, {STR_VAR_1}!\p"
	.string "אופס, תראו את השעה?\n"
	.string "זמן לומר להתראות עד הפעם הבאה!$"

SlateportCity_OceanicMuseum_1F_Text_InterviewRequest:
	.string "אה?\n"
	.string "אתה אולי אוהב פוקימונים?\p"
	.string "אני במשימה עבור רשת הטלוויזיה.\p"
	.string "אני אוספת סיפורים על פוקימונים ו\n"
	.string "מאמנים שאירעו לאחרונה.\p"
	.string "אם לא אכפת לך, תוכל לספר לי\n"
	.string "משהו על עצמך?$"

SlateportCity_OceanicMuseum_1F_Text_InterviewRequestShort:
	.string "אני אוספת סיפורים על פוקימונים ו\n"
	.string "מאמנים שאירעו לאחרונה.\p"
	.string "אם לא אכפת לך, תוכל לספר לי\n"
	.string "משהו על עצמך?$"

SlateportCity_OceanicMuseum_1F_Text_TellMeExperienceInvolvingPokemon:
	.string "אה, כן?\n"
	.string "תודה!\p"
	.string "אז, בבקשה, ספר לי כל דבר\n"
	.string "מעניין שחווית לאחרונה\l"
	.string "שקשור לפוקימונים.$"

SlateportCity_OceanicMuseum_1F_Text_LetMeKnowIfYouHaveStory:
	.string "אה, אני מבינה…\p"
	.string "טוב, אם יש לך סיפור\n"
	.string "מעניין לספר, בבקשה ספר לי.$"

SlateportCity_OceanicMuseum_1F_Text_ThatsAllForInterview:
	.string "אה, איזה סיפור מרומם!\p"
	.string "אני בטוחה שאני אדאג שהסיפור שלך יסופר\n"
	.string "בטלוויזיה.\p"
	.string "זה אמור להיות משודר מתישהו, אני חושבת,\n"
	.string "אז בבקשה תצפה לזה.$"

SlateportCity_OceanicMuseum_1F_Text_BetterWriteUpStory:
	.string "המממ…\n"
	.string "יש לי סיפור טוב לתוכנית טלוויזיה.\p"
	.string "מוטב שאכתוב אותו במהירות!$"

gTVRecentHappeningsText00::
	.string "שלום, הגיע הזמן לאירועים אחרונים.\p"
	.string "עבור מאמני פוקימון, כל יום\n"
	.string "הוא סיפור מהספר.\p"
	.string "מה שאנחנו רוצים לעשות זה להכיר לך\n"
	.string "כמה מסיפורי הפוקימון האלה.\p"
	.string "היום, אנו מביאים לכם את הסיפור\n"
	.string "של המאמן {STR_VAR_1}.\p"
	.string "מה {STR_VAR_1} חווה לאחרונה?\n"
	.string "בואו נגלה.\p"
	.string "בואו נראה…$"

gTVRecentHappeningsText01::
	.string "זה לא היה מאלף?\p"
	.string "הסיפור נותן לך מושג ברור על מה\n"
	.string "{STR_VAR_1} חווה לאחרונה.\l"
	.string "זה כאילו היינו שם כעדים!$"

gTVRecentHappeningsText02::
	.string "”{STR_VAR_3}“. זה\n"
	.string "מדגיש את הסיפור ונותן לו עומק.$"

gTVRecentHappeningsText03::
	.string "”{STR_VAR_3}“.\n"
	.string "זה נותן לסיפור תחושה של מקום.\l"
	.string "זה מאפשר לנו לדמיין את סביבת הסיפור.$"

gTVRecentHappeningsText04::
	.string "החלק ”{STR_VAR_3}“\n"
	.string "של הסיפור הוא מאוד אקספרסיבי.$"

gTVRecentHappeningsText05::
	.string "{STR_VAR_1} סיפר סיפור נפלא\n"
	.string "שקשור לפוקימונים.\p"
	.string "ועכשיו הסיפור של {STR_VAR_1} חרוט בזיכרון\n"
	.string "גם בנשמה שלך.\p"
	.string "זהו זה להיום.\n"
	.string "בבקשה כוון בפעם הבאה.$"

gTVMassOutbreakText00::
	.string "ברכות!\n"
	.string "הגיע הזמן לחדשות פוקימון.\p"
	.string "זה עתה קיבלנו ידיעה על התרחשות\n"
	.string "נדירה מאוד.\p"
	.string "היו דיווחים על התפרצות המונית\n"
	.string "של {STR_VAR_2} בסביבת\l"
	.string "{STR_VAR_1}.\p"
	.string "{STR_VAR_2}, כפי שאתה כנראה מודע,\n"
	.string "ידוע כפוקימון נדיר\l"
	.string "וקשה למצוא.\p"
	.string "זה נשמע כמו הזדמנות נדירה\n"
	.string "לראות את ההתפרצות המסתורית של\l"
	.string "{STR_VAR_2} בטבע.\p"
	.string "אלו החדשות בחדשות פוקימון.$"

gTV3CheersForPokeblocksText00::
	.string "מנחה: אנו מקווים שאתם במצב רוח טוב,\n"
	.string "”3 צהלות לפוקיגוש“ כאן!\p"
	.string "היום, נבחן את הפוקיגוש שערבבו\n"
	.string "על ידי {STR_VAR_1} ושותפיו.\p"
	.string "ללא כל דיחוי, תנו לי להאכיל את זה\n"
	.string "לגולפין, הפוקימון גורמה שלי.\p"
	.string "… … … … … …\n"
	.string "… … … … … …$"

gTV3CheersForPokeblocksText01::
	.string "גולפין: גובי! גוביי!\p"
	.string "מנחה: והפסק דין הוא {STR_VAR_1} מאוד!\n"
	.string "גולפין אומר שזה טעים ”{STR_VAR_2}“!\p"
	.string "תודה רבה לך, {STR_VAR_3}!$"

gTV3CheersForPokeblocksText02::
	.string "ביצועי הערבוב של {STR_VAR_1}\n"
	.string "השאירו מקום לרצון.\p"
	.string "אם המאמן הזה היה יכול לערבב טוב יותר,\n"
	.string "הפוקיגוש היה טעים הרבה יותר.$"

gTV3CheersForPokeblocksText03::
	.string "גולפין: גובי! גוביי!\p"
	.string "מנחה: הממ… זה יותר מדי {STR_VAR_1}.\n"
	.string "גולפין אומר שזה טעים ”{STR_VAR_2}“!\p"
	.string "נראה שטעויותיו של {STR_VAR_3}\n"
	.string "פגעו באיכות הערבוב…$"

gTV3CheersForPokeblocksText04::
	.string "חבל שהמאמץ המוביל של {STR_VAR_1}\n"
	.string "ירד לטמיון.\p"
	.string "בואו נקווה ש{STR_VAR_2} יצליח להפגין\n"
	.string "הופעה טובה יותר בפעם הבאה!$"

gTV3CheersForPokeblocksText05::
	.string "כוון בפעם הבאה!\n"
	.string "הסלוגן שלנו הוא ”3 צהלות לפוקיגוש“!$"

LilycoveCity_PokemonTrainerFanClub_Text_WhatsYourOpinionOfTrainer::
	.string "היי, שם!\p"
	.string "אני מעריץ גדול של {STR_VAR_1}.\n"
	.string "מה דעתך על {STR_VAR_1}?$"

LilycoveCity_PokemonTrainerFanClub_Text_ThatsWhatYouThink::
	.string "אני מבין, אני מבין. זו דעתך\n"
	.string "על המאמן.$"

LilycoveCity_PokemonTrainerFanClub_Text_HaveYouForgottenTrainer::
	.string "שכחת לגמרי\n"
	.string "מ{STR_VAR_1}?$"

LilycoveCity_PokemonTrainerFanClub_Text_WhatsYourOpinionOfTrainer2::
	.string "אני מעריץ גדול של {STR_VAR_1}.\n"
	.string "מה דעתך על {STR_VAR_1}?$"

LilycoveCity_PokemonTrainerFanClub_Text_HowStrongRateTrainer::
	.string "איך היית מדרג את {STR_VAR_1}\n"
	.string "בסולם של מאה?$"

LilycoveCity_PokemonTrainerFanClub_Text_HaveYouForgottenTrainer2::
	.string "שכחת לגמרי\n"
	.string "מ{STR_VAR_1}?$"

LilycoveCity_PokemonTrainerFanClub_Text_YouShouldMeetTrainer::
	.string "אה, אני מבין!\n"
	.string "כדאי שתפגוש את {STR_VAR_1} מתישהו.\l"
	.string "אני בטוח שגם אתה תהפוך למעריץ!$"

LilycoveCity_PokemonTrainerFanClub_Text_ThankYouIllShareThisInfo::
	.string "אני מבין, אני מבין.\p"
	.string "תודה!\n"
	.string "זה מאוד שימושי לדעת.\p"
	.string "אני אשתף את המידע הזה עם מעריצים\n"
	.string "אחרים של {STR_VAR_1} ואדון בו.$"

LilycoveCity_PokemonTrainerFanClub_HopeYouCatchTVSpecial::
	.string "תהיה תוכנית טלוויזיה מיוחדת על\n"
	.string "{STR_VAR_1} בקרוב מאוד.\p"
	.string "אני מקווה שתצפה בה!$"

gTVTrainerFanClubSpecialText00::
	.string "מועדון מעריצים של מאמנים\n"
	.string "מיוחד של {STR_VAR_1}!\p"
	.string "זו מצגת מיוחדת עבור\n"
	.string "המעריצים של {STR_VAR_1} בכל רחבי הון!\p"
	.string "היום, אנו שואלים את השאלה, ”מה אנשים\n"
	.string "חושבים על {STR_VAR_1}?“\p"
	.string "שאלנו את {STR_VAR_2}\n"
	.string "כנציג המאמנים.\p"
	.string "שאלנו, ”במילה אחת, איך היית\n"
	.string "מתאר את {STR_VAR_1}?“\p"
	.string "התשובה: ”{STR_VAR_3}“.\p"
	.string "כל הכבוד ל{STR_VAR_2}!\n"
	.string "איזו דעה נבונה!\p"
	.string "”{STR_VAR_3} {STR_VAR_1}“.\n"
	.string "יש לזה צליל כה נחמד!\p"
	.string "{STR_VAR_2} גם ניקד את הכוח של {STR_VAR_1}\n"
	.string "מ0 עד 001.$"

gTVTrainerFanClubSpecialText01::
	.string "הציון היה {STR_VAR_3} נקודות!\n"
	.string "זהו ציון גבוה מאוד אכן!\p"
	.string "{STR_VAR_2} בטח מחזיק את\n"
	.string "{STR_VAR_1} בהערכה רבה.$"

gTVTrainerFanClubSpecialText02::
	.string "הציון היה {STR_VAR_3} נקודות!\n"
	.string "זהו ציון טוב למדי.\p"
	.string "{STR_VAR_2} בטח מחשיב את\n"
	.string "{STR_VAR_1} כמתחרה.$"

gTVTrainerFanClubSpecialText03::
	.string "הציון היה {STR_VAR_3} נקודות!\n"
	.string "זהו ציון חלש למדי.\p"
	.string "{STR_VAR_2} בטח מחשיב את\n"
	.string "{STR_VAR_1} כסתם שותף.$"

gTVTrainerFanClubSpecialText04::
	.string "הציון היה {STR_VAR_3} נקודה(ות)!\n"
	.string "זהו ציון נורא.\p"
	.string "{STR_VAR_2} בטח מחשיב את\n"
	.string "{STR_VAR_1} ככפוף.$"

gTVTrainerFanClubSpecialText05::
	.string "אז הנה זה, חברים!\p"
	.string "אני חושב שכולנו למדנו משהו\n"
	.string "חדש על {STR_VAR_1}.\p"
	.string "לסיום, אני אשאיר אתכם עם\n"
	.string "מילותיו של {STR_VAR_2}.\p"
	.string "{STR_VAR_3} {STR_VAR_1}!$"

gTVNameRaterText00::
	.string "ועכשיו, הגיע הזמן ל…\n"
	.string "התוכנית של בוחן השמות.\p"
	.string "אני מנבא את מזלו של הפוקימון שלך מ\n"
	.string "הכינוי שהענקת לו.\p"
	.string "עצות הן מה שיש לי לתת, וזו\n"
	.string "עצה מועילה שאני מציע.\p"
	.string "היום, אני אעשה קריאה של\n"
	.string "הכינוי {STR_VAR_3} של הפוקימון {STR_VAR_2}\l"
	.string "של {STR_VAR_1}.\p"
	.string "הממ…\p"
	.string "הממ…\n"
	.string "הכינוי הזה הוא…$"

gTVNameRaterText01::
	.string "כינוי שרומז על כשרון בדרכים\n"
	.string "רבות ושונות.\p"
	.string "אני קורא למאמן הזה לאזור אומץ\n"
	.string "ולקבל על עצמו אתגרים רבים.$"

gTVNameRaterText02::
	.string "כינוי שמשלים בצורה מושלמת\n"
	.string "את {STR_VAR_1}, שמו של המאמן.\p"
	.string "זה מרמז שתצרו שותפות טובה\n"
	.string "עם תזמון מדויק.$"

gTVNameRaterText03::
	.string "כינוי שמתאים לאינדיבידואל ייחודי\n"
	.string "של פוקימון!\p"
	.string "אם יטופח כראוי, הייחודיות של הפוקימון\n"
	.string "הזה תפרח יתר על המידה!$"

gTVNameRaterText04::
	.string "כינוי שיטפח את הצד האכפתי\n"
	.string "והחומל של הפוקימון.\p"
	.string "אם יטופח כראוי, הפוקימון הזה יפגין\n"
	.string "חום אמיתי!$"

gTVNameRaterText05::
	.string "כינוי נחמד מאוד שרומז על\n"
	.string "גדולה עתידית.\p"
	.string "אני מסוקרן לגבי מה שהעתיד\n"
	.string "צופן לפוקימון הזה.$"

gTVNameRaterText06::
	.string "כינוי טוב שאמור להפוך את הפוקימון\n"
	.string "לבריא וחזק!\p"
	.string "הפוקימון הזה אמור להישאר בכושר\n"
	.string "וחסון למשך זמן רב, רב.$"

gTVNameRaterText07::
	.string "כינוי טוב שאמור להפוך את הפוקימון\n"
	.string "לפעיל מאוד!\p"
	.string "אני חושב שהפוקימון הזה יהיה\n"
	.string "מבצע חזק בקרבות.$"

gTVNameRaterText08::
	.string "כינוי מושך שאמור להפוך את הפוקימון\n"
	.string "למקסים מאוד!\p"
	.string "אני לא מטיל ספק בכך שהפוקימון הזה יהיה\n"
	.string "די מקסים בתחרויות פוקימון.$"

gTVNameRaterText09::
	.string "הכינוי {STR_VAR_1} מושרש על ידי\n"
	.string "האות ”{STR_VAR_3}“.\p"
	.string "האות הזו נתמכת על ידי האות\n"
	.string "הראשונה ”{STR_VAR_2}“, שנותנת לו תחושה\l"
	.string "מוצקה של נוכחות ככינוי.$"

gTVNameRaterText10::
	.string "הכינוי {STR_VAR_1} הוא מאוד\n"
	.string "מעוצב בצורה נעימה.\p"
	.string "הנוכחות של האותיות ”{STR_VAR_2}“ ו\n"
	.string "”{STR_VAR_3}“--עכשיו זה טוב במיוחד!$"

gTVNameRaterText11::
	.string "הכינוי {STR_VAR_1}--יש לו תחושה\n"
	.string "נשגבת וזורמת.\p"
	.string "הזרימה מהאות הראשונית ”{STR_VAR_2}“ ל\n"
	.string "”{STR_VAR_3}“ היא נפלאה במיוחד.$"

gTVNameRaterText12::
	.string "בואו נבחן דוגמאות אחרות של כינויים\n"
	.string "יפים, נכון?$"

gTVNameRaterText13::
	.string "נסה את הדוגמה הזו. קח חלק מ\n"
	.string "שם המאמן של {STR_VAR_1}, וסיים\l"
	.string "עם הכינוי הנחמד {STR_VAR_2}{STR_VAR_3}.$"

gTVNameRaterText14::
	.string "הכינוי {STR_VAR_2}{STR_VAR_3} יעבוד גם\n"
	.string "די טוב.$"

gTVNameRaterText15::
	.string "שם המין של הפוקימון {STR_VAR_2}\n"
	.string "יכול לשמש כבסיס\l"
	.string "ליצירת הכינוי {STR_VAR_1}{STR_VAR_3}.$"

gTVNameRaterText16::
	.string "{STR_VAR_1}{STR_VAR_3} יהיה גם כינוי\n"
	.string "יעיל.$"

gTVNameRaterText17::
	.string "מה שתמיד צריך להימנע ממנו הוא שימוש\n"
	.string "בשם מין של פוקימון אחר.\p"
	.string "לדוגמה, הימנע מלקחת את השם של\n"
	.string "{STR_VAR_2} כדי ליצור את הכינוי {STR_VAR_1}{STR_VAR_3}.\l"
	.string "זה לא מקובל.$"

gTVNameRaterText18::
	.string "אני חייב לומר ש{STR_VAR_1} הוא כינוי\n"
	.string "די טוב.\p"
	.string "אני מקווה שהמאמן ימשיך\n"
	.string "לטפל ב{STR_VAR_1} באהבה.\p"
	.string "זהו זה להיום.\n"
	.string "שניפגש שוב.$"

gTVPokemonAnglerText00::
	.string "דייג {STR_VAR_2}\p"
	.string "כרוז: שלום! היום, נקבל טיפים\n"
	.string "על דיג {STR_VAR_2}.\p"
	.string "גורו, איזו עצה אתה יכול לתת ל\n"
	.string "תפיסת {STR_VAR_2}?\p"
	.string "גורו: הממ? תפיסת {STR_VAR_2}?\n"
	.string "טוב, תן לי לומר לך, היה סבלני ו\l"
	.string "חכה. זו השורה התחתונה.\p"
	.string "אתה רואה את {STR_VAR_1} שם?\n"
	.string "המאמן הזה מהווה דוגמה טובה.\p"
	.string "למאמן הזה כבר ברחו\n"
	.string "{STR_VAR_3} פוקימונים.\p"
	.string "אבל {STR_VAR_1} מחכה שם. לא מוותר.\n"
	.string "זה החוק לתפיסת {STR_VAR_2}.\p"
	.string "כרוז: אני מבין…\p"
	.string "הו! {STR_VAR_1} סוף סוף תפס\n"
	.string "{STR_VAR_2} חמקמק!\p"
	.string "המאמן נראה קרוב לדמעות\n"
	.string "מרוב שמחה טהורה!\p"
	.string "לראות את המבט הנלהב הזה, אני מקבל\n"
	.string "גירוד ללכת לדוג גם כן!\p"
	.string "צופים, למה שלא תקחו את זה כרמז ל\n"
	.string "לנסות קצת דיג {STR_VAR_2}?\p"
	.string "עד השידור הבא שלנו, להתראות ו\n"
	.string "דיג טוב לכולכם!$"

gTVPokemonAnglerText01::
	.string "דייג {STR_VAR_2}\p"
	.string "כרוז: שלום! היום, נקבל טיפים\n"
	.string "על דיג {STR_VAR_2}.\p"
	.string "גורו, איזו עצה אתה יכול לתת ל\n"
	.string "תפיסת {STR_VAR_2}?\p"
	.string "גורו: הממ? תפיסת {STR_VAR_2}?\n"
	.string "טוב, תן לי לומר לך, השתמש בחכת הדיג\l"
	.string "שלך במרץ!\p"
	.string "אתה רואה את {STR_VAR_1} שם?\n"
	.string "אתה רואה איך הוא מחזיק את החכה?\p"
	.string "המאמן הזה כבר תפס\n"
	.string "{STR_VAR_3} ברציפות.\p"
	.string "כרוז: זה מדהים!\n"
	.string "זה נראה כמו סערה…\p"
	.string "לראות טכניקה ברמה כזו, אני מקבל\n"
	.string "גירוד ללכת לדוג גם כן.\p"
	.string "צופים, למה שלא תקחו את זה כרמז ל\n"
	.string "לנסות קצת דיג {STR_VAR_2}?\p"
	.string "עד השידור הבא שלנו, להתראות ו\n"
	.string "דיג טוב לכולכם!$"

gTVPokemonTodayFailedText00::
	.string "שלום!\p"
	.string "הגיע הזמן לפוקימון היום!\p"
	.string "אחות גדולה: היי! כולם שמחים ו\n"
	.string "עליזים היום?\p"
	.string "היום, אנחנו הולכים להסתכל על הפוקימון\n"
	.string "{STR_VAR_2} של {STR_VAR_1}!\p"
	.string "אח גדול: כן! זה מה שאנחנו\n"
	.string "הולכים לעשות!$"

gTVPokemonTodayFailedText01::
	.string "אה!\n"
	.string "אם כבר מדברים על {STR_VAR_1}…\p"
	.string "אחות גדולה, ראיתי את המאמן במו\n"
	.string "עיניי!\p"
	.string "אחות גדולה: אה, מה ראית?\p"
	.string "אח גדול: טוב, הייתי צריך לצאת לטיול ל\n"
	.string "{STR_VAR_2}.\p"
	.string "זה כאשר במקרה נתקלתי ב{STR_VAR_1},\n"
	.string "שניסה לתפוס את הפוקימון {STR_VAR_3}, אבל…\l"
	.string "שניסה לתפוס את הפוקימון {STR_VAR_3}, אבל…$"

gTVPokemonTodayFailedText02::
	.string "הפוקימון הצליח לברוח!\p"
	.string "זה הסתיים בבזבוז כמות כזו של\n"
	.string "פוקי כדורים: {STR_VAR_2}!\p"
	.string "היית צריך לראות את הבעת\n"
	.string "התסכול על פניו של {STR_VAR_1} כאשר\l"
	.string "הפוקימון ברח!$"

gTVPokemonTodayFailedText03::
	.string "אבל {STR_VAR_1} התבלבל וגרם\n"
	.string "לפוקימון להתעלף!\p"
	.string "זה הסתיים בבזבוז כמות כזו של\n"
	.string "פוקי כדורים: {STR_VAR_2}!\p"
	.string "היית צריך לראות את הבעת\n"
	.string "ההלם המבוהל על פניו של {STR_VAR_1}\l"
	.string "כאשר הפוקימון התעלף!$"

gTVPokemonTodayFailedText04::
	.string "אחות גדולה: היי, חמוד!\n"
	.string "זה לא נחמד!\p"
	.string "אתה לא צריך לצחוק על חוסר המזל\n"
	.string "של אנשים אחרים!\p"
	.string "אוי, מסכן {STR_VAR_1}.\n"
	.string "איזו בושה!\p"
	.string "אח גדול: זה נכון!\n"
	.string "סליחה שצחקתי.$"

gTVPokemonTodayFailedText05::
	.string "אחות גדולה: בופופו…\p"
	.string "אח גדול: היי!\n"
	.string "גם את צחקת עכשיו!\p"
	.string "אחות גדולה: אה?!?\p"
	.string "אני לא צחקתי!\n"
	.string "באמת, לא צחקתי!\p"
	.string "אוי, מסכן {STR_VAR_1}.\n"
	.string "איזו בושה!\p"
	.string "אח גדול: …$"

gTVPokemonTodayFailedText06::
	.string "אחות גדולה: זה מספיק עם השטויות!\n"
	.string "בואו נסתכל על הפוקימון של היום…\p"
	.string "אה?\n"
	.string "כבר נגמר לנו הזמן?\p"
	.string "אוי!\n"
	.string "לא הצלחנו להציג פוקימון היום!\p"
	.string "אח גדול: נתראה שוב בפעם הבאה!\p"
	.string "אחות גדולה: היי, אל תסיים את התוכנית\n"
	.string "בלעדי!$"

gTVPokemonTodaySuccessfulText00::
	.string "שלום!\p"
	.string "הגיע הזמן לפוקימון היום!\p"
	.string "אחות גדולה: היי! כולם שמחים ו\n"
	.string "עליזים היום?\p"
	.string "היום, אנחנו הולכים להסתכל על הפוקימון\n"
	.string "{STR_VAR_2} של {STR_VAR_1}!\p"
	.string "אח גדול: כן! זה מה שאנחנו\n"
	.string "הולכים לעשות!$"

gTVPokemonTodaySuccessfulText01::
	.string "אחות גדולה: {STR_VAR_1} נתן את הכינוי\n"
	.string "{STR_VAR_3} ל{STR_VAR_2}!\p"
	.string "זה נשמע כאילו {STR_VAR_3} מקבל\n"
	.string "טיפול טוב ואוהב!$"

gTVPokemonTodaySuccessfulText02::
	.string "אח גדול: המאמן היה צריך לזרוק כמות זו\n"
	.string "של פוקי כדורים כדי לתפוס אותו: {STR_VAR_3}!\p"
	.string "זה לבסוף לקח {STR_VAR_2} יחיד\n"
	.string "כדי לתפוס אותו!$"

gTVPokemonTodaySuccessfulText03::
	.string "אחות גדולה: אם זה היה כל כך קל לתפוס,\n"
	.string "זו בטח היתה גורל שהפגיש\l"
	.string "את {STR_VAR_1} וה{STR_VAR_2}!$"

gTVPokemonTodaySuccessfulText04::
	.string "אחות גדולה: וואו! זה כל כך נחמד!\p"
	.string "אבל אתה יודע מה אומרים, פוקימון\n"
	.string "שלוקח הרבה מאמץ לתפוס\l"
	.string "זוכה לאהבת המאמן שלו!$"

gTVPokemonTodaySuccessfulText05::
	.string "אחות גדולה: ה{STR_VAR_2} של {STR_VAR_1} הוא\n"
	.string "פוקימון בלתי נשכח כי זה לקח פוקי כדור\l"
	.string "מאסטר שלא יסולא בפז כדי לתפוס אותו!\p"
	.string "אח גדול: וואו! זה מגה-מדהים!\p"
	.string "אחות גדולה: {STR_VAR_1} בטח רצה\n"
	.string "מאוד את ה{STR_VAR_2} הזה, בוודאות!$"

gTVPokemonTodaySuccessfulText06::
	.string "אח גדול: ואז לתת את הכינוי\n"
	.string "{STR_VAR_3} ל{STR_VAR_2} הזה…\p"
	.string "אתה באמת מקבל מושג טוב על\n"
	.string "החוש של המאמן {STR_VAR_1}.\p"
	.string "אחות גדולה: אני מצטרפת לרעיון הזה!$"

gTVPokemonTodaySuccessfulText07::
	.string "אם זה היה אני, הייתי נותנת את הכינוי הזה\n"
	.string "למשהו כזה {STR_VAR_3}!\p"
	.string "אח גדול: וואו! זו יכולה להיות ההתחלה\n"
	.string "של משהו חדש!$"

gTVPokemonTodaySuccessfulText08::
	.string "{STR_VAR_2} ה{STR_VAR_1}?\n"
	.string "זה לא נשמע מושלם?\p"
	.string "האותיות והכל--הם\n"
	.string "נשמעים בדיוק מתאימים לפוקימון\l"
	.string "{STR_VAR_1}!\p"
	.string "אח גדול: כן, נכון, זה!$"

gTVPokemonTodaySuccessfulText09::
	.string "עד כמה שידוע לי, אף מאמן מעולם לא\n"
	.string "נתן את הכינוי {STR_VAR_2} ל{STR_VAR_1}\l"
	.string "שלו!\p"
	.string "אח גדול: זה רק מראה איזה טעם נהדר\n"
	.string "יש למאמן בבחירת כינויים!$"

gTVPokemonTodaySuccessfulText10::
	.string "בפעם הבאה שאני אתפוס פוקימון,\n"
	.string "אני צריכה לתת לו את השם {STR_VAR_2}.\p"
	.string "אח גדול: אה? גם אני!\n"
	.string "אני אשתמש בכינוי {STR_VAR_2} גם כן!$"

gTVPokemonTodaySuccessfulText11::
	.string "אחות גדולה: אוי, לא!\n"
	.string "תסתכלו על השעה!\p"
	.string "טוב, חבר'ה, זהו זה להיום.\n"
	.string "נתראה שוב בפעם הבאה!\p"
	.string "אח גדול: זכרו, זה יכול להיות הפוקימון\n"
	.string "שלכם באור הזרקורים בפעם הבאה!$"

SmartShopper_Text_Intro::
	.string "שלום!\p"
	.string "הגיע הזמן לקונה הנבון של היום.\p"
	.string "מראיין: מה שלומכם, צופים?\p"
	.string "היום אנחנו מבקרים בחנות\n"
	.string "ב{STR_VAR_2}.\p"
	.string "בואו נבדוק מה היו הפריטים הנמכרים\n"
	.string "החמים ביותר לאחרונה.$"

SmartShopper_Text_ClerkNormal::
	.string "בואו נראיין את הפקיד כדי לקבל את\n"
	.string "הפרטים.\p"
	.string "היי, איך העסק שלך?\p"
	.string "פקיד: אה, אנחנו עושים מצוין.\p"
	.string "לאחרונה, {STR_VAR_2} נמכר\n"
	.string "חזק במיוחד.\p"
	.string "למה, רק לפני כמה ימים מאמן\n"
	.string "בשם {STR_VAR_1} קנה {STR_VAR_3}.$"

SmartShopper_Text_RandomComment1::
	.string "מראיין: המאמן קנה\n"
	.string "{STR_VAR_3} {STR_VAR_2}ים? זו כמות!\p"
	.string "אם יורשה לי לומר, {STR_VAR_1} בטח\n"
	.string "הצטייד למסע ארוך\l"
	.string "למקומות רחוקים.\p"
	.string "לנסיעה, {STR_VAR_2}ים כל כך\n"
	.string "חשובים!$"

SmartShopper_Text_RandomComment2::
	.string "מראיין: אם כבר מדברים על הפריט\n"
	.string "{STR_VAR_2}, זה עתה קניתי {STR_VAR_3} מהם\l"
	.string "לאחרונה.\p"
	.string "אחרי הכל, {STR_VAR_2} הוא פריט נהדר!$"

SmartShopper_Text_RandomComment3::
	.string "מראיין: {STR_VAR_2}?!\n"
	.string "אבל {STR_VAR_3} מהם?!\p"
	.string "לא חשבתי שיהיה מישהו\n"
	.string "שקונה כל כך הרבה.\p"
	.string "אלוהים אדירים, אני יכול להרשות לעצמי רק אחד\n"
	.string "או שניים בכל פעם…$"

SmartShopper_Text_RandomComment4::
	.string "מראיין: פעם אחת, קניתי\n"
	.string "כמות גדולה של הפריט {STR_VAR_2}.\p"
	.string "אבל התברר שזה יותר מדי.\n"
	.string "בסוף הצטערתי על זה…\p"
	.string "מאז, אני קונה רק מה שאני\n"
	.string "באמת צריך…\p"
	.string "אופס!\p"
	.string "אין טעם לדבר עלי!$"

SmartShopper_Text_SecondItem::
	.string "פקיד: {STR_VAR_1} גם קנה את הפריט\n"
	.string "{STR_VAR_2} בכמות גדולה, ולקח {STR_VAR_3}.\p"
	.string "מראיין: אה, זה חכם.\n"
	.string "{STR_VAR_2} הוא גם פריט טוב מאוד.$"

SmartShopper_Text_ThirdItem::
	.string "פקיד: וגם, המאמן גם קנה\n"
	.string "{STR_VAR_3} מהפריט {STR_VAR_2}.$"

SmartShopper_Text_DuringSale::
	.string "פקיד: בנוסף, זה היה במהלך מכירה גדולה.\n"
	.string "זו קנייה חכמה.$"

SmartShopper_Text_OutroNormal::
	.string "מראיין: הממ… {STR_VAR_1} נשמע כמו\n"
	.string "צייד מציאות ממולח למדי!\p"
	.string "בסך הכל, הרכישות של {STR_VAR_1} הגיעו ל…\p"
	.string "¥{STR_VAR_2}?!\n"
	.string "איזה סכום מדהים!\p"
	.string "אופס! נגמר לנו הזמן!\n"
	.string "נתראה בשידור הבא שלנו!$"

SmartShopper_Text_IsVIP::
	.string "פקיד: {STR_VAR_1} הוא לקוח וי.איי.פי.,\n"
	.string "אין ספק בכך.$"

SmartShopper_Text_ClerkMax::
	.string "בואו נראיין את הפקיד כדי לקבל את\n"
	.string "הפרטים.\p"
	.string "היי, איך העסק שלך?\p"
	.string "פקיד: אה, אנחנו עושים עסקים לא יאומנו.\n"
	.string "זה כמעט מכריע.\p"
	.string "לאחרונה, מאמן בשם {STR_VAR_1}\n"
	.string "קנה את הפריט {STR_VAR_2} בכמות גדולה.\p"
	.string "המאמן כמעט ורוקן את כל המלאי\n"
	.string "שלנו של {STR_VAR_2}ים.\p"
	.string "מעולם לא חלמתי שלקוח כלשהו\n"
	.string "אי פעם יצטרך כל כך הרבה {STR_VAR_2}ים.\l"
	.string "זה פשוט לא נשמע!\p"
	.string "מראיין: אז זה בערך 100\n"
	.string "או 200 שנמכרו?\p"
	.string "פקיד: אה, לא, הרבה יותר מזה!\p"
	.string "מראיין: אוי, אלוהים אדירים!\n"
	.string "{STR_VAR_1} בטח קונה מיוחד!\p"
	.string "פקיד: {STR_VAR_1} הוא לקוח וי.איי.פי.,\n"
	.string "אין ספק בכך.$"

SmartShopper_Text_OutroMax::
	.string "מראיין: הממ…\n"
	.string "זה מדהים.\p"
	.string "אבל למה שהמאמן יצטרך לקנות\n"
	.string "כל כך הרבה?\p"
	.string "… …\p"
	.string "התעלומה מעמיקה, אבל זה כל\n"
	.string "הזמן שיש לנו היום.\l"
	.string "נתראה בשידור הבא שלנו!\p"
	.string "ובכל זאת, {STR_VAR_1} הוא בהחלט חידה…$"

gTVWorldOfMastersText00::
	.string "עולם המאסטרים\p"
	.string "שלום, צופים.\p"
	.string "אולי אתם מודעים למאמן\n"
	.string "בשם {STR_VAR_1}.\p"
	.string "{STR_VAR_1} מפורסם כמאסטר ב\n"
	.string "תפיסת פוקימונים.\p"
	.string "החיפוש של {STR_VAR_1} אחר פוקימונים תלוי\n"
	.string "כולו בחיפוש זהיר ברגל.\p"
	.string "ביום בלתי נשכח אחד, המאמן\n"
	.string "צעד כ{STR_VAR_2} צעדים.\p"
	.string "המספר הכולל של פוקימונים שנתפסו\n"
	.string "באותו יום הגיע ל{STR_VAR_3} מרשים!$"

gTVWorldOfMastersText01::
	.string "ההישג המדהים הזה בטח היה\n"
	.string "אפשרי בגלל האמון בין\l"
	.string "המאמן ל{STR_VAR_1}.$"

gTVWorldOfMastersText02::
	.string "המאסטר תפס את {STR_VAR_3} האחרון\n"
	.string "של היום ליד {STR_VAR_2}.\p"
	.string "לפוקימון הזה כנראה יש\n"
	.string "מעמד מיוחד כמחזיק שיא.\p"
	.string "יש לעודד מאמנים מיומנים\n"
	.string "לאתגר את השיא הנחמד הזה.\p"
	.string "זה הכל להיום.\n"
	.string "בבקשה כוון בפעם הבאה.$"

gTVTodaysRivalTrainerText00::
	.string "המאמן המתחרה של היום!\p"
	.string "שלום, חברי מאמני הפוקימון!\n"
	.string "מה שלום כולנו היום?\p"
	.string "היום, כמו בכל יום אחר,\n"
	.string "נבחן אחד מהמתחרים שלנו!$"

gTVTodaysRivalTrainerText07::
	.string "המאמן המתחרה של היום הוא {STR_VAR_1},\n"
	.string "שנמצא בסביבות {STR_VAR_3} עכשיו.\p"
	.string "{STR_VAR_1} רשם עד כה\n"
	.string "{STR_VAR_2} פוקימונים בפוקידקס.$"

gTVTodaysRivalTrainerText08::
	.string "המאמן המתחרה של היום הוא {STR_VAR_1},\n"
	.string "שנמצא בבסיס סודי עכשיו.\p"
	.string "{STR_VAR_1} רשם עד כה\n"
	.string "{STR_VAR_2} פוקימונים בפוקידקס.$"

gTVTodaysRivalTrainerText09::
	.string "המאמן המתחרה של היום הוא {STR_VAR_1}.\p"
	.string "עד כה, {STR_VAR_1} רשם\n"
	.string "{STR_VAR_2} פוקימונים בפוקידקס.\p"
	.string "$"

gTVTodaysRivalTrainerText10::
	.string "המאמן המתחרה של היום הוא {STR_VAR_1},\n"
	.string "שנמצא על מעבורת עכשיו.\p"
	.string "{STR_VAR_1} רשם עד כה\n"
	.string "{STR_VAR_2} פוקימונים בפוקידקס.$"

gTVTodaysRivalTrainerText01::
	.string "וכמה תגים יש למתחרה שלנו?\n"
	.string "המספר הוא {STR_VAR_1}!$"

gTVTodaysRivalTrainerText02::
	.string "אבל המתחרה שלנו לא השיג\n"
	.string "אפילו תג אחד עדיין!$"

gTVTodaysRivalTrainerText03::
	.string "המתחרה שלנו לא השיג אפילו סמל\n"
	.string "אחד של חזית הקרב עדיין.$"

gTVTodaysRivalTrainerText04::
	.string "בואו נראה כמה סמלים של חזית הקרב\n"
	.string "יש למתחרה שלנו.\p"
	.string "סמלי זהב: {STR_VAR_1}!\n"
	.string "סמלי כסף: {STR_VAR_2}!$"

gTVTodaysRivalTrainerText05::
	.string "המתחרה שלנו אסף {STR_VAR_1} נקודה(ות)\n"
	.string "קרב בחזית הקרב.$"

gTVTodaysRivalTrainerText06::
	.string "אז, איך אתה מדד את עצמך\n"
	.string "בהשוואה ל{STR_VAR_1}?\p"
	.string "ההרפתקה ממשיכה!\p"
	.string "חברי מאמנים!\p"
	.string "בואו כולנו נמשיך להתקדם\n"
	.string "ומול המתחרים שלנו!$"

TrendWatcher_Text_Intro::
	.string "רשת צופי טרנדים של דיופורד!\p"
	.string "מנחה: מה קורה?\n"
	.string "אנחנו נשמור על זה אמיתי עם העדכונים\l"
	.string "האחרונים על מה שחם וקורה בדיופורד.\p"
	.string "האורח שלנו היום הוא החתול הזקן הזה ש\n"
	.string "הטוען לתהילה שלו הוא להיות הסמכות\l"
	.string "בכל הדברים בדיופורד.\p"
	.string "איש זקן: שמח להיות כאן.\p"
	.string "מנחה: בואו נחתוך ישר לעניין, ישר ולעניין.\p"
	.string "מה דעתך על מה שמטריף\n"
	.string "את האנשים הטובים של דיופורד?\p"
	.string "איש זקן: {STR_VAR_1} {STR_VAR_2}.\p"
	.string "מנחה: {STR_VAR_1} {STR_VAR_2},\n"
	.string "אתה אומר?\p"
	.string "איש זקן: לא.\p"
	.string "{STR_VAR_1} {STR_VAR_2} אף פעם\n"
	.string "לא הפך פופולרי בכלל.\p"
	.string "תרצה לשמוע על זה?\p"
	.string "מנחה: אה, לא. מה שאנחנו רוצים לדעת הוא\n"
	.string "מה הדבר המודרני כרגע…$"

@ זהה למטה, אולי היה שונה בשפות אחרות
TrendWatcher_Text_MaleTaughtMePhrase::
	.string "איש זקן: {STR_VAR_1} {STR_VAR_2}\n"
	.string "היה מה ש{STR_VAR_3} מליטלרוט\l"
	.string "לימד אותי כטרנדי…$"

TrendWatcher_Text_FemaleTaughtMePhrase::
	.string "איש זקן: {STR_VAR_1} {STR_VAR_2}\n"
	.string "היה מה ש{STR_VAR_3} מליטלרוט\l"
	.string "לימד אותי כטרנדי…$"

TrendWatcher_Text_PhraseWasHopeless::
	.string "אבל זה היה חסר תקווה לחלוטין.\p"
	.string "{STR_VAR_1} {STR_VAR_2} פסטיבל!\p"
	.string "{STR_VAR_1} {STR_VAR_2} תחרות!\p"
	.string "ניסיתי ללמד את כולם הכי\n"
	.string "טוב שיכולתי, אבל…\p"
	.string "אולי החלק {STR_VAR_1} פשוט\n"
	.string "לא היה נכון…\p"
	.string "מנחה: אה, סליחה, חבר, אני צריך\n"
	.string "לשמוע על מה שבפנים עכשיו…$"

@ זהה למטה, אולי היה שונה בשפות אחרות
TrendWatcher_Text_MaleTellMeBigger::
	.string "איש זקן: {STR_VAR_3}!\n"
	.string "בבקשה, ספר לי משהו גדול יותר מ\l"
	.string "זה {STR_VAR_1} {STR_VAR_2}!$"

TrendWatcher_Text_FemaleTellMeBigger::
	.string "איש זקן: {STR_VAR_3}!\n"
	.string "בבקשה, ספר לי משהו גדול יותר מ\l"
	.string "זה {STR_VAR_1} {STR_VAR_2}!$"

TrendWatcher_Text_Outro::
	.string "מנחה: …אה… אז, הנה זה לפניכם,\n"
	.string "כל החתולים הטרנדיים והמגניבים שם בחוץ!\p"
	.string "{STR_VAR_1} {STR_VAR_2}…אה…\n"
	.string "לא הפך למגניב או קורה בדיופורד!\p"
	.string "הזמן שלי נגמר. נתפוס אתכם תוך כדי תנועה!\p"
	.string "איש זקן: {STR_VAR_1} {STR_VAR_2}!$"

gTVHoennTreasureInvestigatorsText00::
	.string "חוקרי האוצרות של הון!\p"
	.string "היי, חבר'ה!\n"
	.string "השגתם פריטים סודיים לאחרונה?\p"
	.string "כמו תמיד, נבחן עדויות ראייה\n"
	.string "לסודות מכל רחבי המקום!\p"
	.string "בואו נתחיל עם מכתב.\n"
	.string "כתוב בו, ”{STR_VAR_1} התגלה!“$"

gTVHoennTreasureInvestigatorsText01::
	.string "וואו, מוטב שנבדוק את המכתב\n"
	.string "הזה! תנו לי לקרוא לכם אותו.\p"
	.string "…חוקרים יקרים,\n"
	.string "אני מקווה ששלומכם טוב.\p"
	.string "ראיתי לאחרונה את {STR_VAR_2} איפשהו\n"
	.string "בסביבות {STR_VAR_3}.\p"
	.string "המאמן מצא את הפריט\n"
	.string "{STR_VAR_1}. זה גרם לי לקנא.\p"
	.string "…טוב, כל הכבוד, {STR_VAR_2}!\p"
	.string "צופים, תנו לזה להניע אתכם ל\n"
	.string "להפעיל את מוצאי הפריטים שלכם ולחפש!\p"
	.string "אני אחכה לחדשות מרגשות\n"
	.string "מכולכם!$"

gTVHoennTreasureInvestigatorsText02::
	.string "וואו, מוטב שנבדוק את המכתב\n"
	.string "הזה! תנו לי לקרוא לכם אותו.\p"
	.string "…חוקרים יקרים,\n"
	.string "אני מקווה ששלומכם טוב.\p"
	.string "ראיתי לאחרונה את {STR_VAR_2} על מעבורת.\p"
	.string "המאמן מצא את הפריט\n"
	.string "{STR_VAR_1}. זה גרם לי לקנא.\p"
	.string "…טוב, כל הכבוד, {STR_VAR_2}!\p"
	.string "צופים, תנו לזה להניע אתכם ל\n"
	.string "להפעיל את מוצאי הפריטים שלכם ולחפש!\p"
	.string "אני אחכה לחדשות מרגשות\n"
	.string "מכולכם!$"

gTVFindThatGamerText00::
	.string "מצא את הגיימר הזה!\p"
	.string "היי, כל הגיימרים!\n"
	.string "איך ה{STR_VAR_2} שלכם מסתובב?\p"
	.string "כמו תמיד, נשים את אור הזרקורים\n"
	.string "על מאמן נדיר שביקר ב\l"
	.string "פינת המשחקים!\p"
	.string "היום, הגיימר מספר 1 שלנו הוא…\n"
	.string "{STR_VAR_1}!$"

gTVFindThatGamerText01::
	.string "{STR_VAR_1} שיחק במשחק {STR_VAR_2}\n"
	.string "וניצח {STR_VAR_3} מטבעות נדירים.\p"
	.string "”כאשר {STR_VAR_1} מגיע, אנחנו צריכים\n"
	.string "לוודא שיש לנו מספיק מטבעות.“\p"
	.string "זה מה שפקידי פינת המשחקים\n"
	.string "מלמלו כאשר הגיימר שלנו במשחק!\p"
	.string "צופים, עדיף לשמור על המטבעות שלכם\n"
	.string "כמו {STR_VAR_1} אם אתם מבקרים בפינת\l"
	.string "המשחקים ומשחקים במשחק {STR_VAR_2}.\p"
	.string "זה בשידור חי מפינת המשחקים --\n"
	.string "שבה אתם יכולים להרגיש את ההתרגשות!\p"
	.string "זה הכל להיום!$"

gTVFindThatGamerText02::
	.string "{STR_VAR_1} שיחק במשחק {STR_VAR_2}\n"
	.string "והפסיד {STR_VAR_3} מטבעות.\p"
	.string "”כאשר {STR_VAR_1} מגיע, נראה ש\n"
	.string "מכירות המטבעות שלנו עולות.“\p"
	.string "זה מה שפקידי פינת המשחקים\n"
	.string "אומרים כאשר הגיימר שלנו במשחק!$"

gTVFindThatGamerText03::
	.string "צופים, עדיף לשמור על המטבעות שלכם\n"
	.string "כמו {STR_VAR_1} אם אתם מבקרים בפינת\l"
	.string "המשחקים ומשחקים במשחק {STR_VAR_2}.\p"
	.string "זה בשידור חי מפינת המשחקים --\n"
	.string "שבה אתם יכולים להרגיש את ההתרגשות!\p"
	.string "זה הכל להיום!$"

gTVBreakingNewsText00::
	.string "חדשות חמות בטלוויזיה!$"

gTVBreakingNewsText01::
	.string "{STR_VAR_2} נדיר נתפס על ידי\n"
	.string "{STR_VAR_1}!\p"
	.string "אנחנו בשידור חי מסביבת\n"
	.string "{STR_VAR_3}!\p"
	.string "{STR_VAR_1} תפס בהצלחה\n"
	.string "{STR_VAR_2} נדיר כאן מוקדם יותר!$"

gTVBreakingNewsText02::
	.string "כאשר {STR_VAR_1} נתקל ב{STR_VAR_2}\n"
	.string "הנדיר, המאמן שלח את\l"
	.string "הפוקימון {STR_VAR_3}.$"

gTVBreakingNewsText03::
	.string "בקרב, מספר הפוקי\n"
	.string "כדורים שנזרקו על ידי המאמן היה {STR_VAR_1}.\p"
	.string "בסופו של דבר, הפוקימון הנדיר נ\n"
	.string "תפס על ידי ה{STR_VAR_2} ששימש אחרון.$"

gTVBreakingNewsText04::
	.string "באותו רגע, {STR_VAR_2}\n"
	.string "הדהד עם שאגות השמחה המנצחות\l"
	.string "של {STR_VAR_1}.\p"
	.string "אני חייב לומר שאני קצת מקנא ב\n"
	.string "{STR_VAR_1}. הייתי רוצה לשאוג גם כן.\p"
	.string "…זה מסיים את הפיד החי מה\n"
	.string "סצנה המאושרת!$"

gTVBreakingNewsText05::
	.string "{STR_VAR_1} נכשל בלכידת {STR_VAR_2}\n"
	.string "נדיר!\p"
	.string "אנחנו בשידור חי מסביבת\n"
	.string "{STR_VAR_3}!\p"
	.string "כאן {STR_VAR_1} נכשל\n"
	.string "בלכידת {STR_VAR_2} נדיר!$"

gTVBreakingNewsText06::
	.string "כאשר {STR_VAR_1} נתקל ב{STR_VAR_2}\n"
	.string "הנדיר, המאמן שלח את\l"
	.string "הפוקימון {STR_VAR_3}.$"

gTVBreakingNewsText07::
	.string "המאמן גרם ל{STR_VAR_2}\n"
	.string "להשתמש במהל {STR_VAR_1}.\p"
	.string "בלי להתכוון, המאמן\n"
	.string "גרם לפוקימון הנדיר להתעלף…$"

gTVBreakingNewsText12::
	.string "עם זאת, {STR_VAR_1} נכנס לפאניקה ב\n"
	.string "למראה ה{STR_VAR_2} הנדיר.\p"
	.string "בבלבול, המאמן הורה\n"
	.string "ל{STR_VAR_3} לתקוף.\p"
	.string "בלי להתכוון, המאמן\n"
	.string "גרם לפוקימון הנדיר להתעלף.$"

gTVBreakingNewsText08::
	.string "באותו רגע, {STR_VAR_2}\n"
	.string "הדהד עם צרחות התסכול\l"
	.string "של {STR_VAR_1}…$"

gTVBreakingNewsText09::
	.string "עם זאת, נראה ש{STR_VAR_1} נגמרו\n"
	.string "הפוקי כדורים.\p"
	.string "המאמן נאלץ להפסיק\n"
	.string "את הקרב עם ה{STR_VAR_2} הנדיר.\p"
	.string "באותו רגע, {STR_VAR_3}\n"
	.string "הדהד עם צרחות התסכול\l"
	.string "של {STR_VAR_1}…$"

gTVBreakingNewsText10::
	.string "עם זאת, ה{STR_VAR_2} נמלט בלי\n"
	.string "אזהרה.\p"
	.string "באותו רגע, {STR_VAR_3}\n"
	.string "הדהד עם צרחות התסכול\l"
	.string "של {STR_VAR_1}…$"

gTVBreakingNewsText11::
	.string "אני חייב לומר שאני מרגיש עם {STR_VAR_1}.\n"
	.string "למה, זה גורם לי לרצות לצרוח גם כן.\p"
	.string "…זה מסיים את הפיד החי מה\n"
	.string "סצנה המלנכולית!$"

gTVSecretBaseVisitText00::
	.string "שלום, חברים!\n"
	.string "הגיע שוב הזמן ל\l"
	.string "ביקור בבסיס סודי.\p"
	.string "היום, אנחנו מבקרים בבסיס הסודי\n"
	.string "של {STR_VAR_1}.\p"
	.string "איך {STR_VAR_1} התאים אישית\n"
	.string "את הבסיס הסודי?\p"
	.string "בואו נגלה!\n"
	.string "… … … … … …$"

gTVSecretBaseVisitText01::
	.string "אה!\n"
	.string "כמה נפלא!\p"
	.string "ה{STR_VAR_2} הזה…\n"
	.string "זה לא מה שהיינו מצפים ל\l"
	.string "למצוא כאן!$"

gTVSecretBaseVisitText02::
	.string "אה!\n"
	.string "כמה יוצא דופן!\p"
	.string "אין כאן אפילו רהיט אחד\n"
	.string "או פריט פנים!\p"
	.string "בני תמותה רגילים לא יכלו לקוות ל\n"
	.string "לחקות את ההצהרה הנועזת הזו!\p"
	.string "זה פשוט, אבל זה מתפרץ, כן,\n"
	.string "מתפרץ בפראות!\p"
	.string "אני מוריד את הכובע בפנייך, {STR_VAR_1}.\n"
	.string "זה היית חייב להיות אתה!$"

gTVSecretBaseVisitText03::
	.string "אה! אני רואה!\n"
	.string "בבהירות מושלמת, אני רואה את זה!\p"
	.string "ה{STR_VAR_2} הזה שנמצא כאן…\n"
	.string "זה שולח מסר יעיל!$"

gTVSecretBaseVisitText04::
	.string "אה! אני רואה!\n"
	.string "בבהירות מושלמת, אני רואה את זה!\p"
	.string "המרחב הזה נשמר בכוונה\n"
	.string "נקי מפריטי פנים!\p"
	.string "זה שולח מסר יעיל!$"

gTVSecretBaseVisitText05::
	.string "וואו!\p"
	.string "השילוב של ה{STR_VAR_2}\n"
	.string "עם ה{STR_VAR_3}!\p"
	.string "זהו שילוב חלומי אם אי פעם\n"
	.string "היה כזה!$"

gTVSecretBaseVisitText06::
	.string "וואו!\p"
	.string "המיקום של ה{STR_VAR_2} הזה\n"
	.string "בדיוק כאן…\p"
	.string "יש לו נוכחות שממלאת\n"
	.string "את כל הבסיס הסודי!$"

gTVSecretBaseVisitText07::
	.string "וואו!\p"
	.string "אין כאן שום דבר במקום.\p"
	.string "למרחב הריק הזה יש השפעה על\n"
	.string "כל הבסיס הסודי.$"

gTVSecretBaseVisitText08::
	.string "אה!\n"
	.string "הנה מגיע {STR_VAR_1}!\l"
	.string "בואו נאתגר את המאמן!\p"
	.string "… … … … … …\n"
	.string "… … … … … …$"

gTVSecretBaseVisitText09::
	.string "אנחה…\n"
	.string "אני חייב להודות ל{STR_VAR_1}.\p"
	.string "הפוקימונים של המאמן היו באמת\n"
	.string "ראויים לתואר אלוף.\p"
	.string "הם נתנו הוכחה מספקת לחוזקה\n"
	.string "של {STR_VAR_1} כמאמן.\p"
	.string "שה{STR_VAR_2} ידע את המהלך\n"
	.string "{STR_VAR_3}…\p"
	.string "זה מראה לך איזה סוג של מאמן\n"
	.string "{STR_VAR_1} הוא.\p"
	.string "בהחלט, זה היה שיעור רציני!$"

gTVSecretBaseVisitText10::
	.string "איייי!\n"
	.string "אני חייב להודות ל{STR_VAR_1}.\p"
	.string "הפוקימונים של המאמן היו\n"
	.string "קשוחים בצורה מפלצתית!\p"
	.string "הם נתנו הוכחה מספקת לעקשנות\n"
	.string "של {STR_VAR_1} כמאמן.\p"
	.string "שה{STR_VAR_2} ידע את המהלך\n"
	.string "{STR_VAR_3}…\p"
	.string "זה מראה לך איזה סוג של מאמן\n"
	.string "{STR_VAR_1} הוא.\p"
	.string "בהחלט, זה היה שיעור רציני!$"

gTVSecretBaseVisitText11::
	.string "וואו!\n"
	.string "אני חייב להודות ל{STR_VAR_1}.\p"
	.string "הפוקימונים של המאמן גודלו בבירור\n"
	.string "בצורה מאוזנת היטב.\p"
	.string "הם נתנו הוכחה מספקת לתשומת\n"
	.string "הלב של {STR_VAR_1} כמאמן.\p"
	.string "שה{STR_VAR_2} ידע את המהלך\n"
	.string "{STR_VAR_3}…\p"
	.string "זה מראה לך איזה סוג של מאמן\n"
	.string "{STR_VAR_1} הוא.\p"
	.string "בהחלט, זה היה שיעור רציני!$"

gTVSecretBaseVisitText12::
	.string "טוב, טוב!\n"
	.string "אני חייב להודות ל{STR_VAR_1}.\p"
	.string "הפוקימונים של המאמן הראו\n"
	.string "הבטחה גדולה לצמיחה עתידית.\p"
	.string "הם ייצגו את התקוות והחלומות\n"
	.string "של {STR_VAR_1}.\p"
	.string "שה{STR_VAR_2} ידע את המהלך\n"
	.string "{STR_VAR_3}…\p"
	.string "זה מראה לך איזה סוג של מאמן\n"
	.string "{STR_VAR_1} הוא.\p"
	.string "בהחלט, זה היה שיעור רציני!$"

gTVSecretBaseVisitText13::
	.string "אני חייב לומר, איזה בסיס סודי מעולה\n"
	.string "זה היה!\p"
	.string "צופים, אם יש לכם הזדמנות,\n"
	.string "בבקשה בקרו בבסיס הסודי של {STR_VAR_1}.\p"
	.string "עד הפעם הבאה, אני נפרד מכם לשלום!$"

gTVPokemonLotteryWinnerFlashReportText00::
	.string "זה מרגש!\n"
	.string "זה דרמטי!\p"
	.string "זהו דיווח הבזק של זוכה\n"
	.string "הלוטו של הפוקימונים!\p"
	.string "שלום! אנחנו מגיעים אליכם בשידור חי מ\n"
	.string "פינת הלוטו של הפוקימונים בקומה\l"
	.string "הראשונה של חנות הכלבו ליליקוב!\p"
	.string "כמו שזה תמיד קורה, עוד\n"
	.string "מאמן בר מזל הופיע היום!\p"
	.string "שמו של המאמן הזה…\n"
	.string "{STR_VAR_1}!\p"
	.string "{STR_VAR_1} זכה בפרס ה{STR_VAR_2}\n"
	.string "ולקח הביתה את ה{STR_VAR_3}!\p"
	.string "{STR_VAR_1}!\n"
	.string "מזל טוב!\p"
	.string "צופים, אל תסתכלו רק,\n"
	.string "היכנסו לפעולה!\p"
	.string "כולנו בחנות הכלבו ליליקוב\n"
	.string "מצפים לביקור הבא שלכם!\p"
	.string "זה היה שידור חי מחנות הכלבו\n"
	.string "ליליקוב, המציעה לכם את המבחר הגדול\l"
	.string "ביותר בכל הון!$"

gTVThePokemonBattleSeminarText00::
	.string "הסמינר של קרב הפוקימונים!\p"
	.string "אנחנו בוחנים קרבות כדי לראות מה\n"
	.string "שיעורים אנו יכולים ללמוד מאחרים.\p"
	.string "מקרה המחקר של היום הוא על הקרב\n"
	.string "של {STR_VAR_1}.\p"
	.string "ה{STR_VAR_2} של {STR_VAR_1} נלחם\n"
	.string "ב{STR_VAR_3} אחד…$"

gTVThePokemonBattleSeminarText01::
	.string "והוא השתמש במהלך {STR_VAR_3}\n"
	.string "על ה{STR_VAR_2}…\p"
	.string "הממ… {STR_VAR_1}!\n"
	.string "זה הדבר הלא נכון לעשות!$"

gTVThePokemonBattleSeminarText02::
	.string "בנוסף למהלך הנידון,\n"
	.string "ה{STR_VAR_1} של המאמן גם ידע$"

gTVThePokemonBattleSeminarText03::
	.string "את המהלכים {STR_VAR_1}, {STR_VAR_2},\n"
	.string "ו{STR_VAR_3}.$"

gTVThePokemonBattleSeminarText04::
	.string "את המהלכים {STR_VAR_1} ו\n"
	.string "{STR_VAR_2}.$"

gTVThePokemonBattleSeminarText05::
	.string "את המהלך {STR_VAR_2}.$"

gTVThePokemonBattleSeminarText06::
	.string "אז, במצב הזה, במה המאמן\n"
	.string "היה צריך להשתמש?\p"
	.string "… … … … … …\n"
	.string "המהלך {STR_VAR_1}!\p"
	.string "המהלך {STR_VAR_1} היה עדיף\n"
	.string "לחלוטין על {STR_VAR_2}.\p"
	.string "צופים, אני קורא לכם ללמוד מהמקרה\n"
	.string "הזה ולהילחם בחוכמה!\p"
	.string "עד הפעם הבאה, להתראות!$"

gTVTrainerFanClubText00::
	.string "כולם יחד, עכשיו!\n"
	.string "מועדון המעריצים של המאמנים!\p"
	.string "מנחה: איך כולם מסתדרים?\n"
	.string "היום, ריכזנו את המעריצים של\l"
	.string "המאמן הפופולרי במיוחד {STR_VAR_1}!\p"
	.string "מעריצים: ווורררוווווואאה!\p"
	.string "מעריצים: {STR_VAR_1}!\p"
	.string "מנחה: כולם!\n"
	.string "איך אתם אוהבים את {STR_VAR_1}?!\p"
	.string "מעריצים: אנחנו אוהבים את {STR_VAR_1}!\p"
	.string "מנחה: מה אתם אוהבים ב\n"
	.string "{STR_VAR_1}?$"

gTVTrainerFanClubText01::
	.string "מעריצים: הדרך המגניבה שלהם לזרוק\n"
	.string "פוקי כדורים!$"

gTVTrainerFanClubText02::
	.string "מעריצים: הדרך החמודה שלהם לרוץ!$"

gTVTrainerFanClubText03::
	.string "מעריצים: איך המאמן הופך לקשוח\n"
	.string "כשהעניינים נעשים קשים!$"

gTVTrainerFanClubText04::
	.string "מעריצים: הידע של המאמן ב\n"
	.string "פוקימונים!$"

gTVTrainerFanClubText05::
	.string "מעריצים: טוב הלב של המאמן כלפי\n"
	.string "כל הפוקימונים!$"

gTVTrainerFanClubText06::
	.string "מעריצים: טכניקות רכיבת האופניים\n"
	.string "המדהימות של המאמן!$"

gTVTrainerFanClubText07::
	.string "מעריצים: סגנון קניית הפריטים\n"
	.string "המרשים של המאמן!$"

gTVTrainerFanClubText08::
	.string "מעריצים: הדרך המקסימה של המאמן\n"
	.string "לתת כינויים לפוקימונים!$"

gTVTrainerFanClubText09::
	.string "מעריצים: הסגנון החמוד של המאמן\n"
	.string "לקשט בסיס סודי!$"

gTVTrainerFanClubText10::
	.string "מעריצים: הדרכים הנועזות של המאמן\n"
	.string "להשתמש בTMs!$"

gTVTrainerFanClubText11::
	.string "מנחה: כפי שראיתם זה עתה, {STR_VAR_1}\n"
	.string "לוהט! כאילו, חם מדי לגעת, יו!\p"
	.string "בקרב המעריצים של {STR_VAR_1}\n"
	.string "יש סלוגן מיוחד!\p"
	.string "מנחה: כשאני אומר {STR_VAR_1},\n"
	.string "אתם אומרים…\p"
	.string "מעריצים: {STR_VAR_2}!\p"
	.string "מעריצים: {STR_VAR_3}!\p"
	.string "מעריצים: {STR_VAR_2}!\p"
	.string "מעריצים: {STR_VAR_3}!\p"
	.string "מנחה: זה נכון, כשמישהו אומר,\n"
	.string "”{STR_VAR_1}“…\p"
	.string "תחזרו עם ”{STR_VAR_2}\n"
	.string "{STR_VAR_3}“!\p"
	.string "יש לזה צליל כה ייחודי!\n"
	.string "אני יכול לראות למה אנשים הופכים למעריצים\l"
	.string "של {STR_VAR_1}!\p"
	.string "אוקי, אתה, מול הטלוויזיה, הצטרף אלינו!\n"
	.string "כולם יחד, עכשיו!\p"
	.string "מנחה: כשאני אומר {STR_VAR_1},\n"
	.string "אתם אומרים…\p"
	.string "מעריצים: {STR_VAR_2}!\p"
	.string "מעריצים: {STR_VAR_3}!\p"
	.string "מעריצים: {STR_VAR_2}!\p"
	.string "מעריצים: {STR_VAR_3}!\p"
	.string "מנחה: תודה שהצטרפתם אלינו, כל המעריצים\n"
	.string "הפרועים של {STR_VAR_1}!\l"
	.string "זו התוכנית! נתראה שוב!\p"
	.string "מנחה: כשאני אומר {STR_VAR_1},\n"
	.string "אתם אומרים…\p"
	.string "מעריצים: {STR_VAR_2}!\p"
	.string "מעריצים: {STR_VAR_3}!$"

TVSpotTheCuties_Text_Intro::
	.string "זהה את החמודים!\n"
	.string "פוקימונים בסרטים!\p"
	.string "שלום, צופי המתוקים!\p"
	.string "אני פשוט יודעת שתסכימו, אבל פוקימון\n"
	.string "שלובש סרטים הוא פשוט אלוהי!\p"
	.string "היום, אני רוצה לשתף אתכם ב\n"
	.string "פוקימון יפהפה שראיתי בזמן\l"
	.string "שיטוט בעיר.\p"
	.string "הפוקימון היפה המוצג היום\n"
	.string "הוא ה{STR_VAR_2} של {STR_VAR_1}.$"

TVSpotTheCuties_Text_RibbonsLow::
	.string "מספר הסרטים שה{STR_VAR_2}\n"
	.string "לובש הוא {STR_VAR_3}.\p"
	.string "זה אומר הרבה על כמה\n"
	.string "{STR_VAR_1} מעריץ את הפוקימון.$"

TVSpotTheCuties_Text_RibbonsMid::
	.string "ה{STR_VAR_2} לובש {STR_VAR_3}\n"
	.string "סרטים מדהימים!\p"
	.string "זה מדבר רבות על המסירות של {STR_VAR_1}\n"
	.string "לפוקימון!$"

TVSpotTheCuties_Text_RibbonsHigh::
	.string "ה{STR_VAR_2} לובש {STR_VAR_3}\n"
	.string "סרטים מדהימים!\p"
	.string "זה מראה לכם את המסירות המוחלטת\n"
	.string "של {STR_VAR_1} כאספן!$"

TVSpotTheCuties_Text_RibbonIntro::
	.string "בואו נסתכל מקרוב על הסרטים\n"
	.string "הרבים שלובש {STR_VAR_2}.$"

TVSpotTheCuties_Text_RibbonChampion::
	.string "סרט האלוף הוא מושך\n"
	.string "במיוחד.\p"
	.string "{STR_VAR_2} קיבל אותו לאחר כניסתו\n"
	.string "להיכל התהילה.\p"
	.string "זה באמת מוציא את האומץ\n"
	.string "של {STR_VAR_2}.\p"
	.string "{STR_VAR_2} וסרט האלוף!\n"
	.string "השילוב הוא סופר יעיל!$"

TVSpotTheCuties_Text_RibbonCool::
	.string "סרט המגניבות הוא מושך\n"
	.string "במיוחד.\p"
	.string "{STR_VAR_2} קיבל אותו עבור ניצחון\n"
	.string "בתחרות מגניבות.\p"
	.string "זה באמת מוציא את המגניבות\n"
	.string "של {STR_VAR_2}.\p"
	.string "{STR_VAR_2} וסרט המגניבות!\n"
	.string "השילוב הוא סופר יעיל!$"

TVSpotTheCuties_Text_RibbonBeauty::
	.string "סרט היופי הוא מושך\n"
	.string "במיוחד.\p"
	.string "{STR_VAR_2} קיבל אותו עבור ניצחון\n"
	.string "בתחרות יופי.\p"
	.string "זה באמת מוציא את היופי\n"
	.string "של {STR_VAR_2}.\p"
	.string "{STR_VAR_2} וסרט היופי!\n"
	.string "השילוב הוא סופר יעיל!$"

TVSpotTheCuties_Text_RibbonCute::
	.string "סרט החמידות הוא מושך\n"
	.string "במיוחד.\p"
	.string "{STR_VAR_2} קיבל אותו עבור ניצחון\n"
	.string "בתחרות חמידות.\p"
	.string "זה באמת מוציא את החמידות\n"
	.string "של {STR_VAR_2}.\p"
	.string "{STR_VAR_2} וסרט החמידות!\n"
	.string "השילוב הוא סופר יעיל!$"

TVSpotTheCuties_Text_RibbonSmart::
	.string "סרט החכמה הוא מושך\n"
	.string "במיוחד.\p"
	.string "{STR_VAR_2} קיבל אותו עבור ניצחון\n"
	.string "בתחרות חכמה.\p"
	.string "זה באמת מוציא את החכמה\n"
	.string "של {STR_VAR_2}.\p"
	.string "{STR_VAR_2} וסרט החכמה!\n"
	.string "השילוב הוא סופר יעיל!$"

TVSpotTheCuties_Text_RibbonTough::
	.string "סרט הקשיחות הוא מושך\n"
	.string "במיוחד.\p"
	.string "{STR_VAR_2} קיבל אותו עבור ניצחון\n"
	.string "בתחרות קשיחות.\p"
	.string "זה באמת מוציא את הקשיחות\n"
	.string "של {STR_VAR_2}.\p"
	.string "{STR_VAR_2} וסרט הקשיחות!\n"
	.string "השילוב הוא סופר יעיל!$"

TVSpotTheCuties_Text_RibbonWinning::
	.string "סרט הניצחון הוא מושך\n"
	.string "במיוחד.\p"
	.string "{STR_VAR_2} קיבל אותו עבור הישגיו\n"
	.string "במגדל הקרב.\p"
	.string "זה באמת מוציא את העוצמה\n"
	.string "של {STR_VAR_2}.\p"
	.string "{STR_VAR_2} וסרט הניצחון!\n"
	.string "השילוב הוא סופר יעיל!$"

TVSpotTheCuties_Text_RibbonVictory::
	.string "סרט הניצחון הוא מושך\n"
	.string "במיוחד.\p"
	.string "{STR_VAR_2} קיבל אותו עבור הישגיו\n"
	.string "במגדל הקרב.\p"
	.string "זה באמת מוציא את העוצמה\n"
	.string "הבלתי נתפסת של {STR_VAR_2}.\p"
	.string "{STR_VAR_2} וסרט הניצחון!\n"
	.string "השילוב הוא סופר יעיל!$"

TVSpotTheCuties_Text_RibbonArtist::
	.string "סרט האמן הוא מושך\n"
	.string "במיוחד.\p"
	.string "{STR_VAR_2} קיבל אותו עבור היותו\n"
	.string "המודל עבור אמן.\p"
	.string "זה באמת מוציא את הקסם של כוכב\n"
	.string "הפופ של {STR_VAR_2}.\p"
	.string "{STR_VAR_2} וסרט האמן!\n"
	.string "השילוב הוא סופר יעיל!$"

TVSpotTheCuties_Text_RibbonEffort::
	.string "סרט העובד החרוץ הוא\n"
	.string "מושך במיוחד.\p"
	.string "{STR_VAR_2} קיבל אותו עבור היותו\n"
	.string "עובד מסור במיוחד.\p"
	.string "זה באמת מוציא את הנחישות\n"
	.string "של {STR_VAR_2}.\p"
	.string "{STR_VAR_2} וסרט העובד החרוץ!\n"
	.string "השילוב הוא סופר יעיל!$"

TVSpotTheCuties_Text_Outro::
	.string "…אנחה…\p"
	.string "סרטים ופוקימונים…\n"
	.string "הם הולכים כל כך נפלא יחד!\p"
	.string "לפני שאני מתעלף,\n"
	.string "אני נפרד מכולכם לשלום!$"

gTVPokemonNewsBattleFrontierText00::
	.string "ברכות!\n"
	.string "הגיע הזמן לחדשות פוקימון.\p"
	.string "יש לנו חדשות מרוממות מ\n"
	.string "חזית הקרב.$"

gTVPokemonNewsBattleFrontierText01::
	.string "המאמן {STR_VAR_1} קבע שיא חדש של\n"
	.string "רצף ניצחונות של {STR_VAR_2} תוך כדי אתגר\l"
	.string "הקרב יחיד בחדר מגדל הקרב.\l"
	.string "הנה ל{STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText02::
	.string "המאמן {STR_VAR_1} קבע שיא חדש של\n"
	.string "רצף ניצחונות של {STR_VAR_2} תוך כדי אתגר\l"
	.string "הקרב כפול בחדר מגדל הקרב.\l"
	.string "הנה ל{STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText03::
	.string "המאמן {STR_VAR_1} קבע שיא חדש של\n"
	.string "רצף ניצחונות של {STR_VAR_2} תוך כדי אתגר\l"
	.string "הקרב מרובה בחדר מגדל הקרב.\l"
	.string "הנה ל{STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText04::
	.string "המאמן {STR_VAR_1} קבע שיא חדש של\n"
	.string "רצף ניצחונות של {STR_VAR_2} תוך כדי אתגר\l"
	.string "הקרב מרובה קישור בחדר מגדל הקרב.\l"
	.string "הנה ל{STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText05::
	.string "המאמן {STR_VAR_1} קבע שיא חדש של\n"
	.string "רצף אליפויות של {STR_VAR_2} תוך כדי\l"
	.string "התחרות בטורנירי קרב יחיד\l"
	.string "של כיפת הקרב.\p"
	.string "הנה ל{STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText06::
	.string "המאמן {STR_VAR_1} קבע שיא חדש של\n"
	.string "רצף אליפויות של {STR_VAR_2} תוך כדי\l"
	.string "התחרות בטורנירי קרב כפול\l"
	.string "של כיפת הקרב.\p"
	.string "הנה ל{STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText07::
	.string "המאמן {STR_VAR_1} קבע שיא חדש של\n"
	.string "רצף ניצחונות של {STR_VAR_2} תוך כדי אתגר\l"
	.string "החלפת קרב יחיד במפעל הקרב.\l"
	.string "הנה ל{STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText08::
	.string "המאמן {STR_VAR_1} קבע שיא חדש של\n"
	.string "רצף ניצחונות של {STR_VAR_2} תוך כדי אתגר\l"
	.string "החלפת קרב כפול במפעל הקרב.\l"
	.string "הנה ל{STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText09::
	.string "המאמן {STR_VAR_1} קבע שיא חדש של\n"
	.string "ניקוי {STR_VAR_2} חדרים תוך כדי אתגר\l"
	.string "בחירת הקרב בשיפוע הקרב.\l"
	.string "הנה ל{STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText10::
	.string "המאמן {STR_VAR_1} קבע שיא חדש של\n"
	.string "רצף ניצחונות של {STR_VAR_2} תוך כדי\l"
	.string "התחרות בטורנירי נוקאאוט קבוע\l"
	.string "של זירת הקרב.\p"
	.string "הנה ל{STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText11::
	.string "המאמן {STR_VAR_1} קבע שיא חדש של\n"
	.string "רצף ניצחונות של {STR_VAR_2} תוך כדי אתגר\l"
	.string "הקרב יחיד באולם הארמון הקרב.\l"
	.string "הנה ל{STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText12::
	.string "המאמן {STR_VAR_1} קבע שיא חדש של\n"
	.string "רצף ניצחונות של {STR_VAR_2} תוך כדי אתגר\l"
	.string "הקרב כפול באולם הארמון הקרב.\l"
	.string "הנה ל{STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText13::
	.string "המאמן {STR_VAR_1} קבע שיא חדש של\n"
	.string "ניקוי {STR_VAR_2} קומות תוך כדי אתגר\l"
	.string "החיפוש אחר קרב בפירמידת הקרב.\l"
	.string "הנה ל{STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText14::
	.string "ולשלושת הפוקימונים, {STR_VAR_1},\n"
	.string "{STR_VAR_2}, ו{STR_VAR_3}!\p"
	.string "מזל טוב על הביצועים\n"
	.string "שובר השיאים שלכם!$"

gTVPokemonNewsBattleFrontierText15::
	.string "ולשני הפוקימונים, {STR_VAR_1}\n"
	.string "ו{STR_VAR_2}!\p"
	.string "מזל טוב על הביצועים\n"
	.string "שובר השיאים שלכם!$"

gTVPokemonNewsBattleFrontierText16::
	.string "ולארבעת הפוקימונים: {STR_VAR_1}!\p"
	.string "{STR_VAR_2}!\p"
	.string "{STR_VAR_3}!$"

gTVPokemonNewsBattleFrontierText17::
	.string "ו{STR_VAR_1}!\p"
	.string "מזל טוב על הביצועים\n"
	.string "שובר השיאים שלכם!$"

gTVPokemonNewsBattleFrontierText18::
	.string "בואו נקווה לעוד הישגים שוברי\n"
	.string "שיאים מ{STR_VAR_1} ומהפוקימונים\l"
	.string "הנאמנים!\p"
	.string "אלו החדשות בחדשות פוקימון!$"

gTVWhatsNo1InHoennTodayText00::
	.string "מהו מספר 1 בהון היום?\n"
	.string "כן, זה שוב הזמן הזה!\p"
	.string "שלום, צופים! אתם נותנים את המקסימום\n"
	.string "בכל מה שאתם עושים?\p"
	.string "בואו נסתכל על המאמן\n"
	.string "שעשה הכי טוב היום!\p"
	.string "המאמן מספר 1 של היום הוא לא אחר\n"
	.string "מאשר {STR_VAR_1}!$"

gTVWhatsNo1InHoennTodayText01::
	.string "בתוך יום אחד, {STR_VAR_1} סיבב את מכונות\n"
	.string "המזל בפינת המשחקים {STR_VAR_2} פעמים.\p"
	.string "בזמן המשחק, נשמע {STR_VAR_1}\n"
	.string "ממלמל, ”בשבילי, הגלגלים אפילו לא\l"
	.string "זזים…“\l"
	.string "זה לא מעניין?$"

gTVWhatsNo1InHoennTodayText02::
	.string "בתוך יום אחד, {STR_VAR_1} שיחק\n"
	.string "במשחק הרולטה בפינת\l"
	.string "המשחקים {STR_VAR_2} פעמים.\p"
	.string "בזמן המשחק, {STR_VAR_1} צעק,\n"
	.string "”תן לכדורים להחליט!“\p"
	.string "עיני המאמן היו ממוקדות ו\n"
	.string "הפנים הראו ריכוז.$"

gTVWhatsNo1InHoennTodayText03::
	.string "בתוך יום אחד, {STR_VAR_1} נלחם ב\n"
	.string "פוקימונים פראיים {STR_VAR_2} פעמים!\p"
	.string "ככל הנראה, הפוקימונים של {STR_VAR_1}\n"
	.string "גדלו להיות חזקים לאין ערוך.\p"
	.string "הם נראים להוטים להילחם בכל מקום,\n"
	.string "בכל זמן, ובכל צורה!$"

gTVWhatsNo1InHoennTodayText04::
	.string "בתוך יום אחד בלבד, {STR_VAR_1} סיבב\n"
	.string "את מערבל הפירות {STR_VAR_2} פעמים!\p"
	.string "לקראת הסוף, אפילו {STR_VAR_1}\n"
	.string "נראה מסוחרר.\p"
	.string "המאמן נראה מתנדנד\n"
	.string "כמו ספינדה!$"

gTVWhatsNo1InHoennTodayText05::
	.string "בתוך יום אחד בלבד, {STR_VAR_1} שתל\n"
	.string "{STR_VAR_2} פירות!\p"
	.string "כתוצאה מכך, הבגדים של {STR_VAR_1}\n"
	.string "התלכלכו עם אדמה.\p"
	.string "במקום שבו המאמן שתל, פרחים\n"
	.string "אינסופיים פרחו.\p"
	.string "נאמר שהפרחים מרגיעים\n"
	.string "את רגשותיהם של אנשים.$"

gTVWhatsNo1InHoennTodayText06::
	.string "בתוך יום אחד בלבד, {STR_VAR_1} קטף\n"
	.string "{STR_VAR_2} פירות!\p"
	.string "התיק של {STR_VAR_1} התמלא כל כך\n"
	.string "בפירות, שהמאמן התקשה\l"
	.string "ללכת לאחר מכן!$"

gTVWhatsNo1InHoennTodayText07::
	.string "בתוך יום אחד בלבד, {STR_VAR_1} השיג\n"
	.string "{STR_VAR_2} נקודות קרב!\p"
	.string "{STR_VAR_1} נראה לאחר מכן מתלבט\n"
	.string "עם הבחירה להחליף את\l"
	.string "נקודות הקרב עבור פריט מגניב או\l"
	.string "קישוט פנים נחמד.\p"
	.string "המאמן דווח כשהוא מחייך\n"
	.string "בזמן שהוא שוקל אפשרויות.$"

gTVWhatsNo1InHoennTodayText08::
	.string "טוב, זה משהו!\p"
	.string "{STR_VAR_1}!\n"
	.string "אתה המאמן מספר 1 של היום!\p"
	.string "צופים, קחו עידוד מ{STR_VAR_1}!\n"
	.string "גם אתם יכולים להיות מספר 1 בכל יום!$"

TVSecretBaseSecrets_Text_Intro::
	.string "סודות הבסיס הסודי!\p"
	.string "מה עושים מאמנים בסודיות\n"
	.string "של בסיסים סודיים?\p"
	.string "היום, אנו חוקרים את הבסיס הסודי\n"
	.string "של {STR_VAR_1}.\p"
	.string "אה? נראה ש{STR_VAR_2} הגיע\n"
	.string "לביקור.\p"
	.string "בואו נציץ!\p"
	.string "מה {STR_VAR_2} יעשה?$"

TVSecretBaseSecrets_Text_WhatWillPlayerDoNext1::
	.string "מה {STR_VAR_2} יעשה עכשיו?$"

TVSecretBaseSecrets_Text_WhatWillPlayerDoNext2::
	.string "ועכשיו, מה {STR_VAR_2} יעשה?$"

TVSecretBaseSecrets_Text_TookXStepsBeforeLeaving::
	.string "בסופו של דבר, {STR_VAR_2} צעד {STR_VAR_3} צעדים\n"
	.string "בבסיס הסודי של {STR_VAR_1} לפני\l"
	.string "שיצא.$"

TVSecretBaseSecrets_Text_BaseFailedToInterestPlayer::
	.string "הממ…\p"
	.string "נראה שהבסיס הסודי של {STR_VAR_1}\n"
	.string "לא הצליח לעניין את {STR_VAR_2}…$"

TVSecretBaseSecrets_Text_PlayerEnjoyedBase::
	.string "{STR_VAR_2} נראה שנהנה\n"
	.string "מהבסיס הסודי של {STR_VAR_1} ביסודיות.$"

TVSecretBaseSecrets_Text_PlayerHugeFanOfBase::
	.string "{STR_VAR_2} נראה שהפך\n"
	.string "למעריץ ענק של הבסיס הסודי\l"
	.string "של {STR_VAR_1}.$"

TVSecretBaseSecrets_Text_Outro::
	.string "צופים אולי ירצו לבדוק גם\n"
	.string "את הבסיס הסודי של {STR_VAR_1}.\p"
	.string "כווננו בפעם הבאה כשנבקר בבסיס סודי\n"
	.string "אחר! תודה שהצטרפתם אלינו!$"

TVSecretBaseSecrets_Text_StoppedMoving1::
	.string "המבקר הפסיק לזוז!\p"
	.string "המבקר לא זז בכלל!\p"
	.string "האם הבסיס הסודי של {STR_VAR_1}\n"
	.string "היה כל כך לא מרשים?$"

TVSecretBaseSecrets_Text_StoppedMoving2::
	.string "המבקר הפסיק לזוז!\p"
	.string "המבקר לא זז בכלל!\p"
	.string "האם זו עייפות?\n"
	.string "האם המבקר התעייף?$"

TVSecretBaseSecrets_Text_UsedChair::
	.string "המבקר התיישב על כיסא!\n"
	.string "המבקר יושב!\p"
	.string "תסתכלו על המבט המאושר הזה!\p"
	.string "הכיסא הזה בטח מאוד נוח\n"
	.string "כדי לקבל תגובה כזו!$"

TVSecretBaseSecrets_Text_UsedBalloon::
	.string "המבקר הסתער על בלון!\p"
	.string "הוא התפוצץ!\n"
	.string "אוי, אלוהים, הוא התפוצץ!\p"
	.string "המבקר נראה מופתע מה\n"
	.string "רעש הפתאומי!$"

TVSecretBaseSecrets_Text_UsedTent::
	.string "המבקר נכנס לאוהל!\p"
	.string "המבקר רץ מסביב!\p"
	.string "אוי, שלי, המבקר משתולל!\p"
	.string "המבקר נראה מופתע מ\n"
	.string "גודל האוהל!$"

TVSecretBaseSecrets_Text_UsedPlant::
	.string "המבקר בוחן\n"
	.string "צמח עציץ!\p"
	.string "למבקר יש טעם בוגר\n"
	.string "באופן מפתיע!$"

TVSecretBaseSecrets_Text_UsedGoldShield::
	.string "המבקר בוחן\n"
	.string "מגן זהב!\p"
	.string "עיני המבקר נראות\n"
	.string "מוארות בפליאה!$"

TVSecretBaseSecrets_Text_UsedSilverShield::
	.string "המבקר בוחן\n"
	.string "מגן כסף!\p"
	.string "המבקר נראה עם עיניים\n"
	.string "פעורות לרווחה!$"

TVSecretBaseSecrets_Text_UsedGlassOrnament::
	.string "המבקר בוחן\n"
	.string "קישוט זכוכית!\p"
	.string "אוי, לא!\p"
	.string "המבקר נוגע בו!\p"
	.string "הוא מתכסה ב\n"
	.string "טביעות אצבע…$"

TVSecretBaseSecrets_Text_UsedTV::
	.string "המבקר צופה בטלוויזיה!\p"
	.string "נראה שיש לנו מעריץ גדול של טלוויזיה!$"

TVSecretBaseSecrets_Text_UsedMudBall::
	.string "המבקר דרך על כדור בוץ!\p"
	.string "המבקר נראה שמח!$"

TVSecretBaseSecrets_Text_UsedBag::
	.string "…אה?\p"
	.string "המבקר מושיט יד אל התיק\n"
	.string "שלו ומחטט בו!\p"
	.string "המבקר שלף\n"
	.string "{STR_VAR_2} אחד!\p"
	.string "תסתכל על המבקר מחייך בזמן\n"
	.string "שהוא מחזיק את ה{STR_VAR_2}!\p"
	.string "זה כמו פרסומת בטלוויזיה!$"

TVSecretBaseSecrets_Text_UsedCushion::
	.string "המבקר תופס כרית ו…$"

TVSecretBaseSecrets_Text_HitCushion::
	.string "…מתחיל להכות בה!\p"
	.string "האם המבקר נמצא תחת הרבה לחץ?$"

TVSecretBaseSecrets_Text_HuggedCushion::
	.string "…מחבק אותה חזק!\p"
	.string "האם המבקר יכול להיות שמח\n"
	.string "בגלל משהו?$"

TVSecretBaseSecrets_Text_BattledWon::
	.string "המבקר משוחח עם\n"
	.string "{STR_VAR_1}!\p"
	.string "נראה שהם הולכים\n"
	.string "לקיים קרב!\p"
	.string "ו…\p"
	.string "זה המבקר!\n"
	.string "המבקר ניצח בקרב חוץ!\p"
	.string "המבקר רוקד\n"
	.string "ריקוד ניצחון!$"

TVSecretBaseSecrets_Text_BattledLost::
	.string "המבקר משוחח עם\n"
	.string "{STR_VAR_1}!\p"
	.string "נראה שהם הולכים\n"
	.string "לקיים קרב!\p"
	.string "ו…\p"
	.string "זה {STR_VAR_1}!\n"
	.string "המבקר הפסיד!\p"
	.string "המבקר נראה מדוכא!$"

TVSecretBaseSecrets_Text_DeclinedBattle::
	.string "המבקר משוחח עם\n"
	.string "{STR_VAR_1}!\p"
	.string "נראה שהם הולכים\n"
	.string "לקיים קרב!\p"
	.string "ו…\p"
	.string "לא, המבקר סירב!\p"
	.string "לא יהיה קרב אחרי הכל!\p"
	.string "האם המבקר מצא את {STR_VAR_1}\n"
	.string "לא מושך?$"

TVSecretBaseSecrets_Text_UsedPoster::
	.string "המבקר בוהה בריכוז\n"
	.string "בכרזה!\p"
	.string "האם הכרזה לטעמו של\n"
	.string "המבקר?\p"
	.string "…אבל… יש משהו מטריד\n"
	.string "בבהייה של המבקר.$"

TVSecretBaseSecrets_Text_UsedNoteMat::
	.string "המבקר דרך על מחצלת צלילים!\p"
	.string "…הממ…\n"
	.string "המבקר הלחין מנגינה מצחיקה!$"

TVSecretBaseSecrets_Text_BattledDraw::
	.string "המבקר משוחח עם\n"
	.string "{STR_VAR_1}!\p"
	.string "נראה שהם הולכים\n"
	.string "לקיים קרב!\p"
	.string "ו…\p"
	.string "זו תיקו!\n"
	.string "שום דבר לא נפתר!\p"
	.string "שני המאמנים נראים מאוד\n"
	.string "מאוכזבים!$"

TVSecretBaseSecrets_Text_UsedSpinMat::
	.string "המבקר דרך על\n"
	.string "מחצלת סיבוב!\p"
	.string "נראה שהמבקר מסוחרר!\p"
	.string "המבקר מתנדנד!\n"
	.string "היזהר!$"

TVSecretBaseSecrets_Text_UsedSandOrnament::
	.string "המבקר מושיט יד ל\n"
	.string "קישוט חול!\p"
	.string "אה!\p"
	.string "זה התפורר!\n"
	.string "זה התפרק לחתיכות!\p"
	.string "המבקר נראה נבוך\n"
	.string "ואשם!$"

TVSecretBaseSecrets_Text_UsedDesk::
	.string "המבקר משפשף שולחן\n"
	.string "עם האצבע!\p"
	.string "ככל הנראה, המבקר לא מאשר\n"
	.string "אבק!\p"
	.string "המבקר מודאג באופן מפתיע\n"
	.string "לגבי ניקיון!$"

TVSecretBaseSecrets_Text_UsedBrick::
	.string "המבקר בוהה בלבנה!\p"
	.string "אולי המבקר חושב על\n"
	.string "האובייקט שעל הלבנה.$"

TVSecretBaseSecrets_Text_UsedSolidBoard::
	.string "המבקר הולך על\n"
	.string "הלוח המוצק.\p"
	.string "המבקר ממשיך להסתכל למטה.\p"
	.string "המבקר נראה ביישן וזהיר\n"
	.string "באופן מפתיע!$"

TVSecretBaseSecrets_Text_UsedFence::
	.string "המבקר מסתכל בריכוז\n"
	.string "על גדר!\p"
	.string "האם רעיון חדש למלכודת קפץ\n"
	.string "לראשו של המבקר?$"

TVSecretBaseSecrets_Text_UsedGlitterMat::
	.string "המבקר דרך על\n"
	.string "מחצלת נצנצים!\p"
	.string "המבקר מקבל מגוון\n"
	.string "של תנוחות!\p"
	.string "המבקר נראה כמפנטז\n"
	.string "להיות אליל!$"

TVSecretBaseSecrets_Text_UsedTire::
	.string "המבקר בוהה בריכוז\n"
	.string "בצמיג!\p"
	.string "האם המבקר חושב על\n"
	.string "סוג המכונית שתשתמש בו?$"

TVSecretBaseSecrets_Text_UsedStand::
	.string "המבקר טיפס על דוכן!\p"
	.string "המבקר מסתכל על הבסיס של {STR_VAR_1}\n"
	.string "מלמעלה!\p"
	.string "ו…\p"
	.string "משחרר שאגה!\n"
	.string "המבקר שואג!$"

TVSecretBaseSecrets_Text_BrokeDoor::
	.string "המבקר הסתער בראשו לתוך\n"
	.string "דלת שבירה!\p"
	.string "המבקר צוחק בקול רם!$"

TVSecretBaseSecrets_Text_UsedDoll::
	.string "המבקר מדבר לבובה!\p"
	.string "…זה קצת מצמרר…$"

TVSecretBaseSecrets_Text_UsedSlide::
	.string "המבקר מטפס על הסולם\n"
	.string "במגלשה!\p"
	.string "ו…\p"
	.string "המבקר גלש למטה!\p"
	.string "נראה שהמבקר נהנה\n"
	.string "מאוד!$"

TVSecretBaseSecrets_Text_UsedSlideButDidntGoDown::
	.string "המבקר מטפס על הסולם\n"
	.string "במגלשה!\p"
	.string "ו…\p"
	.string "המבקר ירד חזרה במורד\n"
	.string "הסולם!\p"
	.string "האם המבקר פתאום נבהל?$"

TVSecretBaseSecrets_Text_UsedJumpMat::
	.string "המבקר דרך על\n"
	.string "מחצלת קפיצה!\p"
	.string "המבקר קפץ פעם אחת!\p"
	.string "קפץ פעמיים!\p"
	.string "ונחיתה מוצלחת!\p"
	.string "המבקר מוחא כפיים!\n"
	.string "איזו הופעת יחיד!$"

gTVSafariFanClubText00::
	.string "מועדון המעריצים של ספארי!\p"
	.string "כתב: כל הזכויות שמורות, חברים!\n"
	.string "אתם זורקים את כדורי הספארי האלה, נכון?\p"
	.string "אתם יכולים להיות בטוחים שאני כאן באזור\n"
	.string "הספארי מלא בפוקימונים מדהימים!\p"
	.string "בואו נתחיל ונקשקש עם החבר הטוב הזה\n"
	.string "של מדריך ספארי!\p"
	.string "בסדר, חבר, איך נראים המאמנים\n"
	.string "המבקרים?$"

gTVSafariFanClubText01::
	.string "מדריך: נראה שכולם עובדים\n"
	.string "קשה על זה.\p"
	.string "{STR_VAR_1} עושה טוב במיוחד.\p"
	.string "למה, לפני כן, {STR_VAR_1} תפס\n"
	.string "{STR_VAR_2} פוקימונים.$"

gTVSafariFanClubText02::
	.string "המאמן חכם עם פוקיגוש.\n"
	.string "השתמש ב{STR_VAR_2} בפעם ההיא, אני חושב.$"

gTVSafariFanClubText03::
	.string "המאמן לא השתמש בפוקיגוש\n"
	.string "אחד! אף אחד!\p"
	.string "זה מומחה בשבילכם.$"

gTVSafariFanClubText04::
	.string "כתב: זה נכון, אם כך?\p"
	.string "נשמע שהחבר שלנו {STR_VAR_1}\n"
	.string "הוא מאסטר ספארי חסון!\p"
	.string "מדריך: אני מקווה שהמאמן יחזור\n"
	.string "ויציג לנו את הטכניקה הנהדרת הזו.$"

gTVSafariFanClubText05::
	.string "מדריך: לא נראה שאף אחד מצליח\n"
	.string "במיוחד.\p"
	.string "{STR_VAR_1} חווה את זה רע במיוחד.\p"
	.string "למה, לפני כן, המאמן רק\n"
	.string "הצליח לתפוס {STR_VAR_2} פוקימונים.$"

gTVSafariFanClubText06::
	.string "מדריך: לא נראה שאף אחד מצליח\n"
	.string "במיוחד.\p"
	.string "{STR_VAR_1} חווה את זה רע במיוחד.\p"
	.string "למה, לפני כן, המאמן לא\n"
	.string "הצליח לתפוס אף פוקימון. אף אחד!$"

gTVSafariFanClubText07::
	.string "המאמן אכן משתמש בפוקיגוש.\n"
	.string "השתמש ב{STR_VAR_2} בפעם ההיא, אני חושב.\p"
	.string "אבל, היי, הלוואי שהמאמן היה\n"
	.string "משתפר קצת בזה.$"

gTVSafariFanClubText08::
	.string "אני חושב שלמאמן היה מזל טוב יותר\n"
	.string "אם היה משתמש בפוקיגוש, שבהם הוא לא\l"
	.string "השתמש בכלל בפעם ההיא.$"

gTVSafariFanClubText09::
	.string "כתב: זה נכון, אם כך?\p"
	.string "נשמע שהחבר שלנו {STR_VAR_1}\n"
	.string "צריך עוד תיבול ספארי.\p"
	.string "מדריך: אני מקווה שהמאמן יבקר\n"
	.string "שוב ושוב כדי לתפוס את העניין.$"

gTVSafariFanClubText10::
	.string "כתב: צודק, זה נכון!\n"
	.string "להתמודד עם אתגרים זה חשוב!\p"
	.string "צופים, בואו לאזור הספארי\n"
	.string "וקבלו את האתגר בעצמכם!\p"
	.string "עד הפעם הבאה, להתראות!$"

ContestLiveUpdates_Text_Intro::
	.string "”עדכונים חיים של תחרות פוקימון!“\p"
	.string "מנחה: תודה שהצטרפתם אלינו!\p"
	.string "אנחנו בשידור חי מאתר ה{STR_VAR_1}\n"
	.string "שזה עתה הסתיים.\p"
	.string "האולם עדיין מלא ב\n"
	.string "קהל שלא מוכן לעזוב.\p"
	.string "צופה: {STR_VAR_2}!\p"
	.string "צופה: {STR_VAR_3}!\p"
	.string "מנחה: כפי ששמעתם זה עתה, בתחרות\n"
	.string "ניצח הפוקימון {STR_VAR_2} של {STR_VAR_3}.\l"
	.string "צופה: {STR_VAR_2}!\n"
	.string "אתה הטוב ביותר!\p"
	.string "צופה: {STR_VAR_3}!\n"
	.string "כל הכבוד!\p"
	.string "מנחה: בואו נשמע מה יש למעריצים\n"
	.string "לומר על התחרות הזו.$"

ContestLiveUpdates_Text_WonBothRounds::
	.string "צופה: ה{STR_VAR_2} היה בראש\n"
	.string "גם בשיפוט הראשוני וגם במשני!\p"
	.string "ה{STR_VAR_2} הזה ימשיך לנצח!$"

ContestLiveUpdates_Text_BetterRound2::
	.string "צופה: ה{STR_VAR_2} לא הצליח\n"
	.string "בשיפוט הראשוני, אבל הוא\l"
	.string "ניקה את הרצפה בשיפוט המשני!\p"
	.string "זה היה קאמבק מהאגדות\n"
	.string "עבור ה{STR_VAR_2} הזה. יופי!$"

ContestLiveUpdates_Text_EqualRounds::
	.string "צופה: ה{STR_VAR_2} נשאר\n"
	.string "עקבי לאורך כל השיפוט הראשוני\l"
	.string "והמשני.\p"
	.string "{STR_VAR_3} וה{STR_VAR_2},\n"
	.string "הם לא שילוב רגיל!$"

ContestLiveUpdates_Text_BetterRound1::
	.string "צופה: מבחינת להיות {STR_VAR_1},\n"
	.string "ה{STR_VAR_2} הזה היה יוצא דופן.\p"
	.string "אני מקווה שהוא יעשה הופעות טובות\n"
	.string "יותר בפעם הבאה, למרות זאת.$"

ContestLiveUpdates_Text_GotNervous::
	.string "צופה: כאשר ה{STR_VAR_2} נהיה\n"
	.string "עצבני, לא יכולתי לעצור את עצמי מ\l"
	.string "לצעוק עידוד.\p"
	.string "הייתי רוצה לומר ל{STR_VAR_2}\n"
	.string "הזה, ”ברכות!“$"

ContestLiveUpdates_Text_StartledFoes::
	.string "צופה: ההופעה של ה{STR_VAR_2} הזה\n"
	.string "הפתיעה אפילו אותי!\p"
	.string "{STR_VAR_2}, היית מדהים!$"

ContestLiveUpdates_Text_UsedCombo::
	.string "צופה: ההופעה המשולבת של ה{STR_VAR_2} הזה\n"
	.string "היתה מדהימה!\p"
	.string "זה זעזע אותי עד עמקי נשמתי!$"

ContestLiveUpdates_Text_ExcitingAppeal::
	.string "צופה: ההופעה של ה{STR_VAR_2}\n"
	.string "המנצח גרמה לליבי לפעום!$"

ContestLiveUpdates_Text_WasCool::
	.string "{STR_VAR_2}!\n"
	.string "היית מגניב!$"

ContestLiveUpdates_Text_WasBeautiful::
	.string "{STR_VAR_2}!\n"
	.string "היית יפה!$"

ContestLiveUpdates_Text_WasCute::
	.string "{STR_VAR_2}!\n"
	.string "היית חמוד!$"

ContestLiveUpdates_Text_WasSmart::
	.string "{STR_VAR_2}!\n"
	.string "היית חכם!$"

ContestLiveUpdates_Text_WasTough::
	.string "{STR_VAR_2}!\n"
	.string "היית קשוח!$"

ContestLiveUpdates_Text_VeryExcitingAppeal::
	.string "צופה: ההופעה של ה{STR_VAR_2}\n"
	.string "המנצח עדיין גורמת לליבי לפעום!$"

ContestLiveUpdates_Text_VeryCool::
	.string "{STR_VAR_2}!\n"
	.string "אתה המילה האחרונה במגניבות!$"

ContestLiveUpdates_Text_VeryBeautiful::
	.string "{STR_VAR_2}!\n"
	.string "אתה הכי יפה!$"

ContestLiveUpdates_Text_VeryCute::
	.string "{STR_VAR_2}!\n"
	.string "אתה פשוט הכי חמוד!$"

ContestLiveUpdates_Text_VerySmart::
	.string "{STR_VAR_2}!\n"
	.string "אתה החכם ביותר מבין החכמים!$"

ContestLiveUpdates_Text_VeryTough::
	.string "{STR_VAR_2}!\n"
	.string "אתה הקשוח מבין הקשוחים!$"

ContestLiveUpdates_Text_TookBreak::
	.string "צופה: אפילו כאשר ה{STR_VAR_2}\n"
	.string "לקח הפסקה מלעשות הופעות,\l"
	.string "לא יכולתי להוריד ממנו את העיניים.\p"
	.string "אני שבוי על ידי ה{STR_VAR_2} הזה.$"

ContestLiveUpdates_Text_GotStartled::
	.string "צופה: כאשר ה{STR_VAR_2} הופתע\n"
	.string "מהופעה של פוקימון אחר,\l"
	.string "הייתי קרוב לדמעות.\p"
	.string "{STR_VAR_2}, היית עמיד!\n"
	.string "כל הכבוד!$"

ContestLiveUpdates_Text_MoveWonderful::
	.string "צופה: אוי…\n"
	.string "ה{STR_VAR_3} של ה{STR_VAR_2} הזה!\l"
	.string "ה{STR_VAR_3} של ה{STR_VAR_2}!\l"
	.string "ה{STR_VAR_3} של ה{STR_VAR_2}!\l"
	.string "איך זה יכול להיות כל כך נפלא?$"

ContestLiveUpdates_Text_TalkAboutAnotherMon::
	.string "מנחה: טוב, הנה זה. המקום הזה\n"
	.string "מלא במעריצים של ה{STR_VAR_1}!\p"
	.string "אני צריך גם לציין שפוקימון\n"
	.string "אחר, ה{STR_VAR_3} של {STR_VAR_2}, תפס\l"
	.string "את עיני.\p"
	.string "ה{STR_VAR_3} של {STR_VAR_2}…$"

ContestLiveUpdates_Text_FailedToAppeal::
	.string "הוא נכשל מלעשות הופעה אחת במהלך\n"
	.string "השיפוט המשני מרוב עצבנות.\p"
	.string "בפעם הבאה, הייתי רוצה לראות את ה{STR_VAR_1}\n"
	.string "הזה עושה אפילו הופעה אחת.$"

ContestLiveUpdates_Text_LastInBothRounds::
	.string "הוא הגיע אחרון מוחלט גם בשיפוט\n"
	.string "הראשוני וגם במשני.\p"
	.string "אני מקווה ש{STR_VAR_1} יאמן מחדש את\n"
	.string "ה{STR_VAR_2} הזה וימחק את הבושה של\l"
	.string "הגמר הזה במקום האחרון הבלתי מעורער.$"

ContestLiveUpdates_Text_NotExcitingEnough::
	.string "הוא נכשל מלהשתמש בהתרגשות\n"
	.string "של הקהל ולעשות הופעה\l"
	.string "מתאימה.\p"
	.string "אנו מקווים ש{STR_VAR_1} ילמד איך לקבל\n"
	.string "תחושה לקהל וללהיב את ההתרגשות\l"
	.string "שלהם לשיא בפעם הבאה.$"

ContestLiveUpdates_Text_LostAfterWinningRound1::
	.string "בזמן שסיים ראשון בשיפוט\n"
	.string "הראשוני, ההופעות שלו בשיפוט המשני\l"
	.string "נכשלו מלהצליח.\p"
	.string "הוא סבל מהפסד משפיל של חזרה\n"
	.string "ממאחור.\p"
	.string "אני בטוח ש{STR_VAR_1} לומד איך לעשות\n"
	.string "הופעות יעילות יותר עכשיו.$"

ContestLiveUpdates_Text_NeverExciting::
	.string "הקהל אף פעם לא התרגש מההופעות\n"
	.string "שלו במהלך השיפוט המשני.\p"
	.string "אנו מקווים שהוא יפסיק לדאוג לגבי\n"
	.string "פוקימונים אחרים וילמד לכוון\l"
	.string "את ההופעות שלו לקהל יותר.$"

ContestLiveUpdates_Text_LostBySmallMargin::
	.string "הוא הפסיד ל{STR_VAR_2} של {STR_VAR_1}\n"
	.string "בהפרש קטן בלבד.\p"
	.string "זה בטח שובר לב להיות\n"
	.string "כל כך קרוב לניצחון רק כדי להיכשל.\p"
	.string "לא הייתי מופתע אם {STR_VAR_3}\n"
	.string "בוכה על התוצאה הזו.$"

ContestLiveUpdates_Text_RepeatedAppeals::
	.string "הוא אכזב את השופט על ידי\n"
	.string "חזרה על אותן הופעות.\p"
	.string "זו טעות בלתי נסלחת בכל\n"
	.string "תחרות, והפוקימון שילם.\p"
	.string "{STR_VAR_1} צריך להרגיש אשם על\n"
	.string "ההופעה המצערת הזו.$"

ContestLiveUpdates_Text_ValiantEffortButLost::
	.string "{STR_VAR_1} הראה מאמץ אמיץ,\n"
	.string "אבל…\p"
	.string "זה היה לשווא, סיים אחרון.\p"
	.string "{STR_VAR_1} צריך ללמוד מההפסד הזה\n"
	.string "ולשים את הידע לשימוש טוב.$"

ContestLiveUpdates_Text_Outro::
	.string "הייתי רוצה לסיים את התוכנית הזו עם\n"
	.string "הפרידה הרגילה שלנו מהמנצחים.\p"
	.string "הפעם, זה {STR_VAR_1} ו\n"
	.string "ה{STR_VAR_2}!\p"
	.string "מנחה: האם כולם מוכנים?\n"
	.string "כולם יחד, עכשיו!\p"
	.string "קהל: {STR_VAR_1}! {STR_VAR_2}!\n"
	.string "מזל טוב!\l"
	.string "אתה המנצח בתחרות!$"

gTVPokemonBattleUpdateText00::
	.string "”עדכון קרב פוקימון!“\p"
	.string "מביאים לכם את תוצאות קרבות הפוקימונים\n"
	.string "כפי שהן מגיעות!$"

gTVPokemonBattleUpdateText01::
	.string "המאמנים {STR_VAR_1} ו\n"
	.string "{STR_VAR_2} התמודדו זה מול זה ב\l"
	.string "קרב {STR_VAR_3}.\p"
	.string "המשחק הזה הסתיים בניצחון ל\n"
	.string "{STR_VAR_1}!$"

gTVPokemonBattleUpdateText02::
	.string "בקרב, ה{STR_VAR_2} של {STR_VAR_1}\n"
	.string "היה כוח אדיר שמשתמש ב{STR_VAR_3}!\l"
	.string "ה{STR_VAR_2} של {STR_VAR_1} היה כוח אדיר\n"
	.string "שהשתמש ב{STR_VAR_3}!$"

gTVPokemonBattleUpdateText03::
	.string "הופעה חלשה של ה{STR_VAR_2} של {STR_VAR_1}\n"
	.string "שבאמת פגעה.$"

gTVPokemonBattleUpdateText04::
	.string "מזל טוב על הניצחון שלך,\n"
	.string "{STR_VAR_1}!\p"
	.string "ולמובס {STR_VAR_2},\n"
	.string "אנו מקווים לתוצאה טובה יותר בפעם הבאה!\p"
	.string "זה מסיים את הפרק הזה של\n"
	.string "”עדכון קרב פוקימון!“$"

gTVPokemonBattleUpdateText05::
	.string "הצוותים של המאמנים {STR_VAR_1} ו\n"
	.string "{STR_VAR_2} נפגשו בקרב מרובה.\p"
	.string "המשחק הזה הסתיים בניצחון ל\n"
	.string "צוות של {STR_VAR_1}.$"

gTVPokemonBattleUpdateText06::
	.string "בקרב, ה{STR_VAR_2} בצוות\n"
	.string "של {STR_VAR_1} היה כוח אדיר\l"
	.string "שהשתמש ב{STR_VAR_3}.$"

gTVPokemonBattleUpdateText07::
	.string "ההופעה החלשה של ה{STR_VAR_3}\n"
	.string "בצוות של {STR_VAR_2} באמת פגעה.\p"
	.string "מזל טוב על הניצחון של הצוות שלך,\n"
	.string "{STR_VAR_1}!\p"
	.string "באשר לצוות המובס של {STR_VAR_2},\n"
	.string "אנו מקווים לתוצאה טובה יותר בפעם הבאה!\p"
	.string "זה מסיים את הפרק הזה של\n"
	.string "”עדכון קרב פוקימון!“$"

GabbyAndTy_Text_GabbyPreFirstBattle:
	.string "גבי: אה! זה עתה ראינו מאמן\n"
	.string "שנראה קשוח דווקא כאן!\p"
	.string "אוקי, להריץ מצלמה!\n"
	.string "בואו נעשה את הראיון הזה.$"

GabbyAndTy_Text_GabbyIntro:
	.string "גבי: אה! אתה {PLAYER}! היי!\n"
	.string "אתה זוכר אותנו מהפעם הקודמת?\p"
	.string "אתה יכול להראות לנו כמה חזק יותר\n"
	.string "נהיית? אוקי, רמז לראיון!$"

GabbyAndTy_Text_GabbyDefeatFirstTime:
	.string "גבי: העיניים שלי לא שיקרו!\n"
	.string "גיליתי מאמן מדהים!$"

GabbyAndTy_Text_WhoAreYouInterview:
	.string "גבי: מדהים! מדהים!\n"
	.string "מי אתה?!\p"
	.string "ידעתי שאנחנו עלינו על משהו פרוע\n"
	.string "כשראינו אותך!\p"
	.string "אה, בבקשה תן לי להסביר. אנחנו מטיילים\n"
	.string "בכל מקום ומראיינים כל מיני\l"
	.string "סוגי מאמנים.\p"
	.string "אז, האם תיתן לנו קצת מזמנך\n"
	.string "לצורך ראיון?$"

GabbyAndTy_Text_QuoteFromLastInterview:
	.string "גבי: ”{STR_VAR_1}“!\p"
	.string "זוכר? זה הציטוט שנתת לנו\n"
	.string "כמכריע הקרב בפעם הקודמת.\p"
	.string "אני אף פעם, אף פעם לא שוכח דברים כאלה!$"

GabbyAndTy_Text_YouStompedUsInterviewAgain:
	.string "בפעם האחרונה שנלחמנו, דרסת\n"
	.string "אותנו לפני שיכולנו להתכונן…\p"
	.string "בכל מקרה, מה דעתך?\n"
	.string "אתה רוצה להתראיין שוב?$"

GabbyAndTy_Text_YouThrewABallAtUsInterviewAgain:
	.string "בפעם האחרונה שנלחמנו, לא\n"
	.string "זרקת עלינו פוקי כדור?\p"
	.string "היינו בהלם! אז סיפרנו לכולם,\n"
	.string "פשוט לכולם, על זה!\p"
	.string "בכל מקרה, מה דעתך?\n"
	.string "אתה רוצה להתראיין שוב?$"

GabbyAndTy_Text_CleverItemSkillsInterviewAgain:
	.string "בפעם האחרונה שנלחמנו, כישורי\n"
	.string "הפריטים שלך גמרו אותנו בחוכמה.\p"
	.string "בכל מקרה, מה דעתך?\n"
	.string "אתה רוצה להתראיין שוב?$"

GabbyAndTy_Text_WeLookedRespectableInterviewAgain:
	.string "בפעם האחרונה שנלחמנו, הצלחנו\n"
	.string "להיראות מכובד.\p"
	.string "בכל מקרה, מה דעתך?\n"
	.string "אתה רוצה להתראיין שוב?$"

GabbyAndTy_Text_InterviewAgain:
	.string "בכל מקרה, מה דעתך?\n"
	.string "אתה רוצה להתראיין שוב?$"

GabbyAndTy_Text_DescribeYourFeelings:
	.string "אתה מוכן?\n"
	.string "תודה!\p"
	.string "אוקי, אני צריכה שתתאר את\n"
	.string "הרגשות שלך לגבי הקרב שלנו, אבל זה\l"
	.string "חייב להיות קצר ומתוק. קדימה!$"

GabbyAndTy_Text_PerfectWellBeSeeingYou:
	.string "גבי: ממ, כן!\n"
	.string "זה המכריע המושלם!\p"
	.string "יש לי הרגשה שזה יהפוך\n"
	.string "לתוכנית טלוויזיה נהדרת.\p"
	.string "יש סיכוי שהם ישדרו את זה\n"
	.string "בטלוויזיה, אז הקפד לחפש אותנו!\p"
	.string "אוקי!\n"
	.string "נתראה!$"

GabbyAndTy_Text_DontGiveUpKeepingEyeOut:
	.string "גבי: אה…\p"
	.string "אוקי, אבל אל תוותר!\n"
	.string "אנחנו נשמור עליך עין!$"

GabbyAndTy_Text_KeepingAnEyeOutForYou:
	.string "גבי: אנחנו נשמור עליך עין!$"

GabbyAndTy_Text_GabbyNotEnoughMons:
	.string "גבי: האם יש מאמן חזק\n"
	.string "בכל מקום עם הרבה פוקימונים?$"

GabbyAndTy_Text_GiveUsAnInterviewThisTime:
	.string "גבי: וואו, אתה משהו!\p"
	.string "נהיית הרבה יותר חזק--הרבה יותר --\n"
	.string "מאז שנלחמנו בפעם הקודמת.\p"
	.string "צדקנו לגביך כאשר\n"
	.string "ראינו אותך כמאמן חם.\p"
	.string "אז, בכל מקרה, מה דעתך?\n"
	.string "האם תהיה מוכן לתת לנו ראיון\l"
	.string "הפעם?$"

GabbyAndTy_Text_GabbyDefeat:
	.string "גבי: זה היה קרב אינטנסיבי!\n"
	.string "האם צילמת את הכל במצלמה?$"

GabbyAndTy_Text_TyPreFirstBattle:
	.string "טיי: היי, תראו כאן! מאמן שנראה\n"
	.string "קשוח דווקא כאן!\l"
	.string "המצלמה רצה!$"

GabbyAndTy_Text_TyIntro:
	.string "טיי: היי, תראו כאן!\n"
	.string "אני זוכר אותך!\p"
	.string "אני אצלם את כל הקרב הזה על ה\n"
	.string "מצלמה הזו!$"

GabbyAndTy_Text_TyPostBattle:
	.string "טיי: אתה טבעי!\n"
	.string "יש לי כאן צילומים מעולים!$"

GabbyAndTy_Text_TyNotEnoughMons:
	.string "טיי: יש לך רק את הפוקימון האחד\n"
	.string "וזהו?\p"
	.string "אם היו לך יותר פוקימונים, זה היה יוצר\n"
	.string "צילומים טובים יותר, אבל…$"

GabbyAndTy_Text_TyDefeatFirstTime:
	.string "טיי: כן, בהחלט ראינו מאמן חם.\n"
	.string "זו סקופ ענק עבורנו!$"

GabbyAndTy_Text_TyDefeat:
	.string "טיי: כן, צילמתי את הכל.\n"
	.string "כל הקרב הזה מצולם.$"

gTVInSearchOfTrainersText00::
	.string "בחיפוש אחר מאמנים…\p"
	.string "גבי: היי! היום אני מבקרת באזור\n"
	.string "ליד {STR_VAR_1}.\p"
	.string "אנחנו מנסים לזהות כמה כישרונות\n"
	.string "חדשים שעולים בתחום.\p"
	.string "היום, הפנינו את העדשה שלנו על ה\n"
	.string "מאמן {PLAYER}.\p"
	.string "יש משהו במאמן הזה\n"
	.string "שעורר את סקרנותנו.$"

gTVInSearchOfTrainersText01::
	.string "נלחמנו ב{PLAYER} לפני כן, אבל אנחנו\n"
	.string "יכולים להעיד שהמאמן בהחלט\l"
	.string "השתפר לעומת קודם.\p"
	.string "ידעתי שאנחנו עלינו על מישהו מיוחד\n"
	.string "כשראינו את המאמן הזה!$"

gTVInSearchOfTrainersText02::
	.string "הדרך הטובה ביותר לקבוע כמה חזק\n"
	.string "מאמן הוא…\p"
	.string "טוב, הדרך המהירה ביותר היא להילחם.\n"
	.string "וכך התחלנו את החקירה שלנו!\p"
	.string "… …\p"
	.string "כך מצאנו את עצמנו בקרב\n"
	.string "עם {PLAYER}.\p"
	.string "בביצוע דומיננטי, השתטחנו,\n"
	.string "התגלגלנו הצידה, ונזרקנו!\p"
	.string "{PLAYER} חזק באכזריות…\p"
	.string "הנה ההתרשמות שלנו לאחר ש\n"
	.string "נלחמנו במאמן המוצג שלנו.$"

gTVInSearchOfTrainersText03::
	.string "השילוב של {STR_VAR_1} ו\n"
	.string "{STR_VAR_3} היה אלוהי!\p"
	.string "המראה שלהם--{STR_VAR_1} ו\n"
	.string "{STR_VAR_3}--תומכים אחד בשני בחוסר\l"
	.string "אנוכיות בלב הקרב…\p"
	.string "זה היה מראה מופלא לצפייה!\p"
	.string "{STR_VAR_2} היה המהלך שבו המאמן\n"
	.string "השתמש אחרון בקרב שלנו.\p"
	.string "המהלך {STR_VAR_2} הוא הסימן\n"
	.string "לידידות של {STR_VAR_1} ו{STR_VAR_3}!$"

gTVInSearchOfTrainersText04::
	.string "…איבדתי ביטחון בעצמי כ\n"
	.string "תוצאה מהמפגש שלנו.\p"
	.string "הוכנו לפני שיכולנו לשגר\n"
	.string "אפילו התקפה אחת.\l"
	.string "אוההה… יללה…\p"
	.string "למרות זאת, הקרבות של {PLAYER}\n"
	.string "שווים צפייה.\p"
	.string "אני ממליץ למאמנים בטוחים ב\n"
	.string "עצמם לאתגר את {PLAYER}.$"

gTVInSearchOfTrainersText05::
	.string "יש רק דבר אחד לומר.\n"
	.string "אל תעז לזרוק פוקי כדור במהלך\l"
	.string "קרב מאמנים!\p"
	.string "{PLAYER} בהחלט חזק, אבל אין לו\n"
	.string "מושג לגבי הכללים הבסיסיים.\p"
	.string "לקהל הטלוויזיה שלנו, יש לי בקשה.\p"
	.string "אם אתם רואים את {PLAYER}, אנא הזהירו\n"
	.string "את המאמן!$"

gTVInSearchOfTrainersText06::
	.string "{PLAYER} מיומן בקריאת\n"
	.string "הפעולות של היריב.\p"
	.string "התזמון של שימוש בפריטים היה יעיל\n"
	.string "בצורה מדהימה!$"

gTVInSearchOfTrainersText07::
	.string "בכנות, חשבתי שאולי\n"
	.string "אני אפילו די טוב.\p"
	.string "למרות שבסוף הפסדנו, היה לנו\n"
	.string "קרב לוהט ומאתגר.\p"
	.string "אבל אם אתה נאבק נגדי,\n"
	.string "יש לך עוד דרך לעבור, {PLAYER}!$"

gTVInSearchOfTrainersText08::
	.string "לאחר הקרב שלנו, ביקשנו מ{PLAYER} לקבל\n"
	.string "סיכום תמציתי.\p"
	.string "המאמן השיב, ”{STR_VAR_1}“.\p"
	.string "הפוקימונים של {PLAYER} {STR_VAR_2} ו\n"
	.string "{STR_VAR_3}…\l"
	.string "ו”{STR_VAR_1}“…\p"
	.string "ממ! זה עמוק! יש משמעות עמוקה\n"
	.string "מאחורי הציטוט הזה!\p"
	.string "זה לא מפתיע--למאמן טוב יש\n"
	.string "דברים טובים לומר.\p"
	.string "זה הכל להיום!\n"
	.string "נתראה שוב בשידור הבא שלנו!$"

ContestLadyShow_Text_Intro::
	.string "”עדכונים חיים של תחרות פוקימון!“\p"
	.string "מנחה: מצטער להפריע לתוכנית\n"
	.string "הרגילה, ותודה שהצטרפתם אלינו!\p"
	.string "אנחנו מביאים לכם את זה בשידור חי מ\n"
	.string "הזירה של {STR_VAR_1}\l"
	.string "שזה עתה הסתיים!\p"
	.string "צופים: ?!!!!\p"
	.string "מנחה: אה! נראה שמשתתפי\n"
	.string "התחרות פונים לכיוון הזה!\p"
	.string "אני אנסה לקבל ראיון מאולתר\n"
	.string "עבורכם שם בבית!\p"
	.string "צופים: ?!!!!\n"
	.string "?!!!!$"

ContestLadyShow_Text_Won::
	.string "מנחה: סליחה!\n"
	.string "תודה שהצטרפת אלינו בטלוויזיה בשידור חי!\p"
	.string "מאי אני לברך אותך על הניצחון שלך?\p"
	.string "מה היה הגורם המרכזי בניצחון\n"
	.string "המדהים של היום?\p"
	.string "יפהפייה: נתנו את המאמץ הטוב ביותר שלנו\n"
	.string "היום, ה{STR_VAR_2} שלי ואני!\p"
	.string "אבל אני בטוחה שלא היינו מצליחים\n"
	.string "אם לא כל העזרה שקיבלנו\l"
	.string "עד לתחרות!\p"
	.string "מנחה: האם יש לך מישהו מיוחד\n"
	.string "שאת רוצה לחלוק איתו את השמחה שלך?\l"
	.string "בואי נשמע את זה בשידור חי!\p"
	.string "יפהפייה: היי, שם בחוץ!\p"
	.string "{STR_VAR_3}! אתה צופה?\n"
	.string "עשינו את זה!\l"
	.string "תודה!$"

ContestLadyShow_Text_Lost::
	.string "מנחה: סליחה!\n"
	.string "תודה שהצטרפת אלינו בטלוויזיה בשידור חי!\p"
	.string "את בטח מאוכזבת מהתפנית\n"
	.string "הזאת. יש לך הערות?\p"
	.string "יפהפייה: זה שובר לב…\n"
	.string "ה{STR_VAR_2} שלי ואני, עשינו את המקסימום…\p"
	.string "אבל אני מרגישה שאכזבתי את כולם\n"
	.string "שתמכו בנו לאורך כל זה.\p"
	.string "מנחה: אני שונא לומר את זה, אבל הצבעוניות\n"
	.string "של הפוקימון קצת חסרה.\p"
	.string "יפהפייה: {STR_VAR_3}, אני כל כך מצטערת…\n"
	.string "אני אעשה טוב יותר בפעם הבאה, אני נשבעת…\l"
	.string "…מנוזל… וואאאא!\p"
	.string "צופים: רואים את זה?\n"
	.string "הילדה המסכנה!\p"
	.string "מנחה: אה… אוי ואבוי…\p"
	.string "אה… זה כל הזמן שיש לנו היום!\n"
	.string "תודה שהצטרפתם!$"

ContestLadyShow_Text_LostBadly::
	.string "מנחה: סליחה!\n"
	.string "תודה שהצטרפת אלינו בטלוויזיה בשידור חי!\p"
	.string "איך עברה ההופעה שלך בתחרות?\p"
	.string "יפהפייה: שום דבר לא הלך כשורה…\n"
	.string "מסיבה כלשהי, ה{STR_VAR_2} שלי\l"
	.string "לא הצליח למשוך שום פופולריות.\p"
	.string "מנחה: אני שונא לומר את זה, אבל הצבעוניות\n"
	.string "של הפוקימון קצת חסרה.\p"
	.string "יפהפייה: … … … … … …\n"
	.string "…מנוזל… וואאאא!\p"
	.string "צופים: רואים את זה?\n"
	.string "הילדה המסכנה!\p"
	.string "מנחה: אה… אוי ואבוי…\p"
	.string "אה… זה כל הזמן שיש לנו היום!\n"
	.string "תודה שהצטרפתם!$"
